### PR TITLE
Upgrade Prisma v2.3.0

### PR DESCRIPTION
**Pull request by thedavidprice**
This upgrade introduces the new dynamic Prisma provider array, which at this time will have an unknown effect on existing migrations and compatibility with the Tutorial process using SQLite then switching to Postgres.

**Existing Schema Syntax: Upgrade**
- [x] need to pass E2E integration test (failing as of initial attempt and requires diagnosing)
    - [x]  yarn rw db save
    - [x]  yarn rw db up
    - [x]  yarn rw dev (both Tutorial cold start and existing App)
    - [x]  DB migration file compatibility (new model db save/up) from previous to 2.2.2
    - [x]  New CRUD query/mutations for tutorial blog posts

**Update Schema Syntax: Upgrade**
- [x] need to pass E2E integration test (failing as of initial attempt and requires diagnosing)
    - [x]  yarn rw db save
    - [x]  yarn rw db up
    - [x]  yarn rw dev (both Tutorial cold start and existing App)
    - [x]  DB migration file compatibility (new model db save/up) from previous to 2.2.2
    - [x]  New CRUD query/mutations for tutorial blog posts

- [x] test Tutorial process: does this work with tutorial as-is, or does Tutorial need to be updated before the release
- [x] test deploy
- [x] is this a breaking change? --> NO 🚀

Related to this is a config change to CRA to stop the Prisma CLI from prompting users to update when new versions are available: https://github.com/redwoodjs/create-redwood-app/pull/83

## Possible associated error?
There have been reported errors that potentially have to do with v2.2.2. See this forum topic for example:
- https://community.redwoodjs.com/t/error-yarn-rw-db-save-linting-disabled-on-prisma/899
> note: this occurred on Windows

## Prisma Release Notes:
v2.2.0 https://github.com/prisma/prisma/releases/tag/2.2.0
- Quick fix suggestions in Prisma VSCode Extension
- Make datasource provider dynamic
- fixes related bug associate with https://github.com/redwoodjs/redwood/issues/575

v2.2.1 https://github.com/prisma/prisma/releases/tag/2.2.1
- misc bug fixes
- @cannikin this might be related to the error you were running into today with .env not being found: https://github.com/prisma/prisma/issues/2971

v2.2.2 https://github.com/prisma/prisma/releases/tag/2.2.2
- fixes binary hash issue

v2.3.0 https://github.com/prisma/prisma/releases/tag/2.3.0
- Rename helper tool in VS Code Extension
- Renaming "Experimental features" to "Preview features"
- Preview Features: Distinct API, Middlewares API

### CODE REVIEW

**Comment by cannikin** [comment]
I was able to get the prisma libs to build correctly by using `yarn rw db generate`! `yarn prisma generate` failed me,  no matter what directory I was in, and whether or not I added `workspace api` in there. My guess is that Prisma itself doesn't care about `dotenv` so the environment variables aren't available. `yarn rw` makes sure those are round to be used by scripts that it runs.

**Comment by cannikin** [comment]
I don't think there will be any problems with NEW migrations—if you have an app that has a database, new migrations will be deployed fine. 

My theory is that if you needed to run those old migrations again (deploying the app from scratch) there will be problems:

1. Have an app with migrations created before 2.2.0 and is deployed using a Postgres DB somewhere 
2. Wipe the Postgres database
3. Redeploy the app

Have we tried this scenario anywhere?

**Comment by thedavidprice** [comment]
> Have we tried this scenario anywhere?

^^ We have not. I tried the "new migrations" scenario on my local Tutorial Test repo running v0.13.0. Problem is that I discovered the yarn.lock + semver issue where I was running 2.2.0 for v0.13.0. SO this is a good sign of no issues. But I want to confirm.

Haven't deployed yet.

**Comment by peterp** [comment]
`v2.3` was released this arvo. :)

**Comment by cannikin** [comment]
Arvo?

**Comment by Errorname** [comment]
I think it's the Australian way of saying "Afternoon": https://www.urbandictionary.com/define.php?term=arvo 😄

**Comment by thedavidprice** [comment]
@cannikin Well, some great news up Prisma's dynamic provider support --> it's 💯 backward compatible. All from my existing app with migrations, I tested:
- cold start
- db up
- db save (new model)
- deploy

For the following three scenarios:
1. upgrade to v2.3.0 only, no syntax changes
2. syntax change `provider = ["sqlite", "postgres"]`, keep plugin
3. syntax change, remove plugin

Everything worked just splendid! 🚀🚀🚀

Rob, this means we don't have to update the Tutorial to use dynamic provider language before merging and releasing this PR. TBD
- [ ] plan for updating Tutorial
- [ ] determine how/if to change CRA code (I vote to leave as is)

**Comment by cannikin** [comment]
Awesome! But we *do* want to update the tutorial to show that you have to add `"postgres"` to the provider list before the first deploy to Netlify, right?

**Comment by thedavidprice** [comment]
🤞

**Pull request merged**
