### PR TITLE
Use relative paths for generator imports

### PR DESCRIPTION
**Pull request by cannikin**
**I'm happy to not have to merge this if it turns out I just have some messed up config locally somehow...**

All of these tests were failing for me locally because it couldn't find the right `src` root for imports like `import 'src/lib/test'`:

```
% yarn jest packages/cli/src/commands/generate/component
yarn run v1.22.10
$ /Users/rob/Sites/redwoodjs/redwood/node_modules/.bin/jest packages/cli/src/commands/generate/component
 FAIL  packages/cli/src/commands/generate/component/__tests__/component.test.ts
  ● Test suite failed to run

    Cannot find module '../../../../../../../src/lib/test' from 'packages/cli/src/commands/generate/component/__tests__/component.test.ts'

      3 |
      4 | // Shared mocks for paths, etc.
    > 5 | import 'src/lib/test'
        | ^
      6 |
      7 | import * as component from '../component'
      8 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/cli/src/commands/generate/component/__tests__/component.test.ts:5:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.92 s
Ran all test suites matching /packages\/cli\/src\/commands\/generate\/component/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

That's way too many `../`s (in this particular example there should have been four, like `../../../../lib/test`. This PR updates all of these imports to be relative, the way they should probably have been to start with.

Tests seem to pass fine on CI here on GitHub, so I'm not sure if there's some additional config or an ENV var I'm missing maybe? But with this the tests pass fine locally again. There are probably many more places in the `cli` package that could use this change.

I've noticed that some imports were already relative `import '../helpers'` but others weren't. We should probably settle on just one way anyway.

### CODE REVIEW

**Comment by dac09** [comment]
@cannikin I think this is your local config :)

**Comment by cannikin** [comment]
Hmm, any advice for fixing? I don’t *have* any local config for general Redwood that I know of. And the tests used to pass just fine, so maybe something changed recently? I’m wondering if others are having similar issues, which would be frustrating for new contributors. :(

**Comment by dac09** [comment]
Can you try using `yarn test` instead of `yarn jest` please? Maybe its the structural changes to the packages..

**Comment by cannikin** [comment]
I could have sworn I switched to `yarn jest` because I was getting weird failures with `yarn test`, but I just did it with the latest `main` and everything was good!

What do you think about changing all of them to relative (or changing them all to absolute) so that all the import paths are consistent? Right now they're all over the place:. For example, from the top of the `scaffold.js` generator:

```javascript
import { getConfig } from '@redwoodjs/internal'

import { generateTemplate } from 'src/lib'
import c from 'src/lib/colors'

import { yargsDefaults } from '../../generate'
import { relationsForModel, intForeignKeysForModel } from '../helpers'
import { files as sdlFiles, builder as sdlBuilder } from '../sdl/sdl'
```

**Comment by dac09** [comment]
I know this is an odd, but I actually like that its mixed up like that. To me the relative imports are usually the stuff we're testing, the "directory named" ones, are usually shared libs/folders.

**Comment by cannikin** [comment]
That's from the actual generator though, not the test!

**Pull request closed without merging**
