### PR TITLE
`api/types` ignored in `dev-server`

### LINKED ISSUE #2750: ensure that `api/types` are ignored by dev-server
It seems that generating the api types was causing my dev-server to reload.

### PR DESCRIPTION
**Pull request by soham4abc**
Fix #2750

### CODE REVIEW

**Comment by peterp** [comment]
@soham4abc Unfortunately neither of these conditions would work - I would suggest going through the `CONTRIBUTING.md` so that you can run these locally, and see if it's working.

**Comment by soham4abc** [comment]
> @soham4abc Unfortunately neither of these conditions would work - I would suggest going through the `CONTRIBUTING.md` so that you can run these locally, and see if it's working.

Okay!

**Comment by soham4abc** [comment]
Once done I will open the Pull request once more. Thanks for the support!

**Comment by peterp** [comment]
No worries, please ping me on Discord if you get stuck at any point!

**Comment by soham4abc** [comment]
> No worries, please ping me on Discord if you get stuck at any point!

Sure !!

**Pull request closed without merging**
