### PR TITLE
Util - adding react-i18n support

### PR DESCRIPTION
**Pull request by noire-munich**
Adding a new util command to provide a basic support of react-i18n.
- It modifies slightly `web/src/index.js`
- It creates a new `web/src/i18n.js` file
- It creates a new `web/src/locales/en/site.json`

Test in progress.

### CODE REVIEW

**Comment by noire-munich** [comment]
@cannikin  Hi Rob!
I'm submitting this one, unfortunately I couldn't test it properly: as for a previous PR I'm losing the directories while executing the command. Can you test it while reviewing?
Many thanks :bowing_man:

**Comment by thedavidprice** [comment]
@noire-munich thank you for this! Great to see support coming in for i18n 🚀

**Info + Question:**
Please take a look at this Forum topic regarding a new category of commands under "setup":
https://community.redwoodjs.com/t/rw-setup-proposal-complementing-generators-with-setup/1123

We are moving this direction and the utility you've created here is a great example of what should be included as a `yarn redwood setup ...` option.

Would you be up for using this PR as an opportunity to create `setup.js` as a command with a directory of options, "i18n" being the first in the directory? We have a solid CLI [README](https://github.com/redwoodjs/redwood/tree/main/packages/cli) created by @jtoar that should help pave the way.

Lastly, I saw your question about testing. We can loop back to that based on how you'd like to proceed regarding "setup".

**Comment by noire-munich** [comment]
@thedavidprice  ok :) that would be a nice thing to work on.
I therefore created this PR: https://github.com/redwoodjs/redwood/pull/1154 shall we move the conversation there?

**Comment by cannikin** [comment]
Should we close this and use #1154 instead?

**Comment by noire-munich** [comment]
@cannikin agreed
Closing in favor of #1154

**Pull request closed without merging**
