### PR TITLE
Add script to create a functional test project using the latest CRWA template

### LINKED ISSUE #2218: RFC Contributing Tools: script to create a functional test project using the latest CRWA template
Local development often requires setting up a functional test project (Redwood App). Additionally, when new hosting providers, auth providers, or other service companies want to integrate with Redwood, they ask if there's a canonical Redwood project for development and testing.

It seems everyone has their own way of managing this, from using an example app, completed Tutorial codebase, a branch from their personal project, etc. During release QA, I start with a fresh project installed using the current create-redwood-app/template codebase in the `main` branch. I then run the E2E Cypress test against this new project, committing the state after it has applied code mods and completed the run successfully. 

**I propose creating a new `./tasks` script that replicates my QA process:**
1. install a new project using the CRWA/template from the current branch `yarn babel-node packages/create-redwood-app/src/create-redwood-app.js path/to/project`
2. apply a series of code mods similar to those [for the Cypress E2E test](https://github.com/redwoodjs/redwood/tree/main/tasks/e2e/cypress/integration/01-tutorial)

### To Do
- [ ] determine a "canonical" feature set and code mods (if not those represented in the Cypress Tutorial test)
    - CLI generators should be prioritized as much as possible
    - bonus: developer could extend the automatic project build "instructions" with additional commands and code mods, e.g. need to add a specific auth provider, components/pages, setup commands, etc. for repeated or collaborative development testing
- [ ] add documentation to [CONTRIBUTING.md](https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by renansoares**
Add first version of command to create blog functional project.

Resolves #2218

### CODE REVIEW

**Comment by dac09** [comment]
This is 😍 @renansoares! Might be a silly question - but did you try the project generated by `./tasks/run-e2e`? I wonder if they serve the same purpose

**Comment by renansoares** [comment]
> This is 😍 @renansoares! Might be a silly question - but did you try the project generated by `./tasks/run-e2e`? I wonder if they serve the same purpose
> 
> EDIT: Saw the original issue from @thedavidprice - I'm not sure I follow how this is different to e2e!

hey @dac09. thank you. yes, I saw the script to run the cypress test.

let's discuss with it's a good idea to have different project

the idea of the functional project is to have a project that a person who wants to contribute can have a way to easily create a project, start making changes and test it. I also agree that it can be done with the current e2e script tho this is not a intention of the script.

you brought up a good point, maybe it's an idea to merge both project into one and use for both (e2e and people use to contribute)? in this case, we will need to rename the e2e and make it clear in the documentation how to create this project and guide a new person into this.

I see they have different purposes and can exist independently, but it's also more code to maintain. in this project, we also want to add more options like authentication, tailwind or others that will come that are not interesting to e2e.

**Comment by thedavidprice** [comment]
Hi gents! Sorry I've been slow to reply this week. FYI @renansoares I did have a chance to talk with @dac09 about this yesterday and brought him up to speed on our conversation.

Using the E2E process to "build" this project is _not_ the right decision (That's what I _have_ to do now, and I'm trying to replace that process with something specific and better.) But I could understand if we do decide to use the E2E code mods. 

This morning I was wondering if we should do something that's more SPA use-case, like the Example To-Do app. Regardless, now that we have a foundation with this PR, we should probably start considering which Redwood components and features should be included. Maybe poll the contributors' community as well? Would you be interested in creating a forum post, @renansoares, to ask what people would like to have in a "canonical" starter project for developing/testing/etc?

Lastly, maybe the 3 of us should try to meet real-time for 30 min next week. Possible?

**Comment by renansoares** [comment]
> Hi gents! Sorry I've been slow to reply this week. FYI @renansoares I did have a chance to talk with @dac09 about this yesterday and brought him up to speed on our conversation.
> 
> Using the E2E process to "build" this project is _not_ the right decision (That's what I _have_ to do now, and I'm trying to replace that process with something specific and better.) But I could understand if we do decide to use the E2E code mods.
> 
> This morning I was wondering if we should do something that's more SPA use-case, like the Example To-Do app. Regardless, now that we have a foundation with this PR, we should probably start considering which Redwood components and features should be included. Maybe poll the contributors' community as well? Would you be interested in creating a forum post, @renansoares, to ask what people would like to have in a "canonical" starter project for developing/testing/etc?
> 
> Lastly, maybe the 3 of us should try to meet real-time for 30 min next week. Possible?

let's do it, I am available! :D 

post: https://community.redwoodjs.com/t/lets-discuss-a-command-to-create-a-functional-test-project/2054

**Comment by peterp** [comment]
I'm also trying to understand the motivation for not doing this via e2e - My main concern is that this is something we'll have to maintain in addition to the e2e tests, except we won't have e2e tests to verify that it's still a valid project.

If that's not helpful then perhaps we can use the fixtures project?

**Comment by thedavidprice** [comment]
## Notes from discussion:
1. this is not meant to be a "template" for building an application; it's meant to be a functional starter project for development and testing
2. my recommendation is this will create a new project starting with `yarn babel-node .../create-redwood-app.js ...`: accounts for changes in the branch `packages/crwa/template` directory, is not dependent on a repo being updated (code modes and version upgrades) — effectively you can trust the project is _always_ at the latest version and up-to-date, which is currently not achieved with any of our other existing repos or processes
3. use the Redwood Tutorial project as reference for features/functionality
4. leverage generators as much as possible
5. built project should have working tests and Storybook stories
6. minimize the use of code modes; ideally code mods will _not_ be full file replaces (e.g. what's currently done for Cypress runs), but instead would use a library or process to update the files created by generators as much as possible
    - note: I don't have a recommendation about a library or syntax or templating for better code modification. But I do know we have a lot of needs for finding a way to do this (e.g. adding to `yarn rw upgrade` command)

**Comment by dac09** [comment]
@renansoares one of the tools I came across for the templates that might be really useful is https://github.com/jondot/hygen.

I like this because instead of creating full files from a string template, we might be able to just inject bits and bobs "before" and "after" certain lines.

**Comment by renansoares** [comment]
hey @thedavidprice and @dac09, I've just updated the PR with the script to create the tutorial blog instead. I ended up using the jscodeshift library, the same used by React codemods. I tried others like hygen but it was really hard to change existing content, using [jscodeshift](https://github.com/facebook/jscodeshift) it is possible to change the AST. I had a good time learning it 🤓 .  I'm using all CLI methods and changing the AST in the files.

So far, it is creating the first part of the tutorial and adding tailwind. Could I have your opinion on this? I know some improvements are needed but if possible I would like you to take a look at the current implementation.

**Comment by dac09** [comment]
Looking very good @renansoares! Let me took a deeper look at this tomorrow

**Comment by thedavidprice** [comment]
@renansoares I agree with Danny! This is a priority for me and came up in discussion (again) earlier today. Thank you and we'll dig in asap.

**Comment by thedavidprice** [comment]
Didn't get to it (yet). On my to-dos for later this evening or tomorrow morning. Thanks for your patience @renansoares

**Comment by thedavidprice** [comment]
@renansoares and @dac09 Wow, there's a lot to like here! The create/setup/add/modify/init and seed DB/ etc. pattern is incredibly thorough and I believe it's the right pattern.

Would you two read through what I wrote below in the Discussion section and let me know if you think the best next step would be a real-time meeting? Danny and I might get a chance to connect Mon or Tue and could follow up after that. I know scheduling takes time, but my gut feeling is that it could be the most efficient path. I'll defer to what you two suggest.

## To Change Now
- [ ] Use `yarn` instead of `npm` to manage tasks/test-project
    - remove `package-lock.json`, which will be replaced with `yarn.lock`
    - run `yarn install` instead of `npm install`

## Discussion
### 1. Option to Set Path to the Output Directory
Currently the test project builds at ./redwoodblog. I think this is a fine default, but I would like to be able to add a path similar to running `yarn create redwood-app `path/to/project>`. (Note: this would also allow setting the name)

### 2. Other Command Options
I think two other options would be high value:
1. Upgrade to Redwood Canary Version (default to current version in CRWA/template as is now)
2. Set project language to TypeScript (default to JS as is now)

### 3. Current package.json Script
I think `yarn build:test-project` is definitely the right way to run this command. (Name is fine for me.) This will work great for developers to run locally. Easy to document in CONTRIBUTING.md, etc.

The other case for using this project will be GitHub CI Automation. Just thinking out loud, but this current implementation will provide everything we need to run this within the CI context as well, correct? The area where I think we'll have a challenge is Prisma DB migration init in the case of Postgres:
    - we'll need a connection string to run `yarn rw prisma migrate dev` 👎
    - seeding the "local" DB won't be necessary

So maybe we'll need options to 1) set the DB provider (someday we'll have Mongo and others) as well as 2) not run the seed command and 3) provide a connection string? 

I'll need to think on the challenge of not being able to run Prisma migrate without a DB connection string (I've asked for this feature before and they declined.) Maybe we could provide a throwaway cloud hosted DB connection string or maybe use a Postgres Container within the GitHub Action container, in which case we'd still need to provide the connection string.

### 4. What's the "complete" Blog functionality we need?
For now, I wouldn't add anything else to the current functionality. Some thoughts for discussion:
- The complete Contact form (as-is now) is a lot of code from front to back. I do think having the form is helpful for dev use cases. But do we need all the fields? And/or other thoughts about whether or not simplification is helpful?
- I would ❤️ being able to have some kind of Auth in the future. I think there's a chance we'll have a true Custom auth provider in the future. But until then I don't think we have a way to add Auth that is super simple and will work out-of-the-box and across all hosting providers, correct?

Lastly, I'm mixed on adding code mods to update Stories and Test files to work. We need this for the E2E CI, but I don't know if that's the same here. Maybe hold off for now as it can easily be added at a later time... ?

### 5.  jscodeshift
I already learned a lot seeing how this works. And I believe @dac09 will agree. (For a different project discussion, we've been looking for a solution to use for code mods when running `yarn rw upgrade`, and this looks very interesting.)

The precision is perfect. But the cost is a lot more code complexity. (Especially for something like the Routes file.) For the E2E code modes where we just replace the whole file, I like that it's readable and also easy to understand how to manage — however, in many cases it doesn't respect the original (or updated) generator syntax, falls out of sync with generator syntax changes, and/or is a bit "sloppy" to just get things done.

So is the trade-off worth it? I really do believe you've added the minimum amount of code mod files as possible. To discuss:
- is this more likely to be maintainable?
- and accessible "enough" for other contributors?
- are there ways to make it more readable? E.g. inline comments... ?
- should we simplify things like the Routes file update with a brute-force overwrite instead of precision?
- ?

## Details for Change/Fix After Discussion Items are Resolved
1. Listr is not nesting correctly. Instead it's appending into a long list that's not easy to understand.
    - The other challenge we always have with Listr is that the syntax makes it challenging to follow what's happening and when it's happening. You did a great job breaking out the sections, but when I read the `globalTasks` function I have the same problem recalling what's included within each of the categories... maybe just handled with inline comments? 
2. Running lint --fix is a great idea. But do we need to handle the errors... I'm just wondering if the current process will make people interpret that something broke during the process
3. Default project name. Since the script is test-project, what if the name included this to be more explicit, e.g. `blog-test-project)?
4. Currently DB model code is handled within Listr objects. I'd suggest we break them out into Code Mod files to be consistent.

**Comment by renansoares** [comment]
> @renansoares and @dac09 Wow, there's a lot to like here! The create/setup/add/modify/init and seed DB/ etc. pattern is incredibly thorough and I believe it's the right pattern.
> 
> Would you two read through what I wrote below in the Discussion section and let me know if you think the best next step would be a real-time meeting? Danny and I might get a chance to connect Mon or Tue and could follow up after that. I know scheduling takes time, but my gut feeling is that it could be the most efficient path. I'll defer to what you two suggest.
> 
> ## To Change Now
> * [ ]  Use `yarn` instead of `npm` to manage tasks/test-project
>   
>   * remove `package-lock.json`, which will be replaced with `yarn.lock`
>   * run `yarn install` instead of `npm install`
> 
> ## Discussion
> ### 1. Option to Set Path to the Output Directory
> Currently the test project builds at ./redwoodblog. I think this is a fine default, but I would like to be able to add a path similar to running `yarn create redwood-app `path/to/project>`. (Note: this would also allow setting the name)
> 
> ### 2. Other Command Options
> I think two other options would be high value:
> 
> 1. Upgrade to Redwood Canary Version (default to current version in CRWA/template as is now)
> 2. Set project language to TypeScript (default to JS as is now)
> 
> ### 3. Current package.json Script
> I think `yarn build:test-project` is definitely the right way to run this command. (Name is fine for me.) This will work great for developers to run locally. Easy to document in CONTRIBUTING.md, etc.
> 
> The other case for using this project will be GitHub CI Automation. Just thinking out loud, but this current implementation will provide everything we need to run this within the CI context as well, correct? The area where I think we'll have a challenge is Prisma DB migration init in the case of Postgres:
> - we'll need a connection string to run `yarn rw prisma migrate dev` 👎
> - seeding the "local" DB won't be necessary
> 
> So maybe we'll need options to 1) set the DB provider (someday we'll have Mongo and others) as well as 2) not run the seed command and 3) provide a connection string?
> 
> I'll need to think on the challenge of not being able to run Prisma migrate without a DB connection string (I've asked for this feature before and they declined.) Maybe we could provide a throwaway cloud hosted DB connection string or maybe use a Postgres Container within the GitHub Action container, in which case we'd still need to provide the connection string.
> 
> ### 4. What's the "complete" Blog functionality we need?
> For now, I wouldn't add anything else to the current functionality. Some thoughts for discussion:
> 
> * The complete Contact form (as-is now) is a lot of code from front to back. I do think having the form is helpful for dev use cases. But do we need all the fields? And/or other thoughts about whether or not simplification is helpful?
> * I would ❤️ being able to have some kind of Auth in the future. I think there's a chance we'll have a true Custom auth provider in the future. But until then I don't think we have a way to add Auth that is super simple and will work out-of-the-box and across all hosting providers, correct?
> 
> Lastly, I'm mixed on adding code mods to update Stories and Test files to work. We need this for the E2E CI, but I don't know if that's the same here. Maybe hold off for now as it can easily be added at a later time... ?
> 
> ### 5. jscodeshift
> I already learned a lot seeing how this works. And I believe @dac09 will agree. (For a different project discussion, we've been looking for a solution to use for code mods when running `yarn rw upgrade`, and this looks very interesting.)
> 
> The precision is perfect. But the cost is a lot more code complexity. (Especially for something like the Routes file.) For the E2E code modes where we just replace the whole file, I like that it's readable and also easy to understand how to manage — however, in many cases it doesn't respect the original (or updated) generator syntax, falls out of sync with generator syntax changes, and/or is a bit "sloppy" to just get things done.
> 
> So is the trade-off worth it? I really do believe you've added the minimum amount of code mod files as possible. To discuss:
> 
> * is this more likely to be maintainable?
> * and accessible "enough" for other contributors?
> * are there ways to make it more readable? E.g. inline comments... ?
> * should we simplify things like the Routes file update with a brute-force overwrite instead of precision?
> * ?
> 
> ## Details for Change/Fix After Discussion Items are Resolved
> 1. Listr is not nesting correctly. Instead it's appending into a long list that's not easy to understand.
>    
>    * The other challenge we always have with Listr is that the syntax makes it challenging to follow what's happening and when it's happening. You did a great job breaking out the sections, but when I read the `globalTasks` function I have the same problem recalling what's included within each of the categories... maybe just handled with inline comments?
> 2. Running lint --fix is a great idea. But do we need to handle the errors... I'm just wondering if the current process will make people interpret that something broke during the process
> 3. Default project name. Since the script is test-project, what if the name included this to be more explicit, e.g. `blog-test-project)?
> 4. Currently DB model code is handled within Listr objects. I'd suggest we break them out into Code Mod files to be consistent.

Thank you for the great review. lots of good ideas and interesting comments. it would be very helpful to have a call to discuss the points you've mentioned. I've sent an e-mail to you about my schedule for this week, if you can forward it to @dac09 and we try to find a suitable time.

Based on your review I have some stuff to work on already. 

I'm going to work in this migration from npm to yarn. I had troubles doing it in the first time, then I used npm just to make it easier to have a first version.

**Comment by renansoares** [comment]
@thedavidprice following up, I've done some improvements:

1. Changed to use yarn instead of npm
2. Moved models to a codemods file
3. Created a simpler version of Routes codemod. I don't think we need that as complex as it was. I just added the wrap to the Set to all current routes.
4. Changed name to test-blog-project
5. Added option to specify path. Use default case path is not specified.
6. I ignored the output of `execa`, Listr is working fine now, it only displays the results of the commands in case of errors. It does not display lint errors neither. What do you think about it?

**Review by thedavidprice — APPROVED** [review]
@renansoares This is a fantastic start as-is. Here's what I'd suggest we do now:
- go ahead and clean-up or tweak (if you'd like) + merge changes from `main`
- we merge this and add it to CONTRIBUTING so people can start using it
- schedule a discussion with you, me, and Danny (probably for end of this week or sometime next week; Danny is really booked this week... You and I could meet this week if best for you.)
- continue work (if applicable) in a new PR

I set the directory path and built a TS project. It felt like 🪄 Really excited to see how other people use this for local dev!

**Comment by thedavidprice** [comment]
This Listr is working _much_ better! I have a few minor thoughts on output details (adding one or two sub-tasks during the long installation steps), but that's for another time.
Screen Shot 2021-05-25 at 5 15 19 PM

I feel like the Menu Title could use a little 🚀

😉 

Screen Shot 2021-05-25 at 5 19 15 PM

**Comment by thedavidprice** [comment]
@renansoares I see your changes. Please let me know when you feel ready to merge this PR! Anything else we can continue in a Part 2 PR.

**Comment by renansoares** [comment]
@thedavidprice I rebased and tested it locally. it looks good to me as the first version. could you merge it? 

I see cypress tests are red but with no reasons, if you can also re-trigger it. I saw it passed in the last runs.

**Pull request merged**
