### PR TITLE
Move tutorial and docs into main repo

### PR DESCRIPTION
**Pull request by jtoar**
Most PRs require adding and/or editing docs. This is already difficult for a variety of reasons, but having the docs in a separate repo makes it more difficult. Let's make it easier on ourselves and our contributors. This PR moves all of redwood/learn.redwoodjs.com and most of redwood/redwoodjs.com into this repo. Now a PR doesn't have to span two or three repos to be considered complete. 

Here's what's going on in this PR:
- the tutorial and docs are in a new directory called `learn.redwoodjs.com`
  - note that we can name this directory anything we want (maybe just `docs`?)
- the `learn.redwoodjs.com` directory is **not** a workspace; it has its own `yarn.lock`
- I renamed some files to 1) make things consistent and 2) avoid having to duplicate information in markdown frontmatter
  - as much as possible, I left the content exactly the same. I had to make a few changes to get things to compile, but they were very minimal  
- the site is docusaurus and we're now on the latest version
- some of the styles may need some tweaking
- this PR is just the first step; I plan to explore things like [shiki-twoslash](https://shikijs.github.io/twoslash/) afterward

I've already tested deployment via a fork of this repo, and made the necessary changes to get things working. I've also reconfigured the eslint/prettier/.gitignore settings so that there's no duplication.

Outstanding tasks/questions:
- [ ] ideally, netlify should only rebuild the site when PRs that change the `learn.redwoodjs.com` get merged. Although I haven't tested it, I'm pretty sure that with this setup, it'll rebuild on all PRs merged to main. So that part needs some tweaking
- [ ] we need to get the sidebar right. Right now, I'm not pulling in the `README.md`, which should be "Introduction" in the sidebar, and should be first
- [ ] we should probably copy over the `netlify.toml` from redwood/redwoodjs.com to preserve the redirects we have
  - [ ] moreover, we need to figure out how we want the URLs to work
- [ ] how does this go live?

### CODE REVIEW

**Comment by Tobbe** [comment]
Great work @jtoar! I'm excited about this one 🎉

**Comment by jtoar** [comment]
More todos:
- [ ] fix broken links and audit all links
- [ ] consider adding some kind of temporary announcement / banner
- [ ] before merging, update docs (e.g., missing doc on CORS)
- [ ] update README with better contributing info
- [ ] algolia

**Comment by thedavidprice** [comment]
@jtoar Not sure how/if you're tracking doc changes. I just updated Auth doc via this PR:
https://github.com/redwoodjs/redwoodjs.com/pull/1008

**Comment by jtoar** [comment]
@thedavidprice tracking is all manual right now, thanks!

**Pull request merged**
