### PR TITLE
Use data previously created in the scenario as input to other scenario data

### PR DESCRIPTION
**Pull request by KrisCoulson**
This is a quick fix to allow scenarios to use other scenario data as input. #2422

It can be used like so.
```
export const standard = defineScenario({
  user: {
    one: { data: { email: 'String8522832' } },
    two: { data: { email: 'String9268083' } },
  },
  event: {
    one: (scenario) => {
      return {
        data: {
          name: 'testing',
          userId: scenario.user.one.id,
        },
      }
    },
  },
})
```
This should work in the order that the keys are defined in the scenario.
Since as of es2015 object keys are chronological https://tc39.es/ecma262/#sec-ordinaryownpropertykeys

Any part of the scenario whose key is created above should be accessible when you use a function to access the data.

Data returned from the function should be an object of the data that you want to be created.

### CODE REVIEW

**Comment by cannikin** [comment]
Dang, why didn't we do this sooner? 😅

**Comment by cannikin** [comment]
Any chance you'd wanna update the Testing doc to reflect these change? No worries if not, we'll just wanna make sure we (probably me, in that case) update the docs around the same time this update goes live so people can start using it!

**Comment by KrisCoulson** [comment]
> Any chance you'd wanna update the Testing doc to reflect these change? No worries if not, we'll just wanna make sure we (probably me, in that case) update the docs around the same time this update goes live so people can start using it!

Yeah I can update them. Just want to get this up here at least in draft mode. I'll swing by the docs to update.

**Comment by jtoar** [comment]
This is really slick! @KrisCoulson it looks good to me; was there more you wanted to add? (Only asking because it's a draft.)

**Comment by KrisCoulson** [comment]
@jtoar no I don't think so I think it's ready to go.

**Review by jtoar — APPROVED** [review]

**Pull request merged**
