### PR TITLE
Firebase: create user within AuthProvider

### PR DESCRIPTION
**Pull request by noire-munich**
Here's a proposition to implement a createUser optional method in our providers.

The reason is: if we use an auth provider we are limited to one login method, otherwise we'd need to make sure our custom login can actually work with what RW offers.

I'm using firebase to demonstrate, I've tested it and it works properly, which means we can support both `signInWithRedirect` and `signInWithEmailAndPassword`  when working with firebase.

Please Review @peterp @cannikin @thedavidprice

### CODE REVIEW

**Comment by peterp** [comment]
@noire-munich Thanks so much for this - We always give the user access to the _original_ client:
```js
const { client } = useAuth()
```
So there's always an opportunity to pop back into the normal auth flow, and I didn't implement the `signUp/ register` method because it wasn't available on the majority of clients that we originally supported.

**Comment by noire-munich** [comment]
No problem @peterp 🙂 and thanks for bringing the `client` up, it eluded me indeed!

Ok, I understand. Does it make any sense to keep this according to RW's policy? I must admit I still struggle to properly understand how we decide to integrate this or that 😋, I just wanted to submit something in the hope it could be useful.

**Comment by peterp** [comment]
@noire-munich I don't think we have a policy which is why it wasn't really clear :), for me this update might make sense, since it removes some ambiguity ("I'm trying to create an account, where is that?!"), but I would like it to work for all the clients:

1. gotrue has `.signup()`
2. netlify has netlifyIdentity.open('signup');
3. auth0 does not appear to have a signup option, it can fallback to login.
3. magic.link should use login.

I think we should default to the "managed" options if they're available, and what I mean by that is rather than supplying a username/ password to the function we forward them to a user interface that's managed by the provider. (If people want unmanaged they can use `client`)

And then, I think we should call this method `signUp`

**Comment by noire-munich** [comment]
Ok @peterp  that makes sense :p

auth0 appears to offer two api endpoints: https://community.auth0.com/t/signup-vs-create-user-apis-which-to-use/7659
and supports a "custom ui" and Lock, a widget from what I gather. I think it could be used as "managed" and "unmanaged", right?

Also, firebase has a FirebaseUI widget to pick a preferred connection method, this one I know for a fact we need to use some code on the front, call a component. I'm not sure how to implement such cases, how'd you see it?

**Comment by peterp** [comment]
> Also if I understand properly, in the case of Firebase which doesn't have a "managed" interface

I think it does; check the example over here: https://redwood-playground-auth.netlify.app/

When I say "managed'; I mean that there's no custom UI work that needs to be completed in order to allow someone to login/ signup.

**Comment by noire-munich** [comment]
Ok that's the one I implemented 🙂, which causes a case of confusion to me.
This interface is used both to sign in and sign up as long as you use a Gmail account.
However Firebase let's you sign up with your email address, which could be @whatever.com, and for this it doesn't offer a specific UI. There's Firebase UI widget but I'd have to check if it's exclusive to sign in, or if it can handle sign up.

**Comment by Terris** [comment]
For what it's worth, Firebase has the package FirebaseUI which does allow for multiple methods of sign up/sign in
- https://github.com/firebase/firebaseui-web
- https://firebase.google.com/docs/auth/web/firebaseui

**Comment by peterp** [comment]
> This interface is used both to sign in and sign up as long as you use a Gmail account.

That's pretty much what I saw in every other provider, which is why I didn't really implement the signUp functionality.

**Comment by AWey95** [comment]
Either with firebase or the other authProviders, having the option to register/login with email/password is a must in my opinion. I don't want to force users to authenticate through social media accounts and not ever user wants to do so. From what I've seen most websites have their own authentication forms, where you input a username/email and password and they give the option to also authenticate with google/facebook/twitter/github if the user so chooses. RW should work in similar way.

**Comment by peterp** [comment]
>  From what I've seen most websites have their own authentication forms, where you input a username/email and password and they give the option to also authenticate with google/facebook/twitter/github if the user so chooses. RW should work in similar way.

You always have access to the original `client` with the `useAuth` hook, so you're free to use any authentication method that they provider supplies.

**Comment by peterp** [comment]
@noire-munich Sorry, I've dropped the ball here a bit. Given that we do provide the original `client` via the `useAuth` hook, do you feel that this is a worthwhile addition?

**Comment by noire-munich** [comment]
@peterp no problem :) 
I am strongly **not** opiniated on the matter tbh, maybe it'd be better collected as a code sample somewhere appropriate - would keep the core code light and offer a direction for those interested. How do you feel about it?

**Comment by peterp** [comment]
@noire-munich I still really like the feature - I'm going to add this to a few more providers that support it and get it merged 👍

**Comment by noire-munich** [comment]
Awesome 🙂
I left on disconnected holidays this morning, but if it can wait until the
24th I could work on some providers with you as well. Is it possible?

**Comment by peterp** [comment]
@noire-munich I will happily await your return, have an amazing vacation!

**Comment by noire-munich** [comment]
Thanks a lot @peterp, see you then \o/

**Comment by dthyresson** [comment]
@peterp as you noted, this issue is similar to https://github.com/redwoodjs/redwood/issues/963.

Do you think the AuthProvider should have a distinct `signup` -- or can the existing `login` be used and based on the options passed to login, call either 

* createUserWithEmailAndPassword(email, password)
* client.auth().signInWithEmailAndPassword(email, password)

**Comment by noire-munich** [comment]
Hi @peterp !

I eventually came back from my amazing vacation x), how should we proceed? any providers you'd rather work on? I'm up to any of them as far as I'm concerned, and any methodology you'd favour.

**Comment by peterp** [comment]
Welcome back @noire-munich! Super jealous that you managed to get some vacation time! 

Let's create a list of our providers and determine which ones support the ability to explicitly sign up, if they do not support the ability to sign up how do you think we should proceed? Should we show the "log in" functionality? Show we throw an error? One of the things that I like to think about is the idea that a Redwood developer could switch an auth provider at any point; so the API should be consistent enough to not introduce breaking changes between providers, in which case I think it's OK to show the login screen instead of the signup screen.

- Netlify: ✅ `netlifyIdentity.open('signup');`
- GoTrue: ✅ `auth.signup(email, password);`
- Auth0: ✅ `screen_hint=signup` parameter?
- Magic.Link:❌: They only have a login option, so show that instead.
- Firebase: ⁉️  `createUserWithEmailAndPassword`

Firebase's provider poses an interesting problem. When people log in we redirected them to the Google Auth Provider; which doesn't have a sign up option, should we introduce two separate providers? `firebase-google` and `firebase-email-password`? That seems like a maintenance nightmare. Or should we add arguments to `login/ signup` that specify the internal firebase provider? Or should we look for `email` and `password` parameters? and then do the right thing?

```js
const { logIn, signUp } = useAuth()


logIn() // redirect to login
signUp() // redirect to login

logIn({ email, password }) // asyncronously authn an account
signUp({ email, password }) // asyncronously create an account
```

**Comment by peterp** [comment]
@dthyresson I think having a specific option to specify that you want to `signUp` is a decent way to go.

**Comment by peterp** [comment]
@noire-munich I would love it if you could contribute this code, of course if it seems like it might be too much that's also OK. (I don't think it would be _a lot_ of code.

And you could use: https://github.com/redwoodjs/playground-auth as a way of testing it.

**Comment by dthyresson** [comment]
> @noire-munich I would love it if you could contribute this code, of course if it seems like it might be too much that's also OK. (I don't think it would be _a lot_ of code.
> 
> And you could use: https://github.com/redwoodjs/playground-auth as a way of testing it.

FYI - I started implementing this from Issue #963 https://github.com/redwoodjs/redwood/issues/963 yesterday but not finished.

If @noire-munich would like to take on the PR, that works for me as the two are related (this issue refers to Firebase and the other Netlify) but they both require the new `signup` and rules noted above.

**Comment by noire-munich** [comment]
Hi @peterp !
Well I was properly exhausted from 6 months of crunch x), so I was very much useless :p, I do wish you to be able to take some time way before that :p

Disclaimer for both @dthyresson and you, my schedule is erratic this September hence the lag in my answers - I hope it's ok if this is not done in the blink of an eye. Either way: I'm happy to help, and thank you @dthyresson for #963, I'll merge it and take it from there, if you could be a reviewer for #783 it would be awesome :).

Couple of notes:
- For the sake of gathering our ideas, what should we do if a provider offers no *managed* authentication, but only code for it? Should we implement it or display a warning?

- In case where a provider would offer the same code for `signUp` and `logIn`, the respect of the API should remain the rule, therefore I would keep both methods implemented on relevant providers. 

- For the peculiar case of firebase, in the current PR I went for parameter detection because it feels pretty natural on the web side when calling the `logIn` method. I think it doesn't pose much of a problem **as long as going this way doesn't get hairy**, if it does we should let the developer handle things on their own, as it seems to be the growing trend :p.

I'll test everything with **playground-auth**, to make sure that if things don't go as expected we could be on the same page app wise :).

**Comment by dthyresson** [comment]
Let's consider: https://github.com/redwoodjs/redwood/issues/1058

Currently, the only supported provider for Firebase if GoogleAuthProvider.

This means login and signup are the same -- you authenticate with your Google account.

If we implement Firebase "Create a password-based account" (note: Firebase client example code):

```js
firebase.auth().createUserWithEmailAndPassword(email, password).catch(function(error) {
  // Handle Errors here.
  var errorCode = error.code;
  var errorMessage = error.message;
  // ...
});
```

See: https://firebase.google.com/docs/auth/web/password-auth

The the login will need to become smart enough to know to use Google Auth or email/password login:

```js
firebase.auth().signInWithEmailAndPassword(email, password).catch(function(error) {
  // Handle Errors here.
  var errorCode = error.code;
  var errorMessage = error.message;
  // ...
});
```

vs

```js
      const provider = new client.auth.GoogleAuthProvider()
      return client.auth().signInWithRedirect(provider)
```

@peterp for pre-v1 and to get signup() to work:

1. keep sign up and login the same

Later, when one can set the Provider:

2. make signup and login specific to the provider's needs

Or, 

3. Replace GoogleAuth with username and password auth for Firebase altogether. Will need to demo how to construct a login and sign up form.

What do you think?

**Comment by noire-munich** [comment]
So, unfortunately I got caught up in other things and @dthyresson in the mean time has been more reactive than me on the matter on https://github.com/dthyresson/redwood/tree/dt-auth-provider-signup-963, so best if I sit this one down. I'll contribute another time.

**Comment by dthyresson** [comment]
@peterp When https://github.com/redwoodjs/redwood/pull/1057 is merged I believe this issue is resolved for the time being until Firebase can support multiple providers.

**Comment by dthyresson** [comment]
This PR should not be merged, but closed when #1057 is merged

**Comment by peterp** [comment]
@noire-munich Thanks for letting us know and thanks for contributing. We totally appreciate and understand that things get busy. Please hit me up if you ever need any help!

**Comment by peterp** [comment]
Closed because is merged #1057

**Pull request closed without merging**
