### PR TITLE
fix`rw prisma [command] --help` console output

### PR DESCRIPTION
**Pull request by thedavidprice**
This fix enables `rw prisma [command] --help` to run `yarn prisma [command] --help`. Previously the `--help` flag was being removed from the args.

Will accept either `help` or `--help`, which is the same behavior as all the other RW Yargs commands.

### CODE REVIEW

**Comment by thedavidprice** [comment]
@dac09 could you take a look at my updated code? If there's a better way you recommend to handle the check + apply, please go ahead and commit. Merge when you're ready -- this is the remaining fix I know of for v0.25.

**Comment by dac09** [comment]
Looks fine to me @thedavidprice! I did notice a check for just `help` though, is that intentional? 

e.g.
```
yarn rw prisma help
```  
will work, when their documentation says

```
yarn rw prisma --help
```

Do you mind if we close this PR and I'll include it in my branch for appending the extra info? (Also converting the cli command to typescript in the process).

**Comment by Tobbe** [comment]
@dac09 
> Will accept either help or --help, which is the same behavior as all the other RW Yargs commands.

😉

**Comment by dac09** [comment]
@thedavidprice superseded (prisma superseeded?) by https://github.com/redwoodjs/redwood/pull/1772

**Comment by dac09** [comment]
Closing in favour of #1772 (I like your code, just preventing conflicts :))

**Comment by thedavidprice** [comment]
😢

**Comment by dac09** [comment]
🍔🍔🍔🍔🍔 your fancy flag parsing code remains

**Pull request closed without merging**
