### PR TITLE
Fix regression where GraphQL Yoga would rename all errors to the default value before other plugins could consume them

### PR DESCRIPTION
**Pull request by twodotsmax**
Fixes issue: https://github.com/redwoodjs/redwood/issues/4913

### CODE REVIEW

**Comment by dthyresson** [comment]
@twodotsmax Thanks for this PR - I have a Draft PR https://github.com/redwoodjs/redwood/pull/4902 in for a similar fix, but your fix explains more about what is going on:

1. Turn off the default masking in Yoga
2. Add back the  plugin (as we did with Helix) and use or custom formatter.
3. Make sure the plugin order is ok, since is important so that the on execute can have the enriched result for the logger

My fix added in the original error - but then I had to modify the logger plugin.

You you confirm that you see the logFormatter log to the API the original error and stack? Maybe a screenshot?

If so, I'll favor yours as has fewer code changes.

FYI my pr was draft as I was trying to figure out a way to test this to prevent regressions.

I am going to share both our approaches with The Guild to get their take -- and also share feedback with them for Yoga.

cc @ardatan @dotansimha  Can you look at this PR and also https://github.com/redwoodjs/redwood/pull/4902 and confirm perhaps why we saw a behavior change with error masking? Thanks!

**Review by dthyresson — COMMENTED** [review]
Have shared with the Guild to get their feedback on both fixes - this one that adds back the plugin, and the one that uses Yoga's masked errors with the formatter.

I think the Yoga version places the plugin too high up in the chain, perhaps, and we need it last to be able to enrich the request for logging?

**Comment by twodotsmax** [comment]
"I think the Yoga version places the plugin too high up in the chain, perhaps, and we need it last to be able to enrich the request for logging?"

Exactly

**Comment by thedavidprice** [comment]
I'm watching this one and marked as critical patch for 1.0

Thanks all!

**Review by dthyresson — APPROVED** [review]
Had a fix in https://github.com/redwoodjs/redwood/pull/4902 but this doesn't need a change to the Redwood Logger plugin.

Will report back to the Guild about the plugin ordering with their Masked Error default.

Thanks @twodotsmax for this! Is a great help.

**Comment by dthyresson** [comment]
FYI a GitPd screenshot here confirms the expected behavior:

image

**Comment by dthyresson** [comment]
HI @twodotsmax can you update this from base main?

We cannot update automatically or push to your branch -- once in I can merge. Thanks!

**Comment by twodotsmax** [comment]
Ok, sorry about that, will have to make changes on a personal account in the future

**Pull request merged**
