### PR TITLE
chore(setup-deploy): refactor setup deploy

### PR DESCRIPTION
**Pull request by dac09**
### Changes to the SLS integration
Merges in changes collected in the branch `serverless-deploy-3686`

### Why the refactor?
This decouples the logic between providers a lot, and makes the code a lot more maintainable (and grokable). I need this as a pre-requisite for making some changes to the serverless integration.

The current way deploy commands work are extremely restrictive, this refactor does the following:
- moves each setup deploy command to use nested commands
- moves common tasks to utlity functions, rather than requiring exports
- moves templates for each provider to a templates folder

### [Full Explanation](https://s.tape.sh/BFe3iT62)
[Img](https://s.tape.sh/BFe3iT62)

### CODE REVIEW

**Review by cannikin — APPROVED** [review]
Looks good to me!

**Comment by thedavidprice** [comment]
still has regression

**Comment by cannikin** [comment]
@thedavidprice I saw you commented something about a regression, but I don't see the comment when I click through on the email notification from Github. What's up?

**Comment by thedavidprice** [comment]
@cannikin too. many. tabs. Nothing to see here...

**Pull request merged**
