### PR TITLE
chore: Additional tests for paths and config

### LINKED ISSUE #613: [Tests] Improve internal `paths.ts` test coverage and cases
Redwoods' CLI commands are increasingly dependent on these helpers, and we are way behind on test coverage, which is resulting in errors and workarounds.

- increase coverage of functions, especially `getPaths()`
- increase coverage of all properties, e.g. `getPaths().api.base`
- test for multiple path cases
    - spaces
    - Windows, Linux, etc.
    - special characters (TBD)

### PR DESCRIPTION
**Pull request by Josh-Walker-GM**
Closes #613 

**Problem**
Additional tests for `getPaths` within the internal package is wanted. 

**Changes**

1. Adds tests for the `getPaths` function which ensures the paths match those expected for the 4 different project fixtures.
2. Adds a test which confirms `getConfig` throws an error when given a bad path
3. Adds tests for the `getConfigPath` function
4. Other changes within the `paths.test.ts` to ensure the tests are run for each fixture.

**Questions**

1. The `paths.test.ts` is quite long now. Perhaps this is not the testing solution that others had envisioned?
2. Is there an appetite to expand this to include additional test coverage or is it fine to just address the paths?

### CODE REVIEW

**Comment by Josh-Walker-GM** [comment]
One thing to add is that in #613 there was a desire to test paths with spaces, different platforms and perhaps even with special characters. Ideally we'd include some of these features within one of the project fixtures so we can test them?

**Review by dac09 — APPROVED** [review]
LGTM! Thanks again @Josh-Walker-GM.

**Comment by dac09** [comment]
> One thing to add is that in https://github.com/redwoodjs/redwood/issues/613 there was a desire to test paths with spaces, different platforms and perhaps even with special characters. Ideally we'd include some of these features within one of the project fixtures so we can test them? I didn't want to go ahead and do this without some input.

You could definitely add to the todo-test-project if you wish!

**Comment by Josh-Walker-GM** [comment]
I'm not sure that `getPaths` would actually ever expect to return a value which contains a space or special character given we're looking for files/directories that the framework sets and expects. 

It should be possible to test this in some of the tests which get the names/paths of cells etc but that's probably best left to when support for special characters (#441) is added in its own PR and those associated tests added. 

I think unless others have suggestions I'm happy with this as it stands.

**Pull request merged**
