### PR TITLE
fix(v6): Refactor Redwood Realtime as a new redwoodjs/realtime package to better handle dependencies 

### PR DESCRIPTION
**Pull request by jtoar**
Supersedes https://github.com/redwoodjs/redwood/pull/8872. Fixes the hack in https://github.com/redwoodjs/redwood/pull/8829.

### CODE REVIEW

**Comment by dthyresson** [comment]
@jtoar thanks for redoing the PR. Is it ok for me to commit here to rework the Fastify server and GraphQL portion of this refactor?

**Comment by jtoar** [comment]
@dthyresson yeah that'd be great!

**Comment by dthyresson** [comment]
@jtoar I have finished up the way the `useRedwoodRealtime` plugin is added only in the Fastify graphql server instance.

Also, the realtime setup does add:

```
      addApiPackages(['ioredis', '@redwoodjs/realtime']),
```

which can error in local dev since `@redwoodjs/realtime` isn't yet published at the moment.

Is there a way to resolve this before publishing?

**Comment by dthyresson** [comment]
@jtoar For you final review and approval.

**Comment by dthyresson** [comment]
@jtoar need anything else from me before merging?

**Comment by dthyresson** [comment]
Woohoo!!

**Pull request merged**
