### PR TITLE
Update CONTRIBUTING.md for handling package discrepancies

### PR DESCRIPTION
**Pull request by jtoar**
This adds two new sections to `CONTRIBUTING.md`--_A Note on Contributing_, and _Handling Package Discrepancies_--and completes its table of contents.

While working on a very WIP contribution to scaffolds, I had to update my local redwood sandbox app's prisma packages. I included the steps I took (relayed to me on [discourse](https://community.redwoodjs.com/t/m-n-relationships-are-not-working-with-migrations/338/9
) via @thedavidprice) in _Handling Package Discrepancies_. 

But I think there's a larger question: contributing to redwood seems to involve some steps that go in-and-out of necessity E.g., when another version of redwood comes out, this prisma step will be unnecessary. But as @thedavidprice mentioned (in the same discourse thread), there will more-or-less always be a discrepancy.

If I understand correctly, build-and-copy tools discussed in #109  would solve this. But for the time being, I included the section _A Note on Contributing_. Let me know what you guys think about a section like this, and how to proceed when it comes to updating CONTRIBUTING.md (i.e. are contributors are expected to be technical enough to figure most of this out? / recoursing to discourse is enough?)

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks for this @jtoar! Since our forum discussion, Peter has made progress on a potential build tool solution. The core team is going to review and discuss this Tuesday. If it works, we’ll be releasing shortly, at which time we’d welcome help with local testing of the tooling and (re)updating these docs.

I’d like to pause this until we know more this Tuesday or Wednesday at the latest. Please check back in if you don’t hear from me first.

Fingers crossed!

**Comment by mohsen1** [comment]
Would it be too much to ask for an automated table generator?


https://github.com/lee-dohm/generate-markdown-table

**Comment by jtoar** [comment]
@thedavidprice I seemed to have effaced my PR while trying checkout #429--the PR for the build tool (was in the midst of checking it out as you can see). Should I try to fix this or just close it?

**Comment by jtoar** [comment]
Fixed? :flushed:

**Comment by peterp** [comment]
@jtoar I've just merged something that I think makes the process a whole lot simpler, could you check https://github.com/redwoodjs/redwood/pull/429 and let me know what you think?

**Comment by thedavidprice** [comment]
Hi gents, I'm going to close out this PR. But I do have some next steps. I've open this Issue with specific items/needs to address: https://github.com/redwoodjs/redwood/issues/434 

The items I listed are a quick, rough sketch and definitely open to discussion. Also, I have some things I'm working on today regarding documentation, but the general approach is still in my head and not yet outlined. This means I might need to clarify the "why" behind suggestions -- just ask when/if that's the case.

@jtoar appreciate you moving this forward. And I'd welcome your help with the next steps if you are able!

**Comment by jtoar** [comment]
@peterp Thank you--I'll start checking it out now.

@thedavidprice Willing and able.

**Pull request closed without merging**
