### PR TITLE
feat(testing): Configure jest to ignore sidecar files in __tests__ folder

### PR DESCRIPTION
**Pull request by V1shvesh**
Solves for #10870

### Description:
`./api` directory structure:
image
`./web` directory structure:
image

Before: 

`yarn rw test api`:
image

`yarn rw test web`:
image

After:
`yarn rw test api`:
image

`yarn rw test web`:
image

### CODE REVIEW

**Comment by V1shvesh** [comment]
@cannikin please have a look, I added config to ignore sidecar files in the `web` directory as well!

**Comment by ahaywood** [comment]
Hey @V1shvesh Thanks for taking the time to do this! We'll take a look.

**Review by dac09 — APPROVED** [review]
Thanks @V1shvesh, looks good!

**Comment by cannikin** [comment]
Thanks so much for this, works perfectly!

**Pull request merged**
