### PR TITLE
7482/validators exclude include caseinsensitive

### PR DESCRIPTION
**Pull request by taivo**

### CODE REVIEW

**Review by jtoar — APPROVED** [review]
LGTM, @cannikin if you could have a look that'd be great; @taivo was specifically wondering about the helper function, if it could be organized a different way. (But if you don't mind then all good)

**Review by cannikin — APPROVED** [review]
Looks great, thanks for working on this!

@jtoar we should probably update the docs? Or is that in a separate PR?

**Comment by jtoar** [comment]
@cannikin ah yeah we should, @taivo would you be up for doing that in this PR as well?

**Comment by taivo** [comment]
@jtoar done!

**Review by jtoar — APPROVED** [review]

**Pull request merged**
