### PR TITLE
Reorg codemod for dev fatal error page

### PR DESCRIPTION
**Pull request by dac09**
### What does this PR do?

Moves dev fatal error page from v0.46 to v0.49->v0.50.x, so its obvious that it should be used once we release the next version.

Nothing has been changed inside the codemod - although I've noticed that this codemod doesn't follow any of the standard patterns in the other ones 🤷

### CODE REVIEW

**Comment by dthyresson** [comment]
> although I've noticed that this codemod doesn't follow any of the standard patterns in the other ones

I patterned it off `packages/codemods/src/codemods/v0.38.x/updateSeedScript/updateSeedScript.ts`

https://github.com/redwoodjs/redwood/blob/28ad2c891fe98e18d9dcc040108871a8e736025a/packages/codemods/src/codemods/v0.38.x/updateSeedScript/updateSeedScript.ts#L43

Or at least tried to.

**Comment by dac09** [comment]
> I patterned it off packages/codemods/src/codemods/v0.38.x/updateSeedScript/updateSeedScript.ts

Yeah no biggie! Just noticed that it doesn't use the utility function in `packages/codemods/src/lib/fetchFileFromTemplate.ts`. No real need to change now though!

**Comment by dthyresson** [comment]
> > I patterned it off packages/codemods/src/codemods/v0.38.x/updateSeedScript/updateSeedScript.ts
> 
> Yeah no biggie! Just noticed that it doesn't use the utility function in `packages/codemods/src/lib/fetchFileFromTemplate.ts`. No real need to change now though!

Oh, I didn't know about that `fetchFileFromTemplate` ... I knew the seeds just replaced the file and did the same.

Good to know.

**Review by dthyresson — COMMENTED** [review]
Did you want to fix the directory `v47` instead of `v0.47` now?

**Comment by dac09** [comment]
Yeah problem with codemods I suppose is that our patterns evolve very quickly, hard to keep track!

**Pull request merged**
