### PR TITLE
Fix typo in Tutorial Chapter 1 Prerequisites

### PR DESCRIPTION
**Pull request by mattdriscoll**

### CODE REVIEW

**Comment by callingmedic911** [comment]
Thanks for the PR! Just wanted to point out that we want to avoid changing docs inside the versioned_docs directory. I think the path you want to modify is:

- docs/tutorial/chapter1/prerequisites.md

After changing the docs you can visit the canary version, something like:
deploy-preview-url--redwoodjs-docs.netlify.app/docs/canary/introduction

More details on contributing docs: [https://github.com/redwoodjs/redwood/blob/main/docs/README.md](https://github.com/redwoodjs/redwood/blob/main/docs/README.md?rgh-link-date=2022-05-27T05%3A44%3A38Z)

**Review by dthyresson — APPROVED** [review]
Thanks @mattdriscoll !

**Review by jtoar — APPROVED** [review]
Thanks @mattdriscoll! I took the liberty of copying the typo fix to the ./docs directory.

**Comment by mattdriscoll** [comment]
Hi there. So sorry for the delay here. I'll be sure to find the markdown files for any future updates. Thanks for your patience.

**Pull request merged**
