### PR TITLE
Auth Provider: Update Nhost to V2

### PR DESCRIPTION
**Pull request by nunopato**
- Update Nhost Auth provider to use Nhost v2.
- Issue here https://github.com/redwoodjs/redwood/issues/4357

cc @dthyresson

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks @nunopato! We were having some trouble earlier with our CI yarn caching, so I gave it a reboot and think it's working now.

Do we need to include instructions for existing projects to upgrade to these changes, e.g. https://github.com/redwoodjs/redwood/pull/4770/files#diff-0d0be1da1708452d96c61864423d49a276ec2b1dd9ff4be7cdbc1d62e8f50a38

Not sure if there's much use at this time.

@dthyresson I'll let you determine if there are related doc updates.

**Review by dthyresson — CHANGES_REQUESTED** [review]
Thanks @nunopato. LGTM and we can then update the playground which I see you have done.

I am not merging, thought, since the title of this PR still says "[wip]".

I will update branch to have CI run again.

But, otherwise approved!

**Comment by thedavidprice** [comment]
@nunopato please do let me know if this is GTG and I'll get it merged.

Additionally, could you please:
1. let me know if there are changes needed for apps upgrading to next version; if so, please write out the instructions
2. confirm the docs are current; please update if not: https://redwoodjs.com/docs/authentication#nhost

Thanks!

**Comment by nunopato** [comment]
@thedavidprice PR is good to go. 

1. The change would be to use the new SDK. If you think this should be mentioned somewhere, please let me know where.
2. The docs PR is here https://github.com/redwoodjs/redwoodjs.com/pull/1008 

Thank you @thedavidprice @dthyresson

**Comment by thedavidprice** [comment]
@nunopato Thank you! 

re: "The change would be to use the new SDK." Could you just comment here as to how someone would do that? From the diff, it looks like it's a simple import swap, correct?

**Comment by nunopato** [comment]
@thedavidprice 

Yes, one would go from:

```js
import { createClient } from 'nhost-js-sdk'

const nhostClient = createClient({
  baseUrl: 'url'
})
```

to
```js
import { NhostClient } from '@nhost/nhost-js'

const nhostClient = new NhostClient({
  backendUrl: 'url'
})
```

**Comment by thedavidprice** [comment]
Perfect. That’s all I need. Thank you!

**Pull request merged**
