### PR TITLE
GraphQL useMutation options

### PR DESCRIPTION
**Pull request by cjreimer**
ToDo:
- [x] Confirm approach with the core team
- [ ] Testing

**Note:  I have not tested the code yet, because I'm currently having trouble getting the current framework to build on my machine with the latest main pull.  Will debug that and address it separately.**

This addresses #3030 regarding being able to send an array of strings rather than queries into the refetchQuery option.
The approach taken was to separate the Query and Mutation option types, which are different, and then update the `refetchQueries `option to mirror the Apollo client options.

**Please confirm:**
1.  An alternative methodology is we could grab all the types from Apollo client, rather than re-writing them.  However, this may make things more difficult in the future if we ever want to go to a different graphQL client.
2. I haven't added every available Apollo option into `GraphQLQueryHookOptions ` or `GraphQLMutationHookOptions`, but rather left the   `[key: string]: any` to provide a little untyped flexibility.  My question is, do we want to align 100% with the Apollo client?

### CODE REVIEW

**Comment by dac09** [comment]
Hey @cjreimer appreciate you taking a stab at this, and for all the extra thought into it!

I'm not 100% confident its possible in this particular case, but maybe we can make use of "type declaration merging". I'm actually do this with overriding the types `QueryOperationResult` and `MutationOperationResult`.

And the way it works is:
a) The default type is defined in this file: https://github.com/redwoodjs/redwood/blob/main/packages/web/src/global.web-auto-imports.ts 

b) Override the type for apollo here: https://github.com/redwoodjs/redwood/blob/main/packages/web/src/apollo/typeOverride.ts

c) When the Apollo provider is imported, typescript will override those types with the ones from typeOverride.ts

This means the types for query/mutation results aren't "locked" to apollo, but they automatically become apollo types as soon as `import { RedwoodApolloProvider } from '@redwoodjs/web/apollo'` is added in App.tsx 

Something to note: this works because we're using interfaces, like you're also doing here. 

Do you think we could try doing something similar here?

**Comment by cjreimer** [comment]
Thanks, @dac09, I like your plan!

That's what I like about being part of the community .... it stretches me to learn new things, as I haven't used type overriding before.  I'll work on it as soon as I can make some time.

**Comment by cjreimer** [comment]
@dac09 I pushed some updated code, trying to use the technique you suggested.  However, it is not working for me.  I'd appreciate any tips you can provide!

**Comment by dac09** [comment]
Sorry @cjreimer - I'll make sure to have a look at this shortly!

**Comment by dac09** [comment]
Hey @cjreimer - moved the types into the global namespace, and that seemed to fix it. It seems for declaration merging to work, it has to be defined in a namespace (or if we override the whole module). 

Note that I also took out our default refetchQueries type, because having it defined there means it doesn't pick up the apollo one.

Also fixed a small issue where onCompleted wasn't getting the generic type, but it does now!

image

**Comment by dac09** [comment]
Please do take it for a quick whirl, as I haven't tested it thoroughly, but if it looks good to you too we can merge :)

**Comment by ajoslin103** [comment]
you guys rock !!

**Comment by dac09** [comment]
Hey @cjreimer - just pinging you about doing a check on this if it solves your original issue?

**Comment by cjreimer** [comment]
Hey Danny,

I was away for a week and I'll try to look at this later today.  Thanks so much for working on this!

**Comment by dac09** [comment]
> I was away for a week and I'll try to look at this later today. Thanks so much for working on this!

No, thank you! :) 🤞it solves the issue, but I'm fairly confident!

**Comment by cjreimer** [comment]
@dac09 It appears to be working.  Thanks for your help!  Should be ready to merge.

**Comment by thedavidprice** [comment]
@dac09 assuming you want this merged for v0.36-rc. Let me know otherwise.

**Comment by dac09** [comment]
Yup merging :)

**Comment by ajoslin103** [comment]
I'm so excited, I could plotz!

   - capt "hawkeye" pierce

**Pull request merged**
