### PR TITLE
Fixed the ESLint error for generated template

### LINKED ISSUE #3058: ESLint errors in scaffold template
image

PR on the way

### PR DESCRIPTION
**Pull request by Albert-Gao**
close #3058 

No visual differences after the fix :)
image

### CODE REVIEW

**Comment by Tobbe** [comment]
@Albert-Gao Welcome to Redwood, and thanks a lot for you PR!

**Comment by Albert-Gao** [comment]
@Tobbe What a great framework! Thanks for all the hardwork!

**Comment by Tobbe** [comment]
@Albert-Gao I noticed there are a few snapshot test failures. Could you please try fixing those?

The easiest way to update the snapshots is by running `yarn jest -u`

**Comment by Albert-Gao** [comment]
I did a `yarn` at the root, and ran `yarn test`, got this error,

image

Any setup I am missing here?

**Comment by Tobbe** [comment]
> Any setup I am missing here?

`yarn install` and `yarn build:clean` are both good things to try when it's not building

**Comment by Albert-Gao** [comment]
Updated, also fixed a prettier warning

image

**Review by dac09 — APPROVED** [review]

**Comment by dac09** [comment]
Thanks once again @Albert-Gao! 🚀🚀

**Pull request merged**
