### PR TITLE
Print metadata

### LINKED ISSUE #5228: logFormatter doesn't print metadata
I have this in my code
```
  logger.debug(
    { foo: 'foo', nested: { arr: ['one', 'two', 'three'] } },
    'Example debug log'
  )
```  

This is what it looks like on LogFlare

image

Running `yarn rw dev` and letting it print to my console, all I get is this

image

I get the "Example debug log" text, but none of the metadata.

I think we should print the metadata locally too. I'll start working on a PR

Also found this:
When generating a directive the generated code contains this debug log:
image

`directiveArgs` will never be printed when running locally because we're not printing any metadata

### PR DESCRIPTION
**Pull request by Tobbe**
Fixes #5228 and rewrites the full logger with proper TS types

**Breaking change**
All metadata sent to the logger will now be printed.
Previously if you did `logger.debug({ user }, 'my user')` only "my user" would be printed. Now the full `user` object will be included in the output

### CODE REVIEW

**Comment by simoncrypta** [comment]
>  Did pino-pretty exist when you decided to write your own log prettifier?

Yes it does, in fact we originally start with pino-pretty and decide to remove because they deprecated pretty option that we used on the last version of Pino and also to get more control over it.  @dthyresson can probably add more about it 😉 

I will take a look to see why tests are failing ...

**Comment by dthyresson** [comment]
> Did pino-pretty exist when you decided to write your own log prettifier?

As @simoncrypta said, it did but we removed it per Pino recommendations (to not have it available as part of mini config especially in production). That said, it could probably be used in dev in conjunction with the log formatter. That may be worth looking into -- since that is dev only.

To test, you could just run api server and pipe to pino pretty.
Instead of:

`yarn rw serve | yarn rw-log-formatter`

`yarn rw serve | <pipe to pino-pretty>`

**Comment by Tobbe** [comment]
@jtoar linked #4154 and #4619 that introduced `custom`. Personally I'd much rather print all values though, like LogFlare does, and like pino-pretty does. Why didn't we want to do it that way?

> Yes it does, in fact we originally start with pino-pretty and decide to remove because they deprecated pretty option that we used on the last version of Pino and also to get more control over it.

Maybe I'm misunderstanding you here. But [pinojs/pino-pretty](https://github.com/pinojs/pino-pretty) is different from the deprecated `prettyPrint` option.

Really, though, I'd *really* like to just use `console.log` syntax for pino logging too. Everyone already knows that syntax. Wouldn't it be awesome if we could use that same syntax for when streaming our logs to LogFlare etc?

**Comment by dthyresson** [comment]
> @jtoar linked #4154 and #4619 that introduced `custom`. Personally I'd much rather print all values though, like LogFlare does, and like pino-pretty does. Why didn't we want to do it that way?

Some background: https://github.com/redwoodjs/redwood/issues/3784

**Comment by Tobbe** [comment]
Thanks for the link to Orta's issue. I can see the point there. Because that's a lot of logging output you have no control over. But if you explicitly add an object to the logging statement I guess you'd like to see it in the logs. No?

**Comment by dthyresson** [comment]
> Thanks for the link to Orta's issue. I can see the point there. Because that's a lot of logging output you have no control over. But if you explicitly add an object to the logging statement I guess you'd like to see it in the logs. No?

There's definite room for improvement. 

Also, the log formatter is only in dev. Your pino logs in production and if sent to logFlare or anywhere else will be the full NDJSON ouput.

**Comment by Tobbe** [comment]
One idea I'm toying with is to make the RW logger a child logger that always adds a name. That way it's easy to know when it's safe to print the metadata

image

**Comment by thedavidprice** [comment]
@dthyresson closing this in favor of https://github.com/redwoodjs/redwood/pull/7813

**Pull request closed without merging**
