### PR TITLE
fix(auth-decoder): Make auth decoder backwards compatible with 0.12

### PR DESCRIPTION
**Pull request by dac09**
### What does it do? 
- Allow users to use any type of auth provider without a hard error.
- Add tests for decoder selection to prevent regression in the future!

### Why?
If you have a custom auth setup, you might want multiple different types of custom auth. e.g. in our case they're "jwt" and "cli-token" - this is a string, not a jwt. Although I could use "custom" instead of "jwt" for web, it would mean all the cli clients would break and would need a forced upgrade.

--- 
### Checklist:
- [x]  Tested with RW contribution flow
- [x] All tests pass with `yarn test`
- [x]  Write some tests to prevent regression

### CODE REVIEW

**Comment by dac09** [comment]
@peterp updated with tests! Please let me know if there's anything else i should add here

**Comment by dthyresson** [comment]
My understanding of the authType was that is *should* be one of the predefined types: netlify, firebase, auth0 etc... and custom is one of those defined types. 

Speaking with @dac09 (from what I understand) is that his app is checking the authType and conditionally doing some logic based on the types; in his case they are `jwt` (for web based requests) and `cli` for cli-based requests.

An option I suggested was to put the value of `jwt` or `cli` as one of the claims in the encoded JWT as either the issuer to audience.

The Issuer (iss) claim seems to fir this use case well .. as does audience (aud).

> The JWT specification defines seven [reserved claims](https://auth0.com/docs/tokens/concepts/jwt-claims) that are not required, but are recommended to allow interoperability with third-party applications. These are:

* iss (issuer): Issuer of the JWT
* aud (audience): Recipient for which the JWT is intended

Other reserved claims:

* sub (subject): Subject of the JWT (the user)
* exp (expiration time): Time after which the JWT expires
* nbf (not before time): Time before which the JWT must not be accepted for processing
* iat (issued at time): Time at which the JWT was issued; can be used to determine age of the JWT


If the token is issued by/for the web (then set it to that `jwt` value); if by/for the cli, then set to `cli` (maybe namespaced). But, the actual auth provider is still custom.

**Comment by dac09** [comment]
You're 100% right @dthyresson, this was my original design too, but requires use of JWT for both auth types. 

If you just want a normal opaque token (like with the cli), unfortunately we can't attach an audience. This is important so that we can revoke the cli token from your account if you choose to.

**Comment by dthyresson** [comment]
> want a normal opaque token (like with the cli),

oh, i see. so, does the clui use something like an access_token or api_key that is sent as `Authorization: Bearer <token>` header?

and the api needs to either decode a JWT to authentication or lookup a token to authenticate? So two distinct with methods. hm.

interesting problem. will give it some thought.

only approach i can think of is if the cli didn't go through the GraphQLHandler and just in a function authenticated itself.

**Comment by dthyresson** [comment]
I had another idea @dac09 ... what if the custom auth provider:

1. extracted token from Authorization header
2. did a quick check to see if it's a JWT
3. if not, treat it as an opaque access token (aka the cli case)
4. if it is, treat it as a JWT and decode as per usual

Since all JWT's have a [header](https://jwt.io/introduction/) like:

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9`

```js
{
  "alg": "HS256",
  "typ": "JWT"
}
```

[What is the JSON Web Token structure?](https://jwt.io/introduction/)

```
In its compact form, JSON Web Tokens consist of three parts separated by dots (.), which are:

* Header
* Payload
* Signature

Therefore, a JWT typically looks like the following.

xxxxx.yyyyy.zzzzz

Let's break down the different parts.

Header

The header typically consists of two parts: the type of the token, which is JWT, and the signing algorithm being used, such as HMAC SHA256 or RSA.

For example:

{
  "alg": "HS256",
  "typ": "JWT"
}

Then, this JSON is Base64Url encoded to form the first part of the JWT.
```
Could have a function that `isJWT` that:

* splits on `.`
* if not 3 parts, then not a JWT
* take first and base64 decode, and look for `typ === 'jwt'`

That way the custom auth could look at the same Bearer token and handle two different cases: opaque or json web ... token.

**Comment by dac09** [comment]
This is a good idea, but I'm conflicted about it too -  a departure from the concept that the header "auth-provider" tells you what sort of token is being sent and how to handle it. As a user of RW, when just inspecting the request and trying to figure out how it works, I think it gives you very important clues on how it works without needing to dive into the source. The relation between input => output is more obvious, because one input gives you one output, and the code is simpler. 

I totally get where you're coming from though, it feels less "built in". At the same time if a user of RW is intentionally deviating from the more common way, we shouldn't clip their wings.

**Comment by dthyresson** [comment]
@dac09  I really like this discussion -- and just so you know --  I don't have a right/wrong or good/bad take. I simply like thinking up other ways of solving problems because that usually makes a solution better .. and lets me understand different way and different approaches. 

So, I'm going to fan this discussion a little more ;) but of course at some point there needs to be a decision and think that should rest with @peterp to give the direction.

> a departure from the concept that the header "auth-provider" tells you what sort of token is being sent and how to handle it

I had a totally different take on  "auth-provider" in that it doesn't tell me the "sort of token is being sent" but it does tell me "how to *get* it" and then sometimes to handle that token it has to decode it or extract it or do nothing. Magic, netlify, auth0, firebase .... the token is always in the Authorization header as a Bearer token. The provider will `getToken`.

Once you have the info contained in that token, what's **in it** that is valuable to authenticate. Is it a user Id? is it an email? is it an accessToken? The implementation of `getCurrentUser` may have to handle that.

Another idea I had for the CLI might be to proxy CLI calls to a function:

`./netlify/fuctions/cli` to `cli`

and the `cli` function then can use the Bearer token as the opaque access token and have a completely independent authorization flow other than that used by `graphql` and `getCurrentUser` (ie, look up userByAccessToken).

Last, I do think it is important to keep in mind that RW is alpha (right?) and not production ready, so it's not unexpected that there will be some backward incompatibility as the architecture becomes more mature and function sigs can change.

**Comment by dac09** [comment]
>  I really like this discussion -- and just so you know -- I don't have a right/wrong or good/bad take.
Ofcourse @dthyresson, appreciate your input - not taken any other way! Likewise from me :)

Totally valid points, let's gets some more input from others here too!

**Comment by peterp** [comment]
Thank you both for having such a great discussion about this!

So, here's an idea: A developer can use "custom" as the provider type, and use the Authorization header to specify what kind of credentials they're passing.
```
Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l
Authorization: <Schema> <Credentials> 
```
The problem is that we don't pass the `schema` to `getCurrentUser` 🤦‍♂️

That said I also think this PR is also OK to merge because the main concern, for me, was to provide ample warning to the developer that they're specifying a client type that isn't supported. (We also do this via the client library)

I specifically wanted to catch cases where a developer could use "magic.link" instead of "magicLink," but I have types and maybe that's not a concern anymore.

**Pull request merged**
