### PR TITLE
fix(crwa): Explicit check for possible null value in `entry.client.tsx`

### LINKED ISSUE #9059: [Bug]: Generated entry.client.tsx isn't passing rw type-check
### What's not working?

The generated `entry.client.tsx` redwood uses/creates when enabling vite should be able to pass `rw type-check`

image

### How do we reproduce the bug?

You should be able to create a new repo and then just run `yarn rw type-check`

### What's your environment? (If it applies)

_No response_

### Are you interested in working on this?

- [ ] I'm interested in working on this

### PR DESCRIPTION
**Pull request by Josh-Walker-GM**
**Problem**
Fixes #9059 which is a type error raised when you have strict type checking enabled. The `getElementById` call can return null as the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById#return_value) mention.

**Changes**
Adds a basic null check taken from the solution given in #9059. 

**Considerations**
This adds some boilerplate code to a user facing file but I think it's a reasonable addition. It's readable and clear what the code is doing without the need for further explanation or technical knowledge. In the case where this causes a runtime error then the message is clearer:
Screenshot from 2023-10-02 23-16-38

I haven't immediately been able to think of some hidden solution to this that isn't exposed to the user in some boilerplate code.

### CODE REVIEW

**Comment by Josh-Walker-GM** [comment]
@jtoar - Do you think this one needs a larger team/group agreement or could we just get this in like any standard change?

**Comment by Tobbe** [comment]
I'd do `if (!redw...` but other than that it LGTM

**Comment by Josh-Walker-GM** [comment]
Happy to change it to the falsy condition

**Comment by Josh-Walker-GM** [comment]
I guess this would actually have to be a manual change for existing projects. Do we need to consider a codemod here or is the change simple enough to document? It's only encountered when you opt-in to strict types so there is already a manual barrier in that regard.

**Comment by Josh-Walker-GM** [comment]
Added the complementary codemod for this change. It should easily cover the vast majority of users - only those who have customised the `entry.client.tsx` file with things like variable renaming should have to implement the change manually. It's not a difficult change to implement anyway.

**Review by jtoar — APPROVED** [review]
thanks @Josh-Walker-GM!

**Pull request merged**
