### PR TITLE
Add curly rule for blocks

### PR DESCRIPTION
**Pull request by Krisztiaan**
ESlint rule against one-liners, see thread below.

> As for the braces for blocks, this should probably be enforced via `eslint`, because my (and potentially others') config defaults to one-liners.

💯  I was actually surprised it wasn't already a rule

_Originally posted by @Tobbe in https://github.com/redwoodjs/redwood/issues/1824#issuecomment-783354078_

### CODE REVIEW

**Comment by Tobbe** [comment]
Oops. That was a bigger change than I anticipated. Mostly in the structure package.

@peterp What do you think?

**Comment by thedavidprice** [comment]
Thanks, @Krisztiaan!

Looked through about half and agree this improves readability. I defer to PP for final say.

**Comment by Tobbe** [comment]
> Looked through about half and agree this improves readability.

It also makes it a lot easier and safer to add more code to a branch of the if/else-statement.

**Comment by peterp** [comment]
Love it 👍

**Comment by thedavidprice** [comment]
Hi @Krisztiaan I'd like to get this into the next release. There's a merge conflict from Peter's PR here https://github.com/redwoodjs/redwood/pull/1827

Didn't want to assume I could just move your change to `.eslintrc` over to the new `.eslintrc.js`. Guessing there might be some other updates as well. Sorry for the double work. Appreciate the help!

**Comment by Krisztiaan** [comment]
@thedavidprice Yeah you could. Rebased, should be g2g now.

**Pull request merged**
