### PR TITLE
Deprecate eslint-plugin-redwood

### PR DESCRIPTION
**Pull request by jtoar**
Last week @peterp mentioned that recent TypeScript additions made [`@redwoodjs/eslint-plugin-redwood`](https://github.com/redwoodjs/redwood/tree/main/packages/eslint-plugin-redwood) expendable. I tested this out by removing it, and it seems like TypeScript alone does indeed do the job, though the tooltip probably needs some work.

`eslint-plugin-redwood` is a custom ESLint rule we wrote that checks to see if the Pages you're referencing as Routes in your `Routes.js` file are actually in Pages in `web/src/pages`. If you do something like this, where `FakePage` doesn't exist:

```js
const Routes = () => {
  return (
    <Router>
      <Route name="fake" page={FakePage} />
      <Route notfound page={NotFoundPage} />
    </Router>
  )
}
```

you'll get the red squiggly line of death and a helpful tooltip:

image

Well, two helpful tooltips actually. The top one (`Page component not found`) is from TS, and the bottom one (`'FakePage' can not be...`) is from `eslint-plugin-redwood`. By removing this line from `@redwoodjs/eslint-config` (in a Redwood App's `node_modules`) 

https://github.com/redwoodjs/redwood/blob/36f2e823cdee5ba9d9448b8d5e5a666f5a5714fc/packages/eslint-config/index.js#L11

The tooltip is reduced to just the top warning:

image

> ~Notice that other error at the top that I'm still working out.~ Just worked that out.

So removing it seems easy enough. But I'm not sure how we'd go about deprecating it; it seems like something we'd just have to swap out. Also, does deprecating an internal package mean removing it from the repo? Or do we want to archive it somehow?

### CODE REVIEW

**Comment by jtoar** [comment]
Failing cypress test is a prerender timeout:

```
  Check Redwood cli commands against tutorial
    ✓ Should run api tests successfully (45863ms)
    ✓ Should run web tests successfully (37700ms)
    (Attempt 1 of 3) Should run build successfully (no prerender)
    (Attempt 2 of 3) Should run build successfully (no prerender)
    1) Should run build successfully (no prerender)
    ✓ Should prerender about and homepage (15983ms)


  3 passing (5m)
  1 failing

  1) Check Redwood cli commands against tutorial
       Should run build successfully (no prerender):
     CypressError: `cy.exec('cd /tmp/redwood.7o3NzL; yarn rw build --no-prerender')` timed out after waiting `60000ms`.

```

**Comment by peterp** [comment]
Awesome! Very few things are better than deleting code :)

**Comment by peterp** [comment]
I can run a npm command to deprecate it

**Review by peterp — CHANGES_REQUESTED** [review]
I left some comments clarifying your questions.

**Comment by jtoar** [comment]
@peterp awesome, thanks for the review! I think this is ready now—I'll rebase after I get the thumps up

**Review by peterp — APPROVED** [review]
LGTM

**Pull request merged**
