### PR TITLE
fix: Remove global context type from web side

### LINKED ISSUE #8314: [Bug?]: with auth setup, `context` on the web side is incorrectly typed
### What's not working?

Some api types are making their way to the web side. (Credit @KrisCoulson):

image

### How do we reproduce the bug?

- add auth to a new project or an existing one; I used dbAuth
- run `yarn rw dev` or `yarn rw g types` to get the types going
- type `context` into a web-side React component like HomePage, etc
- observe that it's typed as `GlobalContext`, which is an api-side type

### What's your environment? (If it applies)

_No response_

### Are you interested in working on this?

- [ ] I'm interested in working on this

### PR DESCRIPTION
**Pull request by cravend**
Closes #8314

### CODE REVIEW

**Comment by cravend** [comment]
Screenshot 2023-05-18 at 02 26 25
When you open the generated `global.web-auto-imports.d.ts` dist file in a project, this Typescript error is shown. However, the exact same TS error is also shown for the `gql` declaration that was already there:

Screenshot 2023-05-18 at 02 29 03

**Review by dac09 — APPROVED** [review]

**Comment by dac09** [comment]
Thank you @cravend! 

@KrisCoulson this is the bug you were seeing in Teamstream, I'm confident this is going to fix it but could you please try it out in Canary?

**Comment by cravend** [comment]
This is causing `yarn rw type-check` to fail... for some reason, I think that the CWD is not correctly changed, because the errors come from `../api/` rather than having the `api` directory be the base.

**Comment by cravend** [comment]
Also, I found an even simpler solution — this context declaration can be removed from both `global.{web,api}-auto-imports.ts` files, because it is already defined in [`api-globalContext.d.ts.template`](https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/generate/templates/api-globalContext.d.ts.template), which is only included by the api/tsconfig.json. I'll push that to see if it fixes the `yarn rw type-check`.

**Comment by cravend** [comment]
Also also, shouldn't `global.web-auto-imports.ts` (and api) be a `.d.ts` file? I can change that here if it makes more sense.

**Comment by dac09** [comment]
> Also, I found an even simpler solution — this context declaration can be removed from both global.{web,api}-auto-imports.ts files, because it is already defined in [api-globalContext.d.ts.template](https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/generate/templates/api-globalContext.d.ts.template?rgh-link-date=2023-05-18T16%3A20%3A06Z), which is only included by the api/tsconfig.json. I'll push that to see if it fixes the yarn rw type-check.

Yes looks like its still failing sadly... Not sure why though! I can't remember where this definition is being included / used. Shouldn't it be automatically be picked up by the includes in tsconfig?

> global.web-auto-imports.ts (and api) be a .d.ts file
In this case, no - because of how we build the package :). If it was a `.d.ts` file it wouldn't exist in the dist folder. Because its a ts file, the .d.ts is generated as part of tsc!

**Comment by Tobbe** [comment]
I'm cleaning up our PRs in preparation for the next major version of RW. This one seems to have gone stale, so I'm going to close it. 
I really appreciate the work that's gone into this PR 🌟 

If anyone is still interested in working on this feature or if there are any unresolved issues, please feel free to:
 1. Reopen this PR: If there are specific changes or updates needed.
 2. Create a new PR: In case you'd like to start fresh or make significant modifications.

Let's keep the collaboration going 🚂  If you have any questions or need assistance, don't hesitate to reach out. Thanks again for the contributions 🙏

**Pull request closed without merging**
