### PR TITLE
When scaffolding, generate Typescript layouts, pages, and cells

### PR DESCRIPTION
**Pull request by dthyresson**
Fixes https://github.com/redwoodjs/redwood/issues/2880

This PR address the issue that the scaffold generator does not create Typescript files.

Layouts, Pages, and cells now have the proper types set as needed.

The Page generator is async since it needs to know the model's idType to set as the id param -- String (cuid, uuid) and for numeric ids.

Result of 

```
yarn rw g scaffold UserExample
```

in a Typescript generated CRWA.

image

### CODE REVIEW

**Comment by dac09** [comment]
LGTM! Just needs those templates being changed from js to ts, and making sure TS isn't generated for JS projects (you can see them in the snapshot tests too).

**Review by dac09 — APPROVED** [review]
Approved, pending above changes :)

**Comment by dthyresson** [comment]
> Approved, pending above changes :)

Thanks! I am still validating e2e as seeing some odd behavior in JS mode.

**Comment by dac09** [comment]
> > Approved, pending above changes :)
> 
> Thanks! I am still validating e2e as seeing some odd behavior in JS mode.

Content just needs to be transformed like this here: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/page/page.js#L101

**Comment by thedavidprice** [comment]
Per discussion, this PR will include work for #734

**Comment by dthyresson** [comment]
> Per discussion, this PR will include work for #734

Actually, tackling as a separate PR. Converting to jsx has other considerations (individual generators, stories, Routes, App) and also may involving changing babel as some jsx files got generated with `;` endings even though template did not have them and some imports failed.

Therefore, #734 is better as a distinct PR.

**Pull request merged**
