### PR TITLE
Make casing consistent for generators

### LINKED ISSUE #4429: Casing of generated components not as expected
When I generate a component with consecutive uppercase letters the resultant components' files don't match their respective declarations.

1. yarn rw g component QRCode
2. files are output as ./web/components/QRCode/QRCode.tsx (and others)
3. file contents declare themselves as QrCode
4. startup storybook and get an error

```
ModuleNotFoundError: Module not found: Error: [CaseSensitivePathsPlugin] `[...]/screens/web/src/components/QRCode/QrCode.tsx` does not match the corresponding path on disk `QRCode.tsx`.

IssueWebpackError: TS1261: Already included file name '[...]/screens/web/src/components/QRCode/QrCode.tsx' differs from file name '[...]/screens/web/src/components/QRCode/QRCode.tsx' only in casing.
  The file is in the program because:
    Imported via './QrCode' from file '[...]/screens/web/src/components/QRCode/QRCode.stories.tsx'
    Imported via './QrCode' from file '[...]/screens/web/src/components/QRCode/QRCode.test.tsx'
    Root file specified for compilation
  > 1 | import QrCode from './QrCode'
```

I'm fine with Redwoods' opinions about how to case names, either one works for me

In this case I renamed the files, choosing to stick with the declarations

### PR DESCRIPTION
**Pull request by jtoar**
Closes #4429. The logic around pascal casing was different for file names and file contents. This PR makes them consistent, preferring the logic for file names.

### CODE REVIEW

**Comment by jtoar** [comment]
@cannikin I feel like this has come up before—that something like `QRCode` should keep it's uppercase casing (and not become `QrCode`). Making it so looks like it'll require changing `nameVariants` slightly. Since that's used in like all the generators, I'll see what the implications are.

**Comment by Tobbe** [comment]
> @cannikin I feel like this has come up before—that something like `QRCode` should keep it's uppercase casing (and not become `QrCode`). Making it so looks like it'll require changing `nameVariants` slightly. Since that's used in like all the generators, I'll see what the implications are.

We have talked about this before. Fwiw I'm fine with `QrCode`. And `DVDPlayer` -> `DvdPlayer`. I think I actually prefer that.

**Comment by cannikin** [comment]
Yeah I don't think we can do this, we need to just be consistent everywhere: whatever you give us becomes PascalCase, we can't have some caps and some not caps, other things down the line (like Prisma) won't like it. We did this somewhere else, someone was talking about stuff like `APIEndpoint` and we updated it to be `ApiEndpoint`.

So whatever this PR does, it actually needs to do the opposite. hahaha  Keep `QrCode` where it's being generated now, and change instances of `QRCode` to be `QrCode`.

**Comment by cannikin** [comment]
Now I'm confusing myself looking through our comments, but found the issue and PR: https://github.com/redwoodjs/redwood/issues/3568 and https://github.com/redwoodjs/redwood/pull/3570

**Comment by cannikin** [comment]
I think ended up saying we WOULD preserve multiple capital letters in a row in that issue/PR. 😬

**Comment by Tobbe** [comment]
Thanks for linking the previous PR Rob. Like @aggmoulik said "I am with the community I just want to share my views". So QRCode it is I guess :)

**Comment by Tobbe** [comment]
Today I ran into a situation where things would straight out break for ALLCAPS model names. See UOM here https://github.com/redwoodjs/redwood/issues/4394

**Comment by jtoar** [comment]
This was one of those PRs I thought would be an easy fix, but there was of course more to it. Still is something that I'd like to see fixed but since we're closing out stale PRs, maybe another time when the generator code is easier to work with.

**Pull request closed without merging**
