### PR TITLE
[forms] Fix number validation msg

### PR DESCRIPTION
**Pull request by andrew-hwahin**
Fix issue #2551

Following is the verified result.

image

image

Sorry for the irrelevant commits, I'm still learning how to fork and contribute. 😅

### CODE REVIEW

**Review by Tobbe — APPROVED** [review]

**Comment by Tobbe** [comment]
You know what would be great? Some tests for this. It's obviously something we're totally missing right now 😅

Do you think you could have a look at adding tests for all the validation messages?

**Comment by Tobbe** [comment]
And hit me up on Discord if you want any help with forking or other git stuff. I can jump on a call and show you.

**Comment by andrew-hwahin** [comment]
I have not written any test before and would need some time to learn how to do so, should we create a separate issue for that?

Previously I performed the modification for this pull request #2487 on the "main" branch of my fork, I think that is why when I open a new branch to fix this issue, all the commits are following along, should I re-fork again?

**Comment by Tobbe** [comment]
For running the tests I can recommend giving this a read ;) http://tlundberg.com/blog/2020-06-21/running-specific-tests-redwoodjs/  (Not biased at all! 😛)

**Comment by Tobbe** [comment]
> Previously I performed the modification for this pull request #2487 on the "main" branch of my fork, I think that is why when I open a new branch to fix this issue, all the commits are following along, should I re-fork again?

You only need one fork. But it's good practice to always create a new branch when you want to work on a new PR. But, no worries, `git` is awesome in that there is (almost) always a way fix whatever screw-up one might have done 😁 In this case I'd reset your branch for this PR to upstream/main, and then cherry-pick the commit(s) you've already done for this fix, and finally force-push to origin/main. Then you have your branch in a clean state where you can continue pushing extra commits, like for tests for example.

**Comment by jtoar** [comment]
Closes #2551

**Comment by thedavidprice** [comment]
Thanks for this @andrew-hwahin! I'm merging now.

I'll let you and @Tobbe discuss a possible follow-up PR for tests. But I agree let's separate into two parts.

**Pull request merged**
