### PR TITLE
testing.md: Update file path in code snippet

### PR DESCRIPTION
**Pull request by makdeb**
The title/path pointed to the wrong file
image

### CODE REVIEW

**Comment by Tobbe** [comment]
@makdeb You marked this as "Draft". Were there more changes you wanted to make?

**Comment by makdeb** [comment]
> @makdeb You marked this as "Draft". Were there more changes you wanted to make?

Actually, I did want to. I wanted to propose a better test to avoid throwing an error in case there are two or more equivalent posts (or at least with similar body) in the ArticlesCell.mock
https://redwoodjs.com/docs/tutorial/chapter5/first-test#adding-the-test
Although this could be another homework for readers, so I'm not sure about this.

**Comment by Tobbe** [comment]
> I wanted to propose a better test to avoid throwing an error in case there are two or more equivalent posts (or at least with similar body) in the ArticlesCell.mock
> [redwoodjs.com/docs/tutorial/chapter5/first-test#adding-the-test](https://redwoodjs.com/docs/tutorial/chapter5/first-test#adding-the-test)
> Although this could be another homework for readers, so I'm not sure about this.

I'm also not sure, but if it's going to be a PR, let's create another one for that 🙂

**Comment by Tobbe** [comment]
Thanks for your first PR @makdeb!

**Pull request merged**
