### PR TITLE
Use CheckboxField for Boolean fields on scaffolded forms

### PR DESCRIPTION
**Pull request by lachlanjc**
This PR uses the new `CheckBox` component from #488 instead of `TextField` automatically for Boolean fields in scaffolded forms, with a simple place to add other components for other field types. The majority of the diff is adding a Boolean field to the test app to verify this works reliably.

If #493 gets merged first, there will be a small merge conflict, but should be an easy fix. (Update: fixed it!)

### CODE REVIEW

**Comment by peterp** [comment]
Love it, thank you!

**Comment by cannikin** [comment]
@lachlanjc awesome, thanks! 

I actually haven't used checkboxes in react-hook-form yet, but what gets submitted when you leave a checkbox blank and submit the form? The HTML standard says that if a checkbox doesn't have a field then it is not submitted through the form at all. It makes it very hard to tell from the server side if you want to turn a checkbox off, or if you just didn't include it in your form.

Ruby on Rails gets around this by giving the checkbox a value of `1` and making a second, hidden field with the same name as the checkbox box field, with the value `0`. If you check the box on then it's name attribute overrides the hidden field's value and `1` gets submitted. Otherwise the `0` gets submitted. This way you're always passing a value to the server whether or not the checkbox is on.

Have you used this in your own scaffolds? What's the behavior like?

**Comment by cannikin** [comment]
> @lachlanjc awesome, thanks!
> 
> I actually haven't used checkboxes in react-hook-form yet, but what gets submitted when you leave a checkbox blank and submit the form? The HTML standard says that if a checkbox doesn't have a check then it is not submitted through the form at all. It makes it very hard to tell from the server side if you want to turn a checkbox off, or if you just didn't include it in your form.

Answered my own question! The field is always included in the resulting object and it's `false` if the checkbox isn't checked! AWESOME

**Comment by cannikin** [comment]
But now the problem is: if the field is required in the schema, it will be required in the generated scaffold, which means it being checked *on* is required for the form to submit. This is probably not the intended behavior. Yes, it shouldn't be `NULL` in the database, but you should be able to submit either a `true` or `false` via the form submit.

What should we do about this? Somehow ignore Boolean fields from the `{ required: true }` check that goes into the generated form template?

**Comment by lachlanjc** [comment]
Ok, sounds good. Yep, I was super confused why my Boolean fields were marked as required in the template. That’s a simple fix :+1:

**Comment by cannikin** [comment]
Note this one might be merging soon which will change `<CheckBox>` to `<CheckboxField>`: https://github.com/redwoodjs/redwood/pull/511

Whoever merges first wins, the other one has to update this code. ;)

**Comment by lachlanjc** [comment]
Beautiful. When I add this, I'll use the new field names

**Comment by Terris** [comment]
@lachlanjc @cannikin Hi there. Just wanted to share some thoughts based on some experimenting I've done with required boolean fields in my schema and the checkbox field in my scaffolded forms. Starting here:

> What should we do about this? Somehow ignore Boolean fields from the { required: true } check that goes into the generated form template?

Including the { required: true } validation props on the CheckboxField component is obviously producing some undesirable results as the user should be able to leave it unchecked. To my mind, it isn't necessary to include { required: true } in the form template since the checkbox will reliably submit _a value_ (true or false) so long as it is present in the form. I've tested this in Chrome, Safari, and Firefox—all with the same result.

However, in order to persist the selected value—for instance, such that the checkbox remains checked or unchecked on the edit form—I've found it more useful and behaviorally predictable to use the `defaultChecked` prop for the selected value and to set the defaultValue to true like so ([in reference to this line](https://github.com/redwoodjs/redwood/pull/495/files#diff-c3c51a9b18305887f732e7148f3695f9R125)):

```javascript
<CheckboxField
   name="isPinned"
   defaultValue={true}
   defaultChecked={props.post?.isPinned}
/>
```
This will persist the selected value and insist that the submitted value is true if checked or false if unchecked.

An aside—one caveat of the checkbox input that I've discovered is that it's submitting a "true" or "false" value in string format which GraphQL's type checking doesn't like, for good reason. In my experiments, I've successfully implemented some massaging in the onSubmit function of the PostForm.js template. E.g.:

```javascript
const onSubmit = (data) => {
    data.isPinned = data.isPinned === 'true' ? true : false
    props.onSave(data, props?.ticket?.id)
  }
```

Not particularly elegant and certainly I'm open to suggestions :)

**Comment by cannikin** [comment]
@lachlanjc That PR got merged #511 so you should be good to go! What do you think about @Terris observations here?

I thought I tested checkboxes and found they were returning actual `true` and `false` rather than strings...was that a dream I had? If so, in the scaffolded forms we added a step to convert inputs that need to be integers for GraphQL: https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template#L21 We could do something similar for booleans...although that's getting to be a lot of ugly, long lines of code. Maybe we could refactor all of that into something like a `castInputs()` function that the New and Edit forms can share.

**Comment by Terris** [comment]
@cannikin @lachlanjc 

> I thought I tested checkboxes and found they were returning actual true and false rather than strings...

You are correct @cannikin and I was mistaken. Apologies. The string value is actually a result of setting `defaultValue={true}` which isn't necessary as the checkbox submits true / false values by default, just as you observed. As long as `defaultChecked={props...}` is used the selected value will persist.

It should be clear, though, that setting `defaultValue={props.post?.isPinned}` will result in an undesirable  behavior: If the stored value in the database = false, then a checked checkbox will submit as false because it will have rendered something like `<input type="checkbox" value="false" />`.

So my suggested implementation is to swap defaultValue for defaultChecked props like so:

```javascript
<CheckboxField
   name="isPinned"
   defaultChecked={props.post?.isPinned}
   ...
/>

```
...and then no casting required. 💪

**Comment by cannikin** [comment]
@Terris Ahh okay, that makes more sense! Yes that change sounds good to me. We've done some refactoring of the inputs and all types are built in one loop now, the only difference being the value of `type`. We'd need to make some changes for checkbox (and maybe radios should use the same `defaultChecked` prop?) to be unique from the others.

**Comment by cannikin** [comment]
@Terris We have a coercion plan in process that should handle this for us going forward: https://github.com/redwoodjs/redwood/issues/608#issuecomment-637761055

**Comment by Tobbe** [comment]
I'd love to see this merged, but the code needs some updates in light of recent code changes. Is there any way I can help with that?

**Comment by thedavidprice** [comment]
@Tobbe No, you cannot. You'd need to fork `lachlanjc:scaffolds-use-checkbox-fields` and then PR/commit against that branch. :-/
- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

@lachlanjc are you available and/or could you give @Tobbe commit permissions to your fork?

**Comment by Tobbe** [comment]
Updated code here: https://github.com/redwoodjs/redwood/pull/646

**Comment by thedavidprice** [comment]
Hi @lachlanjc I’m seeing your activity here, thanks! Question: are you coordinating with @Tobbe and/or have you seen his work over here #646?

**Comment by lachlanjc** [comment]
Thanks so much for the work @Tobbe & the input @Terris!

@thedavidprice I’ve updated so checkbox fields use `CheckboxField` instead of `Checkbox`, not be required, & to use `defaultChecked` instead of `defaultValue`. #646 looks great but doesn’t have those second two parts. I’ve run an example app locally to verify the scaffolds are generated correctly, & updated the tests. (& considering the number of commits here, you’ll probably want to squash the branch.)

**Comment by cannikin** [comment]
Battle of the PRs! Where does this one stand vs #646? What is happeningggg

image

**Comment by lachlanjc** [comment]
Haha sorry @cannikin. Super appreciate #646, but this PR additionally removes the `required` validation & uses `defaultChecked` instead of `defaultValue`.

**Comment by Tobbe** [comment]
Only reason I made #646 was to get things moving along. And, mission accomplished! 😃 
@lachlanjc has done great work here, LGTM!

**Comment by thedavidprice** [comment]
@lachlanjc checking back on this one -- did you see the review comments from @cannikin? And no pressure per availability on your end, but any updates about potential ETA? 

Thanks!

**Comment by Tobbe** [comment]
I've tried this trick before--let's see if it works again 😜

Updated PR here: #719

**Comment by lachlanjc** [comment]
Sorry for the delay, had a lot of work on this sitting locally but been super busy launching some new projects. Will address in the next few days!

**Comment by cannikin** [comment]
Closing this because we just merged #719 

Thanks for initial work on this and getting the ball rolling, but we've got several features waiting on this one and just needed to get this feature in there so we can start work on those.

**Pull request closed without merging**
