### PR TITLE
Adds warning in auth templates about the return of getCurrentUser() on the web side

### LINKED ISSUE #3632: Update dbAuth auth.js template/comment to select minimal data from getCurrentUser()
Right now the default template for `api/src/lib/auth.js` looks up the user, selecting all db column data, and making them available as `currentUser` on both the web and api sides. The "selecting all attributes" part is dangerous, as by default this would include things like `hashedPassword` and `salt`, which, on the server (api side), wouldn't be an issue. But this data is also sent down to the client (web side).

We're going to update the default template to only select the user's `id` out of the box. A comment above the function will explain the implications of changing this list of attributes.

We'll also update the templates for the other auth clients explaining the implications of adding more data to the response object.

### PR DESCRIPTION
**Pull request by cannikin**
Also updates dbAuth's auth template to only select the `id` from the user record in the database.

Not sure that these are absolutely needed, but if we want to point out the change in the Release Notes:

## Release Notes

If you are using dbAuth, the default `getCurrentUser()` function in `api/src/lib/auth.js` returns a complete user record in your database. You may not be aware, but anything returned from `getCurrentUser()` is sent down to the client, and could be viewed by anyone who inspects requests back and forth to the server. Starting with this release we're only returning the `id` field on the user by default, and it's up to the developer to add more fields. If you want to update your `getCurrentUser()` to match our newly generated code, replace yours with this:

```javascript
export const getCurrentUser = async (session) => {
  return await db.user.findUnique({
    where: { id: session.id },
    select: { id: true }
  })
}
```

If your table is named something other than `user` you'll need to change that property on the `db` call. Add any additional fields you want to return to the `select` object. You can read more about Prisma's `select` syntax in [their docs](https://www.prisma.io/docs/concepts/components/prisma-client/select-fields#select-specific-fields).

---

Closes #3632

### CODE REVIEW

**Comment by thedavidprice** [comment]
@cannikin are you waiting for a review on this one? Or anything else to help?

**Comment by cannikin** [comment]
Yeah, thought maybe someone wanted to review, but if not, MERGE IT

**Comment by thedavidprice** [comment]
Looping in @dthyresson DT, not sure if you audited template TS here per #3596

**Review by dthyresson — APPROVED** [review]
Message seems appropriate.

In future, I do wonder if there would be two currentUsers -- something that sets the info in the browser and something that can be uses api-side.

This may not be an issue, if instead of storing the decoded JWT in localStorage, a session cookie is used.

**Pull request merged**
