### PR TITLE
fix: `emotion` compatibility with latest storybook

### PR DESCRIPTION
**Pull request by callingmedic911**
This is a work in progress, I'll add more details.

Currently Storybook doesn't seem to work with the latest [emotion](https://www.npmjs.com/package/@emotion/core). I had to modify some emotion fallback introduced with Chakra integration. Assuming this is related: https://github.com/storybookjs/storybook/issues/16547

Need to do next:
- [x] Understand the context for existing `withEmotionVersionFallback`
- [x] ~Test compatibility with combination of older emotion (and storybook?)~ Removed feature flag
- [ ] Test if Chakra is still functional
- [x] ~If checking `@emotion/core` is sufficient to disable emtion alias.~ Removed feature flag

cc: @dac09 @virtuoushub

### CODE REVIEW

**Comment by TimKolberger** [comment]
Hi there :wave:

> Understand the context for existing withEmotionVersionFallback

The function `withEmotionVersionFallback` handled the emotion version mismatch of storybook and Chakra UI, before the feature flag `emotionAlias` was added in Storybook 6.4.
It can be safely omitted, if the Storybook version is >= 6.4.

**Comment by dac09** [comment]
Thanks @TimKolberger appreciate the insight!

**Comment by jtoar** [comment]
Thanks @TimKolberger! We did just upgrade to Storybook 6.5—it passed CI and everything but should be tested a bit more—so we may actually be in the clear here.

**Comment by TimKolberger** [comment]
Awesome! 🚀

**Comment by jtoar** [comment]
@callingmedic911 is it possible for you try the latest canary to see if it fixes the issue?

**Comment by callingmedic911** [comment]
Yep, sure. What is changed btw?

**Comment by jtoar** [comment]
@callingmedic911 the latest canary upgraded to Storybook v6.5.3 which may already fix the issue.

**Comment by callingmedic911** [comment]
@jtoar With the latest canary, I just omitted the fallback function and the storybook was up. It didn't need `emotionAlias` feature flag. Updating this PR.

**Comment by dac09** [comment]
Remember to also double check chakra please?

**Comment by callingmedic911** [comment]
I just tried Chakra. 
- Created test project. `yarn run build:test-project <test>`.
- Setup Chakra using docs here: https://chakra-ui.com/guides/getting-started/redwoodjs-guide 
- and then added a `Button` component as a test.

Ran across issue spinning up `rw dev` and `rw storybook`: Latest Chakra depends on React 18 APIs (error in `@chakra-ui/hooks/dist/chakra-ui-hooks.esm.js`) but Redwood doesn't support React 18 just yet.

So I downgraded to `@chakra/react` to v1.3.0 and the storybook was running fine with these PRs changes. So unrelated to this PR, @TimKolberger @jtoar should we pin version `@chakra/react` to the latest v1 in `rw setup ui chakra-ui` till we have React 18 support?

**Comment by jtoar** [comment]
@callingmedic911 yeah that's probably the best way forward. We can release a patch with that fix. Should be a one-liner right?

**Review by jtoar — APPROVED** [review]
This looks good. Going to get this into the minor RC, which has Storybook v6.5.4, to see if this fixes MUI for @MichaelrMentele.

**Pull request merged**
