### PR TITLE
WIP: Improved Scaffold error output

### LINKED ISSUE #787: Improving scaffold error output
If scaffolding the first file (the sdl) fails, it might be clearer to _not_ say "Writing..." for all the other files. 

rw-scaffold-failure

I think the original thinking was: the fact that we use a gerund should mean that nothing has actually been written (plus, there's no green check). But the fact that there's only one red X instead of red X's across the board might leave some users wondering, "But what about the other files?"

I think the original thinking was: the red X is to show exactly where the scaffold failed. And since the other files didn't fail (moreover, didn't even start), it'd technically be incorrect to red-X them.

For reference, here is successful scaffold output:

rw-scaffold-success

The current design makes the most sense in light of the partial success output:

rw-scaffold-success-partial

The way our CLI's setup, it's probably too hard to suppress output if the scaffold fails. But what we could do is add some kind of identifier (like a dash: - ) next to the tasks that haven't started.

Discord message for reference: https://discord.com/channels/679514959968993311/716252919875240007/728024690433589301 (do these links actually work?)

### PR DESCRIPTION
**Pull request by santhoshle**
Fixes #787 

Currently improved the scaffold output handling while generating the files.

### CODE REVIEW

**Comment by peterp** [comment]
Hey @santhoshle 

This is nice! Can you add a screenshot of what it'll look like when you're done?

**Comment by santhoshle** [comment]
Thanks @peterp. 
Here is a screenshot of the improved scaffold.
command_generate

**Comment by peterp** [comment]
This is awesome, thanks @santhoshle ! I saw it's still a WIP, is that still the case or can we review it?

**Comment by thedavidprice** [comment]
@peterp wanted to check on two things with you:
- Are you ok with the specific Task Titles? I am, but just wanted feedback as I suggested them originally
- This modifies all generators. I'm taking a quick look around to make sure there isn't somewhere it _doesn't_ make sense. I think it will be helpful across the board, most likely.

**Comment by peterp** [comment]
@thedavidprice I like the wording 👍, and I don't think it'll be a problem for the other generators 👍

**Review by thedavidprice — APPROVED** [review]

**Comment by thedavidprice** [comment]
Just did a sanity check and agree, it improves across the board! Thanks for confirming as well.

**Pull request merged**
