### PR TITLE
GH Action to create packages from PRs

### LINKED ISSUE #1458: Publish PR packages to NPM
Currently whenever a PR is merged a "canary" package is automatically published to npm. This is a super nice feature! I'd like to suggest we expand this to also automatically publish PR packages as soon as a PR comes in (and it passes all tests).

This idea originally came up in chat, so here's the transcript

> @Tobbe: Like if I make a PR (and all tests pass), could we publish a pr version of RW? Like 0.20.0-pr.5557. That would make it really easy for someone to test my PR changes by just installing that RW version
> @dthyresson: that might publish code that has not been reviewed though or approved.
> @Tobbe: Yeah, any PR would become a package. But the only way to install that package would be to explicitly specify the exact package name.
> @Tobbe: It would, for example, let me make a PR for my version of RW without apollo client, and you could install the package to test it out
> @Tobbe: So it's easier for anyone to test stuff before it gets merged (and a canary release is available)

The need/want for this recently came up again here https://github.com/redwoodjs/redwood/pull/1311#issuecomment-723924890 which prompted me to create a proper issue for it

### PR DESCRIPTION
**Pull request by Tobbe**
This is a Github action that builds PR branches and runs `npm pack` to create packages. These packages are then uploaded to s3 and links are posted as a comment on the PR

image

Before merging this PR AWS secrets should be added to the repo (I don't have access to do that)

Resolves #1458

### CODE REVIEW

**Comment by jeliasson** [comment]
Great work @Tobbe! 🎉
What's the reason you deleting `build-eslint-jest.yaml`, `netlify-build.yaml` and `publish-npm-canary.yaml`?

**Comment by Tobbe** [comment]
Yeah, should not delete the other workflow files. That was not supposed to be part of this PR. I did that (on another branch I though) on my own fork of RW to lessen the noise when building and testing this thing. Will re-add.

The tests were done on my own s3 bucket (Free tier). Before merging we need keys and secrets for a proper one to use. But there will only ever be one set of binaries stored for a PR. When you push new code the old binaries get overwritten.

I'll see about retention policy. Otherwise we'll have to write our own scheduled clean-up.

**Comment by Tobbe** [comment]
I added a 90 days retention rule. Was easy enough to set up 🙂 Great idea @jeliasson!

**Comment by Tobbe** [comment]
The packages for one build totals 619.9 KB. Currently we have 25 PRs open, so like 15 mb in total... I don't think storage is going to be a problem 😁

**Comment by peterp** [comment]
Aw yeah! I'll get those s3 details and then we can merge this - is that comment added whenever a user commits something?

**Comment by Tobbe** [comment]
There is an `allow-repeats: false` setting. Right now it's set to `false`, as you can see. That means the comment will only be posted once. If we want it for every commit we can switch it to `true`

**Comment by jeliasson** [comment]
I have tested this to build #1311 via `Tobbe/redwood` and it works great. Wrote a [short writeup](https://gist.github.com/jeliasson/f7c6276c061c948d0f30d2c3e7f43271) for a few people that was eager to start working on the auth.

While I think this is mergable right now, I see a few improvements going forward:
1. Have the commit sha in the filename to be deterministic, and to rule out any server- or client caching (if any).
2. For every build, update the bot comment with the latest build and/or create a gist with the history, [example here](https://gist.github.com/jeliasson/c852c0963bf3f2270eae90eec84e2cbf). 
3. Identify what packages goes where (checking `package.json`'s?) and to generate a `yarn [...] add` list and avoid hard-coding.
4. Handle issue where `@redwoodjs/auth` is being reverted back to current `0.20.0` when running `yarn rw g auth [...]` (later `yarn rw setup auth [...]`)
5. Extend the Redwood upgrade CLI (e.g. `yarn rw upgrade --pr [number/sha]`) to install the PR builds.

Thoughts?

Again, good work @Tobbe!

**Comment by Tobbe** [comment]
Great summary @jeliasson. I agree that this is mergeable as-is. Then, in future PRs, your suggestions can be addressed. As we chatted about, I think having unique filenames per commit/build is what I'm going to focus on first. 

4. is an issue we're also seeing when working on the `setup` command, especially the tailwind setup. Everything has to be done in exactly the right order otherwise packages will get overwritten. A few practice runs, and I think we'll figure out a way-of-working that can be documented. Or we jump straight to 5. 🙂

**Comment by peterp** [comment]
I've added the secrets and we're creating the bucket.

**Pull request merged**
