### PR TITLE
Update GraphQL Explorer in the Tutorial

### PR DESCRIPTION
**Pull request by jtoar**
Closes https://github.com/redwoodjs/redwood/issues/5016. I've still got one more to replace.

### CODE REVIEW

**Comment by Philzen** [comment]
Looks awesome :rocket: :tada: 

Happy Redwood v1.0.0 day :smile_cat: !

**Comment by Philzen** [comment]
@jtoar I've realized your (and @simoncrypta's)  commit messages often start with lowercase.

I'm unaware whether RedwoodJS employs rules of engagement for writing commit messages – but when in doubt i always apply the 7 "golden rules" from this excellent article: https://chris.beams.io/posts/git-commit/ :monocle_face:

**Comment by jtoar** [comment]
@Philzen right now we don't have any rules of engagement, just conventions. As to the lowercasing the first word, it's probably my slack tendencies seeping into my commit messages haha.

When a PR's merged to main its commits are squashed. But I could definitely put a little more thought into some of my commit messages. We may have considered commit hooks in the past, but it was too much friction at the time. Is that something you'd like to see though?

**Comment by Philzen** [comment]
> Is that something you'd like to see though?

@jtoar It's really not about what *i'd* like to see, i guess. However, since i started adhering to those seven rules a few years ago all my commit histories have become more beautiful and better to read, and i've successfully introduced them to all the teams i've consulted with so far. There merely a best practice that the Spring team has come up with after years of initial chaos :wink:  

i didn't realize that the project is configured to squash all commits on merge. In that case it really doesn't matter that much, apart from PR name to be formatted nicely, preferably according to the 7 rules. 

Has this setup been a conscious decision? It has a few pro's an cons. Almost all projects i work on nowadays keep the individual commits and created a seperate merge commit that has all the individual commits linked to it. The advantage is, that when there was a single offending commit in the merged feature branch, it's easy to revert just that one without having to revert all other nice functionality that came with it.

Disadvantage is: git fanboys like me will nag the hell out of the contributors' commit history until it is only contains perfectly crafted, atomic commits with flawlessly formatted commit messages :laughing:

**Comment by Philzen** [comment]
> Sometimes over 30! And most with the title "wip" (work in progress) sweat_smile

That's what git interactive rebase, fixup, and amend were made for ;)

**Comment by jtoar** [comment]
I love rebase! But not everyone does. 😅 While rebase feels like a legit superpower, it took me quite some time to learn, and I actually still can't do it without emacs ([magit](https://magit.vc/)). So it'd just be hard to communicate that we expect everyone to clean up history before merging. Better to just squash it all 🤷

**Pull request merged**
