### PR TITLE
Check if prisma schema has the correct binary targets before deployin…

### PR DESCRIPTION
**Pull request by hemildesai**
…g to aws via serverless

### CODE REVIEW

**Comment by hemildesai** [comment]
Not sure why the tests are failing on windows. The failures seem totally unrelated to the change.

**Comment by thedavidprice** [comment]
@hemildesai Windows CI fail is likely a cache issue (false positive Cache Hit in the runner when instead it needs to run yarn install). It's become an ongoing problem and I'll try to look into it now.

For this PR, I'd recommend you go ahead and add the binary target to schema.prisma and then provide a message at the end of the output. With other "setup" commands, we are doing code modifications like this as it seems to provide a better DX overall.

Thoughts/discussion either way?

**Comment by hemildesai** [comment]
Yeah I can work on adding it directly during setup. I'll close this PR and start a new one for that.

**Comment by thedavidprice** [comment]
@hemildesai just nudging you here about adding the binary target during CLI setup. Would be a good improvement if you have the time.

**Comment by hemildesai** [comment]
@thedavidprice Yeah I'll get the PR in soon.

**Pull request closed without merging**
