### PR TITLE
Return reply from fastify handler

### PR DESCRIPTION
**Pull request by mwoenker**
See https://www.fastify.io/docs/latest/Guides/Migration-Guide-V4/#need-to-return-reply-to-signal-a-fork-of-the-promise-chain

This fixes returning a Stream as the body of the response from an api function.

### CODE REVIEW

**Comment by jtoar** [comment]
Hey @mwoenker thanks for your PR and patience! I thought I saw this brought up somewhere else, but I can't remember whether it was an issue, or on the forums or Discord. (I tried searching each briefly but couldn't find anything.) This change seems simple enough and adds up based on the doc you linked to. @dthyresson any thoughts?

**Comment by jtoar** [comment]
Do we need to make the change here too?

https://github.com/redwoodjs/redwood/blob/main/packages/api-server/src/requestHandlers/awsLambdaFastify.ts#L77

**Comment by dthyresson** [comment]
Thanks @mwoenker 

Is there a way to test this behavior in `packages/api-server/src/__tests__/requestHandlers/awsLambdaFastify.test.ts`?

Something like:

```
  test('requestHandler replies with simple body', async () => {
    jest.spyOn(mockedReply, 'send')
    jest.spyOn(mockedReply, 'status')

    const handler = async (req, mockedReply) => {
      mockedReply = { body: { foo: 'bar' } }
      return mockedReply
    }

    await requestHandler(request, mockedReply, handler)

    expect(mockedReply.send).toHaveBeenCalledWith({ foo: 'bar' })
    expect(mockedReply.status).toHaveBeenCalledWith(200)
  })
```

But for a stream?

**Comment by mwoenker** [comment]
@dthyresson I've pushed a test. It tests to see if the stream is passed to `send()`, but also whether the reply is returned from `requestHandler` which is the thing that will actually change as a result of this patch. Maybe the other tests should check that as well?

**Comment by dthyresson** [comment]
@dac09 I think this is the issue we fixed this morning https://github.com/redwoodjs/redwood/issues/6765

**Pull request closed without merging**
