### PR TITLE
fix/supabase version 1

### PR DESCRIPTION
**Pull request by duncanhealy**
- fix methods used by supabase 1.0 #1426
- update supabase package to 1.0 #1426

### CODE REVIEW

**Comment by dthyresson** [comment]
@Tobbe and I realized tonight that perhaps something changed in the Supabase API that will no require a custom decoder to extract the `currentUser` info on the API side.

see: https://github.com/redwoodjs/redwood/blob/2b18246ef41ea92a0336f9d719e587d1cb6a5b13/packages/cli/src/commands/generate/auth/templates/auth.js.template#L100

```
export const getCurrentUser = async (decoded, { _token, _type }) => {
  return { ...decoded, roles: parseJWT({ decoded }).roles }
}```
 It is "spreading" the JWT into chars -- and not sure if it did that in the past.

This might mean that supabase should get its own decoder similar to what is done for Netlify Identity:

https://github.com/redwoodjs/redwood/blob/main/packages/api/src/auth/decoders/netlify.ts

where is

```
jwt.decode(token)
```

so that `currentUser` will have the decoded version of it.

Note: this does not verify the accessToken, though it probably should ... to check for expiry against the secret --- which would be then a required env.

**Comment by Tobbe** [comment]
I'm adding a comment here, mainly for myself, to understand what's going on.

So, supabase were missing some TypeScript types in their GoTrue library.
This has now been fixed thanks to https://github.com/supabase/gotrue-js/pull/24
So, now we're waiting for a new release of gotrue-js (new releases will show up here https://github.com/supabase/gotrue-js/releases)
After that we'll have to wait for a release of supabase-js that includes this new gotrue-js version (https://github.com/supabase/supabase-js/releases)
Once we have this, we can finish off this PR

@duncanhealy Does the above sound correct to you?

**Comment by duncanhealy** [comment]
yup! The api surface for supabase 1.0 changed as well as documented by the issue #1426 but I think we have accounted for that with the changes

The draft supabase.ts just has a mockup of the types - not sure if it is correct
I will pull down your supaslack example to see if works as is with version bumped

**Comment by viperfx** [comment]
@Tobbe can you clarify why a wait of a new release of the goTrue library is needed?

**Comment by viperfx** [comment]
does @kiwicopple know a new release is needed? for us to continue with this release.

**Comment by kiwicopple** [comment]
thanks for the tag @viperfx.

I just released the new version of gotrue-js to include @duncanhealy's [commit](https://github.com/supabase/gotrue-js/pull/24#issuecomment-734195751) , then bumped the version in supabase-js. 

> The draft supabase.ts just has a mockup of the types - not sure if it is correct

Let me know if that's all you need here, otherwise I can jump in and figure out the types. I did actually start on this but I'm swamped with our beta launch - thanks the patience 🙏

**Comment by viperfx** [comment]
Thanks @kiwicopple 

Look forward to these changes @duncanhealy 

Let me know if you need help testing.

**Comment by duncanhealy** [comment]
I'm getting null back for the user object from the graphql endpoint after logging in 
```json
{"data":{"redwood":{"currentUser":{"0":"n","1":"u","2":"l","3":"l","roles":[]}}}}
```
looking at local dev -> might be because of this
https://github.com/redwoodjs/redwood/blob/1185f0f0b06c11004e7c0d86c19d0cd0c37b3c34/packages/api/src/auth/decoders/index.ts#L17

changing `typesToDecoders.supabase to netlify`

with that change I get back -
```json
{"data":{"redwood":{"currentUser":{"roles":[]}}}}
```

**Comment by dthyresson** [comment]
> might be because of this

Hi @duncanhealy you may need to implement a decoder for supabase.

I do not think using the netlify decoder is 100% correct, because it relies on the Identity feature of Netlify to place a decoded and populated user in the context in production  --- and that the token is decoded in in dev.

What is supabase setting as the token in

https://github.com/redwoodjs/redwood/blob/1185f0f0b06c11004e7c0d86c19d0cd0c37b3c34/packages/api/src/auth/decoders/index.ts#L21

?

Based on that will need to determine how the decode it if needed.

**Comment by Tobbe** [comment]
@duncanhealy Thanks for getting the ball rolling on this! Your work both here and over in the supabase repo(s) is much appreciated ⭐ 

I went ahead and upgraded to Supabase 1.0 over here https://github.com/redwoodjs/redwood/pull/1536 and that PR has now been merged.

**Comment by Tobbe** [comment]
@kiwicopple I did the upgrade from scratch over in https://github.com/redwoodjs/redwood/pull/1536 and so I wanted to ask if you could please take a look at the type imports. More details over in that PR.

**Pull request closed without merging**
