### PR TITLE
Adds skipLibCheck flag to tsconfig

### PR DESCRIPTION
**Pull request by dac09**
### What? 
Adds the `skipLibCheck` flag to tsconfig, to prevent tsc from checking entire libraries. A good explanation I found here: https://stackoverflow.com/questions/52311779/usage-of-the-typescript-compiler-argument-skiplibcheck

For comparison (doing a clean build):
Without skipLibCheck -> `yarn build`  -> 1m 10s
Without skipLibCheck -> `yarn lerna run build`  -> 1m 15s

With skipLibCheck → `yarn build` → 30s
With skipLibCheck →`yarn lerna run build` -> 40s

### CODE REVIEW

**Comment by dac09** [comment]
@aldonline, @Tobbe could you guys take a look at this small change? Shouldn't be a big deal, since we still get type checking for types/functions we import just not the entire library

**Comment by thedavidprice** [comment]
#want

**Comment by aldonline** [comment]
I think it is worth trying it out. 
Then we can waste that extra minute in a more creative way ;)

The way I use this is that I keep `skipLibCheck : true` by default (because it makes things run significantly faster, as you've already seen), and turn it back on if I run into any type errors that seem to be coming from libraries to get some more info.

**Comment by peterp** [comment]
@aldonline Is there any value to have a GitHub action build with this flag enabled? (From @Tobbe's suggestion in chat.)

**Review by peterp — APPROVED** [review]
Approved pending Aldo's recommendation about running it in a GH action.

**Comment by dac09** [comment]
> @aldonline Is there any value to have a GitHub action build with this flag enabled? (From @Tobbe's suggestion in chat.)
@aldonline let us know what you think, HODL the PR till then

**Comment by dac09** [comment]
Advice from aldo as per last core meeting is, to try it. Let's merge this after the release and try it out in canary for a while!

**Pull request merged**
