### PR TITLE
Docs: link to roadmap in readme

### PR DESCRIPTION
**Pull request by jtoar**
This PR adds a bullet to the end of the Features list directing readers to the Roadmap. @thedavidprice is this what you had in mind?

### CODE REVIEW

**Comment by thedavidprice** [comment]
@jtoar This could work as is. My original thought was a standalone sentence or two in the section as a call out.

But makes sense for you to decide @mojombo --> Goal is to add info + link to the Roadmap in the #Features section of the main README. Is there anything you'd like to do further with this section and/or adding v1.0 Vision with goal to reach by end of year?

**Comment by mojombo** [comment]
I think the Roadmap is important enough to warrant its own "Roadmap" section. I'd put it after Features and say a few words about our intention to ship v1.0 before end of year and link to the Roadmap doc.

**Comment by thedavidprice** [comment]
@jtoar ping!

**Comment by jtoar** [comment]
@thedavidprice pong! 😅

**Review by thedavidprice — APPROVED** [review]
🚀

**Pull request merged**
