### PR TITLE
chore(crwa): Convert Create Redwood App to ESM

### PR DESCRIPTION
**Pull request by virtuoushub**
see also: 
- https://github.com/redwoodjs/redwood/pull/9057
- https://github.com/redwoodjs/redwood/pull/8159
- _note: skipping `possibleTypes` https://github.com/redwoodjs/redwood/pull/9560_

### CODE REVIEW

**Comment by Tobbe** [comment]
@virtuoushub We're running into NX cache issues from time to time on some PRs. That's what you saw here with all the tests failing. I cleared that up and re-ran the tests. Seems to be only one thing that's failing due to ESM now

image

**Comment by virtuoushub** [comment]
> @virtuoushub We're running into NX cache issues from time to time on some PRs. That's what you saw here with all the tests failing. I cleared that up and re-ran the tests. Seems to be only one thing that's failing due to ESM now
> 
> image

awesome! thanks for your help with ea1d5a55223976e8c8cb4bf6480d62c2acf36774

**Comment by Tobbe** [comment]
This looks good, but please hold off merging until we've got a better plan in place for ESM support.
I'll carry this forward, or hand off as needed.

**Comment by Tobbe** [comment]
Superseded by #9786

**Pull request closed without merging**
