### PR TITLE
Add support to realtime/subscriptions with Apollo Subscriptions

### PR DESCRIPTION
**Pull request by nunopato**
Hi everyone! I wanted to try out using subscriptions (natively with cells instead of using the apollo client directly) with Nhost and RedwoodJS and so here is a proposal for adding support to them. Prisma doesn't support subscriptions so one would have to use something else like Nhost and Hasura. 

This PR adds support for [apollo subscriptions](https://www.apollographql.com/docs/react/data/subscriptions/), through cells, by allowing for the export of the named constant `SUBSCRIPTION`, as well as `QUERY`. Depending on which one is exported, a subscription or a query is used.

[here](https://github.com/nhost-examples/nhost-redwoodjs-realtime) is the example app I used to test the PR. 

Missing bits:

- [ ] tests
- [ ] (to discuss) add a flag to `yarn rw g cell CellName` to export the name constant `SUBSCRIPTION` instead of the default `QUERY`.
- [ ] `subscriptions-transport-ws` has to be added manually to the redwood app (adding it to this repo's web package is not working) because of an issue with webpack 4 (solved on v5): https://github.com/webpack/webpack/issues/6191.

Looking forward to getting feedback from you.

Screenshot 2021-02-16 at 22 41 02

### CODE REVIEW

**Comment by Tobbe** [comment]
This is really cool! Let's see what @peterp et al have to say about it :)

**Comment by thedavidprice** [comment]
Hi @nunopato Thanks for getting this going! Just letting you know we have this on our radar and will be discussing some next steps and getting back to you. Currently, we're focused on getting the next release v0.26.0 out the door in a couple of days. You should be hearing from us after that. But please don't hesitate to check back by end of the week if needed.

**Comment by nunopato** [comment]
@thedavidprice thank you for letting me know! And no worries, take as much time as you need. Good luck with the release 👍

**Comment by thedavidprice** [comment]
Checking in: I will make sure this gets attention when we start the v0.29 sprint next week.

**Comment by thedavidprice** [comment]
@peterp @jtoar I don't fully understand the implications of this one. But as more options for hosting providers come online, using GraphQL Subscriptions is going to be more possible. If this gets Redwood prepared for that reality, I think it's definitely additive.

**Comment by dac09** [comment]
Hey @nunopato! Just following up on this - was this PR ready for review? (Has WIP in the title)

**Comment by nunopato** [comment]
@dac09 sorry for only coming back to this now, I would say it is ready to be discussed. I think we still need to figure out how subscriptions would look like.

**Comment by dthyresson** [comment]
> I would say it is ready to be discussed. I think we still need to figure out how subscriptions would look like.

@nunopato You mentioned this PR to met in out chat today and wanted to bump it to @dac09 and @peterp 's attention, but was wondering if there was more to be discussed or if it is still WIP.

**Comment by nunopato** [comment]
@dthyresson I see that this PR is in progress (Current-Release-Sprint) and worked on by @jtoar. I don't have much time at the moment but feel free to ping me if you need anything.

**Comment by thedavidprice** [comment]
@nunopato thanks for checking in. We are attempting to use "Assign" as a way to have a Core Team maintainer as a point-of-contact for each PR. Not sure how to best communicate that but we'll figure it out.

We are aware that you're heads down on nHost. Please know that we're not waiting on anything from you at this time. All good! @jtoar is currently doing some work with Cells + Apollo and has this PR on his radar. If he needs anything he'll definitely reach out.

Hope things are going great with nHost!

**Comment by nunopato** [comment]
@thedavidprice That makes sense. I should have looked into it a bit closer.

Sounds good, I will try to sync with @jtoar and move this forward as soon as I can. 

We're doing good, just a lot going on now with hiring and infra V2, thank you! BTW, it is Nhost. We are starting to think that the logo is misleading there hehe

**Comment by jtoar** [comment]
@nunopato thanks for getting subscriptions on our radar. We're trying to make subscriptions possible from a framework perspective but probably won't provide any help for getting them setup. I.e., if they're there, we'll merge them into our schema, but setting up the service, picking the right deploy target, etc. will be up to the user. We definitely want subscriptions, we're just not sure what the best way to do it is yet, especially since prisma doesn't have any native support for real time. That's why we think it's important to make it possible, just to allow experimentation in hopes for settling on a standard way we can bake back into the framework.

Sorry we couldn't make this one happen but thanks for all your work here again! It'll help us a lot as a point of reference when we circle back to implement some of these features in the future

**Comment by ajcwebdev** [comment]
A couple more resources for anyone checking out this issue in the future, while it is true Prisma does not offer subscriptions natively there are a handful of user implementations that others can reference if they are determined to get something spun up today:

* [Graphql Subscriptions on AWS Lambda (with Prisma)](https://github.com/guerrerocarlos/graphql-lambda-prisma-example)
* [Subscriptions Apollo Server + Nexus](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-subscriptions)
* [CDK API with GraphQL and Aurora Serverless PostgreSQL and Prisma](https://github.com/ryands17/graphql-api-cdk-serverless-postgres)
* [Open Prisma issue on Subscriptions/real-time API support](https://github.com/prisma/prisma/issues/298)

And another promising avenue I would explore is the [Prisma-AppSync](https://github.com/maoosi/prisma-appsync) plugin from [Sylvain Simao](https://github.com/maoosi)
* [Real-time GraphQL APIs with Prisma and AWS AppSync - Sylvain Simao | Prisma Day 2021](https://www.youtube.com/watch?v=k2tjpxC7mrQ&ab_channel=Prisma)

**Pull request closed without merging**
