### PR TITLE
fix: Fix logFormatter when no undefined ns, name, or message.

### LINKED ISSUE #8180: [Bug?]: Log Formatter includes extraneous "undefined" text labels when missing certain properties
### What's not working?

When the log formatter encounters log statements that lack the `ns` or log `name` attribute -- say from Fastify or Yoga debug logging, the message includes "undefined".

image

image

Note that when the `graphql-server` logs, the child logger has a name, but not a `ns` value.

### How do we reproduce the bug?

1. Configure `  loggerConfig: { logger, options: { query: true } }`
2. Launch test project app in `rw dev`
3. Make cell/GraphQL requests
4. Look at formatted log output

### What's your environment? (If it applies)

_No response_

### Are you interested in working on this?

- [X] I'm interested in working on this

### PR DESCRIPTION
**Pull request by dthyresson**
Fix  #8180.

When the log formatter encounters log statements that lack the `ns` or log `name` or no `message` attribute -- say from Fastify or Yoga debug logging, the message includes "undefined".

image

image

Note that when the `graphql-server` logs, the child logger has a name, but not a `ns` value.

The PR checks for the undefined cases when formatting the values and also adds a test to ensure that the text "undefined" does not appear in the formatted log content when ns, name or message are not provided.

### CODE REVIEW

**Comment by dthyresson** [comment]
Not unable to test with `yarn rwfw` to show updated screens.

**Comment by thedavidprice** [comment]
@dthyresson what help do you need to get this one in (if anything)?

**Comment by dthyresson** [comment]
I just need to test with rwfw . My unit tests pass. Then a review. I’ve got it in morning

**Comment by thedavidprice** [comment]
@dthyresson Roger that 👍 Was going to suggest you try testing via canary package if needed. Keep me/us posted.

**Comment by dthyresson** [comment]
Tested in GitPod and looks good 
image

**Review by thedavidprice — APPROVED** [review]
Good for me ✅

Not sure if you were simply looking for another pair of eyes or had specific questions for Tobbe. Deferring to you re: next steps here.

**Pull request merged**
