### PR TITLE
fix: Use sse link with `@live` directive

### PR DESCRIPTION
**Pull request by callingmedic911**
There isn't any defect without the SSE link with live queries but using explicit SSE links allows proper headers that in turn show proper requests with the body in browser devtools.

This is something DT and I noticed when pairing. Separately another user reported this symptom: https://github.com/redwoodjs/redwood/issues/10511#issuecomment-2292315773

Copied over from: https://github.com/n1ru4l/graphql-live-query/tree/main/packages/todo-example/client-apollo/src/apollo-link

### CODE REVIEW

**Review by dthyresson — CHANGES_REQUESTED** [review]
Thanks for tracking this down @callingmedic911 .

Unfortunately we cannot always import the live query in web. First, it adds to bundle and second it's not always needed unless you have realtime enabled.

We've had to dynamically import this in `Internal`: 

https://github.com/redwoodjs/redwood/blob/28c2daf5e4c1dca05e1dd7aee72734663d3380b6/packages/internal/src/generate/graphqlSchema.ts#L34

```ts
  // If we're serverful and the user is using realtime, we need to include the live directive for realtime support.
  // Note the `ERR_  prefix in`ERR_MODULE_NOT_FOUND`. Since we're using `await import`,
  // if the package (here, `@redwoodjs/realtime`) can't be found, it throws this error, with the prefix.
  // Whereas `require('@redwoodjs/realtime')` would throw `MODULE_NOT_FOUND`.
  if (resolveFile(`${getPaths().api.src}/server`)) {
    try {
      const { liveDirectiveTypeDefs } = await import('@redwoodjs/realtime')
      schemaPointerMap[liveDirectiveTypeDefs] = {}
    } catch (error) {
      if ((error as { code: string }).code !== 'ERR_MODULE_NOT_FOUND') {
        throw error
      }
    }
  }
```

So, need to do something similar here.

For subscriptions, since that's a standard GraphQL type we can always check.

I'll have to think oil the condition that would determine the live query import.

**Comment by dthyresson** [comment]
Actually the await/require and throw error might be enough. Well, maybe not since web side.

**Comment by dthyresson** [comment]
I asked AI and they suggested to try:

```ts
const uploadOrSSELink =
  typeof SSELink !== 'undefined'
    ? split(
        ({ query }) => {
          const definition = getMainDefinition(query)
          return (
            // Check for subscriptions
            (definition.kind === Kind.OPERATION_DEFINITION &&
              definition.operation === OperationTypeNode.SUBSCRIPTION) ||
            // Check for @live directive on queries
            (definition.kind === Kind.OPERATION_DEFINITION &&
              definition.operation === OperationTypeNode.QUERY &&
              definition.directives?.some((directive) => directive.name.value === 'live'))
          )
        },
        new SSELink({
          url: uri,
          auth: { authProviderType, tokenFn: getToken },
          httpLinkConfig,
          headers,
        }),
        uploadLink,
      )
    : uploadLink```

**Comment by callingmedic911** [comment]
I can always inline the code from that external package. :D I think it wasn't a tiny package.

**Comment by dthyresson** [comment]
> I can always inline the code from that external package. :D I think it wasn't a tiny package.

This where I defer to @Josh-Walker-GM and @Tobbe on how to manage dependencies - add one, add code instead, etc.

**Comment by Tobbe** [comment]
> I can always inline the code from that external package. :D I think it ~wasn't~ was a tiny package.

What about the dependencies of that package? If we want to take ownership of everything new, how much is it? (new === packages we don't already import as part of something else)

**Comment by callingmedic911** [comment]
No deps (it's just `graphql` package as peer dep, which we already have).

**Comment by Tobbe** [comment]
Thanks @callingmedic911, I was looking at the wrong package.json first. This is the package that we're thinking of adding: https://github.com/n1ru4l/graphql-live-query/tree/main/packages/graphql-live-query and it is indeed a very small package.

**Comment by Tobbe** [comment]
Since we're bundling web we can't just do normal dynamic imports 🤔 

image

I think we could do something like we do for our DevFatalErrorPage!

* Create a separate file, let's call it `isLiveQuery.ts`, that imports Laurin's package and does this for us:
    ```
    const isLiveQuery =
              !!definition &&
              isLiveQueryOperationDefinitionNode(definition, variables)
    ```
* Take a look at `packages/babel-config/src/plugins/babel-plugin-redwood-remove-dev-fatal-error-page.ts`
* Write a babel plugin that checks if `@redwoodjs/realtime` package is included in the project's `package.json`. If it's not, it replaces `import { isLiveQuery }  from './isLiveQuery'` with `const isLiveQuery = () => false`
* Manually make sure `isLiveQuery.ts` (and, more importantly, the graphql-live-query package) is tree-shaken out of the final web bundle

**Comment by Tobbe** [comment]
> I think we could do something like we do for our DevFatalErrorPage!

Update for anyone checking in: 
We can't do what I suggested as this is all within the framework. It's already built/bundled/shipped well before we know if the user wants to use realtime features or not :(  
(The fatal error OTOH lives inside the user's project, so that's why we can do it there)

**Comment by callingmedic911** [comment]
These are the ways forward I see:
1) Keep this package as a dependency. Drawback: increased bundle size, especially bad when realtime isn't set up.
2) We can have a copy of the package and inline it. Drawback: Doesn't really help with bundle size, also adds maintenance overhead.
3) We maintain a simpler version of it. Drawback: It doesn't support the [`throttle`](https://github.com/n1ru4l/graphql-live-query/pull/628) and [`if`](https://github.com/n1ru4l/graphql-live-query/pull/396) directive arguments. We don't implement or expose `throttle` from the server-side, so we don't lose anything there.

I went ahead with 3, but I'm open to any suggestions.

**Review by Tobbe — APPROVED** [review]
I like how simple the check became 👍 

(But now I kind of also think we should include throttling in our live support 😅)

**Comment by callingmedic911** [comment]
Just realised my changes are essentially what DT wrote. Hah!

**Comment by dthyresson** [comment]
> Just realised my changes are essentially what DT wrote. Hah!

ChatGDT wins again! 🤓

**Comment by callingmedic911** [comment]
> (But now I kind of also think we should include throttling in our live support 😅)

Totally reasonable request but since we didn't have the support for it already I'm gunna punt it as out of scope for this PR. :)

**Comment by Tobbe** [comment]
> > (But now I kind of also think we should include throttling in our live support 😅)
> 
> Totally reasonable request but since we didn't have the support for it already I'm gunna punt it as out of scope for this PR. :)

💯

**Pull request merged**
