### PR TITLE
Adds a CI Check to run CLI against Windows and Ubuntu; adds build:test-project as reusable fixture

### LINKED ISSUE #4485: [CI] Test Windows and all Command
We do not run Tutorial-like E2E checks for Windows. Additionally, we do not have coverage for all CLI commands in our current CI.
- add new GH Workflow
- use Build:test-project
- run through commands
- can we use `yarn dev ... --cwd` to test things like setup commands
- Need to have something like https://github.com/redwoodjs/redwood/issues/4259

### PR DESCRIPTION
**Pull request by thedavidprice**
Closes #4485

What's the point:
- make test-project use more efficient
- use test-project for CI
- use test-project as a fixture for unit tests
- remove CLI checks from E2E CI Workflow
- add missing CLI checks to CI
- replace telemetry-benchmarks workflow with this one

## CLI checks
- [ ] Need to run `yarn rw dev` and `yarn rw serve`: See https://github.com/redwoodjs/redwood/issues/4259
- [ ] How to handle `rw setup` command: tailwindcss, chakra-ui, auth, deploy, etc: they all fail even if using `yarn dev <command> --cwd ...` due to setup trying to install `yarn workspace web add ...` during the process

## build:test-project option
- [ ] `--re-build-fixture`: option to build new project at `./__fixtures__/test-project`
    - typescript
    - latest published version of Redwood Packages
    - remove yarn.lock
- [ ] `--copy-from-fixture`: default=true, when running build:test-project use codebase at __fixtures/test-project to copy into target directory instead of creating codebase from scratch
- [ ] determine a process about when to rebuild `__fixtures__/test-project`: breaking change, adding feature/code to test, new codemod, etc.?

## publishing Redwood packages
- should we rebuild `__fixtures__/test-project` each time we publish?
  - probably "no"
- or just update package versions (along with script "update-package-versions)?

## Misc
- [ ] build:test-project — cleanup lint and codemods?

### CODE REVIEW

**Comment by jtoar** [comment]
@thedavidprice I'm testing an action right now in another repo, I'll commit it here when it's ready.

**Comment by jtoar** [comment]
@thedavidprice I got past the setup step. Reverted back to an action. Things are working!

I had to disable `yarn rw type-check` and `yarn rw check`. The error from `yarn rw check` seems legitimate (there's a `createContact` mutation, but not service), but I can't reproduce the error from `yarn rw type-check`, which is about `gql` missing.

**Comment by thedavidprice** [comment]
Thanks @jtoar 🚀

Lesson learned --> do it _all_ in an Action 🤬

I've continued this work over here in https://github.com/redwoodjs/redwood/issues/4500

**Comment by dac09** [comment]
No all good :) thank you

**Pull request merged**
