### PR TITLE
Added missing type to routing-params.md

### PR DESCRIPTION
**Pull request by pr0h0**
Added missing type FindArticleQueryVariables to routing-params.md file

### CODE REVIEW

**Comment by Josh-Walker-GM** [comment]
Thanks! Do you think we should add the import to this line also?
https://github.com/redwoodjs/redwood/blob/656a2c86e28a915a8f8552a44c8b79331873f7f7/docs/docs/tutorial/chapter2/routing-params.md?plain=1#L352

**Comment by pr0h0** [comment]
@Josh-Walker-GM  I'm not really sure, I can't figure it out from markdown only, I agree with whatever you decide.

**Review by Josh-Walker-GM — APPROVED** [review]
Thanks!

**Comment by Tobbe** [comment]
I just updated this branch. With the changes that _just_ got merged in https://github.com/redwoodjs/redwood/pull/9417 hopefully this can now also be merged!

**Pull request merged**
