### PR TITLE
Add warning box for missing roles in authorization doc

### PR DESCRIPTION
**Pull request by Avataw**
For [#5542](https://github.com/redwoodjs/redwood/issues/5542)

## ✅ What it does

- Chapter Four > Authorization
  - added warning box for missing roles after the auth.js/ts is shown

## 🔮 What needs to be verified
Originally I wanted to only show the warning box when typescript mode is active (ts tab was clicked), but I did not find a suitable solution. Instead I opted for a more general warning box without actually mentioning the typing error at all.

Therefore I'd like to know if this added warning box is not too vague for TS users, stumbling over missing roles (as this was the original intent of this PR)

### CODE REVIEW

**Comment by jtoar** [comment]
> Originally I wanted to only show the warning box when typescript mode is active (ts tab was clicked), but I did not find a suitable solution

@Avataw did moving the admonition into the `<TabItem value="ts" label="TypeScript">` not work? I tried it and it seemed to work locally—only shows up for TS:

```
:::caution

At this point of the tutorial we have **not added roles** to our user model yet, therefore you can ignore the `hasRole` method in the `api/src/lib/auth.{js,ts}` for now.

If this bothers you, feel free to peek into [the tutorial chapter about Authorization](../chapter7/rbac.md) and add the missing field as described there.

:::

</TabItem>
</Tabs>
```

**Comment by Avataw** [comment]
@jtoar you are completely right, thank you :) 
In the end I actually did like at least mentioning that a huge part of the file is not yet relevant to JS-users as well.
Therefore I split it up into two different caution boxes: 
- the JS one mentioning that a huge part is not yet relevant
- the TS one explicitly mentioning the error you would get.

**Comment by thedavidprice** [comment]
@Avataw Thank you for your patience with this! Vacation schedules resulted in this being lost in the shuffle.

The copy is ✅

However, I tried viewing this via the Netlify preview and it doesn't seem to be displaying via including within the tabs. See:
https://deploy-preview-5611--redwoodjs-docs.netlify.app/docs/tutorial/chapter4/authentication#add-a-logout-link

It's possible the preview isn't rebuilding the docs correctly. Can you confirm these callouts are displaying via screenshot when you try locally? And/or other ideas to verify?

**Comment by callingmedic911** [comment]
> However, I tried viewing this via the Netlify preview and it doesn't seem to be displaying via including within the tabs. See: [deploy-preview-5611--redwoodjs-docs.netlify.app/docs/tutorial/chapter4/authentication#add-a-logout-link](https://deploy-preview-5611--redwoodjs-docs.netlify.app/docs/tutorial/chapter4/authentication#add-a-logout-link)
> 
> It's possible the preview isn't rebuilding the docs correctly. Can you confirm these callouts are displaying via screenshot when you try locally? And/or other ideas to verify?

DP, the Netlify build defaults to the last published version but the PR changes are in the `canary` version. This is a bit misleading, if there's an option to update Netlify URL maybe we can link directly to the canary one.

You can review the updated copy here (notice /carnary in URL):
https://deploy-preview-5611--redwoodjs-docs.netlify.app/docs/canary/tutorial/chapter4/authentication/#add-a-logout-link.

**Comment by thedavidprice** [comment]
@callingmedic911 Perfect! I assumed something like that was going on and took a look at Netlify settings. Just didn't have time to find the path and didn't want to merge until I figured it out. All good now 🚀

Huge thanks again @Avataw Definitely an improvement here.

**Pull request merged**
