### PR TITLE
[v1.0.0-rc] Remove deprecated features

### LINKED ISSUE #2631: Remove deprecated features for v1
The codebase currently includes many items indicating v1 deprecation.

We should find those and deprecate them.

### PR DESCRIPTION
**Pull request by callingmedic911**
Closes #2631.
___  
Before merging, maybe we want recheck:
- [x] If we have any more deprecated features to remove.
   EDIT 29th Sept 21: 
  - [x] ~~`beforeResolver` is deprecated in v0.37.~~ **Already removed**
- [x] If we need anything from 15fdd40b877fb4510c5ef083f667018f3843be37. **Applied again**.
- [ ] ~~Update docs~~ **Not required anymore.**

This removes deprecated features [planned for v1-rc](https://github.com/redwoodjs/redwood/pull/2896#issuecomment-883771543).

- Form changes moved to #3043 
- Moved non-critical changes to #3088 
- Reverted form changes commits, reverted api-server deprecation. Kept revert commits.
- Removed flash component deprecated, it's already been removed in #2909
___
Original:
I removed everything that says deprecated, even if it was marked deprecated only a few weeks ago. For example: https://github.com/redwoodjs/redwood/commit/56f601967d6e482da15574153f38efb8c4103e36 (Supabase `data` field)
Also, I made sure one commits maps to individual features, so it's a bit easier to review commit-wise and revert.

The only deprecated annotation left is - [processPagesDir()](https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/paths.ts#L211), which we can remove once we have the suggested alternate implementation.

@dac09 @jtoar @thedavidprice

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thank for getting this going @callingmedic911 

@dac09 @peterp When do you think the timing is right for this one? Maybe v0.36, which will be within a couple of releases of v1-rc?

**Comment by thedavidprice** [comment]
Hi @callingmedic911 Thank you for your patience with us on this one. I had a discussion with the core team maintainers, and we would like to handle this is two parts:
1. deprecate some non-critical features now or in any other releases leading up to v1.0.0-rc.0
2. wait for "critical" deprecations until the release of v1.0.0-rc.0

Our thinking it that we don't want to create much resistance to people upgrading now.

## To Deprecate Now
For deprecations to include in our next release, I suggest:
1. fully deprecating the obsolete commands, so any files in `packages/cli/src/commands/*` included in this PR. Note: we'll need to update the CLI documentation as well.
2. the Forms package deprecations `packages/core/src/index.ts` and `packages/forms/src/index.tsx`
    - it feels more appropriate to make those changes in this PR upgrading React Hook Forms #3042 
    - could you coordinate with @LBrian and @jtoar for a plan?

## To deprecate with v1.0.0-rc.0
Then the remaining deprecation should happen along with the v1-rc release (along with anything else new that's scheduled for deprecation).  

---

What do you think of this plan? If it makes sense, just let me know how you want to split the PRs. Maybe just create a new PR for the commands deprecation and then pull the changes into this PR? Loop me in however needed.

**Comment by LBrian** [comment]
> Hi @callingmedic911 Thank you for your patience with us on this one. I had a discussion with the core team maintainers, and we would like to handle this is two parts:
> 
> 1. deprecate some non-critical features now or in any other releases leading up to v1.0.0-rc.0
> 2. wait for "critical" deprecations until the release of v1.0.0-rc.0
> 
> Our thinking it that we don't want to create much resistance to people upgrading now.
> 
> ## To Deprecate Now
> For deprecations to include in our next release, I suggest:
> 
> 1. fully deprecating the obsolete commands, so any files in `packages/cli/src/commands/*` included in this PR. Note: we'll need to update the CLI documentation as well.
> 2. the Forms package deprecations `packages/core/src/index.ts` and `packages/forms/src/index.tsx`
>    
>    * it feels more appropriate to make those changes in this PR upgrading React Hook Forms [Error while deploying web side with prerender through Serverles #3042](https://github.com/redwoodjs/redwood/issues/3042)
>    * could you coordinate with @LBrian and @jtoar for a plan?
> 
> ## To deprecate with v1.0.0-rc.0
> Then the remaining deprecation should happen along with the v1-rc release (along with anything else new that's scheduled for deprecation).
> 
> What do you think of this plan? If it makes sense, just let me know how you want to split the PRs. Maybe just create a new PR for the commands deprecation and then pull the changes into this PR? Loop me in however needed.

@thedavidprice I had a quick look of this PR, agreed and makes sense we should cherry-pick `form` changes into #3043 for sure, I will do that later today. Btw, just a kind reminding you might wrongly pasted the wrong PR number, just in case others get confused. :) @callingmedic911 I will keep you in the loop.

**Comment by thedavidprice** [comment]
@LBrian gah, fixed! (thank you... numbers are hard sometimes.)

**Comment by callingmedic911** [comment]
> Our thinking it that we don't want to create much resistance to people upgrading now.

Totally agree.

>   1. fully deprecating the obsolete commands, so any files in `packages/cli/src/commands/*` included in this PR. Note: we'll need to update the CLI documentation as well.

I'll create a separate PR and cherry-pick `commands` deprecation.
>    2. the Forms package deprecations `packages/core/src/index.ts` and `packages/forms/src/index.tsx`
>        
>        * it feels more appropriate to make those changes in this PR upgrading React Hook Forms [Upgrade RHF to v7.11.0 #3043](https://github.com/redwoodjs/redwood/pull/3043)
>        * could you coordinate with @LBrian and @jtoar for a plan?

I see @LBrian has cherry-picked https://github.com/redwoodjs/redwood/pull/2896/commits/502159acf1a43e1bbd56f5a5c2e49385d49ebec6 and https://github.com/redwoodjs/redwood/pull/2896/commits/ff10aee5d9afdebda4ef77bd0c28eba723cec8cb. Thanks a lot @LBrian. :) I'll remove these commit from this PR now.
By the way, @thedavidprice also mentioned `packages/core/src/index.ts`, do we want to cherry-pick https://github.com/redwoodjs/redwood/pull/2896/commits/fd9a5908f0749fd38e5e2a9eabaddb43ec7fecc3? I don't think it's related to `forms`.

> Then the remaining deprecation should happen along with the v1-rc release (along with anything else new that's scheduled for deprecation).
> 
> What do you think of this plan? If it makes sense, just let me know how you want to split the PRs. Maybe just create a new PR for the commands deprecation and then pull the changes into this PR? Loop me in however needed.

Sounds good! I'll use new `commands` deprecation branch as head for this one and we can merge remaining changes in v1-rc.

**Comment by thedavidprice** [comment]
> I guess this also includes api-server CLI command?

Ah, I forgot to mention that we should skip anything api-server related for now. Peter has changes coming, so let's wait for those. 

> By the way, @thedavidprice also mentioned packages/core/src/index.ts, do we want to cherry-pick fd9a590? I don't think it's related to forms

My mistake. I didn't mean to include that file. Let's skip for now 🤦‍♂️

Thanks!

**Comment by callingmedic911** [comment]
Got it. Thank you!

**Comment by callingmedic911** [comment]
All set @thedavidprice. 

Both non-critical changes and this one are independent, so I didn't need to rebase. Also, I've remove flash deprecation, it's already been removed from a different PR.

**Review by dac09 — APPROVED** [review]

**Review by thedavidprice — CHANGES_REQUESTED** [review]
HOLD merging. This PR is for including in v1.0.0-rc.0

**Comment by callingmedic911** [comment]
@thedavidprice Hello! I'm back at the desk. Here's what I've changed this time:

- Remove recently deprecated TS types for apiProxyPath from ambient type files.
- Re-applied the commit to remove deprecated `api-server`.
- Reverted supabase deprecated field because I realized the Supabase's GoTrue client still has these fields, so keeping them for now.

**Comment by thedavidprice** [comment]
@callingmedic911 awesome! Is this ready for review?

**Comment by callingmedic911** [comment]
@thedavidprice Yep, ready for review. :slightly_smiling_face:

**Review by thedavidprice — CHANGES_REQUESTED** [review]
Looping in others for specific questions.

### Redwood-tools
I think it's time to fully deprecate redwood-tools.js
- packages/cli/src/redwood-tools.js
- references to `redwood-tools` and `rwt` in packages/cli
    - including references in packages/cli/README.md

Agreed @dac09?

### __REDWOOD__API_PROXY_PATH
Looks like we still have a reference to remove over here:
- packages/web/src/global.web-auto-imports.ts

### Supabase.ts
@dthyresson do you have suggestions about how/if we should handle deprecations in:
- packages/auth/src/authClients/supabase.ts

?

### Scaffold.js
@cannikin any reason not to fully deprecate this in v0.39?
https://github.com/redwoodjs/redwood/blob/f129c58305f8a861c5a6c9271bb044196763d885/packages/cli/src/commands/generate/scaffold/scaffold.js#L692-L697

### processPagesDir
@peterp @dac09 Is this still an intended deprecation?
https://github.com/redwoodjs/redwood/blob/f129c58305f8a861c5a6c9271bb044196763d885/packages/internal/src/paths.ts#L218-L227

**Comment by cannikin** [comment]
> @cannikin any reason not to fully deprecate this in v0.39?

Nope, go ahead and remove! I updated the docs recently to reference the new command `yarn rw g dbAuth` so we should be safe to remove.

**Comment by callingmedic911** [comment]
Thanks for reviewing thoroughly @thedavidprice!

>**__REDWOOD__API_PROXY_PATH:** Looks like we still have a reference to remove over here:
>-   packages/web/src/global.web-auto-imports.ts

I'm not able to find any references to `__REDWOOD__API_PROXY_PATH`, am I missing something here?

Apart from this, I have removed `dbAuth` deprecation warning in the scaffold. Waiting for confirmation from others, then if required will those as well.

**Comment by dthyresson** [comment]
@thedavidprice for

>Supabase.ts

> @dthyresson do you have suggestions about how/if we should handle deprecations in:

> packages/auth/src/authClients/supabase.ts


I assume this question refers to:

```ts
  }): Promise<{
    user: User | null
    session: Session | null
    error: Error | null
    data: Session | User | null // Deprecated
  }>
```

to `data`. 

I'll check as that may no longer be in the current Supabase js sdk.

**Comment by dthyresson** [comment]
FYI for Supabase, can upgrade to latest and then remove deprecations, but relies on a fix: https://github.com/supabase/gotrue-js/pull/178

**Comment by dthyresson** [comment]
> FYI for Supabase, can upgrade to latest and then remove deprecations, but relies on a fix: [supabase/gotrue-js#178](https://github.com/supabase/gotrue-js/pull/178)

https://github.com/supabase/gotrue-js/pull/179 has been merged, just need to await the next supabase-js release which I believe well be next week.

**Comment by jtoar** [comment]
@thedavidprice `processPagesDir` looks like something we can remove at any time in the RC process since it's internal. It's used in the structure package and a babel plugin (for auto-loading the routes in `Routes.js`) so it we also can't remove it without an alternative.

**Comment by thedavidprice** [comment]
Finalizing and merging this now.

Moved Supabase deprecation step to #3756

# Release Notes: Breaking
## Router Globals
Fully deprecates:
- `__REDWOOD__API_URL`
- `__REDWOOD__API_GRAPHQL_SERVER_PATH`
- `__REDWOOD__API_PROXY_PATH`

Use the following instead:
- `RWJS_API_GRAPHQL_URL`
- `RWJS_API_DBAUTH_URL`
- `RWJS_API_URL`

**Pull request merged**
