### PR TITLE
fix(types): wrong type path on server.config.js

### PR DESCRIPTION
**Pull request by rapzo**
The path for the Fastify configuration is not available at the current location when generating a new project.

### CODE REVIEW

**Review by Tobbe — APPROVED** [review]

**Review by Tobbe — CHANGES_REQUESTED** [review]
Can you please make the same change in the JS template?

**Comment by rapzo** [comment]
Will do!

**Comment by rapzo** [comment]
FIY: i did the change via GitHub's web interface. Let me know if there's something else needed done on a local side and I'll clone it and go through the proper process. But since it was a type in a comment, I took that leap of faith :-D

**Comment by Tobbe** [comment]
@rapzo Technically we should have updated the test project fixture too. But, as you said, it's just a type in a comment, so wasn't worth the extra cycle 😄

**Pull request merged**
