### PR TITLE
update CRWA success message

### PR DESCRIPTION
**Pull request by robobunny**
# Work in progress for issue #909 

Screenshot from 2020-10-16 14-05-40

## Changes I made

- Added the link to the tutorial
- Changed the link to the newsletter
    - Note: this link doesn't work yet, I submitted a PR on the .com ([See Issue 418](https://github.com/redwoodjs/redwoodjs.com/pull/418))
- Minor changes to the verbiage to unify voice

## Changes I didn't make

Because it seemed like too much tinkering for my first PR and because it's not obvious how to proceed:

- Didn't change the text about `yarn rw dev`
- Didn't add a list of CLI commands
- `git init && git add . && git commit -m "initial commit"`
    - I couldn't tell if @thedavidprice is suggesting to add that to this success message or to add that to the code so it automatically does that, like create-react-app does

### CODE REVIEW

**Comment by Tobbe** [comment]
@robobunny That looks great! I love it ♥ Thanks for submitting this PR :)

**Comment by peterp** [comment]
@robobunny It looks great, let me know when it's ready for review 👍

**Comment by robobunny** [comment]
@peterp Sorry I don't know what to do ... do I just tell you? It's ready for review

**Comment by Tobbe** [comment]
@robobunny Thanks for your contribution. Your changes will make for a better experience for all future CRWA users 👍

**Comment by robobunny** [comment]
@Tobbe: Pleasure! My first ever OSS contribution! I love redwood so much and the community is awesome. Great work!

**Comment by thedavidprice** [comment]
> My first ever OSS contribution! I love redwood so much and the community is awesome. Great work!

Well, this is just brilliant all around! The community is glad to have you be a part of it 😁

**Pull request merged**
