### PR TITLE
Add default config for Component generation

### PR DESCRIPTION
**Pull request by jvanbaarsen**
[wip]

## Todo

* [x] generate/component
* [x] generate/cell
* [x] generate/layout
* [x] generate/page
* [x] generate/service
* [x] generate/scaffold
* [x] Go over documentation to make sure this stuff is written down somewhere

Fixes: #1166

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@cannikin I'm having some trouble getting the tests to properly pass on the Scaffolding. Reason for this is that it is relying on the redwood.toml file, but it doesn't seem to have one in the templates for the tests so I'm getting this error:

```
Could not find a "redwood.toml" file, are you sure you're in a Redwood project?
```

Is there an easy way to resolve this?

**Comment by cannikin** [comment]
If you look at `/packages/core/config/__tests__/webpack.common.test.js` there a `jest.mock` there that mocks `getConfig()` to return the content you want it to have (as if it was read from `redwood.toml` and parsed into JSON already). And it looks like in your code changes you're importing `getConfig` from `packages/internal`, so that should be just the mock you're looking for.

So I think you can copy that mock to the scaffold tests and try out different combinations of settings and you should be good to go! Maybe? Try and let me know!

**Comment by jvanbaarsen** [comment]
@cannikin Thanks, I'll give that a shot!

**Comment by jvanbaarsen** [comment]
@cannikin Gave this a try, but doesn't seem to do anything. I'm wondering if it might make sense to actually add the `--tests` flag to the scaffold command in general (Currently that is the only one that doesn't have anything). That way it becomes also easier to "just" pass in the test valuable instead of relying on `getConfig`.

**Comment by cannikin** [comment]
> I'm wondering if it might make sense to actually add the --tests flag to the scaffold command in general 

Makes sense to me! 

I'm curious as to why adding that mock doesn't work...can you dump the contents of `getConfig()` in the test or does it error out before it gets that far? You need to be sure and include the mock before any code actually calls `getConfig()` or it'll use the real version instead of the mocked one. If it's the first thing in the test suite before any other includes, I'm not sure why it wouldn't work...

**Comment by jvanbaarsen** [comment]
@cannikin I added this to the top of scaffoldPathMultiword.test.js:

```
jest.mock('@redwoodjs/internal', () => {
  return {
    getConfigPath: () => {
      console.log('Here?')
      return '/path/to/project/redwood.toml'
    },
    getConfig: () => {
      console.log('getConfig here?')
      return {
        generate: {
          tests: true,
        },
      }
    },
  }
})
```

It still throws the same error, and actually calls getPath from the original package instead of the mock.

**Comment by cannikin** [comment]
Hmm, `src/lib/test` also mocks `@redwoodjs/internal` so there might be some kind of clash going on. You could try removing that `import` and copying the relevant parts of the mock that's defined in `src/lib/test` (mostly `getPaths()`) and copy it into this inline one instead?

**Comment by jvanbaarsen** [comment]
Yeah that's what I assumes as well, so I did try removing the lib/test, but that raised some other issues. 

Let me give it another try later this week, I'll make sure to post the errors I got here.

**Comment by jvanbaarsen** [comment]
@thedavidprice Is updating the docs something we want to do in this PR? Or shall we do that in a separate PR? That way this PR might remain easier to review?

**Comment by jvanbaarsen** [comment]
@thedavidprice Ping (Might have slipped through your notification cracks :) )

**Comment by thedavidprice** [comment]
🤦‍♂️ huge apologies for going silent on this one @jvanbaarsen It won't make it into this week's v0.28 release. But I have it in the sprint for v0.29 starting next week. Promise!

Looping in @jtoar to think through Documentation as well:
- it needs to go in [App Configuration: redwood.toml](https://redwoodjs.com/docs/app-configuration-redwood-toml) for sure
    - we should also audit this to see if it's current in general (Dom, what if we add all this as commented boilerplate in the redwood.toml file itself --> or at least a link to this doc?0
- I think we should add a callout in [Testing doc](https://redwoodjs.com/docs/testing)
- And we should add a callout in upcoming Storybook Doc https://github.com/redwoodjs/redwoodjs.com/pulls

Dom, once we have a working plan, we can open the appropriate Issues/PRs and remove from To-dos for this PR.

Thanks all!

**Comment by thedavidprice** [comment]
**Update**: Jeroen and I connected. He is going to be out of the loop for a while, so I am going to take lead on this PR for the final steps.

**Comment by thedavidprice** [comment]
@jtoar I'd like you and I to prioritize this one for the next release sprint.

**Comment by dac09** [comment]
Bumping this back onto your radar @thedavidprice, @jtoar

**Review by thedavidprice — APPROVED** [review]
-[x] handled lots o' merge conflicts (mostly due to enabling TS/JS generator option with defaults.
-[x] confirmed config (and TS/JS option) is working for each generator

Great work on this @jvanbaarsen Sorry it took so long to get in.

**Comment by thedavidprice** [comment]
Doc update here: https://github.com/redwoodjs/redwoodjs.com/pull/695

**Comment by jvanbaarsen** [comment]
@thedavidprice Thanks for taking it across the line :)

**Comment by dthyresson** [comment]
@thedavidprice Note I mentioned this issue in #2569 as not 100% sure that the destroy cell is removing mocks, tests, stories. And this seems to impact page as well.

**Comment by cjreimer** [comment]
@jvanbaarsen, thanks for all your great work here!

I just pulled the main branch and started working on code to address issue #2543.

Perhaps this is covered through other code, but I got an error when trying to generate a scaffold:

TypeError: Cannot read property 'tests' of undefined
    at Object.handler (D:\Dev\redwoodjs\testScaffold\node_modules\@redwoodjs\cli\dist\commands\generate\scaffold\scaffold.js:39

The offending code in commands/generate/scaffold/scaffold/scaffold.js was
`    tests = getConfig().generate.tests`
The issue resolved once I added the following to my toml file.
```
[generate]
  tests = true
  stories = true
```

Is it a task yet remaining to gracefully handle the case when these entries are not in the toml file or am I missing something?

**Comment by jtoar** [comment]
@cjreimer I just tried to reproduce your issue and couldn't; you shouldn't have to add those to the toml for it to work since there's a default config that gets merged with the user config:

https://github.com/redwoodjs/redwood/blob/505a54ddfc274a5f3573c6b2b7c0c44a886dbff5/packages/internal/src/config.ts#L72-L75

https://github.com/redwoodjs/redwood/blob/505a54ddfc274a5f3573c6b2b7c0c44a886dbff5/packages/internal/src/config.ts#L85

Maybe I didn't reproduce your steps exactly; did you just do something like:
- make a new project; add a model to it's `schema.prisma`
- `yarn rwt link [path to framework]` to start contributing
- generate the scaffold in the original project

**Comment by cjreimer** [comment]
I'm sorry for wasting your time ... the problem is on my end!

I landed up getting a combination of code from redwood-canary and redwood-main branch in my test app, which I believe caused the issue.
I've had issues with rwt, which I have been pushing off debugging, and instead have been manually doing the redwood updates to the test app.  I got bit and wasted your time... sorry!

**Comment by jtoar** [comment]
@cjreimer please don't worry at all—definitely not a waste of time! 

> I've had issues with rwt, which I have been pushing off debugging, and instead have been manually doing the redwood updates to the test app

We're wasting _your_ time with those issues if anything! Have you seen this FAQ? https://github.com/redwoodjs/redwood/issues/2215. We really want rwt to be rock solid, so that contributing is as easy as possible. I can try helping you fix those issues if you want to elaborate on them a bit more.

**Pull request merged**
