### PR TITLE
Call any included onClick before navigating with <Link> and <NavLink>

### PR DESCRIPTION
**Pull request by cannikin**
Ran into an interesting case where I wanted to do something before navigating away from the page with a `<Link>`. My first thought was to use an `onClick` attribute but it didn't work. After some inspection I found that `<Link>` actually uses `onClick` to do the navigation, so if you define your own, nothing happens.

This PR captures any included `onClick` and calls it first, then continues on with the navigation code as originally implemented. The `event.preventDefault()` happens *after* the call to `onClick()`. I'm not sure if this could cause issues with event bubbling—what if onClick itself tries to propagate an event somehow? Is manual propagation even a thing?

This applies to both `<Link>` and `<NavLink>`.

### CODE REVIEW

**Comment by peterp** [comment]
Nice - Since `onClick` didn't ever work this wouldn't be a breaking change. I think most React developers simply ignore event propagation and pretend it doesn't exist.

I'm wondering if we could introduce a way to disable the internal navigation step, like returning false explicitly, to not make that happen? My reasoning for this is that I might want to use a Link for showing a modal, but don't want to style it differently from other things.

```
<Link to="#modal" onClick={() => { showModal(); return false; } }></Link> // Will not navigate
```

**Comment by cannikin** [comment]
Ahhh I like that! I’ll update the code tomorrow!

**Review by peterp — APPROVED** [review]
Nice!

**Comment by razzeee** [comment]
Is this still working? I can't get it to work. Even if I just try to log something.

**Comment by cannikin** [comment]
Hmm, code seems valid, but maybe something else has changed since? What are the reproduction steps? Are you trying to do some other logic within `onClick` but still navigate? Or are you returning `false` and hoping to *not* navigate?

**Comment by razzeee** [comment]
I want to still navigate, but close an overlay done via https://headlessui.com/react/menu as far as I remember (not on my work PC right now)

**Comment by razzeee** [comment]
Here's a repro repo https://github.com/razzeee/redwood-navlink-repro

I would expect this to show up in the logs, if it worked https://github.com/razzeee/redwood-navlink-repro/blob/main/web/src/components/Header/Header.tsx#L35

**Pull request merged**
