### PR TITLE
Improve automated tutorial tests

### PR DESCRIPTION
**Pull request by peterp**
The tutorial automated tests aren't really working at the moment since they're not automated. Let's make that happen.

- [x] Use `yarn create redwood-app`
- [x] Upgrade to canary
- [x] Run against a tmp version

### CODE REVIEW

**Comment by peterp** [comment]
@thedavidprice You're going to love me. I've fixed the e2e tests. They've now got two modes:

Start from scratch mode will `./tasks/test-tutorial` create a brand new app and upgrade it to canary.

Or, run against my existing app `./tasks/test-turial /path/to/app` where it'll not upgrade to canary but run the usual tests.

**Comment by thedavidprice** [comment]
FYI: updated instructions for this in CONTRIBUTING

**Comment by thedavidprice** [comment]
@alvincrespo prior to this update, the tests were running against a static copy of the CRWA install template that was (very) out of date. So unless you first upgraded the test project to the latest canaries, packages would be missing. And then there were code mods that hardened been applied...

This improvement now runs yarn create redwood-app at the start of the process. 

Make sense?

**Comment by alvincrespo** [comment]
Ah ok - that makes sense. Thank you for explaining this!

**Comment by peterp** [comment]
@alvincrespo Sorry, I somehow missed this!

**Pull request merged**
