### PR TITLE
enhance(graphql): simplify graphql handler

### PR DESCRIPTION
**Pull request by ardatan**
Simplify GraphQL handler by following AWS Lambda recipe of Yoga;

https://github.com/dotansimha/graphql-yoga/blob/master/examples/aws-lambda/lambda/graphql.ts#L7

### CODE REVIEW

**Comment by jtoar** [comment]
Thanks @ardatan! 

@dac09, @dthyresson could I assign this one to either of you (or both)? And is this important to get in as a fix soon or can take its time? (Assuming the latter)

**Comment by jtoar** [comment]
Sorry for losing this one @ardatan I'll bring this one up at our standup this week.

**Comment by dthyresson** [comment]
@ardatan Is this rework still needed now that we are Yoga v3 - or is there still an opportunity to simplify our handler? Thanks!

**Comment by ardatan** [comment]
@dthyresson This is already done in Yoga v3 PR. But I will takea look later still :)

**Pull request closed without merging**
