### PR TITLE
[TS + Docs] Include potential gql input variables in ListCell's Loading and Success component typing & improve TS docs

### PR DESCRIPTION
**Pull request by Philzen**
Although list cells in the simpler examples don't have input variables, they *will* very well have them in more advanced apps (i.e. only selecting the items that belong to a certain user or given other constraints), so it good to have these input vars available for autocompletion out of the box.

- Adds to #5343 (updating all docs to reflect QUERY annotation with `TypedDocumentNode`)
- adds to in https://github.com/redwoodjs/redwood/pull/11737, as i realized these now have to be passed in order for the types to still work.
- Updated documentation for new generated …QueryVariables generic on Failure and Success components
- docs: fixed some tsx highlighting blocks
- docs: fixed import order to reflect Eslint rules since RW 2

### CODE REVIEW

**Comment by Philzen** [comment]
> Please add docs etc as well 👍

I'm on it. Checklist:

- [ ] Update fixtures
- [ ] https://docs.redwoodjs.com/docs/tutorial/chapter2/cells
- [ ] https://docs.redwoodjs.com/docs/tutorial/chapter2/routing-params
- [ ] https://docs.redwoodjs.com/docs/tutorial/chapter5/first-story
- [ ] https://docs.redwoodjs.com/docs/tutorial/chapter5/first-test
- [ ] https://docs.redwoodjs.com/docs/tutorial/chapter6/multiple-comments
- [ ] https://docs.redwoodjs.com/docs/tutorial/chapter6/comments-schema
- [ ] https://docs.redwoodjs.com/docs/tutorial/chapter6/comment-form
- [ ] https://docs.redwoodjs.com/docs/tutorial/chapter7/rbac
- [ ] https://docs.redwoodjs.com/docs/tutorial/chapter7/api-side-currentuser
- [ ] https://docs.redwoodjs.com/docs/typescript/generated-types
- [ ] https://docs.redwoodjs.com/docs/typescript/utility-types
- [ ] https://docs.redwoodjs.com/docs/canary/graphql/mocking-graphql-requests
- [x] https://docs.redwoodjs.com/docs/how-to/pagination/

**Comment by Philzen** [comment]
Phew this was quite a lot of work, but it's done. @Tobbe kindly review at your convenience.

BTW – i'm not sure what prettier is complaining there, i pretty much ran all changed code through my local linter before copying it into the docs.

**Comment by Tobbe** [comment]
> @Tobbe kindly review at your convenience.

Will do!

BTW, did you see my DM on the forums?

**Comment by Philzen** [comment]
> BTW, did you see my DM on the forums?

Just saw it two days ago and still digesting it … will answer soon, promised.

**Comment by Philzen** [comment]
@Tobbe the smoke tests are failing b/c 

https://github.com/Philzen/redwood/blob/4f5ac126f4c7292bfe7575afdce625f9559724ef/__fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.test.tsx#L25-L42

these generated tests include an `id` prop … but the cell doesn't require one :monocle_face: 

These IDs appeared in https://github.com/redwoodjs/redwood/commit/495f6259448e614f93a69ccc4cdce43a0d30eb09#diff-61b70e171dde41fe8e245f38f44c78d8ec3354923c8b8b9a9713d1b1f7db74f8 – so i guess `idName` evaluates to true in the template when it shouldn't.

**Comment by Tobbe** [comment]
> @Tobbe the smoke tests are failing b/c
> 
> https://github.com/redwoodjs/redwood/blob/95afaf986a5f8d2a409f96ec51ef1ab2da3edfda/__fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.test.tsx#L25-L41
> 
> these generated tests include an `id` prop … but the cell doesn't require one 🧐
> 
> These IDs appeared in [495f625#diff-61b70e171dde41fe8e245f38f44c78d8ec3354923c8b8b9a9713d1b1f7db74f8](https://github.com/redwoodjs/redwood/commit/495f6259448e614f93a69ccc4cdce43a0d30eb09#diff-61b70e171dde41fe8e245f38f44c78d8ec3354923c8b8b9a9713d1b1f7db74f8) – so i guess `idName` evaluates to true in the template when it shouldn't.

Fixed in #11779 
Thanks for figuring out what was wrong

**Pull request merged**
