### PR TITLE
Support unix socket or port for functions server

### PR DESCRIPTION
**Pull request by brentjanderson**
I'm trying to get instructions together to run Redwood on Heroku. Given that half of the app runs as a statically built site and the other half runs with `@redwoodjs/api-server`, I'm planning on doing the following:

1. Add a build script to the root package.json `yarn rw build`
2. Have a [`release` phase](https://devcenter.heroku.com/articles/release-phase) that runs `yarn rw db up`
3. Have a modified "start" script that fires up the api-server using a UNIX Socket (because that's what Heroku lets you work with [when you want to run multiple backends from a single frontend Nginx server](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-nginx))
4. Use the Heroku NGINX buildpack and point it at that unix socket for the API and the built `web` HTML

This PR enables step 3. If you specify `--socket` then it will mount it on that local socket instead of a given port. On process exit, we clean up the socket. The other changes would be made by teams wanting to deploy to heroku.

### CODE REVIEW

**Comment by peterp** [comment]
This is awesome, thanks!

**Review by peterp — APPROVED** [review]

**Comment by brentjanderson** [comment]
@peterp I missed putting the `process.on('exit', ...` around the app.close. Should exhibit the expected behavior now.

**Comment by brentjanderson** [comment]
As a follow-on to this, I've got the bare bones of a guide for running Redwood on Heroku here: https://gist.github.com/brentjanderson/dcb59c46023c67c44eb12492b038ff84

I've got it working on an internal app built with Redwood and running on Heroku. I haven't had someone try and use those instructions themselves yet to proof that they're workable, but it's pretty straightforward once this PR lands and if you add in the right pieces for heroku (Nginx conf file, Procfile, app.json, build/start script, etc.)

Comments there welcome - I'll drop a note on the forum as well for feedback.

**Comment by Tobbe** [comment]
> I'll drop a note on the forum as well for feedback.

Great idea! 👍

**Comment by brentjanderson** [comment]
https://community.redwoodjs.com/t/self-host-on-heroku/1765

**Pull request merged**
