### PR TITLE
Upgrade Azure Active Directory authentication from msal to @azure/msal-*

### PR DESCRIPTION
**Pull request by jeliasson**
### Motivation 💡

Microsoft's [msal](https://www.npmjs.com/package/msal) package used for Azure Active Directory authentication is deprecated in favor of [@azure/msal-browser](https://www.npmjs.com/package/@azure/msal-browser). This new library uses the [OAuth 2.0 Authorization Code Grant](https://oauth.net/2/grant-types/authorization-code) with PKCE instead of Implicit Flow. Furthermore, in the current version of RedwoodJS we are using a msal's popup method to initialize the login process. On modern browsers, combined with corporate policies, this becomes challenging. For that reason, let's try using redirects.

### Breaking 💥

This PR will break current Azure Active Directory authentication implementations and will require code modifications. 

#### Suggestion to upgrade notes
Microsoft has deprecated `msal` in favor of `@azure/msal-browser` which introduces [OAuth 2.0 Authorization Code Grant](https://oauth.net/2/grant-types/authorization-code) with PKCE instead of Implicit Flow. Long story short, you need to make a few changes;

1. Update your [Application registration](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md#1-update-application-registration). Redwood docs will be updated with version 0.39, but a preview can be found [here](https://deploy-preview-814--redwoodjs.netlify.app/docs/authentication#azure-active-directory).
2. Replace dependency `msal` with `@azure/msal-browser` in **web/package.json**. Example [here](https://github.com/redwoodjs/playground-auth/pull/78/files#diff-b861012a5dd72b8a9f3281b7cf09f5a779c98569d040b1bbc1db50f1b15e7cce)
3. Replace import reference `UserAgentApplication` from `msal` to `PublicClientApplication` from `@azure/msal-browser` in **web/App.js**. Example [here](https://github.com/jeliasson/playground-auth/commit/531198d6f90ec1bce2bde0dcd9daae3354d7fcfb#diff-38c7c61831a48537ce060ecbc4950d85dc5d35c51a74cf2674b9af7692fa4c7bR1-R11).

As of this version, we will use redirect instead of popup, as some browsers may disable popup on first click.

### Todo 🐻

- [X] Initial implementation
- [x] Figure out a good way to handle redirect promise. Use of `restoreAuthState()` method?
- [x] Update decoder
- [x] Test: Playground Auth
- [x] Update snapshot (2a3a46c4e33b13d09c8116ae74cc57ea6649f4c1)
- [x] Linting and tests are passing
- [x] Test: OOBE project with `rwfw` linking
- [x] Canary release (#3631)
- [x] Test: Canary release
- [x] Breaking release notes
- [x] Documentation
- [ ] Ship

### Related PR's
- [redwoodjs/redwood](https://github.com/redwoodjs/redwood/issues/3490): Upgrade of auth client
- [redwoodjs/playground-auth](https://github.com/redwoodjs/playground-auth/issues/78): Test of auth client (__Awaiting 0.38 release__)
- [redwoodjs/redwoodjs.com](https://github.com/redwoodjs/redwoodjs.com/issues/814): Documentation

### References
* [David's summary on `msal` library is no longer receiving new features](https://github.com/redwoodjs/redwood/issues/3377#issuecomment-918783480)
* [Microsoft documentation on Migrating from MSAL 1.x to MSAL 2.x](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md)

/cc @andrewlamyw

### CODE REVIEW

**Comment by jeliasson** [comment]
@thedavidprice In order to test this in live application (not using `rwfw`), how would one go about doing that? Any RC around the corner? I really miss the PR builds, but I think @Tobbe explained that they were not that reliable and I guess that's the reason they are removed. 

I have a few more things to test/make shiny before I will make it ready for review.

/cc @andrew-hwahin

**Comment by thedavidprice** [comment]
@jeliasson thank you for working on this! We definitely would like to have this updated for v1-rc 🚀

FYI: I need to bump the ETA release (doing now) as it's not going to be on the 19th

Testing:
Yes, this is definitely one of those PRs that can't be fully tested locally. Here's what I suggest:
- test as much as you can locally via rwfw project:sync
- one you feel GoodEnough™ let's get this merged, which will trigger a `canary` release
- we should run complete functional tests by installing the canary in a test project

How does that sound?

**Comment by jeliasson** [comment]
@thedavidprice Sounds great. I do a few more `rwfw project:sync` tests and get back to you by the end of the week when I think we're go to go with a RC.

@andrew-hwahin Feel free to ping me on Discord if you have any issues or suggestions on your end with the current PR.

**Comment by thedavidprice** [comment]
@jeliasson apologies for the delay here! Huge thank you. And we'll definitely get this in for v0.39 All the content for Release Notes is 🤩

Looping in @dthyresson for review of the auth template types.

**Review by dthyresson — APPROVED** [review]
LGTM. As for the types the current template has the same types as others -- the issue as that  is noted is that context.currentUser isn't typed so roles has an unknown type.

But that isn't specific to Azure.

**Review by thedavidprice — APPROVED** [review]

**Comment by thedavidprice** [comment]
Canary release corresponding to this PR is `@redwoodjs/web@0.38.1-canary.29`

**Pull request merged**
