### PR TITLE
Custom `useAuth` pass through for `RedwoodApolloProvider`

### PR DESCRIPTION
**Pull request by realStandal**
Looping in @dac09 as he helped a bunch with debugging this with me.

Bit of a background, I'm using a [custom authentication client](https://github.com/LockTech/cerberus-service-client-js) and [provider](https://github.com/LockTech/cerberus-service-client-js/tree/master/src/RedwoodAuth). Long story short, it's to use Supabase (GoTrue) in ways it wasn't *technically*, truly built for. (I've roughly explored using Redwood's `AuthProvider`, but felt it'd be more patchy to get it to work in my favor than to provide a "proper" custom alternative, I'm off subject)

This PR will provide better pass through for a custom `useAuth` hook, given to `<RedwoodApolloProvider>`. The commits highlight each change. Worth noting is that it makes the `useAuth` hook optional for `RedwoodApolloProvider`. I've ran into the TypeScript error for wanting it since I started using TS with Redwood, I assume it should be optional and took the chance to set it as so; figure it fits well with the rest of the changes here.

Prior to the PR, Redwood would only use its hook to retrieve the current auth-state, for requests sent through Apollo. This would result in my application's requests not containing the proper `Authorization`, and related, headers; causing all of my requests to be rejected.

[This is my application](https://github.com/LockTech/cerberus/blob/aaae65afe578ecfcf5d24eb5774996fd86a81461/web/src/App.tsx#L27), there are no existing tests for the ApolloProvider so I used it to test. I ran it with and without defining the custom hook, with the above not taking place and taking place, respectively.

I have a general idea as to how a test would look for it:

- Mock Redwood's `useAuth` and a custom one.
- Run seperate test, providing no `useAuth` hook and then providing the mocked one.
- Assert, based on which test, that the mocked functions are (not) called after a `useQuery`/`useMutation` is ran.

---

Alternatively, is there another way to make my hook known that I'm overlooking? Right now I pass it to both `RedwoodApolloProvider` and my `Router`; which covers making my `<Private>` and (after this PR) requests aware of the provider, but I've also seen `global.__REDWOOD_USE_AUTH` or similar. That seems to be a backup/fallback though?

### CODE REVIEW

**Comment by peterp** [comment]
This seems reasonable, but I'm wondering if a  custom auth client wouldn't work for you?

**Comment by realStandal** [comment]
@peterp With this change merged, I *should* be able to drop my `AuthProvider` (~90% of it is Redwood's, as is).

Off the top of my head (I should have wrote this down, lol), my issue was wanting a custom client but with some of the functionality offered by `type="supabase"`. If I recall correctly, I need this functionality on the backend; using it to trick my API into thinking the request originated from a supabase client, so I can take advantage of Redwood's decoder.

With this PR, I maybe able to minimize the custom-code to just the hook. Redwood should then use my hook, which I can configure to pass my custom client with `type="supabase"`, like I need.

**Review by dac09 — APPROVED** [review]
LGTM!

**Comment by dac09** [comment]
Hey @realStandal - looks like you didn't give us permission to modify the branch, needs a pull from main before merge :)

**Comment by realStandal** [comment]
@dac09 Windows hasn't completed its test, but there you are; updated and any GitHub action resolved.

**Comment by Tobbe** [comment]
@realStandal Could you please add this to the docs as well? So ppl know this is possible.
And also, this links needs updating now
image

**Comment by realStandal** [comment]
@Tobbe sure, which page is that your screenshot is from?

**Comment by Tobbe** [comment]
Ohh, sorry, should obviously have given you the link. Here it is!

https://redwoodjs.com/docs/graphql

**Comment by realStandal** [comment]
Thank you @Tobbe I'll get to it ASAP

**Comment by Tobbe** [comment]
> Thank you @Tobbe I'll get to it ASAP

🔥

**Pull request merged**
