### PR TITLE
Update Clerk import in decoder

### PR DESCRIPTION
**Pull request by stephenhandley**
We ran into the following error when trying to use Clerk with Redwood. 
```
api | 16:37:43 🚨 graphql-server Error building context. Error: Exception in getAuthenticationContext: Cannot find module './dist/instance'
api | Require stack:
api | - PROJECT_DIR/node_modules/@clerk/clerk-sdk-node/instance.js
api | - PROJECT_DI/node_modules/@redwoodjs/api/dist/auth/decoders/clerk.js
api | - PROJECT_DIR/node_modules/@redwoodjs/api/dist/auth/decoders/index.js
api | - PROJECT_DIR/node_modules/@redwoodjs/api/dist/auth/index.js
api | - PROJECT_DIR/node_modules/@redwoodjs/api/dist/index.js
api | - PROJECT_DIR/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js
api | - PROJECT_DIR/node_modules/@redwoodjs/graphql-server/dist/index.js
api | - PROJECT_DIR/api/dist/functions/graphql.
```

We had a dep of `@clerk/clerk-sdk-node` of 4.4.0 

I believe what was at issue are the following lines in the decoder:
https://github.com/redwoodjs/redwood/blame/main/packages/api/src/auth/decoders/clerk.ts#L5-L7
```
const Clerk = require('@clerk/clerk-sdk-node/instance').default

const { users, base }: IClerk = new Clerk()
```

Clerk version 4.4.0 no longer has a `dist/instance.js` file instead there are `dist/esm/instance.js` and `dist/cjs/instance.js` files. they also now just export a singleton on the default. Changing the above lines to the following fixed things for us locally
```
const { users, base } = require('@clerk/clerk-sdk-node').default
```

### CODE REVIEW

**Comment by noire-munich** [comment]
@stephenhandley good to see you!
Many thanks for taking the time to make a PR on this, we shall look into it.

**Comment by stephenhandley** [comment]
Awesome thanks @noire-munich good to see you too!

**Review by noire-munich — APPROVED** [review]

**Comment by Tobbe** [comment]
Just a heads up here 🙂   I merged #5985 about an hour ago. The clerk decoder now lives in https://github.com/redwoodjs/redwood/blob/main/packages/auth-providers-api/src/clerk/decoder.ts

**Review by noire-munich — CHANGES_REQUESTED** [review]
Since decoupled auth has been merged the file has changed location, please check this comment
https://github.com/redwoodjs/redwood/pull/6685#issuecomment-1278179874

**Comment by stephenhandley** [comment]
@noire-munich @Tobbe ok just moved the changes to the new file path

**Review by noire-munich — APPROVED** [review]

**Comment by Tobbe** [comment]
We also have this PR that seems to be making a similar change. Which one should we go with? https://github.com/redwoodjs/redwood/pull/6719

**Comment by stephenhandley** [comment]
@Tobbe good thing from that PR missing from mine is all the bumped deps, however the implementation in the [decoder](https://github.com/redwoodjs/redwood/pull/6719/files#diff-4c9cf0cde0481046fffd2bbf5680e8d2ff883832ae98672e0c417d20bcbbab0d) looks a lot more brittle with the use of the instance paths.

**Comment by noire-munich** [comment]
@stephenhandley I'm holding my approval until either this PR or [this one](https://github.com/redwoodjs/redwood/pull/6719) gets everything we feel we'd need.
I'd opt for your implementation of not using the instance paths, but @SokratisVidros being the founding engineer of Clerk I'm interested into knowing why he's using it.

**Comment by SokratisVidros** [comment]
@stephenhandley Thanks for submitting this. 

@noire-munich The PRs are basically the same, fixing a backward incompatible change we made in `@clerk/clerk-sdk-node`. 

You can merge either of them.

**Comment by MehdiSv** [comment]
@noire-munich Any update on this? We'd love to be able to use the latest version of Clerk with Redwood.

**Comment by alephao** [comment]
@noire-munich can we just approve this one then, it seems @SokratisVidros is fine with it and it doesn't use instance paths

**Review by noire-munich — APPROVED** [review]

**Comment by noire-munich** [comment]
@stephenhandley I've approved this, if you'd like to bump before we merge it would be great, otherwise we'll use the other PR for that.

**Comment by SokratisVidros** [comment]
Cool. I am closing mine.

**Comment by Tobbe** [comment]
I've confirmed that this fixes the require call for the decoder. Still seems like we have a problem with our Clerk implementation though. I'll try to merge this PR, and then I'll submit a new PR for fixing the new issue I found. (Navigating to a page that requires that you're logged in prints "Please wrap your auth provider with `<ClerkLoaded>`" in the console and just redirects you back to the home page. We do wrap our router in `<ClerkLoaded>`

**Pull request merged**
