### PR TITLE
Check node yarn compatibility before starting crwa

### LINKED ISSUE #1968: create-redwood-app should fail if the requirements are not met
At the moment 3/112021 6:05 pm EST it generates some code - and only then realizes that it should not have generated any

image

### PR DESCRIPTION
**Pull request by callingmedic911**
Closes #1968

- [x] Moved node and yarn compatibility check before copying template files. Reads `engines` from `package.json` of `templateDir` instead of `newAppDir`, since there’s nothing copied so `newAppDir` is blank. 
- [x] Link to the doc if compatibility check fails. Currently using https://learn.redwoodjs.com/docs/tutorial/prerequisites/#nodejs-and-yarn-versions
- [x] If there's an error during CRWA process, check if the new directory is created and warn user about it.

Screenshot of compatibility error with docs link:
Screenshot 2021-06-11 at 5 51 40 PM

If there's an error during the process:
Screenshot 2021-06-11 at 5 51 09 PM

Let me know if I should better rephrase the warning, update any docs/test.

### CODE REVIEW

**Review by jtoar — CHANGES_REQUESTED** [review]
@callingmedic911 thanks for taking this on! This is super important for v1 since we want the first experience to be as graceful as possible.

There's a few things I'm thinking about suggesting, but here's just one for now: if there's one error, it outputs all the errors. For example, here I have the wrong node version but the right yarn version, but it still says my yarn version is incorrect:

image

**Comment by callingmedic911** [comment]
> There's a few things I'm thinking about suggesting, but here's just one for now: if there's one error, it outputs all the errors. For example, here I have the wrong node version but the right yarn version, but it still says my yarn version is incorrect

@jtoar Filtered to show only unsatisfied dependencies.
I, too, was wondering whether this was intentional. But missed to bring it up for discussion, thanks for the suggestion.

If you think there's more to improve here, please do suggest. I'll be glad to incorporate. :)

**Comment by Tobbe** [comment]
I'm running node 16 locally. Would it be possible to have a --force option to copy the files even though the check fails? That way I can manually update `engines` in `package.json` and then run `yarn install`.

And/or disable the version check if running with `--no-install`

**Comment by thedavidprice** [comment]
> And/or disable the version check if running with --no-install

Good call @Tobbe Added this check to skip the task. Updated option description as well.

**Comment by thedavidprice** [comment]
Thanks for all your work here @callingmedic911 🚀

**Pull request merged**
