### PR TITLE
update scaffold generator to use emptyAsUndefined when its needed

### PR DESCRIPTION
**Pull request by samthuang**
Update the use of scaffold generator to include `emptyAs('undefined')` when the FormField component is a relational field and is not required.

resolves: https://github.com/redwoodjs/redwood/issues/4354

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks @samthuang 🚀

@Tobbe would you be able to help with this one?

**Comment by Tobbe** [comment]
Thanks for jumping in to help @samthuang! Much appreciated 🙂 

Try doing a console.log of the prisma dmmf and you'll see that it has all the info you need to figure out if a field is relational or not.

You can start looking in `packages/cli/src/lib/schemaHelpers.js` where you'll see that we use `getDMMF` from `@prisma/internals`. Following the code execution path you'll see that `getSchema()` in that schemaHelpers file has the dmmf info, and that function is already called from the scaffold generator. 

I hope that info helps you get started. Let me know if you need anymore guidance

**Comment by samthuang** [comment]
Hello, hello, @Tobbe - thank you for pointing me to the right place to look. It's beneficial! I get to learn a few things about how Prisma types its [Field](https://github.com/prisma/prisma/blob/30a839d53778bfdc3cd271c21e40ce41109eb95c/packages/generator-helper/src/dmmf.ts#L69-L93) on a Model. Super cool.

I believe it's probably best to add a test for this. Can you be so kind and show me where and how to do so? thanks!

**Comment by Tobbe** [comment]
> I believe it's probably best to add a test for this.

A test would be great! Take a look at `packages/cli/src/commands/generate/scaffold/__tests__/editableColumns.test.js` It uses mocks to mock out the filesystem. So you can call the scaffold generator and the files will be generated in memory. You can then verify that `emptyAs` has been generated as you expect. If you need to you can add a new model to `packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma`, or update an existing model if you find something that's already close to what you need.

**Comment by samthuang** [comment]
Thank you for the swift response ⚡ and the pointers. Please let me know what you think of the test and the approach. cheers

**Comment by Tobbe** [comment]
I'm sorry I wasn't more clear. I didn't mean for you to add the test to editableColumns. I just used that as an example because it was pretty small and isolated. I think it's best to keep that one as it was, just for testing the exclusion of fields with default values. Please see if you can find some other test you can integrate the `emptyAs` test into. Or create a separate test and model for it, if needed. How you actually test your fix is perfect, just need to be moved somewhere else 🙂

**Comment by samthuang** [comment]
Good point. I took it too literally 😆. I created a separate test. Let me know if the test can be further improved on. https://github.com/redwoodjs/redwood/pull/8031/commits/2f900985e9cb8e6c80e9956e00a649ab6363ca02.

**Pull request merged**
