### PR TITLE
Parameterize query names in scaffold templates

### PR DESCRIPTION
**Pull request by saimonmoore**
Fix for issue: https://github.com/redwoodjs/redwood/issues/394

Completely untested... 

I'll try testing it tomorrow when I'm rested...

cc @cannikin

### CODE REVIEW

**Comment by cannikin** [comment]
@saimonmoore Did you ever get a chance to test?

**Comment by saimonmoore** [comment]
Not had the chance yet :(  Got very busy at work and confinement with the kids at home is tough.

**Comment by cannikin** [comment]
@saimonmoore I radically reorganized the generators and added a ton of tests so everything is conflicting everywhere! Did you want to try to fix those? I totally understand if you don't want to or don't have the time. Just let me know and I'll make the fixes. :)

**Comment by thedavidprice** [comment]
@saimonmoore Just a friendly check-in here. 100% understood about the dynamics + load these days —> if timing isn’t working out, just let us know and we’d be happy to move this forward. Thanks! And hope all is well on the work and home-front.

**Comment by saimonmoore** [comment]
Hi David,

Yes beg your pardon. Life is overtaking my ability to contribute :(

Won’t be able to do much for a while

**Comment by thedavidprice** [comment]
@saimonmoore completely understood. Thanks for letting us know and hope all is well for you and yours.

**Comment by thedavidprice** [comment]
@cannikin let me know if I can help with the conflicts. Assuming you’ll dive in otherwise.

**Comment by cannikin** [comment]
All these files have moved, the conflict resolution is gonna suckkkkk. Gonna just close this and copy stuff over to a new one.

**Pull request closed without merging**
