### PR TITLE
[WIP] Add RouteAnnouncer for accessibility

### PR DESCRIPTION
**Pull request by jtoar**
> ⚠️ WIP ⚠️

This PR addresses #540 by starting to bake accessibility into Redwood via `@redwoodjs/router`. Right now, our implementation and approach are inspired by gatsby, wholesale. Relevant links:
- [Accessibility Improvements to Client Side Routing in Gatsby - Available in 2.19.8](https://www.gatsbyjs.org/blog/2020-02-10-accessible-client-side-routing-improvements/)
- [RouteAnnouncer](https://github.com/gatsbyjs/gatsby/blob/5b15471e793aa16d8e63ad920d0f8c4c4f46052f/packages/gatsby/cache-dir/navigation.js#L161-L208)

Right now this PR just adds a `RouteAnnouncer` component to `PageLoader` that announces that the page has loaded (by saying "New page" + `location.pathname`, which is obviously less than ideal, but just getting started), which was one of the two issues mentioned in #540.

### Outstanding
- [ ] the location of this component will probably change. it should probably be moved up the tree, maybe even wrapping the Router
- [ ] focus management; Marcy's research suggests a skip link should take focus. we need to both make 1) making skip links possible, part of the framework (whether that means exporting a component or...) and 2) focus them on navigation
- [ ] add a `RouteAnnoucement` component. companion to the RouteAnnouncer (here)&mdash;letting users decide what to announce
- [ ] we've got to be wary of prerender, react helmet (this is related to that https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/route-announcer-props.js)

### CODE REVIEW

**Comment by mojombo** [comment]
Great stuff, thanks for diving into this!

**Comment by peterp** [comment]
@jtoar Is there anything that you need from me on this PR?

**Comment by jtoar** [comment]
@peterp I don't think so or not yet at least (besides what you just did, which was already super helpful: remind me I need to do this!).

**Comment by jtoar** [comment]
When it was just the `pathname`, the `RouteAnnouncer` was working because the `pathname`'s updated immediately. The whole app starts to rerender in response. But as soon as we go looking for `RouteAnnoucements`/`pageHeadings` (i.e. `<h1>`s), we run into the same problem as scroll, which is we have to wait for the page to load. As a result, it's looking like most of these a11y features might not be implemented as their own components, but as parts of the `PageLoader`.

**Comment by jtoar** [comment]
Closing in favor of #1817

**Pull request closed without merging**
