### PR TITLE
pr/setup-offline - New setup command for offline raw init.

### PR DESCRIPTION
**Pull request by noire-munich**
Since I had just added some bare support for an offline init on my project I thought I should share - there's some interest on the broader topic ( #1319 force instance )

Copies some templates to `web/public`:
- manifest.json
- offline.html
- sw.js

Modifies `web/public/index.html` to add calls to `manifest.json` & `sw.js`.

### CODE REVIEW

**Comment by Tobbe** [comment]
Create-React-App has all of this by default. Is that something for RW to consider as well? Or should we keep it as a setup command?

**Comment by noire-munich** [comment]
> Create-React-App has all of this by default. Is that something for RW to consider as well? Or should we keep it as a setup command?

Good point!
I'd argue it's tightly related to the advancement of the conversation on the offline support topic, it still is a conversation and I haven't found much code about it.
A setup command would make a 'proper' init, until we'd have settled on a clearly defined deep strategy allowing for a full support as create-react-app does.

We could also settle for an implementation equivalent to the one of create-react-app until a RW's way has been figured out.

**Comment by thedavidprice** [comment]
@noire-munich Thanks for getting this rolling! I'd really like to see this move forward. I think a good flow for this will be first adding it as an optional Setup command. This will then be a good foundation to revisit whether or not it should be part of the default for a Redwood installation.

My knowledge of this is limited. I did some research on this back in Feb/March specific to PWA requirements and mentally categorized offline support into 1) required config and 2) (magical) service worker. So the files and config you have here are jogging my memory, but I don't understand enough to know how they coordinate with a service worker.

What I'd like to see next is a discussion in the related forum topic:
https://community.redwoodjs.com/t/offline-support/1305

- Outline what Redwood needs for Redwood support
- Share research, examples e.g. Gatsby or CRA (and code?), articles for best practices... anything to help us all learn together
- Explain a bit more what you’re proposing to do here in this PR
- ?

How does that sound?

**Comment by thedavidprice** [comment]
@noire-munich just checking back on this. Assuming you've been busy with other work. But wanted to make sure my prior comment didn't add confusion or kill your momentum in some way. 

Would be great to figure out a good next step for this when you're available.

**Comment by noire-munich** [comment]
Hi @thedavidprice !
Apologies, I'm on vacations, which partly explains the delay :) ( no momentum nor motivation issues ;) ).

Ok so: my own knowledge about the topic is rather limited, I have succeeded to make the bare version of PWA working on my current RW app with the files we have here ( for the sake of demonstration, here's the [link](https://laughing-bartik-ded394.netlify.app) to my work in progress project, you can see what it provides on install - not much, bare minimum! ).

So far what I gather of it is rather close to what you have, PWA needs:
- a manifest.json configuration file, which is the first step as I understand. It has some options, but few of them are required to get it working. Chrome's console will validate your file in case of doubt, otherwise here's some doc: https://developer.mozilla.org/en-US/docs/Web/Manifest

- a declared service worker file ( `packages/cli/src/commands/setup/serviceworker/templates/sw.js.template` in the PR ). Google's documentation is the best I've found so far on the matter, explaining what it is today and giving some hints as to how we can make an active use of it: https://developers.google.com/web/fundamentals/primers/service-workers

In a nutshell, the index.html page of a website will **install** on the device the service worker on user's request. Name of the file doesn't matter. With the files in the PR, I could install the app on my phone and also on my laptop ( sweet! ).
The service worker is a versioned file and its update can be forced in the chrome console.
Service workers never deal with the DOM or the user's actions, they perform background tasks and allow us to do things in an intermediate layer, for instance, listening to any network connections and working on them, handling some file and request cache, use some APIs to communicate with the application's client side. The PR roughly shows how to cache a file and listen to network status.

Not much but I hope it puts some light on the PR :), if you can check the app you should know the only difference with my project's implementation is that I cached more files.

I'll answer in the dedicated forum topic.

**Comment by thedavidprice** [comment]
Hi @noire-munich Checking in here — is this PR something you'd like to keep working on? Even as an initial attempt, I think it's something that would be valuable given your availability.

Please do let us know as I'll likely close this out otherwise. Thanks!

**Comment by thedavidprice** [comment]
Hi @noire-munich I'm closing out this PR for now and moving the discussion to this Issue #3093

If it's something you'd like to resume, please don't hesitate to re-open this PR (or open a new one). No pressure either way!

**Comment by noire-munich** [comment]
> Hi @noire-munich I'm closing out this PR for now and moving the discussion to this Issue #3093
> 
> If it's something you'd like to resume, please don't hesitate to re-open this PR (or open a new one). No pressure either way!

Hi @thedavidprice sure, no problem, I'm buried in SportOffice still but if I can contribute I'll let you know :).

**Pull request closed without merging**
