### PR TITLE
Use Replay for smoke tests

### PR DESCRIPTION
**Pull request by callingmedic911**
This PR set up Replay for smoke tests. Dom integrated Replay in the past to debug hard-to-repro problems. There have been a lot of updates with Replay (Chromium instead of Firefox as base, new test suite dashboard, new CLI). Eventually, I want to set up Playwright (with Replay) for framework users but first for framework authors (you guys).

### How do I access the Replay dashboard?
[Dashboard home for RedwoodJS](https://app.replay.io/team/dzo0NDZlMDE1Yi1mM2RjLTRiOTktOTU4NS0xMjliNzg2MzYwYzg=) 

### How does the dashboard look?
Screenshot 2024-05-23 at 4 43 59 PM

### Can you show me how you debug with Replay?
https://www.loom.com/share/6553abcaaaac489f999547cb76773134 (very rushed, tiny demo). Docs is also a good place to start: https://docs.replay.io/ (We rewrote that recently)

Other things to note:
- Replay is not currently available for Windows. Those tests will run directly on Chromium.
- Progressive SSR is failing only on the Replay browser with headless mode. I have filed an issue internally, I'll do a follow-up once that is fixed. SSR smoke tests are running on Chromium directly.

### CODE REVIEW

**Comment by ahaywood** [comment]
@callingmedic911 Thanks for opening this PR! ... I know it's still in Draft mode, but I wanted to go ahead and point out that one of the things that we've been paying careful attention to with Replay in our repo is speed. So, as you're working on this, would you mind to pay special attention to that? ❤️

**Comment by callingmedic911** [comment]
@dac09 followup on our "failing test on Replay" discussion: I have filed an issue internally and as a workaround, I'm running that test on Chromium instead. 

I tagged you guys because you have the most context, but feel free to pass and / or ask questions. :)

**Comment by ahaywood** [comment]
@callingmedic911 I'm going to rope @Tobbe in to help provide additional context.

**Comment by Tobbe** [comment]
@callingmedic911 Thanks for doing all the work of integrating Replay with our smoke tests

**Comment by dac09** [comment]
I think we need to add the API keys! Getting failures on other PRs

```
Error: `@replayio/playwright/reporter` requires an API key to upload recordings. Either pass a value to the apiKey plugin configuration or set the REPLAY_API_KEY environment variable
```

**Comment by Tobbe** [comment]
Weird. I added that last week
[image.png](https://files.slack.com/files-pri/TE3RAGKLL-F076FF5L76U/image.png)

**Comment by callingmedic911** [comment]
Looking into it.

**Pull request merged**
