### PR TITLE
docs: Fix Typescript typo in authentication chapter

### PR DESCRIPTION
**Pull request by kunalarya**
Fixes a minor TypeScript-related typo.

### CODE REVIEW

**Comment by callingmedic911** [comment]
Thanks for the PR @kunalarya! Just wanted to point out that we want to avoid changing docs inside the versioned_docs directory. I think the path you want to modify is:

- docs/tutorial/chapter4/authentication.md

After changing the docs you can visit the canary version, something like:
[deploy-preview-5621--redwoodjs-docs.netlify.app/docs/canary/introduction](https://deploy-preview-5621--redwoodjs-docs.netlify.app/docs/canary/introduction)

More details on contributing docs: [https://github.com/redwoodjs/redwood/blob/main/docs/README.md](https://github.com/redwoodjs/redwood/blob/main/docs/README.md?rgh-link-date=2022-05-27T05%3A44%3A38Z)

**Comment by kunalarya** [comment]
Ha, thanks! I was lazy and clicked on the "edit this page" link. If I get time, I'll see if I can tweak that to point to the source rather than generated docs :)

**Comment by callingmedic911** [comment]
Fair enough, we received similar feedback in another PR. Passed the feedback to the team :)

**Review by jtoar — APPROVED** [review]
Thanks @kunalarya!

**Pull request merged**
