### PR TITLE
Support custom @id column name in scaffold

### LINKED ISSUE #5649: Add UUID support for scaffold generation
Hello!

As of v1.4.1, `yarn rw g scaffold [data-model]` generates files that assume in some places that a data model has an `id` column, even when it has been instead created with a `uuid` column.  It would be nice if scaffolding was able to generate `uuid` columns, too, since editing manually requires opening many files and is prone to error, though this is not a blocking issue.

As always, thanks for everyone's hard work.

### PR DESCRIPTION
**Pull request by samthuang**
An improvement to the scaffold feature (and other generators) allows columns with custom names to serve as the `@id` field in the Prisma data model. The scaffold feature assumes that the `@id` field is named "id" by default. This change provides flexibility to specify any name for the `@id` column if it is marked with the `@id` attribute in the Prisma data model.

### Changes
- Update the scaffold feature to accept a custom `@id` column name during code generation.
- Introduce helper functions to get id name to account for the custom `@id` column name in the generated code.
- Update template files: routes, page, cell, component, SDL, and service.
- Add tests to ensure the scaffold feature functions correctly with custom `@id` column names.

resolves #5649

### CODE REVIEW

**Comment by jtoar** [comment]
Hey @samthuang thanks for taking this one on, this part of the codebase is a little gnarly so it's super appreciated. I tried it locally and there's still some things to work out. I pushed one commit with a fix here: https://github.com/redwoodjs/redwood/pull/8264/commits/45ed22b760f9433c5da88db4fe2257e8297d27d8. This got me a little farther in creating a new user with a custom ID. Here's where I'm at now:

image

It looks like the custom ID is being generated as a required field on the create SDL (in this example, my custom ID's name is `myId`):


```diff
   input CreateUserExampleInput {
+    myId: Int!
     email: String!
     name: String
   }
```

**Comment by samthuang** [comment]
hey @jtoar - sorry for the slow response; I've been on the road for work (actually in SF now). And just to clarify on the next step, we have to somehow find a way to include the custom ID name in that `IGNORE_FIELDS_FOR_INPUT` array right (conceptually)?

**Comment by jtoar** [comment]
@samthuang yep that's right!

**Comment by samthuang** [comment]
hey hey @jtoar and team - I just want to give a quick update. I've been occupied with other works recently and haven't have the chance to visit this PR, but I still plan to work on this if possible. Hopefully to get some focus time soon!

**Comment by samthuang** [comment]
sorry it's taking me a while to wrap up the PR. I will have a ready-for-review version by the end of this week : )

**Comment by samthuang** [comment]
Hello @jtoar - again, sorry it took a while to prepare the PR for review. Please let me know if this enhancement is still needed : ) Looking forward to a review : )

**Comment by Tobbe** [comment]
@samthuang Thanks a lot for this PR. This is impressive work! So sorry we lost track of this PR 🙁 

I just tried running the tests locally (thanks for writing those!) and I'm seeing some failures

image

Are you still interested in working on this PR? If so, could you try to see why the tests are failing?
I really like the work you've done here, so I can't promise I won't go and try to fix the tests myself, just to be able to merge this PR 😆

**Comment by samthuang** [comment]
@Tobbe, thank you so much for carrying the PR to the end! sorry i have not been active in a while in following up 😅 . just curious, but how did switching to generating TS files resolve the bug?!

**Comment by Tobbe** [comment]
> just curious, but how did switching to generating TS files resolve the bug?!

`files` in the code below will be a map with file paths as keys, and file contents as values
```
  let files

  beforeAll(async () => {
    files = await scaffold.files({
      ...getDefaultArgs(defaults),
      typescript: true,
      model: 'CustomIdField',
      tests: true,
      nestScaffoldByModel: true,
    })
  })
```

At some point after you created this PR we changed to `.jsx` for JavaScript files with JSX syntax in them. So some filepaths were now like `/path/to/SomeCell.jsx` instead of `/path/to/SomeCell.js`, and so the lookup for file contents returned `undefined`. 

So I could have just updated the file paths to `.jsx` instead of `.js`. But I wanted to make sure the tests also worked with TS projects as I believe that's what most of our users choose these days.

**Comment by samthuang** [comment]
Ah! Got it, thank you so much for taking the time to explain 😄 really appreciate it.

**Pull request merged**
