### PR TITLE
feat(CI): speed up docs-only CI step

### PR DESCRIPTION
**Pull request by jtoar**
The docs-only action does need some dependencies (unfortunately), but it turns out we can just install the ones it needs by making it's own package.json and yarn.lock file. This should save some valuable CI time (if it works). Thanks @dac09!

Before:

Screen Shot 2022-07-26 at 1 39 34 AM

After:

Screen Shot 2022-07-26 at 1 37 44 AM

### CODE REVIEW

**Comment by dac09** [comment]
Looks like it does! 1m+ saved!

**Review by dac09 — APPROVED** [review]

**Comment by dac09** [comment]
Just need to remove these deps from the main package.json now!

**Comment by jtoar** [comment]
@dac09 Ah they're still used by https://github.com/redwoodjs/redwood/blob/main/tasks/check/check.mjs. But maybe we could optimize that too

**Comment by dac09** [comment]
Happy to merge as is, we can tackle that separately :)

**Pull request merged**
