### PR TITLE
Specify node_env before running build web

### PR DESCRIPTION
**Pull request by dac09**
Small change to make sure all downstream loaders/plugins for webpack receive NODE_ENV as production when running `yarn rw build web`

This takes care of a lot of weird issues that arise, such as Tailwind not minifying (unless you're lucky, and your build environment has NODE_ENV production by default).

### CODE REVIEW

**Review by peterp — APPROVED** [review]

**Comment by dac09** [comment]
I know I blocked merging this, but I have to resolve conflicts in build.js anyway. Gonna merge!

**Comment by razzeee** [comment]
Would this explain, why accessing `NODE_ENV` on a deployed server always seems to return `production` instead of what we've set in `NODE_ENV`, or should that still be loaded from env when we run `yarn rw serve`?

https://redwoodjs.com/docs/environment-variables#where-does-redwood-load-my-environment-variables isn't very clear if it really applies to all `yarn rw` commands I think.

**Comment by dac09** [comment]
> Would this explain, why accessing `NODE_ENV` on a deployed server always seems to return `production` instead of what we've set in `NODE_ENV`, or should that still be loaded from env when we run `yarn rw serve`?
> 

Correct - NODE_ENV will always be overridden to production when you build and serve.

**Comment by razzeee** [comment]
might be worth documenting on the env var docs

**Pull request merged**
