### PR TITLE
Amend import order in auth templates according to ESLint rules introduced in v2.0

### PR DESCRIPTION
**Pull request by Philzen**

### CODE REVIEW

**Review by jtoar — APPROVED** [review]
Looks good, thanks again @Philzen!

**Comment by jtoar** [comment]
This PR changes a setup command, so leaving a quick note to myself to double check the fixtures.

**Comment by Philzen** [comment]
> This PR changes a setup command, so leaving a quick note to myself to double check the fixtures.

While working on #6159 i realized that there are multiple templates that needed import order fixes. I've fixed all of those now. As i'm currently trying to close off any open ends before i go silent for my summer hiatus, just wanted to quickly check back whether the fixtures are OK or anything needs to be done. I'm happy for you to add any necessary changes to this PR otherwise.

---

@jtoar as i am currently peeking in the `.github`-folder and can see you wrote a lot of the CI configuration (which is an art by itself, but a highly useful one!): the other day i was contemplating about the types of issues i'm seeing and working on, and i believe it's a good dozen now that all come down to the same thing: TypeScript or linting errors in code that is generated via CLI that would easily be detected via `yarn rw lint`

I can see that there is a linting job in the `ci.yml`, but i believe we should expand a little bit here. We'd need a smart test suite that executes each and every possible code-generating command (scaffolds, other generators, setup ui, setup auth) etc. on the generated test project, runs `yarn rw lint` after that each of them on the generated files, and then hard resets it again.

What do you think? Would that be achievable?

From what i can see, that would have saved us dozens of individual "cleanup afterwards" PRs – and i can foresee many regressions happen over and over again, e.g. next time we change the ESLint rules, but also on simple changes to some of the more complex generators.

**Review by Tobbe — APPROVED** [review]

**Comment by Tobbe** [comment]
@Philzen Thanks for this. This is great. And I've made the same changes to my auth refactor PR https://github.com/redwoodjs/redwood/pull/5985

This PR now needs the test project fixtures updated. So either you do that (__fixtures__/test-project/api/src/lib/auth.ts)
Or we close this PR and wait for my refactor PR to land. You decide :)

**Comment by Philzen** [comment]
> @Philzen Thanks for this. This is great. And I've made the same changes to my auth refactor PR #5985
> 
> This PR now needs the test project fixtures updated. So either you do that (**fixtures**/test-project/api/src/lib/auth.ts) Or we close this PR and wait for my refactor PR to land. You decide :)

@Tobbe I must be too tired / overworked but i'm simply not getting what i'd need to change in `__fixtures__/test-project/api/src/lib/auth.ts` (the import order seems fine in there), can you give me a hint?

Also, do i understand correctly that this file would also need to be synchronized for #6159 to go through?

As i already invested the effort, i'd of course prefer those to go through and claim the (albeit-so-little) fame :wink: But if you're saying this will create huge rebasing conflicts on your branch, and that is going to land soon (=early enough to ship in v2.3) you may close this.

Otherwise, i'd prefer you pushing the necessary change to this PR directly, enlighten me directly through that, and have those fixes merged and available for any users starting fresh with v2.3.

**Comment by Tobbe** [comment]
> @Tobbe I must be too tired / overworked but i'm simply not getting what i'd need to change in `__fixtures__/test-project/api/src/lib/auth.ts` (the import order seems fine in there), can you give me a hint?

It's a weird hour for both of us 🙂 

The bot isn't smart enough to know if anything *actually* needs to be updated. It just looks at what files were changed. I've overruled the bot, and have now enabled auto-merge

**Comment by Tobbe** [comment]
> Also, do i understand correctly that this file would also need to be synchronized for #6159 to go through?

Yes, for that one you actually do have to update the fixture

> As i already invested the effort, i'd of course prefer those to go through and claim the (albeit-so-little) fame 😉 

Fame is well deserved! Of course you should have it

> But if you're saying this will create huge rebasing conflicts on your branch, and that is going to land soon (=early enough to ship in v2.3) you may close this.

The next release is most likely going to be a breaking v3.0 release. Hopefully this or next week. I feel like I'm making good progress on the auth refactor, but I can't promise it'll be ready for v3. Especially since we'd need to update the api side too to take full advantage of the changes I'm making. And that work has only been started on an experimental level so far. No ongoing PR.

**Comment by Philzen** [comment]
@Tobbe While finalizing #6061 i realized the imports in the dbAuth scaffolds were also not yet ordered accordingly and quickly added that on top as a separate commit. Kindly review.

**Pull request merged**
