### PR TITLE
fix: typo in graphql.md generate service command

### PR DESCRIPTION
**Pull request by alephao**
Fix typo `yarn rw g services` -> `yarn rw g service`

### CODE REVIEW

**Review by jtoar — APPROVED** [review]
Thanks @alephao!

**Comment by jtoar** [comment]
@alephao I'm also realizing now that you may have clicked "edit this page on GitHub" at the bottom of the page and that may have directed you to the versioned file. If that's the case we have a fix in the works here: https://github.com/redwoodjs/redwood/pull/5658.

**Comment by alephao** [comment]
> I'm also realizing now that you may have clicked "Edit this page"
Oh yea, that's what I did, will update pr

**Comment by alephao** [comment]
@jtoar I made the change on all versioned docs (since it seems to be wrong in all versions) AND the docs folder. Not sure if I should have done on all or just docs. Let me know if it's better to remove from versioned_docs.

**Review by jtoar — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
