### PR TITLE
fix issue with function import in generate model

### PR DESCRIPTION
**Pull request by Cluster444**
I think this should resolve the issue, not sure exactly how to test it but it makes it the same as `record/init.js`

### CODE REVIEW

**Comment by cannikin** [comment]
After talking with @Tobbe it looks like a `.default` on the import will make it work, and keep the import async:

```js
const { parseDatamodel } = (await import('@redwoodjs/record')).default
```

Apparently v6 handles these `export *` declarations differently than before. All of that is now packaged up inside `default` instead of spreading them out like `export { parseDatamodel }` would have.

A cleaner option: get the `export` to *not* package that stuff up into `default` and make it stay a named export (which would be expected by folks using the package, I imagine).

@Tobbe suggests that adding `"type": "module"` into Record's `package.json` may do the trick without having to change the import *or* the export syntax. That enables ES6 modules. But if that doesn't work, just see about fixing the `export`!

**Comment by Tobbe** [comment]
Yeah, setting `"type": "module"` will probably have other side effects that breaks other things. But it's worth a shot.

**Comment by cannikin** [comment]
And assuming one of those solutions works, let's switch over `record init` to do an `async` import as well, so that the package is no longer being included by default!

**Comment by Cluster444** [comment]
Ok that sounds good. I'll tinker with it here in a bit.

Certainly agree on it being best to not have it in the bundle if it's not being used!

**Comment by Tobbe** [comment]
I'm cleaning up our PRs in preparation for the next major version of RW. This one seems to have gone stale, so I'm going to close it. 
I really appreciate the work that's gone into this PR 🌟 

If anyone is still interested in working on this feature or if there are any unresolved issues, please feel free to:
 1. Reopen this PR: If there are specific changes or updates needed.
 2. Create a new PR: In case you'd like to start fresh or make significant modifications.

Let's keep the collaboration going 🚂  If you have any questions or need assistance, don't hesitate to reach out. Thanks again for the contributions 🙏

**Pull request closed without merging**
