### PR TITLE
chore: Updates Supabase readme, docs and tests for sign up with options and user/session

### PR DESCRIPTION
**Pull request by dthyresson**
This PR:

* Updates Supabase auth readme and docs to include examples of sign up with options (user metadata, redirectUrl)
* Updates also with how to get current user and user metadata
* Adds tests for signing up with options

Addresses https://github.com/redwoodjs/redwood/issues/6146 via documentation (and the prior v2 upgrades).

### CODE REVIEW

**Comment by KrisCoulson** [comment]
Just dropping this here for when we get around to SSR with render modes and using supabase cookies 

https://supabase.com/docs/guides/auth/server-side-rendering

**Comment by jtoar** [comment]
@dthyresson I think some of the existing docs are incorrect. I can't comment on all the relevant lines but here are my notes:

- the code block in [Sign in a user through Passwordless/OTP](https://deploy-preview-7765--redwoodjs-docs.netlify.app/docs/canary/auth/supabase#sign-in-a-user-through-passwordlessotp) and [Sign in a user through OAuth](https://deploy-preview-7765--redwoodjs-docs.netlify.app/docs/canary/auth/supabase#sign-in-a-user-through-oauth) is the same
- I'm not sure the code block in [Verify and log in through OTP](https://deploy-preview-7765--redwoodjs-docs.netlify.app/docs/canary/auth/supabase/#verify-and-log-in-through-otp) is helpful because it won't work in react component (you have to put the await in a `useEffect`)
  - same with [Retrieve a session](https://deploy-preview-7765--redwoodjs-docs.netlify.app/docs/canary/auth/supabase#retrieve-a-session)
  - [Listen to auth events](https://deploy-preview-7765--redwoodjs-docs.netlify.app/docs/canary/auth/supabase#listen-to-auth-events) should also be in a `useEffect` because it's setting up an event listener; when do we clean it up? does that happen automatically?

These changes would have to be replicated in the readme.

**Comment by dthyresson** [comment]
> @dthyresson I think some of the existing docs are incorrect. I can't comment on all the relevant lines but here are my notes:
> 
> * the code block in [Sign in a user through Passwordless/OTP](https://deploy-preview-7765--redwoodjs-docs.netlify.app/docs/canary/auth/supabase#sign-in-a-user-through-passwordlessotp) and [Sign in a user through OAuth](https://deploy-preview-7765--redwoodjs-docs.netlify.app/docs/canary/auth/supabase#sign-in-a-user-through-oauth) is the same

Thanks for catching. Fixing.

> * I'm not sure the code block in [Verify and log in through OTP](https://deploy-preview-7765--redwoodjs-docs.netlify.app/docs/canary/auth/supabase/#verify-and-log-in-through-otp) is helpful because it won't work in react component (you have to put the await in a `useEffect`)
>   
>   * same with [Retrieve a session](https://deploy-preview-7765--redwoodjs-docs.netlify.app/docs/canary/auth/supabase#retrieve-a-session)
>   * [Listen to auth events](https://deploy-preview-7765--redwoodjs-docs.netlify.app/docs/canary/auth/supabase#listen-to-auth-events) should also be in a `useEffect` because it's setting up an event listener; when do we clean it up? does that happen automatically?
> 
> These changes would have to be replicated in the readme.


For these, I referenced the Supabase docs, such as:

https://supabase.com/docs/reference/javascript/auth-getsession

```

const { data, error } = await supabase.auth.getSession()

```

I'm not sure if it needs to be in a useEffect(). I'll ask Supabase.

**Comment by dthyresson** [comment]
Turns out, they do need to be in a useEffect() as shown in this Remix example: https://supabase.com/docs/guides/auth/auth-helpers/remix

```ts
const { env, session } = useLoaderData<typeof loader>()
const fetcher = useFetcher()

const [supabase] = useState(() =>
  createBrowserClient<Database>(env.SUPABASE_URL, env.SUPABASE_ANON_KEY)
)

const serverAccessToken = session?.access_token

useEffect(() => {
  const {
    data: { subscription },
  } = supabase.auth.onAuthStateChange((event, session) => {
    if (session?.access_token !== serverAccessToken) {
      // server and client are out of sync.
      // Remix recalls active loaders after actions complete
      fetcher.submit(null, {
        method: 'post',
        action: '/handle-supabase-auth',
      })
    }
  })

  return () => {
    subscription.unsubscribe()
  }
}, [serverAccessToken, supabase, fetcher])
```

@jtoar I've made those doc updates. Thanks!

**Review by jtoar — APPROVED** [review]

**Pull request merged**
