### PR TITLE
Layer0 Deploy: Rebrand Layer0 to Edgio

### PR DESCRIPTION
**Pull request by tristanlee85**
This is dependent on new releases from Edgio team for `@layer0/redwood` and `@edgio/redwood` packages that includes the `toml` > `@iarna/toml` dependency update.

### CODE REVIEW

**Comment by tristanlee85** [comment]
@jtoar We released Edgio v5.0.5 which includes the package updated for this PR: https://docs.edg.io/guides/changelog#:~:text=(5.x)%20Update%20Redwood%20toml%20dependency%20(%231577)%20%40tristanlee85

Let me know the next steps, please. Thank you!

**Review by jtoar — APPROVED** [review]

**Comment by jtoar** [comment]
Thanks @tristanlee85—are there any changes we have to make upgrading from `@egio` v5 to v6?

**Comment by tristanlee85** [comment]
> Thanks @tristanlee85—are there any changes we have to make upgrading from `@edgeio` v5 to v6?

There's no changes in Edgio v6 from v5 other than Node 16 support.

**Comment by ajcwebdev** [comment]
It looks like this is merged but the docs are still showing the Layer0 example, do you know what's up with that @jtoar?

https://redwoodjs.com/docs/deploy/layer0

**Comment by thedavidprice** [comment]
This is a breaking change included in v5. Respective docs are canary version.

**Pull request merged**
