### PR TITLE
Fix gitpod port forwarding

### LINKED ISSUE #3430: Current GitPod + Redwood Issues
cc @dac09 @mikenikles

GitPod test with current v0.37.0 release branch:
http://gitpod.io/#https://github.com/redwoodjs/redwood/tree/release/minor/v0.37.0

## API Port: broken proxy
After startup with `yarn rw dev` seeing this console error, which breaks API in the Test-project.
```
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8910/graphql to http://[::1]:8911/ [EADDRNOTAVAIL] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
Screen Shot 2021-09-25 at 11 24 42 AM

My best guess is this is due to changes in the Webpack-dev-server API (upgraded to v4 in Redwood v0.36): https://webpack.js.org/configuration/dev-server/

I can't find applicable settings in GitPod to manage this.

## Safari Console: output is hidden
In the screenshot below, you can see the output is available (highlighted block), but the font is styled so that it doesn't display:
Screen Shot 2021-09-25 at 11 26 36 AM

##

### PR DESCRIPTION
**Pull request by dac09**
Fixes #3430

### CODE REVIEW

**Comment by dac09** [comment]
@mikenikles afraid this doesn't quite work. I think its less to do with webpack, and something that's changed recently in forwarding ports within gitpod. 

Tried accessing the graphql explorer directly on 8911, doesn't seem to work either:
https://8911-XXXX.gitpod.io/graphql

**Comment by mikenikles** [comment]
Hey Daniel, I get it to work when I also change `[::1]` to `localhost` as mentioned in https://github.com/redwoodjs/redwood/issues/3430#issuecomment-927393564.

To get `/graphql` on port 8911 to work, please update `.gitpod.yml` as follows:

```diff
ports:
  - port: 8911
    onOpen: ignore
+   visibility: public
```

In June, port visibility change to private by default ([changelog entry](https://www.gitpod.io/changelog/introducing-the-gitpod-local-companion-app#fixes-and-improvements)). Since the GraphQL Playground sends unauthenticated requests to the server, we have to open up that port.

Keep me posted on how this goes.

**Comment by thedavidprice** [comment]
Thanks for the help here @mikenikles!

> Hey Daniel, I get it to work when I also change [::1] to localhost as mentioned in #3430 (comment).

We'll try to address this once we pick up work on #2822 (a priority for next release cycle)

---

Updating the .gitpod.yml with `visibility: public` now.

**Comment by mikenikles** [comment]
Even when you try with localhost vs ::1?

I'm going to open an issue on the Gitpod side to see if something changed with IPv6 support.

**Comment by thedavidprice** [comment]
@mikenikles I can confirm this works:
```
// webpack.development.js
...
    proxy: {
      [redwoodConfig.web.apiProxyPath]: {
        target: `http://localhost:${redwoodConfig.api.port}`,
...
```

I just can't pull the trigger on that as it will have other downstream effects. (But will continue the discussion.)

I thought I could find a Gitpod-specific workaround using this but no go so far.

---

Mostly I'm confused by this behavior:
- I follow the terminal output link for `http://[::1]:8911/`...
- which takes me to a working 8911 here: https://8911-rose-mammal-0jhkft4m.ws-us18.gitpod.io/
- (add the `/graphql` to see [the playground working here](https://8911-rose-mammal-0jhkft4m.ws-us18.gitpod.io/graphql))

So the error `Error occurred while proxying request localhost:8910/graphql to http://[::1]:8911/ [EADDRNOTAVAIL]` isn't correct 'cause `http://[::1]:8911/` _is_ available... 🤷‍♂️

**Comment by mikenikles** [comment]
Yep I'm with you, it's a misleading error message. I understand the implications of the localhost change and will dig a bit deeper to see what may cause the issue.

**Review by thedavidprice — APPROVED** [review]
EnvVarRescue9000™

**Pull request merged**
