### PR TITLE
add cli support for gerating Magic.Link authentication provider

### LINKED ISSUE #623: Generators: Add auth generator for Magic.Link
Now that support for Magic.Link has been added to @redwoodjs/auth as of [0.8.0](https://github.com/redwoodjs/redwood/releases/tag/v0.8.0) we can add a generator that helps setup and configure this automatically.

Take a look at the [existing providers](https://github.com/redwoodjs/redwood/tree/master/packages/cli/src/commands/generate/auth/providers) and the README to see how to add Magic.Link support. If you need additional hooks to insert generated code into you will need to modify the [auth generator](https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/generate/auth/auth.js) itself.

### PR DESCRIPTION
**Pull request by gizmoGremlin**
Closes #623

Generators: Add auth generator for Magic.Link

### CODE REVIEW

**Comment by gizmoGremlin** [comment]
I'm noticing a typo in the commit message. Should I amend and force push or leave it?

**Comment by thedavidprice** [comment]
@gizmoGremlin excited to see this one get started! re: commit message typo --> all good to leave as is.

Please let @cannikin know when this is ready for review. Thanks again!

**Comment by gizmoGremlin** [comment]
@cannikin This is ready for review.

**Comment by cannikin** [comment]
Seems simple enough! Have you used the generator and got the login actually working properly?

**Comment by gizmoGremlin** [comment]
@cannikin  Yes, I was able to create a magic.link signup in test mode using the magic.auth.loginWithMagicLink({ email }) method.

**Comment by cannikin** [comment]
LET'S DO IT

**Pull request merged**
