### PR TITLE
update flightcontrol deploy config

### PR DESCRIPTION
**Pull request by flybayer**
We have a new nixpacks build option that automatically detects package manager versions, node versions, etc. So install command is no longer needed and no longer need to manually install yarn stable version.

### CODE REVIEW

**Comment by noire-munich** [comment]
Thanks for the update @flybayer 👍🏻 should be merged in no time.

**Review by noire-munich — APPROVED** [review]

**Comment by noire-munich** [comment]
@jtoar just wanted to double check on this one, I added the `fixture-ok` label, is this indeed the correct move for our case?
I'm rolling back on my approval because of this only.

**Comment by Tobbe** [comment]
@noire-munich Yes, fixture-ok is the right choice. Our test project doesn't use this file and isn't affected by this change in any way.

**Comment by noire-munich** [comment]
Thanks @Tobbe ! This confirms how I thought about it, it's good to know 👍

**Review by noire-munich — APPROVED** [review]

**Comment by jtoar** [comment]
Thanks @noire-munich! Yeah let's get this merged so we can hand it off to the deploy target CI repo.

**Pull request merged**
