### PR TITLE
Add Graphql Armor package for better security

### PR DESCRIPTION
**Pull request by talk2MeGooseman**
As part of the [ZEAL Redwood Extravaganza](https://community.redwoodjs.com/t/redwood-zeal-october-extravaganza/4130/3?u=talk2megooseman), I am submitting a PR to add graphql-armor for better redwood security.

graphql-armor comes with several plugins already included and enabled by default here is an itemized list below of what Redwood would get.

Enabled by default: [Aliases Limit](https://github.com/Escape-Technologies/graphql-armor#aliases-limit)
Enabled by default: [Cost Limit](https://github.com/Escape-Technologies/graphql-armor#cost-limit)
Enabled by default: [Depth Limit](https://github.com/Escape-Technologies/graphql-armor#depth-limit)
Enabled by default: [Directives Limit](https://github.com/Escape-Technologies/graphql-armor#directives-limit)
Enabled by default: [Field Suggestion](https://github.com/Escape-Technologies/graphql-armor#field-suggestion)
Enabled by default: [Token Limit](https://github.com/Escape-Technologies/graphql-armor#token-limit)

This PR removes cost-limit plugin since gql-armor comes with all the fixings.

Updated GQL docs to explain how to use the new configuration and what the new plugin options do for education and configuration.

### CODE REVIEW

**Comment by dthyresson** [comment]
@talk2MeGooseman We're about to finally get Yoga v3 merged in and have revisited this PR.

Am just checking with the Core Team if they want to just pass along the graphQL Armor config as you have done -- or add options to the handler.

To upgrade Armor at a later date, seems best to do as you have done -- so we don't need to update types for ned armor features moving forward.

Thoughts on the name?

`graphQLArmorConfig`
`protectConfig`
`protectionConfig`
`securityConfig`
`securitySettings`

?

**Comment by dthyresson** [comment]
> This PR removes cost-limit plugin since gql-armor comes with all the fixings.

Depth Limit. Yup! Thanks!

**Comment by dthyresson** [comment]
I think I'd like to move out the configuration of the 

```

   // Add GraphQL Armor security plugins
   const armor = new EnvelopArmor({
     maxDepth: {
       n: 8,
       ...graphQLArmorConfig?.maxDepth,
     },
     ...omitBy(graphQLArmorConfig, (_value, key) => key === 'maxDepth'),
   })
   const protection = armor.protect()
```

and import that so we can add tests to make sure security is enabled and with expected defaults -- and to test that can configure based on custom needs.

See: https://github.com/Escape-Technologies/graphql-armor/blob/main/packages/graphql-armor/test/envelop/armor.spec.ts for some ways to perhaps test the config?

**Review by dthyresson — CHANGES_REQUESTED** [review]
Have left some comments already, but this is great!

We are about to merge in Yoga v3 and then can get this in.

Some thoughts:

1. naming the config? 
2. extract out the protection config and defaults
3. add tests to confirm the config
4. add tests and test kit to confirm defaults are enforced

Happy to take over this PR and move it forward.

**Comment by talk2MeGooseman** [comment]
> Have left some comments already, but this is great!
> 
> We are about to merge in Yoga v3 and then can get this in.
> 
> Some thoughts:
> 
> 1. naming the config?
> 2. extract out the protection config and defaults
> 3. add tests to confirm the config
> 4. add tests and test kit to confirm defaults are enforced
> 
> Happy to take over this PR and move it forward.

Thanks for the feedback! The soonest I'll be able to tackle any updates is Friday, but if you like to work on it sooner, feel free to take it over since v3 is over the horizon.

**Comment by dthyresson** [comment]
Sounds good @talk2MeGooseman ... I'll let you know tomorrow.

**Comment by dthyresson** [comment]
@talk2MeGooseman FYI. If it's ok, I am going to close this PR and add a new one. I am making a `useGraphQLArmor` plugin and also added a set of tests for the plugin like:


```

describe('useGraphQLArmor', () => {
  describe('when blocking field suggestions', () => {
    it('returns the field suggestion masked', async () => {
      const handler = createGraphQLHandler({
        loggerConfig: { logger: createLogger({}), options: {} },
        sdls: {},
        directives: {},
        services: {},
        onException: () => {},
      })

      const mockedEvent = mockLambdaEvent({
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ query: '{ posts { id, toootle } }' }),
        httpMethod: 'POST',
      })

      const response = await handler(mockedEvent, {} as Context)
      const { data, errors } = JSON.parse(response.body)

      expect(response.statusCode).toBe(200)
      expect(data).toBeUndefined()
      expect(errors[0].message).toEqual(
        'Cannot query field "toootle" on type "Post". [Suggestion hidden]?'
      )
    })
  })
})
```

Thanks for the work on this! Helped me get my bearings.

**Comment by dthyresson** [comment]
Closing in favor of https://github.com/redwoodjs/redwood/pull/7291

**Pull request closed without merging**
