### PR TITLE
Exploration on adding Mutation support to Cells

### PR DESCRIPTION
**Pull request by ajoslin103**
This is a work in progress -- I am very welcome of architecture-related comments 

To be clear, I've no yet even got the contribution environment up and running, nor can I run tests yet.

This is a work in progress -- Redwood Rules !!

### CODE REVIEW

**Comment by jtoar** [comment]
@ajoslin103 love the enthusiasm! And I like the idea—a mutation does behave a lot like the query in a Cell, in that the request goes out (Loading), and it can either succeed or fail. I don't have any specific comments right now; just looking forward to seeing where this goes! 🚀

**Comment by ajoslin103** [comment]
referencing another attempt: https://community.redwoodjs.com/t/cells-with-mutation/2231/2 

much less intrusive and potentially much easier to manage...

**Comment by thedavidprice** [comment]
@jtoar are you able to help guide this one further?

**Comment by ajoslin103** [comment]
If I were not overloaded I would love to have brought this closer...

I know this is possible, I feel it in my ghost.

This has become very boilerplate now (kudos to @realStandal)
```

import { useCallback, useEffect, useState } from 'react'
import { useMutation } from '@redwoodjs/web'

import { filterInputs } from 'src/lib/utils'
const allowedFields = [
  'name',
  'description',
  'start',
  'stop',
]

export const MUTATION = gql`
  mutation createEvent($input: CreateEventInput) {
    createEvent(input: $input) {
      id
      plannerId
      name
      description
      start
      stop
      created_at
      updated_at
    }
  }
`

export const beforeQuery = (props) => {
  const variables = { ...props }
  return { variables, fetchPolicy: 'no-cache' }
}

export const Loading = () => null;

export const Empty = () => null;

export const Failure = ({ error }) => <div style={{ color: 'red' }}>Error: {error?.message}</div>

export const Success = ({ createEvent }) => null

const CreateEventCell = ({ props }) => {

  const [stage, setStage] = useState('loading')

  const [error, setError] = useState()
  const [result, setResult] = useState()

  const _onComplete = useCallback(
    (data) => {
      const { exfiltrate } = props
      if (exfiltrate) { exfiltrate(data) }
      // console.debug('_onComplete', JSON.stringify(data, null, 2))
      // onComplete(data)
      setResult(data)
      setStage('success')
    },
    [setResult, setStage]
    // [onComplete, setResult, setStage]
  )

  const _onError = useCallback(
    (err) => {
      console.error('_onError', JSON.stringify(err, null, 2))
      // onError(err)
      setError(err)
      setStage('failure')
    },
    [setError, setStage]
    // [onError, setError, setStage]
  )

  const [mutate, { called }] = useMutation(MUTATION, {
    onCompleted: _onComplete,
    onError: _onError,
  })

  useEffect(() => {
    if (!called) {
      mutate({ variables: { input: filterInputs(props, allowedFields) } })
    }
  }, [called, mutate])

  console.log(`stage: ${stage}`, error, result)

  return (
    <>
      {stage === 'loading' && <Loading />}
      {stage === 'failure' && <Failure {...error} />}
      {stage === 'success' && <Success {...result} />}
    </>
  )
}

export default CreateEventCell
```

This ensures a mutation doesn't throw on unintended fields:
```
// input: {}, keys: []
export const filterInputs = (input: Object, allowed: String[]) => {
    return Object.keys(input).reduce((r,e) => {
        if (allowed.includes(e)) {
            r[e] = input[e];
        }
        return r;
    },{});
}
```

This also"works" as it does modify the database, but I hate cloaking the mutation:
```
 const beforeQuery = (props) => {
  const variables = { ...props }
  return { variables, fetchPolicy: 'no-cache' }
}

export const QUERY = gql`
  query ensureAttendee($eventId: String!, $input: CreateAttendeeInput) {
    ensureAttendee(eventId: $eventId, input: $input) {
      id
      event {
        id
        name
      }
      name
      description
      phone
      email
      hasGuests
    }
  }
`

export const Loading = () => null

export const Empty = () => null

export const Failure = ({ error }) => (
  <div style={{ color: 'red' }}>Error: {error?.message}</div>
)

export const Success = ({ ensureAttendee, variables }) => {
  console.log(`Success ~ ensureAttendee`, ensureAttendee)
    if (variables.exfiltrate) { // set timeout keeps react from complaining about updating state from a different object
      setTimeout(() => variables.exfiltrate(ensureAttendee))
    }
  return null
}
```

**Comment by ajoslin103** [comment]
you guys rock !!

most recently

    I see that PR #3401 (https://github.com/redwoodjs/redwood/pull/3041) is heading our way !

exciting!!

(I love the currentSprint and next-release-priority tags I'm seeing !!)

**Comment by ajoslin103** [comment]
You guys rock !!

**Comment by olance** [comment]
Hey @ajoslin103, I've been wanting the same thing today: having Cells support mutation request.

Would you mind letting me know what's the PR status? 🙂

**Comment by ajoslin103** [comment]
I've been working on other things but now that RW is 1 I was thinking on trying out the same thing that is in the sample todo app

https://github.com/redwoodjs/example-todo/blob/f29069c9dc89fa3734c6f99816442e14dc73dbf7/web/src/components/TodoListCell/TodoListCell.js#L26-L44

Basically, I see no reason why, if this works, that we change the cell generator to just generate cells with both mutation and query -- then people could remove the one they didn't want?

Anyway, I'm fighting to a get a 1.0 of my own out the door - then maybe more on this

**Comment by ajoslin103** [comment]
I am closing this PR in favor of the next one

https://github.com/redwoodjs/redwood/pull/4594

**Pull request closed without merging**
