### PR TITLE
Upgrade Clerk Auth to v2

### LINKED ISSUE #3622: Upgrade Clerk Auth to v2
cc @zackdotcomputer 

Clerk has released a new v2 which is incompatible with v1:
- https://docs.clerk.dev/main-concepts/auth-v2
- https://github.com/clerkinc/clerk-sdk-node/releases/tag/v2.0.0

Because this is a breaking change, ideally it should be upgraded either before v1-rc or after v1 (included in v2). However, the core team maintainers most likely will not be able to prioritize this. So community contributions are needed!

### PR DESCRIPTION
**Pull request by aggmoulik**
Fixes #3622
Signed-off-by: Moulik Aggarwal <qwertymoulik@gmail.com>

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks for getting this going @aggmoulik Looping in @igneel64 and @SokratisVidros

I'm naive about Clerk, but based on the research I did in the original Issue #3622 I'm (pleasantly) surprised to see the only required change is dependency updates. I just want to double check, however. Here's the code that will be used when the `rw setup auth clerk` command is run (config added to App.js|ts and dependencies to install):
- https://github.com/redwoodjs/redwood/blob/8d5d31d1018f1604250d826c66f0278d1a15aba3/packages/cli/src/commands/setup/auth/providers/clerk.js
And here's the template that will be used for `api/src/lib/auth.js|ts`:
- https://github.com/redwoodjs/redwood/blob/6d82028163ef9650d2040ab241431fc8224fa8c9/packages/cli/src/commands/setup/auth/templates/auth.ts.template

Looking at those files, can you all confirm no other changes/updates are needed in this PR?

---

@zackdotcomputer once it's confirmed this PR is ready, would you be able to test it locally in your project?

**Comment by thedavidprice** [comment]
@aggmoulik the CI check is failing on yarn dependency duplication check:
```
Run yarn dedupe --check
4
➤ YN0000: ┌ Deduplication step
5
Deduplication step
12
➤ YN0000: └ Completed
13
Error: The operation was canceled.
```

You can resolve by running `yarn dedupe`. 

The CI also now runs `yarn constraints`, which you can check locally as well. 

Thanks again!

**Comment by thedavidprice** [comment]
Hi @aggmoulik, @igneel64, and @SokratisVidros Just checking back on this one re: my previous comments. Thanks!

**Comment by SokratisVidros** [comment]
Hey @thedavidprice. A version bump should be enough.

Apologies for the delayed reply.

**Comment by thedavidprice** [comment]
Thanks @SokratisVidros Appreciate the confirmation!

@zackdotcomputer is there any chance you could validate by bumping the versions in your app and confirming that nothing breaks?

**Comment by thedavidprice** [comment]
Hi all. Thank you again for your help with this. I had a chance to test things locally and run through some upgrade tests. I must say, Clerk has a wonderful DX and is a peace of 🍰 to get up and running. Well done 🚀

Merging now.

**Pull request merged**
