### PR TITLE
upgrade eslint v7.25.0 and other eslint packages

### PR DESCRIPTION
**Pull request by thedavidprice**
Trying to get ahead of dependabot:
- Bump eslint from 7.22.0 to ~7.24.0~ 7.25.0 #2333 #2396
- Bump eslint-plugin-prettier from 3.3.1 to 3.4.0 #2311
- Bump eslint-plugin-react from 7.22.0 to 7.23.2 #2312
- Bump eslint-config-prettier from 6.15.0 to 8.3.0 #2356
- bump eslint-import-resolver-babel-module from 5.2.0 to 5.3.1 #2371
- Build(deps): Bump eslint-plugin-jest-dom from 3.7.0 to 3.8.1 #2410

### CODE REVIEW

**Comment by thedavidprice** [comment]
@dac09 trying different methods with the dependabot PRStorm™

This is all ESlint related --> builds and passes CI — can you think of anything else to do before merging?

**Comment by dac09** [comment]
Also needs manual verification I think @thedavidprice

**Comment by thedavidprice** [comment]
> Run `lint` on the E2E generated project.
Ah, interesting 👍

**Comment by thedavidprice** [comment]
local test ✅

**Pull request merged**
