### PR TITLE
Run Teardown after each test

### PR DESCRIPTION
**Pull request by jvanbaarsen**
We currently run Teardown at the end of a scenario, but whenever we fail
to load in a scenario the tests are erroring and we don't perform the
cleanup

Fixes: #1815

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
I need to test this against a PR package since the local RWT flow is broken at the moment.

**Comment by dac09** [comment]
I don't have full context of this, but wouldn't it make more sense to use `afterAll` ? I imagine that you would setup a fixture for each describe block

**Comment by jvanbaarsen** [comment]
@dac09 You want to reload the scenario's on a per test basis. Otherwise they start to interfere with each other.

**Comment by thedavidprice** [comment]
Thanks for this @jvanbaarsen This looks good to me and I'd like to get it into the v0.26.0 release. Will loop in @cannikin for the final ok.

> but whenever we fail
to load in a scenario the tests are erroring and we don't perform the cleanup

^^ Do either of you have any suggestions about how to test for this. And/or could you confirm you've tested this locally and it's working as intended?

**Comment by cannikin** [comment]
Yeah if you can confirm this is working as planned it looks good to me @jvanbaarsen Were you ever able to test it against a PR release?

Does this take care of the case where a scenario seed fails? We've got an open issue #1804 to address that, but this change might fix it. One way to test is to add another model to the scenario that doesn't exist:

```javascript
const standard = defineScenario({
  post: {
    one: {
      title: 'First post'
    }
  },
  foo: 'bar'
})
```

That should throw an error like `can't call method create on undefined` or something similar. But `afterEach()` should be anticipating errors and still executing, I hope?

/cc @agiannelli this PR might have coincidentally fixed your issue as well!

**Comment by jvanbaarsen** [comment]
@thedavidprice / @cannikin Please hold back a bit with merging this. I haven't been able to properly test this just yet (Should have put this back in Draft)

**Comment by jvanbaarsen** [comment]
Ready for review!

You can test this by running the following steps:
* Create a new project, and create a service using `rw g service UserExample` (We are using the default table in schema.prisma for this)
* Run `rw test api`, all should be green
* Update the UserExample scenario to this:
  ```
export const standard = defineScenario({
  userExample: {
    one: { email: 'String7883988' },
    two: { email: 'String1051631' },
  },
  foo: 'bar',
})
  ```
* Run tests again, you should get an error
* Run it again and you should still see the same error (If you don't get a Unique Constraint error this fix works)

**Comment by cannikin** [comment]
Sweet! So this should close both #1815 AND #1805, correct? Whether your own code fails, or the seeding of the scenario fails, the database is cleared out looks like.

**Comment by jvanbaarsen** [comment]
Yep! Sorry @agiannelli I wasn’t aware that these issues were overlapping :(

**Comment by cannikin** [comment]
Also closes https://github.com/redwoodjs/redwood/issues/1701

**Comment by agiannelli** [comment]
@jvanbaarsen no need to apologize! I'm still working on getting my local up and running anyway 🙈

**Comment by jvanbaarsen** [comment]
@agiannelli Let me know if you need any help with that 👍

**Comment by thedavidprice** [comment]
Hi All! I'm looking into this now as a potential patch release. brb!!

**Comment by cannikin** [comment]
patch it!

**Comment by cannikin** [comment]
In this GIF metaphor the water is the extra records left around in the database.

**Comment by cannikin** [comment]
This closes #1804 not #1805!

**Pull request merged**
