### PR TITLE
Fixes issue where `rw exec` exits early when running scripts that spawn other processes

### LINKED ISSUE #2843: `rw exec` exits early when running scripts that spawn other processes
I am planning some docs for the cli script, and I was just trying the task worker example with Faktory

I used this specific example when I was developing the CLI script and had this in my redwood app. This used to work in the initial contribution, but something might have changed to make this type of script not work as expected.

```
import { db } from '../api/src/lib/db'
import { logger } from '../api/src/lib/logger'
const faktory = require('faktory-worker')
faktory.register('ResizeImage', async ({ id, size }) => {
  console.log('run ResizeImage')
})
export default async ({ args }) => {
  faktory.work()
}
```

node.js version:
14
npm/yarn version:
1.22.5
faktory-server version:
Faktory 1.5.1
facktory-worker package version:
4.1.4

Per the docs `faktory.work()` "Starts a worker. Doesn't resolve until the worker is shut down. Only call this once per-process."

**Current behavior**
Exits the script straight away and the worker is not run.

### PR DESCRIPTION
**Pull request by viperfx**
Removes process.exit() as regular scripts and promises resolve as expected. But this fixes the issue where long-running scripts that have an event loop like Faktory worker can keep the script running and prevent premature exit.

Closes #2843

### CODE REVIEW

**Review by dac09 — APPROVED** [review]

**Comment by dac09** [comment]
@viperfx I'm afraid this _did_ break it for all other cases. `rw exec` now doesn't exit.

**Comment by viperfx** [comment]
Shoot! Okay I will test more examples and see what could be causing this.

**Comment by dac09** [comment]
Found it @viperfx - we spent an hour or so trying to debug this mystery - it happens when you use prisma - just have to call db.disconnect at the end :) 

I'll create a PR for it later. Thanks for offering to look into it though!

**Comment by viperfx** [comment]
Ah! So what is the best solution? Because we don't auto-import prisma for every CLI script. The user can decide to import it and do db calls. So do we always do a disconnect after .run()? or do we add a note in the generation script to remind them to disconnect.

**Comment by dac09** [comment]
Simple fix here https://github.com/redwoodjs/redwood/pull/2894 👍

**Comment by viperfx** [comment]
Sweet! Looking forward to getting this. 

Can this go in next release?

**Pull request merged**
