### PR TITLE
Fix aws_serverless config when api folder missing

### LINKED ISSUE #1550: Generators don't work if the api folder is missing
I'm trying to start a new Redwood project that won't need the API side. Following the cookbook, I've deleted the `/api` folder and re-run `yarn install`. Now when running any generator command I get:

`Error: ENOENT: no such file or directory, scandir '{projectdir}/api/src/functions'`

Running Redwood without the api side has worked in the past.

For now I can work around it by just not using the generators, and instead manually creating pages/components/etc.

### PR DESCRIPTION
**Pull request by bennettrogers**
Fixes #1550

Note: The ternary in the template string isn't necessarily the cleanest looking solution, but it seems to be the simplest.

### CODE REVIEW

**Comment by Tobbe** [comment]
Thanks for taking the time to submit this PR. Have you tried it, so it still works to deploy to AWS?

**Comment by bennettrogers** [comment]
I did try to run the Redwood AWS deploy generator, but that fails due to the api workspace being missing in the first place.

I did not try manually writing an AWS deploy config and triggering that, nor did I try generating an AWS deploy config before deleting the api workspace and then triggering the deploy. It seems like neither of those would work or make sense without the existence of an api side.

**Comment by Tobbe** [comment]
I didn't realize we only supported deploying the api side to AWS. I thought we deployed the web side to an s3 bucket as well... If it's just the API side, then, yeah, not much to test if there is no api side 😀

**Comment by Tobbe** [comment]
I generated aws deploy config (**with** the api stuff in place) and renamed the file to `serverless.yml_`. Then I installed the PR packages for this PR (need to be on latest canary release for that to work) and ran the generator again.

image

Want to tweak that, and then I think this is ready to merge!

**Comment by bennettrogers** [comment]
I did notice that it was indenting that line, but forgot that it would be a problem since the result is a YAML file...

What's the best way to fix this? If I just try to move the `functions:` bit to its own line, the configured Prettier setup just puts it right back where it is. I guess `// prettier-ignore` would work? Is there a better way?

**Comment by Tobbe** [comment]
> What's the best way to fix this? If I just try to move the `functions:` bit to its own line, the configured Prettier setup just puts it right back where it is. I guess `// prettier-ignore` would work? Is there a better way?

This seems to work for me

```
package:
  individually: true

${
  fs.existsSync(path.resolve(getPaths().api.functions))
    ? `functions:
  ${fs
    .readdirSync(path.resolve(getPaths().api.functions))
    .map((file) => {
```

**Comment by Tobbe** [comment]
Thanks for the fix Bennett!

**Pull request merged**
