### PR TITLE
Move whatwg-fetch from devDep to dep

### LINKED ISSUE #1581: whatwg-fetch and breaking boilerplate tests through yarn rw tests
Hey everyone, I see this has come up a few times before, notably in #1264 

I am still getting these errors even after running `yarn rw upgrade` about five minutes ago. 

`yarn rw test` is failing with this error: 

```
  ● Test suite failed to run

    Cannot find module 'whatwg-fetch' from '../node_modules/@redwoodjs/core/dist/configs/browser/jest.setup.js'

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/@redwoodjs/core/dist/configs/browser/jest.setup.js:5:1)
```

Looks like I'm running v0.21.0. All of my web tests are failing, including the boilerplate ones from running the page generator like: `yarn rw g page home`. API tests are all fine. 

Are there additional steps I need to take in upgrading, beyond `yarn rw upgrade`? Or is something still broken here? Thank you!

### PR DESCRIPTION
**Pull request by Tobbe**
Fixes #1581

### CODE REVIEW

**Comment by Tobbe** [comment]
**Demonstrating that it doesn't work without this PR**

```terminal
tobbe@XPS9550 MINGW64 ~/dev/redwood
$ yarn create redwood-app whatwgfetch
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[...]
Done in 58.87s.

tobbe@XPS9550 MINGW64 ~/dev/redwood
$ cd whatwgfetch/

tobbe@XPS9550 MINGW64 ~/dev/redwood/whatwgfetch
$ yarn rw g page test
yarn run v1.22.4
$ C:\Users\tobbe\dev\redwood\whatwgfetch\node_modules\.bin\rw g page test
  √ Generating page files...
    √ Successfully wrote file `./web\src\pages\TestPage\TestPage.stories.js`
    √ Successfully wrote file `./web\src\pages\TestPage\TestPage.test.js`
    √ Successfully wrote file `./web\src\pages\TestPage\TestPage.js`
  √ Updating routes file...
Done in 4.37s.

tobbe@XPS9550 MINGW64 ~/dev/redwood/whatwgfetch
$ yarn why whatwg-fetch
yarn why v1.22.4
[1/4] Why do we have the module "whatwg-fetch"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 1.48s.

tobbe@XPS9550 MINGW64 ~/dev/redwood/whatwgfetch
$ yarn rw test
[...]
$ C:\Users\tobbe\dev\redwood\whatwgfetch\node_modules\.bin\jest --passWithNoTests --watchAll --runInBand --config C:\Users\tobbe\dev\redwood\whatwgfetch\node_modules\@redwoodjs\core\config\jest.config.js --projects web api
 FAIL   web  web/src/pages/TestPage/TestPage.test.js
  ● Test suite failed to run

    Cannot find module 'whatwg-fetch' from '../node_modules/@redwoodjs/core/dist/configs/browser/jest.setup.js'

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/@redwoodjs/core/dist/configs/browser/jest.setup.js:5:1)
```

**Demonstrating that we get further with this PR**

```
tobbe@XPS9550 MINGW64 ~/dev/redwood/whatwgfetch
$ yarn rw upgrade --pr 1625:0.22.1-3520c0b
yarn run v1.22.4
$ C:\Users\tobbe\dev\redwood\whatwgfetch\node_modules\.bin\rw upgrade --pr 1625:0.22.1-3520c0b
[...]
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ @redwoodjs/cli@0.22.1
info All dependencies
├─ @redwoodjs/cli@0.22.1
└─ whatwg-fetch@3.5.0
[...]
Done in 60.00s.

tobbe@XPS9550 MINGW64 ~/dev/redwood/whatwgfetch
$ yarn rw test
[...]
$ C:\Users\tobbe\dev\redwood\whatwgfetch\node_modules\.bin\jest --passWithNoTests --watchAll --runInBand --config C:\Users\tobbe\dev\redwood\whatwgfetch\node_modules\@redwoodjs\core\config\jest.config.js --projects web api
 FAIL   web  web/src/pages/TestPage/TestPage.test.js
  ● Test suite failed to run

    Cannot find module '@redwoodjs/router/dist/index' from '../node_modules/@redwoodjs/testing/dist/MockRouter.js'

    Require stack:
      C:/Users/tobbe/dev/redwood/whatwgfetch/node_modules/@redwoodjs/testing/dist/MockRouter.js
      src/Routes.js
      C:/Users/tobbe/dev/redwood/whatwgfetch/node_modules/@redwoodjs/testing/dist/MockProviders.js
      C:/Users/tobbe/dev/redwood/whatwgfetch/node_modules/@redwoodjs/testing/dist/customRender.js
      C:/Users/tobbe/dev/redwood/whatwgfetch/node_modules/@redwoodjs/testing/dist/index.js
      C:/Users/tobbe/dev/redwood/whatwgfetch/node_modules/@redwoodjs/core/dist/configs/browser/jest.setup.js

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/MockRouter.js:31:14)
```

So with this PR it doesn't complain about whatwg-fetch missing anymore. But now it breaks on MockRouter instead. I don't think that's related to this PR though.

**Review by peterp — APPROVED** [review]

**Comment by thedavidprice** [comment]
The package is also included in [`redwood/package.json`](https://github.com/Tobbe/redwood/blob/3520c0bec725c39f4e0c1de87fac7c810a4b5eb3/package.json#L49). 

We don't need both, do we?

**Comment by Tobbe** [comment]
@thedavidprice I noticed that too. I did dig in to it a little bit. It was added to that file by @peterp in this commit
```
commit da6ebb41bb02d5eaf43495726fcea0ce46397e34
Author: Peter Pistorius <peter.pistorius@gmail.com>
Date:   Sun Jun 14 14:31:26 2020 +0200

    Move testing things to global package.
```

```diff
diff --git a/package.json b/package.json
index 5dbbb66b..22d0ec86 100644
--- a/package.json
+++ b/package.json
@@ -16,11 +16,16 @@
     "@babel/runtime-corejs3": "^7.9.2",
     "babel-plugin-auto-import": "^1.0.5",
     "babel-plugin-module-resolver": "^4.0.0",
+    "bundlesize": "^0.18.0",
     "cross-env": "^7.0.2",
     "jest": "^25.2.3",
     "lerna": "^3.20.2",
     "nodemon": "^2.0.2",
-    "typescript": "^3.8.3"
+    "typescript": "^3.8.3",
+    "@testing-library/react": "10.2.1",
+    "@testing-library/jest-dom": "5.10.0",
+    "msw": "0.19.3",
+    "whatwg-fetch": "3.0.0"
   },
   "eslintConfig": {
     "extends": "@redwoodjs/eslint-config",
@@ -43,4 +48,4 @@
     "lint": "yarn eslint packages",
     "lint:fix": "yarn eslint --fix packages"
   }
-}
+}
\ No newline at end of file
```

If whatwg-fetch should be removed, should we remove the other packages too? Or should whatwg-fetch only be in this top level package.json, but moved to `dependencies`? The top level package.json doesn't have any other deps, only devDeps. @peterp What do you think?

**Comment by thedavidprice** [comment]
Opened a new issue with the comment above here: https://github.com/redwoodjs/redwood/issues/1631

**Pull request merged**
