### PR TITLE
fix flightcontrol template and doc

### PR DESCRIPTION
**Pull request by flybayer**

### CODE REVIEW

**Review by thedavidprice — APPROVED** [review]

**Comment by thedavidprice** [comment]
Adding to next Patch release

@flybayer Would it be helpful if I include a note in the patch Release Notes that projects will need to add the port if they tried this previously?

**Comment by thedavidprice** [comment]
@flybayer Ah, I don't have permission to update this branch. Could you handle the merge conflict? I did enable auto-merge once CI passes.

**Comment by thedavidprice** [comment]
@flybayer checking back here — can you handle merge conflict as I don't have edit permissions?

**Comment by flybayer** [comment]
@thedavidprice there, sorry for delay!

**Pull request merged**
