### PR TITLE
Typing services on makeMergedSchema

### PR DESCRIPTION
**Pull request by dthyresson**
Fix https://github.com/redwoodjs/redwood/issues/3114
Fix https://github.com/redwoodjs/redwood/issues/3123

In the app's `graphql.ts` function where we `createGraphQLHandler` there is a type issue in `services`:

```js
src/functions/graphql.ts:16:5 - error TS2322: Type 'ServicesCollection' is not assignable to type 'Services'.
  Index signatures are incompatible.
    Type 'Services' is not assignable to type 'Resolver'.
      Type 'Services' provides no match for the signature '(...args: unknown[]): unknown'.

16     services: makeServices({ services }),
       ~~~~~~~~

  ../node_modules/@redwoodjs/api/dist/makeMergedSchema/makeMergedSchema.d.ts:11:5
    11     services: Services;
           ~~~~~~~~
    The expected type comes from property 'services' which is declared here on type '{ schemas: { [key: string]: { schema: Record<string, unknown>; resolvers: Record<string, unknown>; }; }; services: Services; schemaDirectives?: { [name: string]: typeof SchemaDirectiveVisitor; }; schemaOptions?: Partial<...>; }'
```

This PR corrects the type from Services to ServicesCollection.

### CODE REVIEW

**Comment by dthyresson** [comment]
In redwood, with `blog-test-project` and `yarn rw type-check api` with import {
  createGraphQLHandler,
  makeMergedSchema,
  makeServices,
} from '@redwoodjs/graphql-server':

```terminal
[12:50:39] Typechecking "api"... [completed]
✨  Done in 11.68s.
```

**Comment by dthyresson** [comment]
In redwood, with blog-test-project and yarn rw type-check api with import {
createGraphQLHandler,
makeMergedSchema,
makeServices,
} from '@redwoodjs/api':

```
[13:38:53] Typechecking "api"... [completed]
✨  Done in 14.80s.
```

**Comment by dthyresson** [comment]
To test:

* `yarn build:test-project --typescript`
* in `blog-test-project/api/src/functions/graphql.ts` check that importing from `'@redwoodjs/api'`
* `yarn rw type-check api` should pass
* then change in `blog-test-project/api/src/functions/graphql.ts` check that importing from `'@redwoodjs/graphql-server'`
* `yarn rw type-check api` should pass

**Review by dac09 — APPROVED** [review]
Nice one 🔥 DT!

**Pull request merged**
