### PR TITLE
Upgrade Jest v27

### PR DESCRIPTION
**Pull request by thedavidprice**
Jest v27 Release Notes with (very unhelpful) Breaking change notices:
- https://github.com/facebook/jest/releases/tag/v27.0.0

A majority of the breaking-change fixes I applied were:
1. Setting the Jest environment to `jsdom`
    - Doc: https://jestjs.io/docs/next/configuration#testenvironment-string
    - "Default to Node testing environment instead of browser (JSDOM)" in Jest [PR#9874](https://github.com/facebook/jest/pull/9874)
    - For `yarn rw test`, I added `testEnvironment: 'jest-environment-jsdom',` to `jest.config.js`
2. Jest test() no longer allows `done` callback _and_ a Promise
     - all errors were case where Promise was returned; I modified to keep promise and remove callback
     - Doc: https://jestjs.io/docs/next/asynchronous#callbacks
     - "Disallow mixing a done callback and returning a Promise from hooks and tests" in Jest [PR#10512](https://github.com/facebook/jest/pull/10512)

## To Do
@peterp @dac09 I could use your help finishing this one up.

> Update: Confirming Danny is correct --> `yarn rw test web` fails with same error when using `yarn rwt link`. So likely a false symptom. Still failing E2E though.

For current `yarn rw test` errors in the E2E context, see this comment below https://github.com/redwoodjs/redwood/pull/2698#issuecomment-853188195

<details>
<summary>Previous "false symptom" Error Message</summary>
Using `yarn rwt link ...`, I can successfully run `yarn rw test api` = ✅

I'm getting path errors when I run `yarn rw test web` = ⛔️

This looks like a Babel error. Either way, I'm having trouble diagnosing. All of my tests fail with this error:
```zsh
 FAIL   web  web/src/pages/BlogPostPage/BlogPostPage.test.js
     Test suite failed to run
    Jest encountered an unexpected token
    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:
    /Users/price/Repos/tdp-redwood-tutorial-test/redwood/structure/dist/model/RWCell.js:3
    import { createCell } from "@redwoodjs/web";
    ^^^^^^
    SyntaxError: Cannot use import statement outside a module
      33 | var _URL = require("../x/URL");
      34 |
    > 35 | var _RWCell = require("./RWCell");
         |               ^
      36 |
      37 | var _RWComponent = require("./RWComponent");
      38 |

      at Runtime.createScriptFromCode (../node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (../redwood/structure/dist/model/RWProject.js:35:15)
```

</details>

### CODE REVIEW

**Comment by dac09** [comment]
Hey DP, I believe this is the normal error we see when trying to run `rw test` in a `link`Ed project.

**Comment by thedavidprice** [comment]
@dac09 it fails in E2E, too, which is why I attempted via `yarn rwt link`. Going to clarify, but I'm pretty sure we have tests running just fine on rwt link.

**Comment by thedavidprice** [comment]
Confirming Danny is correct --> `yarn rw test web` fails with same error when using `yarn rwt link`. So likely a false symptom.

Local E2E:
- test API = passes
- test web = fails

CI E2E:
- test API = fails
- test web = fails

**Comment by thedavidprice** [comment]
## Errors from E2E context
### rw test api
```bash
FAIL   api  api/src/services/posts/posts.test.js
  posts
    ✕ returns all posts (81 ms)
    ✕ returns a single post (28 ms)
    ✕ creates a post (24 ms)
    ✕ updates a post (25 ms)
    ✕ deletes a post (30 ms)

  ● posts › returns all posts

    TypeError: Cannot read property 'testPath' of undefined

      at Object.<anonymous> (../node_modules/.RedwoodJSFrameworkPackages/packages/core/dist/configs/node/jest.setup.js:82:51)

  ● posts › returns a single post

    TypeError: Cannot read property 'testPath' of undefined

      at Object.<anonymous> (../node_modules/.RedwoodJSFrameworkPackages/packages/core/dist/configs/node/jest.setup.js:82:51)

  ● posts › creates a post

    TypeError: Cannot read property 'testPath' of undefined

      at Object.<anonymous> (../node_modules/.RedwoodJSFrameworkPackages/packages/core/dist/configs/node/jest.setup.js:82:51)

  ● posts › updates a post

    TypeError: Cannot read property 'testPath' of undefined

      at Object.<anonymous> (../node_modules/.RedwoodJSFrameworkPackages/packages/core/dist/configs/node/jest.setup.js:82:51)

  ● posts › deletes a post

    TypeError: Cannot read property 'testPath' of undefined

      at Object.<anonymous> (../node_modules/.RedwoodJSFrameworkPackages/packages/core/dist/configs/node/jest.setup.js:82:51)
```

### rw test web
Blast, I thought this was fixed with the Jest Environment change to jest.config.js.
```bash
 FAIL   web  web/src/pages/HomePage/HomePage.test.js
  ● HomePage › renders successfully

    expect(received).not.toThrow()

    Error name:    "ReferenceError"
    Error message: "document is not defined"

           6 |   it('renders successfully', () => {
           7 |     expect(() => {
        >  8 |       render(<HomePage />)
             |       ^
           9 |     }).not.toThrow()
          10 |   })
          11 | })

          at render (node_modules/@testing-library/react/dist/pure.js:83:5)
          at customRender (node_modules/.RedwoodJSFrameworkPackages/packages/testing/dist/customRender.js:20:29)
          at web/src/pages/HomePage/HomePage.test.js:8:7
          at Object.<anonymous> (node_modules/expect/build/toThrowMatchers.js:83:11)
          at Object.toThrow (node_modules/expect/build/index.js:339:21)
          at Object.<anonymous> (web/src/pages/HomePage/HomePage.test.js:9:12)

       7 |     expect(() => {
       8 |       render(<HomePage />)
    >  9 |     }).not.toThrow()
         |            ^
      10 |   })
      11 | })
      12 |

      at Object.<anonymous> (src/pages/HomePage/HomePage.test.js:9:12)

 FAIL   web  web/src/pages/ContactPage/ContactPage.test.js
  ● ContactPage › renders successfully

    expect(received).not.toThrow()

    Error name:    "ReferenceError"
    Error message: "document is not defined"

           6 |   it('renders successfully', () => {
           7 |     expect(() => {
        >  8 |       render(<ContactPage />)
             |       ^
           9 |     }).not.toThrow()
          10 |   })
          11 | })

          at render (node_modules/@testing-library/react/dist/pure.js:83:5)
          at customRender (node_modules/.RedwoodJSFrameworkPackages/packages/testing/dist/customRender.js:20:29)
          at web/src/pages/ContactPage/ContactPage.test.js:8:7
          at Object.<anonymous> (node_modules/expect/build/toThrowMatchers.js:83:11)
          at Object.toThrow (node_modules/expect/build/index.js:339:21)
          at Object.<anonymous> (web/src/pages/ContactPage/ContactPage.test.js:9:12)

       7 |     expect(() => {
       8 |       render(<ContactPage />)
    >  9 |     }).not.toThrow()
         |            ^
      10 |   })
      11 | })
      12 |

      at Object.<anonymous> (src/pages/ContactPage/ContactPage.test.js:9:12)
...
```

**Comment by peterp** [comment]
Just a heads up that the e2e tests do not use the same mechanism as link, the redwood packages are copied into node_modules, so they should not suffer the same fate as link (although link is now fixed.)

**Comment by thedavidprice** [comment]
work is continued here #2893

Keeping opening in the near-term as reference

**Review by peterp — COMMENTED** [review]
Maybe we can try this again with `rwfw` when it's released?

**Comment by thedavidprice** [comment]
@peterp For sure! I was holding off for that reason. Also, see updated work in this PR along with topics for next-step discussion+decisions #2893

**Pull request closed without merging**
