### PR TITLE
Add CLI command "yarn rw db fix" to handle potential Prisma 'migrate.lock' file conflicts

### LINKED ISSUE #304: Create Redwood equivalent of `prisma2 migrate fix` command
After running migrations prisma creates a `migrate.lock` file which tracks which migrations have been run against the database. In some circumstances there could be a conflict in that file (multiple devs creating migrations). Prisma provides a command `prisma2 migrate fix` to fix it. We should create our own version of that, maybe something like:

* `yarn rw db fix`
* `yarn rw db migrate-fix`
* `yarn rw db up:fix`

### PR DESCRIPTION
**Pull request by Thieffen**
An attempt to fix #304 

To my best knowledge, Prisma2 **does not support yet** this particular command.

A reference to <code>prisma2 migrate fix</code> is effectively displayed in the terminal :
https://github.com/prisma/migrate/blob/1e25f34db22725589d9978441f6ca4147e17b009/src/Lift.ts#L253

I've been unable to find it the codebase.
Also current Prisma2 command list does not mention anything about it : 
https://github.com/prisma/migrate/blob/1e25f34db22725589d9978441f6ca4147e17b009/src/cli/commands/LiftCommand.ts#L30

Maybe I missed something, let me know.

### CODE REVIEW

**Comment by peterp** [comment]
Thanks for this, I'll ping them prisma team to figure out the current status of that command

**Comment by peterp** [comment]
It doesn't look like this command is available in prisma preview 24: 

```bash
yarn prisma2 migrate fix --experimental
yarn run v1.22.4
$ /Users/peterp/Personal/redwoodjs/create-redwood-app/node_modules/.bin/prisma2 migrate fix --experimental

! Unknown command "fix"
```

**Comment by Thieffen** [comment]
open issue here:
https://github.com/prisma/migrate/issues/51

**Comment by thedavidprice** [comment]
Our CI Checks were not running for PRs from external, forked repos. See #358 

This is now fixed but will not retroactively apply to this PR. Before merging, please locally confirm the following checks pass:
- [ ] `yarn build`
- [ ] `yarn lint`
- [ ] `yarn test`

Thanks in advance!

**Comment by Thieffen** [comment]
- [X] build
- [X] lint
- [X] test

@thedavidprice PR should be ready now :)

**Comment by Thieffen** [comment]
Updated yarn command from `prisma2` to `prisma` ( see #386 )

**Comment by cannikin** [comment]
> Updated yarn command from `prisma2` to `prisma` ( see #386 )

Yep, let's be sure we merge that first before merging this one!

**Comment by Thieffen** [comment]
Prisma original issue has just been closed :
https://github.com/prisma/migrate/issues/51

And the mention about this command has been removed from the codebase :
https://github.com/prisma/migrate/commit/ccb9f7bcd397bdbd714f17f38cad3d88c83cff22

I suppose this PR is not relevant anymore.

Let's close it?

**Comment by peterp** [comment]
@Thieffen Yeah, sorry about the hassle, and thanks for the PR!

**Pull request closed without merging**
