### PR TITLE
Webpack: Use resolve-url-loader to handle absolute paths in css url()

### PR DESCRIPTION
**Pull request by Tobbe**
Using [resolve-url-loader](https://github.com/bholloway/resolve-url-loader) to set `root` for absolute imports. This makes it possible to use the same absolute-path style imports in css for both webpack and Vite RW projects.
So CSS like this should work for both Webpack and Vite now 

```css
@layer base {
  @font-face {
    font-family: 'My font';
    src: url('/fonts/abeezee-v22-latin-regular.woff2') format('woff2');
    font-weight: 300;
    ascent-override: 97%;
  }

  * {
    font-family: 'My font';
  }
}
```

Notice `url('/fonts/...')`. The initial `/` is what's important.

### CODE REVIEW

**Review by jtoar — APPROVED** [review]

**Comment by chuckcarpenter** [comment]
@Tobbe @jtoar in a new RW project (v6.6.2) I'm getting the error when running storybook of 
`Error: resolve-url-loader: error processing CSS`

I'm using the format noted in the PR description above:
```css
@font-face {
  font-family: 'Founders Grotesk';
  src: url('/fonts/FoundersGrotesk-Regular.woff2') format('woff2'),
  url('/fonts/FoundersGrotesk-Regular.woff') format('woff');
  font-weight: normal;
  font-style: normal;
}
```

Any ideas on why that could be and what I can do?

**Comment by Tobbe** [comment]
@chuckcarpenter I've passed the issue on to @ahaywood and @arimendelow, who are both more knowledgable about Storybook

**Comment by chuckcarpenter** [comment]
@Tobbe sure, happy to help. Albeit, all I've done is go through the tutorial and when styling with tailwind I added two font faces to the public directory and in the globall.css declared it as noted above. The repo is also public, if that helps. https://github.com/shepherd-pro/pro-platform

**Comment by arimendelow** [comment]
Hi @chuckcarpenter, welcome! I'm getting a 404 on that repo. Maybe a permissions issue - can you ping back here once you've fixed that?

I haven't actually ever used `@font-face`, I usually just use google fonts and stick something like this on top of my `index.css`: `@import url('https://fonts.googleapis.com/........');`

I've had no issues doing it that way. I'll look more into this once I'm able to access your repo.

**Comment by chuckcarpenter** [comment]
@ahaywood coming back to this and that worked for me, thank you!

**Pull request merged**
