### PR TITLE
Fix path for windows in cli test command

### PR DESCRIPTION
**Pull request by RobertBroersma**

### CODE REVIEW

**Comment by Tobbe** [comment]
I just tried this change locally, and I'm afraid it doesn't seem to make a difference

**Comment by Tobbe** [comment]
I added some console.log commands to see what's going on

```
  try {
    /**
     * Migrate test database. This should be moved to somehow be done on a
     * per-side basis if possible.
     */
    console.log('CACHE_DIR', CACHE_DIR)
    console.log('TEST_DATABASE_URL', process.env.TEST_DATABASE_URL)
    console.log('joined', `file:${path.join(CACHE_DIR, 'test.db')}`)
    const DATABASE_URL = process.env.TEST_DATABASE_URL || `file:${path.join(CACHE_DIR, 'test.db')}`
    console.log('DATABASE_URL', DATABASE_URL)
    await _execa.default.command(`yarn rw db up`, {
      stdio: 'inherit',
      shell: true,
      env: {
        DATABASE_URL
      }
    });
    jest.run(args);
  } catch (e) {
    console.log(_colors.default.error(e.message));
  }
```

This is the output

```
$ yarn rw test
yarn run v1.22.4
$ C:\Users\tobbe\dev\redwood\redwood-testing\node_modules\.bin\rw test
CACHE_DIR C:\Users\tobbe\dev\redwood\redwood-testing\node_modules\.redwood
TEST_DATABASE_URL undefined
joined file:C:\Users\tobbe\dev\redwood\redwood-testing\node_modules\.redwood\test.db
DATABASE_URL file:C:\Users\tobbe\dev\redwood\redwood-testing\node_modules\.redwood\test.db
$ C:\Users\tobbe\dev\redwood\redwood-testing\node_modules\.bin\rw db up
Migrate database up... [started]
$ C:\Users\tobbe\dev\redwood\redwood-testing\node_modules\.bin\prisma migrate up --experimental --create-db
Error: Command failed with exit code 255: C:\Users\tobbe\dev\redwood\redwood-testing\node_modules\@prisma\cli\migration-engine-windows.exe cli --datasource file:C:\Users\tobbe\dev\redwood\redwood-testing\node_modules\.redwood\test.db create-database
Jul 20 00:36:17.924  INFO migration_engine: Starting migration engine CLI git_hash="45c4da4dd3ccd6a322796b228bdf937c7ce884e8"
Jul 20 00:36:17.931 ERROR migration_engine::commands: Unknown error occured: Error in datamodel: Error validating: This line is not a valid definition within a datasource.
{"is_panic":false,"message":"Unknown error occured: Error in datamodel: Error validating: This line is not a valid definition within a datasource.","backtrace":null}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Migrate database up... [failed]
→ Command failed with ENOENT: yarn prisma migrate up --experimental --create-db
spawn yarn prisma ENOENT
Command failed with ENOENT: yarn prisma migrate up --experimental --create-db
spawn yarn prisma ENOENT
```

And, as we discussed earlier, if I run it like this instead, it works:

```
$ TEST_DATABASE_URL=file:./test.db yarn rw test
```

**Comment by Tobbe** [comment]
Alright, I have a fix. I'll need to clean it up first though. Will do that tomorrow and post a new PR

**Comment by RobertBroersma** [comment]
I suppose Prisma doesn't appreciate the backslashes?

**Pull request closed without merging**
