### PR TITLE
Test prerendering meta tags

### PR DESCRIPTION
**Pull request by Tobbe**
This is a follow-up to #7321

Adding tests so we don't regress

### CODE REVIEW

**Review by jtoar — APPROVED** [review]
LGTM; should @dac09 have a look?

**Comment by Tobbe** [comment]
> should @dac09 have a look?

Sure. I'll wait with the merge until tomorrow

**Review by dac09 — APPROVED** [review]
Thank you Tobbe!

**Review by dac09 — CHANGES_REQUESTED** [review]
✋ test always passes, investigating

**Review by dac09 — APPROVED** [review]

**Pull request merged**
