### PR TITLE
Remove favicons-webpack-plugin

### LINKED ISSUE #25: Can't install packages with yarn
When trying to `yarn install` on a fresh clone of `redwood` I'm getting build errors for the `sharp` package on macOS 10.15.2 (Catalina). 

If it just turns out there is some other dependency that's required we should note that in the README. The sharp docs mention the following for [MacOS installation](https://sharp.pixelplumbing.com/en/stable/install/#mac-os): 

> libvips and its dependencies are fetched and stored within `node_modules/sharp/vendor` during `npm install`. This involves an automated HTTPS download of approximately 8MB.
>
> To use your own version of libvips instead of the provided binaries, make sure it is at least the version listed under `config.libvips` in the `package.json` file and that it can be located using `pkg-config --modversion vips-cpp`.

```bash
rob$ yarn
yarn install v1.19.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-fbf8bba0-e61a-4da9-85c7-4295a3010636 > @redwoodjs/cli > ink@2.6.0" has unmet peer dependency "@types/react@>=16.8.0".
warning "workspace-aggregator-fbf8bba0-e61a-4da9-85c7-4295a3010636 > @redwoodjs/web > @apollo/react-components@3.1.3" has unmet peer dependency "react@^16.8.0".
warning "workspace-aggregator-fbf8bba0-e61a-4da9-85c7-4295a3010636 > @redwoodjs/web > @apollo/react-components@3.1.3" has unmet peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-fbf8bba0-e61a-4da9-85c7-4295a3010636 > @redwoodjs/web > @apollo/react-hooks@3.1.3" has unmet peer dependency "react@^16.8.0".
warning "workspace-aggregator-fbf8bba0-e61a-4da9-85c7-4295a3010636 > @redwoodjs/web > @apollo/react-hooks@3.1.3" has unmet peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-fbf8bba0-e61a-4da9-85c7-4295a3010636 > @redwoodjs/web > @apollo/react-components > @apollo/react-common@3.1.3" has unmet peer dependency "react@^16.8.0".
[4/4] 🔨  Building fresh packages...
[-/15] ⠄ waiting...
[-/15] ⠄ waiting...
[-/15] ⠄ waiting...
[-/15] ⠄ waiting...
error /Users/rob/Sites/redwoodjs/redwood/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/rob/Sites/redwoodjs/redwood/node_modules/sharp
Output:
info sharp Using cached /Users/rob/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=13.2.0 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.7
gyp info using node@13.2.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/rob/Sites/redwoodjs/redwood/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/Sites/redwoodjs/redwood/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/Sites/redwoodjs/redwood/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/Library/Caches/node-gyp/13.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/rob/Library/Caches/node-gyp/13.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/rob/Sites/redwoodjs/redwood/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/rob/Library/Caches/node-gyp/13.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/rob/Sites/redwoodjs/redwood/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc:130:19: error: no matching member function for call to 'Set'
        channels->Set(i, channelStat);
        ~~~~~~~~~~^~~
/Users/rob/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/rob/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
1 error generated.
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rob/Sites/redwoodjs/redwood/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.2.0/bin/node" "/Users/rob/Sites/redwoodjs/redwood/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/rob/Sites/redwoodjs/redwood/node_modules/sharp
```

### PR DESCRIPTION
**Pull request by cannikin**
Fixes the `sharp` issues I've been having by removing that dependency altogether. Sorry favicons!

We should update create-redwood-app to include the favicon explictly in `index.html` along with a favicon.png (made from our official logo!) in `public`.

Closes #25

### CODE REVIEW

**Comment by peterp** [comment]
We'll need to make the `static/` directory available as an alternative.

**Comment by peterp** [comment]
I did a bit of research and I think I've found an alternative, it is kinda nice that it generates all the variants and this is one less thing that developers have to worry about: https://github.com/brunocodutra/webapp-webpack-plugin

**Comment by sw-yx** [comment]
just curious @cannikin, what were the sharp issues you ran into?

**Comment by cannikin** [comment]
@sw-yx I've got another issue with the stack trace: https://github.com/redwoodjs/redwood/issues/25

**Pull request merged**
