### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ubugnu**

### CODE REVIEW

**Review by SwiftyProgrammer690 — COMMENTED** [review]
I don't think this a typo , I think there is supposed to be a `scenario,` instead of a `scenario:`

**Review by jtoar — APPROVED** [review]
Thanks @ubugnu!

**Comment by jtoar** [comment]
@SwiftyProgrammer690 this edit looks correct. It's to the TypeScript tab, which is supposed to use colons to delimit the type from the param name

**Comment by SwiftyProgrammer690** [comment]
> @SwiftyProgrammer690 this edit looks correct. It's to the TypeScript tab, which is supposed to use colons to delimit the type from the param name

My bad

**Comment by jtoar** [comment]
@SwiftyProgrammer690 No worries!

**Pull request merged**
