### PR TITLE
upgrade prisma preview24

### PR DESCRIPTION
**Pull request by thedavidprice**
https://github.com/prisma/prisma2/releases/tag/2.0.0-preview024

### CODE REVIEW

**Comment by thedavidprice** [comment]
Closes #279

**Comment by peterp** [comment]
LGTM!

**Comment by peterp** [comment]
@thedavidprice I'm going to merge this :)

**Comment by thedavidprice** [comment]
But, um, did you test to make sure it works first?!?

😬

**Comment by thedavidprice** [comment]
🤣🤣 🤣 🤣 🤣  

So. Many. Lulz.....

**Pull request merged**
