### PR TITLE
Ch4: Deployment - Updating Environment variable section

### PR DESCRIPTION
**Pull request by MrOnosa**
Netlify has changed how Environment Variables are set. They are no longer nested inside Build & Deploy.

### CODE REVIEW

**Review by pantheredeye — COMMENTED** [review]
Thanks for the update, @MrOnosa! I have reviewed the Env vars section, and all seems well there with [Netlify's new Env. Var section.](https://docs.netlify.com/environment-variables/overview/) I have not confirmed the change with "Site is live" to "Deployment failed". If noone gets to it prior, I will look to get that confirmed this week. Thanks again!

**Comment by MrOnosa** [comment]
Thank you for double-checking everything. Always appreciated. For context, this is what it shows for me. 
image

**Comment by cannikin** [comment]
Thanks so much for this PR!

**Comment by cannikin** [comment]
You can preview the changes here: https://deploy-preview-6970--redwoodjs-docs.netlify.app/docs/canary/tutorial/chapter4/deployment#environment-variables

**Review by cannikin — APPROVED** [review]

**Comment by cannikin** [comment]
Looks great, thanks for the fix!

**Pull request merged**
