### PR TITLE
Update deployment.md

### PR DESCRIPTION
**Pull request by Ayo-faks**
Deploying to Netlify was a bit misleading. Not inputting the database URI as an environment variable in the netlify deploy settings leads to the build process throwing errors.
I edited it to reflect adding the database URI as an environment variable so Netlify can detect and migrate our database.

### CODE REVIEW

**Comment by noire-munich** [comment]
Thanks @Ayo-faks for this PR, Netlify is the first provider we've worked with, it needs proper care indeed!

I'll have a comment though ;)

**Review by noire-munich — APPROVED** [review]

**Comment by jtoar** [comment]
Thanks @Ayo-faks! Before I suggest any changes, let me get @cannikin's thoughts on merging the "Environment variables" section into the "Signup" section. It seems ok to me but what do you think?

**Comment by Ayo-faks** [comment]
Hi,

It's also fine by me. But you seek cannikin <https://github.com/cannikin>'s
opinion

Cheers

**Comment by jtoar** [comment]
@Ayo-faks ah sorry, that was poor writing on my part. That question was meant for @cannikin but it doesn't read that way at all 😅

**Comment by Ayo-faks** [comment]
Lol. No worries

**Comment by cannikin** [comment]
Thanks for the PR! So I make a point of telling people about the build error that will occur doing that first deploy in the text there, I don't think it's too misleading?

1. Setup site, point to GitHub
2. Build errors :(
3. Now add missing environment variables
4. Build succeeds :)

It goes along with whole ethos of the tutorial, where sometimes we write some code just to see what will happen, then correct it later. I'm trying to group each thing in logical chunks: initial site setup is one mental grouping of tasks, configuring environment variables is another. And the fact that it's covered as its own topic makes it (hopefully) easy to refer back to in your mental model when it comes time to add your own ENV vars in the future.

I can see that if you only followed along in the tutorial sentence-by-sentence, it may be a surprise to get that build error. But I prefer that over giving them too many things to do at once, and effectively saying "just copy and paste everything I'm doing, don't worry about what's happening." It's like getting directions from your GPS: it's much better (to me, at least) to get feedback as I'm driving about where to make turns as they're happening, than to just see a big list of directions at the start of the trip that I then need to try and remember while driving.

What do you think?

**Comment by noire-munich** [comment]
> What do you think?

Not sure an answer would be expected from me :p though! 

I wondered why I was reading not as you intended it to be read @cannikin and the reason is easy: I have not done the tutorial in over 2 years. When looking for the info, I arrived from the Reference, which felt like missing the info I needed but redirected me to the tutorial. I'm confident I know enough about Redwood so I skip reading carefully and read sentence by sentence, defeating the purpose of the tutorial. My shame, clearly.

I would advocate for keeping the tutorial as you wrote it - full process included, and stuff up a bit more the reference to make sure we don't need to redirect to the tutorial.

**Comment by jtoar** [comment]
Closing this one due to inactivity and @cannikin's last response, but happy to reopen and reconsider.

**Pull request closed without merging**
