### PR TITLE
teardown should attempt to delete dbName table

### PR DESCRIPTION
**Pull request by nexneo**
model name can be different than dbName when `@@map("actual_table_name")` has been used in prisma schema

I'm unsure if there is any test associated with jest setup, please suggest if I need to do anything else here.
Thanks!

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks for this @nexneo! We're heads down on QA for the v0.28 release. I'm adding this to the review queue as soon as we're  post v0.28.

**Comment by thedavidprice** [comment]
@cannikin I believe this one relates to the "teardown test DB" work you've been overseeing ongoing. Could you review and advise on failing tests? Thanks!

**Comment by cannikin** [comment]
Hmm, how do you figure out what actually failed? All the messages seem to be cypress itself complaining that that there was a failure, but it doesn't bubble up and tell you what actually failed in the test suite?

image

**Comment by cannikin** [comment]
I guess it's something inside api/src/services/posts/posts.test.js? That would be the one *in* the app, that's generated as a result of a generator somewhere, correct? Does that fail for you locally @nexneo ?

**Comment by nexneo** [comment]
> I guess it's something inside api/src/services/posts/posts.test.js? That would be the one _in_ the app, that's generated as a result of a generator somewhere, correct? Does that fail for you locally @nexneo ?

Let me explain issue I was trying to solve here. In redwood blog example if you change schema.prisma Post model with `@@map("posts")` as follows - After that if you run api service tests then in tearDown tests will fail because in teardown code `m.name` is `Post` but database table is `posts` so in that case `m.dbName` should be used.

Also I figured out issue why tests were failing previously, when you do not override table name with `@@map` m.dbName is null. Now first it tries to use m.dbName and then m.name. With that change all tests are passing now

```
model Post {
  id       Int @id @default(autoincrement())
  title    String
  slug     String @unique
  author   String
  body     String
  image    String?
  tags     Tag[]
  postedAt DateTime?
  @@map("posts")
}
```

**Comment by nexneo** [comment]
@cannikin @thedavidprice Can you please update status? Thanks

**Comment by cannikin** [comment]
Looks good! I'll merge assuming all the tests pass after this rebase. Thanks!

**Pull request merged**
