### PR TITLE
Private as alias for Set private

### PR DESCRIPTION
**Pull request by Tobbe**
This PR makes `<Private>` an alias for `<Set private>`

So doing this:

```jsx
const TestRouter = () => (
  <Router useAuth={mockUseAuth(true)}>
    <Route path="/" page={HomePage} name="home" />
    <Private unauthenticated="home">
      <Route path="/private" page={PrivatePage} name="private" />
    </Private>
  </Router>
)
```

Is equivalent to doing this:

```jsx
const TestRouter = () => (
  <Router useAuth={mockUseAuth(true)}>
    <Route path="/" page={HomePage} name="home" />
    <Set private unauthenticated="home">
      <Route path="/private" page={PrivatePage} name="private" />
    </Set>
  </Router>
)
```

### CODE REVIEW

**Comment by dac09** [comment]
Updated the description a little :)

**Comment by mojombo** [comment]
I endorse this approach.

**Review by dac09 — APPROVED** [review]
Looks good to me!

**Comment by thedavidprice** [comment]
Docs please! (adding to release notes)

**Comment by Tobbe** [comment]
PR for docs here: https://github.com/redwoodjs/redwood/pull/2418

**Comment by Tobbe** [comment]
@thedavidprice / @dac09 Updated the title of this PR to something that might be more fitting for the release notes. But up to you, as always.

**Comment by dac09** [comment]
@Tobbe had a thought about improving the types when the private prop is added! Let's chat on Monday!

**Pull request merged**
