### PR TITLE
Minor tweaks to apollo index.tsx

### PR DESCRIPTION
**Pull request by Tobbe**
More small changes extracted from #5985, this time Apollo related

### CODE REVIEW

**Comment by jtoar** [comment]
The changes are super small and seem inconsequential, but if I put my strict-mode hat on, this seems breaking to me, unless we don't consider TypeScript changes to be breaking?

**Comment by Tobbe** [comment]
Because before you could have no children, and now it'll show a TS error if you don't?

**Comment by Tobbe** [comment]
Or was there something else you thought of?

**Comment by jtoar** [comment]
That (but I mean, that component always has children) and we're renaming an exported type. Do you think people are using `UseAuthProp` explicitly?

**Comment by Tobbe** [comment]
I don't think anyone is using that type. That's why I'm not even exporting it anymore

**Pull request merged**
