### PR TITLE
feat(auth): Clerk v3 upgrade

### PR DESCRIPTION
**Pull request by igneel64**
Clerk upgrade to v3

1. Upgrade Clerk auth libraries
2. Introduce getToken options parameter for JWT templates on FE
3. Add correct logout typings :)

### CODE REVIEW

**Comment by Tobbe** [comment]
I'd prefer to wait with this until after V1.
That said, please do continue working on the PR. We can even merge it if we want. Just not cherry-pick it for inclusion in v1

**Comment by thedavidprice** [comment]
@Tobbe roger that ✅ I'll follow your lead here. Thanks!

**Comment by igneel64** [comment]
@thedavidprice @Tobbe 
The required merge has been done, since there will be no change needed from a user point of view.
Let me know for anything needed.

It would be nice to see this moving forward 🤗

**Comment by Tobbe** [comment]
I'll take this for a spin in a local project I have that uses Clerk. If that works (I'm sure it will) I'll merge this. Don't have time for that right now though, unfortunately

**Comment by igneel64** [comment]
@Tobbe If you need any help or we have any news you can let me know 😄

**Comment by Tobbe** [comment]
> @Tobbe If you need any help or we have any news you can let me know 😄

LOL. Thanks for the gentle nudge ❤️ 

I'll get to this one tomorrow. Pinky-swear.

**Comment by Tobbe** [comment]
@igneel64 Thanks for the PR. Finally got around to testing it in a clerk app I have 🙂

**Comment by thedavidprice** [comment]
I just cut the branch for 1.1 and released an RC. I've added the `next-release-patch` to remind me to cherry-pick this into the release branch for 1.1.0 release next Tuesday.

Thanks, all!

**Comment by nivivive** [comment]
@Tobbe do you have any examples of where we can update the code to take advantage of getToken(options) and pass the JWT template?

**Pull request merged**
