### PR TITLE
chore(studio): update tremor to v3

### PR DESCRIPTION
**Pull request by Josh-Walker-GM**
[Tremor](https://www.tremor.so/) released v3 with the changelog [here](https://www.tremor.so/changelog). This PR updates the studio frontend in accordance with the new v3 api.

See #8560 that triggered this.

### CODE REVIEW

**Review by dthyresson — CHANGES_REQUESTED** [review]
In my test, seems there is a background issue in select lists:

image

**Comment by dthyresson** [comment]
Also, tremor has release 3.2.2 since this PR to fix some regressions; perhaps this is one.

**Comment by Josh-Walker-GM** [comment]
Hmm okay I can take another look and check. Things looked okay when I pushed up but I'll double check of course.

**Comment by dthyresson** [comment]
I did a new test project and then rwfw project sync; setup open telemetry, start studio.

**Review by dthyresson — APPROVED** [review]
We paired and demo'd to see v3 working well.

**Pull request merged**
