### PR TITLE
fix(router): Skip search params with undefined and null values passed to named routes

### PR DESCRIPTION
**Pull request by antonmoiseev**
Automatically ignoring null and undefined values for search params helps avoiding repetitive and verbose checks when calling `navigate()` function.
Examples:
1. Passing `redirectTo` parameter in case of multi-step (multi-page) sign in / sign up process:
    ```ts
    navigate(routes.webAuthn({ redirectTo }))
    ```
2. Filter params on a search page:
    ```ts
    navigate(routes.clothes({ size, category, color }))
    ```
In both examples parameters are optional and may be missing. Currently we have to manually filter out undefined and null values before passing them to generated route functions.

### CODE REVIEW

**Comment by antonmoiseev** [comment]
I noticed it wasn't included in the 8.4.0 release, does it needs anything else?

**Comment by antonmoiseev** [comment]
@Josh-Walker-GM sorry for tagging you, just want to make sure we have a chance to resolve any issues before next release

**Comment by Josh-Walker-GM** [comment]
Hey @antonmoiseev! No worries about the pinging. Thanks for making sure this doesn't slip out of our memory! I think some others on the team wanted to just double/sanity check this but we've all been bogged down with other work so this has slipped. Sorry about that, we really do appreciate the contributions and the team has mentioned a number of times that we're grateful for your involvement in-particular. 

I'll see if I can get someone to look at this pr this week/next.

**Comment by Philzen** [comment]
@Tobbe @antonmoiseev with this merged, i think #11598 can be closed now :rocket:

**Pull request merged**
