### PR TITLE
Upgrade setup tailwind

### PR DESCRIPTION
**Pull request by jtoar**
This PR upgrades the setup tailwind command to 1) take advantage of postcss v8 compatibility and 2) enable jit mode by purging (effectively "watching") the correct files.

Todos:
- [x] we add `@tailwind` directives to index.css but there's other ways to do it. look more into the pros/cons of each
  - `import 'tailwind/tailwind.css'` is now added to App.{js|tsx} instead of adding the directive block to index.css; this is cleaner and keeps index.css just for index.css things
- [ ] write a migration guide for postcss-v7 compatible users
- [x] are there other settings we should configure by default in `tailwind.config.js`?
  - jit and purge are enough
- [x] make sure css is actually being built for production: https://tailwindcss.com/docs/installation#building-your-css

Other changes:
- we use the tailwind cli to initialize a postcss.config.js (instead of maintaining a template that we copy over)
- tailwind.config.js is moved to web/config because the extension recognizes it there now

### CODE REVIEW

**Comment by antonmoiseev** [comment]
@jtoar thank you for working on this! I'm starting a new project with Redwood and desperately want to use the latest and greatest Tailwind CSS with it. Please, let me know if there is something I can help with to make it happen sooner.

**Comment by jtoar** [comment]
@antonmoiseev awesome, thanks for the offer! Trying to get this done today. Most of it's setup and is working, I'm just a little confused on where tailwind JIT actually outputs to (in the demo videos, they use the tailwind cli which is writing to a file, but with webpack I think everything's held in memory?). Also want to make sure when it's built for production, things are actually purged

**Review by thedavidprice — APPROVED** [review]
🚀

**Comment by jtoar** [comment]
This needs docs

**Comment by jtoar** [comment]
Seeing an error with this in the canary... debugging now
image

**Pull request merged**
