### PR TITLE
Add 'windows-latest' to CI action matrix

### PR DESCRIPTION
**Pull request by thedavidprice**
We need to include Windows runner for the telemetry-benchmarks GitHub Action.

### CODE REVIEW

**Review by dac09 — APPROVED** [review]

**Comment by dac09** [comment]
Obviously we can't merge right now, but seems sensible!

**Comment by thedavidprice** [comment]
@dac09 Thank you! I'd prefer to handle in Workflow file itself if possible, I just don't Windows very well.

@Tobbe no pressure, but if you're available I sure could use some help here. I'm just trying to create a temporary directory to build a project and could have swarn that New-TempDirectory was a real command in powershell. 

The trick is I also need to output the vars to the Github Action so I can re-use them in the following steps (i.e. the `echo "::set-output name=project_path::$project_path"` parts, which GitHub says will work on Windows powershell)

No need to figure out the workflow conditionals. I just want to get this running on Windows as is to see if Telemetry is working or failing.

**Comment by Tobbe** [comment]
> could have swarn that New-TempDirectory was a real command in powershell.

It totally should be!

For now this was the first hit on Google

```powershell
function New-TemporaryDirectory {
    $parent = [System.IO.Path]::GetTempPath()
    [string] $name = [System.Guid]::NewGuid()
    New-Item -ItemType Directory -Path (Join-Path $parent $name)
}
```

https://stackoverflow.com/questions/34559553/create-a-temporary-directory-in-powershell

But I'm guessing you can't define new PS functions in the workflow file, right?

**Comment by thedavidprice** [comment]
> But I'm guessing you can't define new PS functions in the workflow file, right?

Not ideal (and/or might not be possible). I don't know how powershell works, e.g. can I define on a line and use in the next?

If need be, I'll just use something like Danny's code to handle via JS.

Thanks for looking at this!

**Comment by Tobbe** [comment]
Weird, I replied to this using pullflow, but it seems it didn't show up :/ This is what I wrote

> Honestly I prefer the JS solution. That way we have code anyone can jump in and help out with. If we do something with PS very few people in our community is going to feel comfortable touching it.

**Comment by thedavidprice** [comment]
replaced by #4495

**Pull request closed without merging**
