### PR TITLE
Upgrade to Prisma 2.5.1

### PR DESCRIPTION
**Pull request by thedavidprice**
Prisma Release Notes:
- https://github.com/prisma/prisma/releases/tag/2.5.0
  - Middlewares
  - removing duplicates with `distinct`
  - aggregations
  - many more preview features; see release notes
- https://github.com/prisma/prisma/releases/tag/2.5.1
  - Client bug fixes

Basic local tests == ✅

### CODE REVIEW

**Comment by thedavidprice** [comment]
@peterp wanted you to see this before merging (couldn't remember if you had something in progress and were holding off). If GTG, please go ahead and merge.

**Comment by thedavidprice** [comment]
Super strange, non-Prisma related CI error:
https://github.com/redwoodjs/redwood/pull/1004/checks?check_run_id=1029275108#step:8:100

`ReferenceError: Cannot access 'mockFs' before initialization` 

Wondering if it's a GH Action hiccup. Will try to re-run and take a deeper look later.

**Comment by thedavidprice** [comment]
Whelp, always fun when local tests pass just fine:
Screen Shot 2020-08-25 at 7 39 26 PM

**Review by peterp — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
