### PR TITLE
Generate AvailableRouteNames

### PR DESCRIPTION
**Pull request by peterp**
This PR generates a union of available route names that can be used to inform Private's "unauthenticated" property.

image

Typically types cannot be enhanced, because TypeScript will complain about duplicate definitions, but this works by not declaring the original type and suppressing the TypeScript errors where they are imported. The types are provided by the client side at build-time and TypeScript is none the wiser in the end.

I hope that this technique will illustrate some additional flexibility in our TypeScript generation toolbox, but perhaps there's a way to do this entirely dynamically with inference? If that's possible then I would appreciate any direction in the comments, so I can start building up my TypeScript inference skillset. (I did attempt this, but I quickly ran into the "duplicate definition" problem that this is attempting to solve.)

/cc @Tobbe @dac09

- [ ] Genearate AvailableRouteNamesPrivate
- [ ] Genearate AvailableRouteNamesPublic
- [ ] Add post-build step to include `// @ts-expect-error` to generated type definitions.

### CODE REVIEW

**Comment by Tobbe** [comment]
Hah! So this was what you were teasing. I like it 🙂  This really makes the DX even better!

**Comment by peterp** [comment]
I actually thought about this a bit - and I don't know why I don't just overwrite the type in node_modules. I'll give that a test in a few.

**Comment by dac09** [comment]
Hey @peterp, once you figure this out could we spend a few mins together, to help me understand where the userland generated type gets put? 

I want to use this solution for https://github.com/redwoodjs/redwood/issues/2267, so that we can also infer union types on CurrentUser on the web side

**Comment by peterp** [comment]
@dac09 The generated type is placed in `.redwood/types`, but the more I thought about that the more I wondered why I'm trying to deal with TypeScript extendability... which has limitations.

I think what I might try is create a separate file for the "availableRouteNames"  type definition: `node_modules/@redwoodjs/router/dist/availableRouteNames.d.ts`, and I think if we delete that file, and re-create it (with the proper types) that TypeScript will just use that instead.

I think deleting it, and re-creating it, is the key for VSCode to pick it up.

I think we could probably adapt this for all our types, and instead of having a `.redwood/types` file we could just distort the actual types.

**Comment by peterp** [comment]
Closing this since it's complicated. I tried to ignore the errors when declaring the types, but those are also inserted into the generated type definitions.

**Pull request closed without merging**
