### PR TITLE
Revert auth provider refactor

### PR DESCRIPTION
**Pull request by jtoar**
After merging https://github.com/redwoodjs/redwood/pull/4880, we started seeing act-related (a React testing thing) warnings show up in web tests that just use `render` to check if the component renders (see https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/component/templates/test.tsx.template). After trying to solve this (see https://github.com/redwoodjs/redwood/pull/6058), we decided that it'd be better to just revert the change for now since we'll be refactoring the auth provider for decoupling auth anyway and can fix the issue then (see https://github.com/redwoodjs/redwood/pull/5985, https://github.com/redwoodjs/redwood/pull/6029).

So in terms of PR, this PR reverts the following (see commits https://github.com/redwoodjs/redwood/commit/37d686a44bb1ddf3576fb96b5137460c2690cad4, https://github.com/redwoodjs/redwood/commit/1e0cfef4ace1e390466575d96cbc493ae3a8b0d7):

- https://github.com/redwoodjs/redwood/pull/4880
- https://github.com/redwoodjs/redwood/pull/5969
- https://github.com/redwoodjs/redwood/pull/5998

And slightly changes the following (commits https://github.com/redwoodjs/redwood/commit/ac9508042c32ee046a9af6f0f496de3b2314d4b4, https://github.com/redwoodjs/redwood/commit/14ddc26d3b3e36e9a7f3739d34d95504e0908f45):

- https://github.com/redwoodjs/redwood/pull/5088
- https://github.com/redwoodjs/redwood/pull/5680
- https://github.com/redwoodjs/redwood/pull/5851

### CODE REVIEW

**Comment by jtoar** [comment]
I ran `build:test-project --rebuild-fixture` to update the test project fixture and there's two things that may need some attention:
- The rebuild process deletes the comments in `schema.prisma`. Should we keep them? @dthyresson are they used in tests?
- The `users.scenario.ts` file gets deleted, but seems like it shouldn't be

**Comment by jtoar** [comment]
@zackdotcomputer tagging you here in case you see this one cause I don't want you to feel bad. Not your fault at all—just the wrong time for us, and we couldn't find a fix we were happy with. We do have a real fix in the works, but it'll take more time, and we're a little overdue on a release, so just trying to be pragmatic here. Thank you for the work you did, it's informing our decisions for decoupling auth and teaching us what to look out for!

**Comment by Tobbe** [comment]
@zackdotcomputer You changes live on in spirit here: https://github.com/redwoodjs/redwood/pull/5985 (It'd actually be great if you could take a look at the Clerk parts of that PR) + here: https://github.com/Tobbe/rw-decouple-auth-demo/blob/main/web/src/auth.tsx

**Comment by dac09** [comment]
Hey Dom, not sure i can anything more to reviewing this PR - you seem to have a good handle on what changes are required here. 

But the `setup auth clerk` command seems to work (I don't have clerk creds to do a full e2e).

I think its important we merge this in ASAP so we can continue shipping!

**Comment by Tobbe** [comment]
Thanks for the kick in the butt Danny 😄  I do have Clerk creds, so I ment to do a full test, but I didn't get to it yet

**Comment by dac09** [comment]
Haha not a kick in the butt - just a gentle nudge to the shoulder 😉

**Comment by Tobbe** [comment]
I just confirmed it worked in a new project I created with the code in this PR. Could generate the auth setup and login using clerk's dialog and my clerk credentials 👍

**Review by Tobbe — APPROVED** [review]

**Pull request merged**
