### PR TITLE
Added quick start reference to CRA messages

### PR DESCRIPTION
**Pull request by kevPo**
This PR is in response to a request from this [PR](https://github.com/redwoodjs/redwoodjs.com/pull/414#issuecomment-714166525). 

Is this what you were hoping for @thedavidprice? 

image

### CODE REVIEW

**Comment by thedavidprice** [comment]
Indeed! That's looking good.

For discussion:
1. Visually for me the three sentences are lost between "Thanks for trying..." and "Join the Community" — it's hard to notice they are suggesting next steps and a command to run. I've been starting at this for months, so wondering if it has the same effect on you (i.e. no visually prominent)? 
   - If so, maybe try different text color for the information
   - And/or maybe the "We've created your app..." leave as is. But then the next two lines get formatted like a bulleted (or numbered) list with some indent. Could also try this with or without different text color
2. Somewhere along the way those bullet images for each section turned into `?` boxes, which is _not_ the original design. This started with the "return arrow", then a kind of "check box". So anything else would be better than what's currently showing. Example of original below (from https://github.com/redwoodjs/redwood/pull/1195):

Screen Shot 2020-10-23 at 2 32 41 PM

**Comment by Tobbe** [comment]
> Visually for me the three sentences are lost between "Thanks for trying..." and "Join the Community"

100% not just you! I had to scan that screen shot way too many times before I even found the link to the quickstart guide!

**Comment by kevPo** [comment]
image

@thedavidprice @Tobbe 

Any thoughts on this?

I tried emojis, but wasn't sure they they fit in with everything else. I felt the comet spoke to the speed of the quick start guide, and the bullet point reminded me a _little_ of the redwood acorn (it's a stretch I know, I've been staring at bullet points for way too long at this point).

**Comment by thedavidprice** [comment]
I'm digging it. Thanks for sticking with the tedium to work on this. It makes a difference.

Ok, to me the comet looks like a lawn sprinkler at best 😆 Although not everyone on the team is a huge fan of emojis, I'm sure we could sneak in something here --> maybe a ⚡️ for _speed_?

Layout is much better. Only thing that loses me is the `yarn rw dev` commands. I tried a few of the color options and didn't feel they worked any better than the green success could. What do you think about this?

Screen Shot 2020-10-26 at 9 18 13 PM

**Comment by kevPo** [comment]
Lawn sprinkler for sure! 😂 

I like the ⚡ a lot better. Also agree that the bright green helps to bring more attention to those commands. I added a separate style for `brightGreen` because using the `success` style for those commands felt wrong.

**Review by thedavidprice — APPROVED** [review]
🚀

**Comment by thedavidprice** [comment]
@kevPo this is great! I made some small tweaks:
- formatting per Prettier requirements (oh boy, check out that horrible `;[` action... it's a thing!)
- agreed about the success, but the double brightGreen option made me just resort to the green. Cool? (Can still change)
- ah, if the ⚡️moves outside the chalk styling it's possible to get the full emoji in some editors. boom ⚡️

**Comment by kevPo** [comment]
Thanks @thedavidprice! Looks great.

**Comment by jeliasson** [comment]
Sorry for being late to the party, but those bullets looks great! 🎉

@kevPo I noticed that you added `brightGreen` to the styles, whereas this chalk style is already defined as `success`. What do you think of using `success`? 

```js
const style = {
  [...]
  success: chalk.greenBright,
  [...]

  green: chalk.green,
  brightGreen: chalk.greenBright
}
```
Reference: https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/src/create-redwood-app.js#L38

**Pull request merged**
