### PR TITLE
fix(deploy): Restore Render deploy setup script

### LINKED ISSUE #11703: [Bug?]: Process for deploying to render no longer matches documentation
### What's not working?

Hello!

I've deployed a handful of Redwood apps to render over the last few years, and just tried to again yesterday but [the process](https://docs.redwoodjs.com/docs/deploy/render/) found in documentation no longer seems to line up with the CLI.

Specifically, when you run `yarn rw setup deploy render` you are now asked to pick a side to deploy:
```
> yarn rw setup deploy render
rw setup deploy render <side>

Build, migrate, and serve command for Render deploy

Positionals:
  side  Side to deploy               [string] [required] [choices: "api", "web"]

Options:
      --cwd                 Working directory to use (where `redwood.toml` is
                            located)
      --load-env-files      Load additional .env files. Values defined in files
                            specified later override earlier ones.       [array]
      --telemetry           Whether to send anonymous usage telemetry to
                            RedwoodJS                                  [boolean]
      --version             Show version number                        [boolean]
  -f, --force               Overwrite existing configuration
                                                      [boolean] [default: false]
      --prisma              Apply database migrations  [boolean] [default: true]
      --data-migrate, --dm  Apply data migrations      [boolean] [default: true]
  -h, --help                Show help                                  [boolean]

For more commands, options, and examples, see Redwood CLI Reference

Not enough non-option arguments: got 0, need at least 1
```

In the past, and detailed further in Render's [documentation](https://docs.render.com/deploy-redwood), this would have created a `render.yaml` file that would have made it easy to deploy both the `api` and `web` sides within Render, and (I believe) create a `healthz` function that render would use to check on the API side.

I'm not sure which process is preferred, the process detailed in the CLI or the process in the documentation.  But right now the conflicting guidance makes it unclear how to proceed.

If the process detailed in the CLI is preferred (it _is_ the [more-recently updated](https://github.com/redwoodjs/redwood/pull/10869) than the docs,) then it would be helpful if the documentation was updated to detail what's necessary to get the web side to successfully send requests to the api side after deploying each side independently.

### How do we reproduce the bug?

`yarn rw setup deploy render`

### What's your environment? (If it applies)

_No response_

### Are you interested in working on this?

- [ ] I'm interested in working on this

### LINKED ISSUE #11826: [Bug?]: Generate command for Render deployment configuration doesn't work
### What's not working?

Try following the docs by running `yarn rw setup deploy render`, and it will prompt you to provide a workspace, and you'll get this error

```
rw setup deploy render <side>

Build, migrate, and serve command for
Render deploy

Positionals:
  side  Side to deploy
   [string] [required] [choices: "api",
                                 "web"]

Options:
      --cwd            Working
                       directory to use
                       (where
                       `redwood.toml`
                       is located)
      --load-env-file  Load additional
      s                .env files.
                       Values defined
                       in files
                       specified later
                       override earlier
                       ones.    [array]
      --telemetry      Whether to send
                       anonymous usage
                       telemetry to
                       RedwoodJS
                              [boolean]
      --version        Show version
                       number [boolean]
  -f, --force          Overwrite
                       existing
                       configuration
             [boolean] [default: false]
      --prisma         Apply database
                       migrations
              [boolean] [default: true]
      --data-migrate,  Apply data
      --dm             migrations
              [boolean] [default: true]
  -h, --help           Show help
                              [boolean]

For more commands, options, and
examples, see Redwood CLI Reference
(​https://redwoodjs.com/docs/cli-comman
ds#deploy​)

Not enough non-option arguments: got 0, need at least 1
```

even after providing a workspace, it doesn't generate any `render.yaml` files.

### How do we reproduce the bug?

Simply follow the docs for generating via `yarn rw setup deploy render`

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 15.1.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - /private/var/folders/rg/_dktrz6s4x5f2mll_rd5f9880000gn/T/xfs-dfaaeaf4/node
    Yarn: 4.4.0 - /private/var/folders/rg/_dktrz6s4x5f2mll_rd5f9880000gn/T/xfs-dfaaeaf4/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Safari: 18.1.1
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 8.4.2 => 8.4.2 
    @redwoodjs/cli-data-migrate: ^8.4.2 => 8.4.2 
    @redwoodjs/core: 8.4.2 => 8.4.2 
    @redwoodjs/project-config: 8.4.2 => 8.4.2 
  redwood.toml:
    [web]
      title = "Audiochan"
      port = 8910
      apiUrl = "/.redwood/functions" # You can customize graphql and dbauth urls individually too: see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths
      includeEnvironmentVariables = [
        # Add any ENV vars that should be available to the web side to this array
        # See https://redwoodjs.com/docs/environment-variables#web
      ]
    [api]
      port = 8911
    [browser]
      open = true
    [notifications]
      versionUpdates = ["latest"]
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

### PR DESCRIPTION
**Pull request by Tobbe**
Fixes #11826
Fixes #11703

The setup script for Render was accidentally overwritten with the deploy script for Render in #10869
This PR simply restores the setup script to what it looked like before that PR was merged

### CODE REVIEW

**Comment by maferland** [comment]
@Tobbe Was this released yet? I'd like to try deploying to render so it would help if this could be released sometimes soon. I'd be happy to help if there's anything needed to release this bug fix.

**Comment by Tobbe** [comment]
It's not related yet. I've been traveling. I'm back home again tomorrow and will prioritize getting a release out. Thanks for your patience

**Comment by Tobbe** [comment]
@maferland It's available in RW v8.4.4 (v8.4.3 had an issue with the packages published to npm, so please go straight to v8.4.4)

**Comment by maferland** [comment]
Awesome, I appreciate the quick release <3

**Pull request merged**
