### PR TITLE
Remove deprecated non-critical features

### LINKED ISSUE #2631: Remove deprecated features for v1
The codebase currently includes many items indicating v1 deprecation.

We should find those and deprecate them.

### PR DESCRIPTION
**Pull request by callingmedic911**
Partially closes #2631.

- [x] Removes deprecated commands - db, generate and util
- [x] Removes unused `generateDepracatedHandler`
- [ ] Update docs

Reference: https://github.com/redwoodjs/redwood/pull/2896#issuecomment-883771543

### CODE REVIEW

**Review by thedavidprice — APPROVED** [review]
🚀

**Comment by thedavidprice** [comment]
Thank you @callingmedic911 I have a reminder to myself about docs. Just let me know if you beat me to it 🚀

**Comment by callingmedic911** [comment]
Haha sure! I'll try to get it done tomorrow. Just to confirm, we need to remove section with these deprecated command right?

**Comment by thedavidprice** [comment]
@callingmedic911 confirmed! And thank you again!!

**Comment by callingmedic911** [comment]
Docs ✅

**Pull request merged**
