### PR TITLE
Use correct number type!

### PR DESCRIPTION
**Pull request by guledali**

### CODE REVIEW

**Comment by dac09** [comment]
Hi @guledali - thanks for the PR!

A description would be appreciated :), but I also do not think this change is quite correct - its possible that the id could be a different type. 

Would you please describe the problem you're having in an issue first?

**Review by dac09 — CHANGES_REQUESTED** [review]
Needs more context.

**Comment by guledali** [comment]
I just saw that TypeScript was complaining when I ran the linting

**Comment by dac09** [comment]
> I just saw that TypeScript was complaining when I ran the linting but I think someone had PR somewhere addressing this.

Understood - lets close this for now then, but if you find the issue isn't resolved by the other PR, please do feel free to open another issue and/or PR!

Thanks 🚀

**Pull request closed without merging**
