### PR TITLE
Auth: Add TS types for auth method options

### PR DESCRIPTION
**Pull request by Tobbe**
Provide types for the auth method options, like `options` in `logIn(options)` and `signUp(options)`

Users who were previously (probably unknowingly) passing unsupported parameters to `logIn`, `signUp` and a few more methods will now see TS type errors when trying to build their code base, requiring them to fix their code.

### CODE REVIEW

**Comment by dthyresson** [comment]
I have integrated my Supabase v2 PR https://github.com/redwoodjs/redwood/pull/7719 with this to test out the types -- which work great!

This PR also adds tests for the Supabase auth integrations: password, otp/passwordless, id token, and sso.

**Comment by dthyresson** [comment]
@Tobbe please have a quick review if my combining v2 and the auth types works for you. 

It was rather nice to write tests with all the proper types as it knew when my provider was missing -- or invalid.

TODO: I am going to add docs for each of the methods similar to: https://supabase.com/docs/reference/javascript/auth-signinwithpassword

**Comment by dthyresson** [comment]
Added docs to explain how to login with various methods. but, I just noticed there was no test or doc for sign up. Will add.

**Comment by dthyresson** [comment]
cc @bnn1  

Fixes https://github.com/redwoodjs/redwood/issues/7689

**Comment by Tobbe** [comment]
I moved the upgrade of Supabase to v2 back into #7719

**Pull request merged**
