### PR TITLE
Update scaffold.css.template

### PR DESCRIPTION
**Pull request by fakkio**
Fix a visual issue with the `.rw-table-wrapper-responsive` scrollbar, that made it look like an ellipse.

### CODE REVIEW

**Comment by jtoar** [comment]
Hey @fakkio this is what this fixes right?

image

@cannikin did you get these styles from a source that had the `50%` there originally for some reason?

**Comment by jtoar** [comment]
@fakkio since this PR changes the template, it looks like you have to update a snapshot in one of the cli tests to get tests passing. That should be as easy as:
```bash
cd packages/cli
yarn test -u
# commit changes
```
but let me know if that doesn't end up working.

**Comment by fakkio** [comment]
> @fakkio since this PR changes the template, it looks like you have to update a snapshot in one of the cli tests to get tests passing. That should be as easy as:
> 
> ```shell
> cd packages/cli
> yarn test -u
> # commit changes
> ```
> 
> but let me know if that doesn't end up working.

@jtoar i failed 44 test on 48, this is the error:
```
Cannot find module '@redwoodjs/internal' from 'src/commands/__tests__/dev.test.js'
```
Results:
```
Test Suites: 44 failed, 4 passed, 48 total
Tests:       17 passed, 17 total
Snapshots:   0 total
Time:        7.579 s
```

I also tried to clone a fresh new project but i get the same error. I checked my `node_modules` and `@redwood/internal` is there.
I'm sorry to waste your time but i don't know what to do.

**Comment by jtoar** [comment]
@fakkio no worries, I think I forgot to tell you a step actually so my bad! You have to build the framework first. Try running `yarn build` in the root of the framework before running `yarn test -u` in `packages/cli` and let me know if that works:

```bash
yarn build # the step I forgot to mention
cd packages/cli
yarn test -u
# commit changes
```

**Comment by fakkio** [comment]
@jtoar ok it worked, I've committed the new snapshots. Do I need to do anything else?

**Comment by cannikin** [comment]
Huh... that's not a style I added, I didn't even know you could do that. Might have been from a previous PR for someone tweaking the styles?

**Review by jtoar — APPROVED** [review]
@fakkio nothing else necessary to do, this looks good!

**Pull request merged**
