### PR TITLE
WIP: run E2E on CircleCI

### PR DESCRIPTION
**Pull request by thedavidprice**
## CircleCI dashboard
https://app.circleci.com/pipelines/github/redwoodjs/redwood

## To Do
- [x] init config.yml environment
- [ ] create the test project 
    - env var is not being created correctly
- [ ] run Cypress
- [ ] improve performance options (note: I don't think default cache is working with Yarn workspaces...)

## Why?
This is a near-term patch I'm time-bounding. Unlike GitHub Actions, we can boost the container horsepower on CircleCI.

### CODE REVIEW

**Comment by jtoar** [comment]
Docs on `working_directory` here:

```
In which directory to run this step. 
Will be interpreted relative to the working_directory of the job). (default: .)
```


https://circleci.com/docs/2.0/configuration-reference/#run

**Comment by jtoar** [comment]
@thedavidprice I think I've got things working now; assuming using `cd` instead of `working_directory` is an acceptable trade off? Setting `working_directory` for a step will set it relative to the job's working directory. I haven't found a way to set it absolutely from a step yet (you can set it absolutely at the job-level, but `PROJECT_PATH` doesn't exist at that level).

**Comment by thedavidprice** [comment]
Thanks so much @jtoar! 

> I think I've got things working now; assuming using cd instead of working_directory is an acceptable tradeoff?

^^ I'll just have to see what this means for the following steps. I'll just run some commands and output directory to figure it out.

**Comment by thedavidprice** [comment]
giving up the ghost on this one

**Pull request closed without merging**
