### PR TITLE
Update docs node version requirement to reflect current redwood reqs

### PR DESCRIPTION
**Pull request by dkmooers**
Wasn't sure whether to keep `<= 16.x` format from current docs, or switch to `< 17.0.0` from current redwood CLI error message, but opted for the latter

### CODE REVIEW

**Comment by dkmooers** [comment]
BTW this is my first commit to an open source project, sorry if I borked something!

**Comment by dkmooers** [comment]
Sorry, I didn't follow the official redwoodjs contributing workflow. Will start over with this PR!

**Comment by dkmooers** [comment]
Am I supposed to add a `release:chore` label to this PR somehow? Not sure if I have privileges to do that, can't figure out how

**Comment by thedavidprice** [comment]
Welcome to Redwood! Glad to have you as a contributor. 

We will take care of the label. 

Do see my comment about bumping the version engine. Node.js does things in a unique way.

**Review by thedavidprice — CHANGES_REQUESTED** [review]

**Comment by dkmooers** [comment]
OK great, updated min version to 14.19 and left max as is.

**Comment by thedavidprice** [comment]
Thank you! Merging now

**Comment by dkmooers** [comment]
Yeah for sure, thanks!

**Pull request merged**
