### PR TITLE
Path for generators

### PR DESCRIPTION
**Pull request by fveauvy**
This pull request aims to handle path argument for layout, component, page and cell generators. 
This PR is linked to issues #2232, #1597 and to this [Discourse thread](https://community.redwoodjs.com/t/addition-to-the-cell-generator/2008).

I closed #2236 because [I messed up the commits](https://github.com/redwoodjs/redwood/pull/2236#issuecomment-824385415) and decided to open a new PR.

## Purpose of this PR

 - Specify a path for component, page, cell and layout generators. For instance `yarn rw g component ui/button` will generate :
```sh
  ✔ Generating component files...
    ✔ Successfully wrote file `./web/src/components/ui/Button/Button.test.js`
    ✔ Successfully wrote file `./web/src/components/ui/Button/Button.stories.js`
    ✔ Successfully wrote file `./web/src/components/ui/Button/Button.js`
✨  Done in 6.37s.
```
ui-button

 - Apply camelCase instead of PascalCase to folder's name generated when a path is provided (scaffold included)
 - Remove empty folders when using destroy command
 - Fix route for `path/name` pattern when using page generator
 - Page destroyer now removes stories and tests files aswell
 - Update scaffold tests
 - Add tests for the cell generator with path and nested path patterns

## What's left to do

There is a bug when the user provides a nested path on the page generator.

The command `yarn rw g page path/test` works properly.

Although when I run the following : `yarn rw g page nested/path/test` 

I got this error in the `Routes.js` file :
```
'nestedPathTestPage' can not be found in '/web/src/pages'.eslint(@redwoodjs/redwood/no-unavailable-pages)
```

I'm not sure why it's happening and I could use some help to figure this out.

### CODE REVIEW

**Comment by fveauvy** [comment]
@Tobbe I closed #2236 because I couldn't figure out a easy way to clean the commit history

Would you care for checking my pull request ?

**Comment by Tobbe** [comment]
Thanks for this @fveauvy. This is much easier to review 🙂  I'll have a look tomorrow!

**Review by Tobbe — COMMENTED** [review]
I left a few minor comments. But the main thing I'm missing from this are updates to `paths.ts`, `paths.test.ts`, `babel-plugin-redwood-routes-auto-loader.ts`, and test for the babel stuff.

Please have a look and see what updates are needed to those files (if any)

**Comment by fveauvy** [comment]
So far I only worked on the CLI package.

I'll try to get a grasp on core and internal packages in order to update the files you mentionned. 

Thanks for your input.

**Comment by dac09** [comment]
@fveauvy thanks for the great work on this so far! Could we target for v0.33 do you think? (~2 weeks time)

**Comment by fveauvy** [comment]
@Tobbe I used `git pull --rebase upstream main` as you suggested on #2236 to update my branch. It seems I messed up th commit history again :(

@dac09 I'll try to work on it this weekend

**Comment by jtoar** [comment]
@fveauvy rebase is one of the hardest things to learn, but it's totally worth it once you've got it down. If you haven't used git's magical time machine before (reflog), I highly recommend it! Check it out here: https://dangitgit.com/en.

In the meantime, I can pull this one down and help you out. Do you know which commit you started with? Was it this one? https://github.com/redwoodjs/redwood/pull/2430/commits/abf45132df518f77c4439c364e626c9535336cac I'll also do some investigating to see if I can figure it out.

**Comment by jtoar** [comment]
@fveauvy does this look right? I'll also rebase it onto main for you

**Comment by Tobbe** [comment]
@fveauvy No pressure at all, just wanted to check in with you and see how you're doing. Do you still want to work on this, or do you want someone else to take it over?

**Comment by fveauvy** [comment]
Hello @Tobbe,

Sorry for the delay. A lot is happening at work currently.
If someone want to take it over, I won't mind.

@jtoar made a cleaner PR #2606

**Comment by Tobbe** [comment]
@fveauvy No need to be sorry. Thanks for letting us know!

**Comment by jtoar** [comment]
@fveauvy like @Tobbe said no worries at all and thanks for getting this going. This is definitely a long-awaited feature, I'll be sure to get it across the finish line for you

**Comment by arimendelow** [comment]
Was anything like this ever merged?

**Comment by Tobbe** [comment]
@arimendelow No, not yet. There's a draft PR open here: https://github.com/redwoodjs/redwood/pull/3595

**Pull request closed without merging**
