### PR TITLE
Improve Error Handling at FatalErrorBoundary

### LINKED ISSUE #140: Show JS errors on FatalError page in dev mode.

### PR DESCRIPTION
**Pull request by thedavidprice**
Fixes #140 

Adds the Webpack Plugin 'ErrorOverlayPlugin':
https://github.com/smooth-code/error-overlay-webpack-plugin

**Error display before:**
```javascript
Something went wrong
```
**Error display after:**

Screen Shot 2020-04-29 at 8 59 51 PM

### CODE REVIEW

**Comment by mojombo** [comment]
Nice! What’s the behavior in production? We need to ensure this info doesn’t leak in that environment.

**Comment by thedavidprice** [comment]
The plugin states by default it's "development ENV only" but I'd like to test it. I first wanted to see if Peter agrees with this plugin/implementation, but your question was also on my mind.

If this is the path forward, I’ll make sure we test in a Production environment before releasing it.

**Comment by peterp** [comment]
Nice! Tom makes a good point, maybe we should only import it in `core/webpack.development.js`

**Comment by thedavidprice** [comment]
@peterp moved settings to webpack dev config. Please go ahead and merge if it all's good.

**Pull request merged**
