### PR TITLE
`yarn rw test` automatically creates api/jest.config.js and web/jest.config.js if they dont exist

### LINKED ISSUE #907: Running yarn rw test should automatically generate jest.config.js files for api and web if they're missing
**EDIT:** The original issue is solved by adding jest.config.js files. So, running `yarn rw test` should automatically generate jest.config.js files for api and web if they're missing.

Original issue: Tests [web] are failing to run because __REDWOOD__API_PROXY_PATH is not defined
```bash
yarn rw test web

Test suite failed to run

    ReferenceError: __REDWOOD__API_PROXY_PATH is not defined

    > 1 | import { render } from '@redwoodjs/testing'
        | ^
      2 | 
      3 | import { Header } from './Header'
      4 | 

      at Object.<anonymous> (../node_modules/@redwoodjs/web/dist/config.js:5:36)
      at Object.<anonymous> (../node_modules/@redwoodjs/web/dist/index.js:68:1)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/MockProviders.js:15:12)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/customRender.js:17:22)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/index.js:78:21)
      at Object.<anonymous> (src/components/Header/Header.test.js:1:1)
`

```bash
yarn rw info

yarn run v1.22.4
$ /Users/terriskremer/Sites/kremer/kremerlibrary/node_modules/.bin/rw info

  System:
    OS: macOS Mojave 10.14.6
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.1 - /var/folders/s3/jyccmmxs11j893bfb92tt0900000gn/T/yarn--1596039261212-0.9150607551937429/node
    Yarn: 1.22.4 - /var/folders/s3/jyccmmxs11j893bfb92tt0900000gn/T/yarn--1596039261212-0.9150607551937429/yarn
  Databases:
    SQLite: 3.24.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 74.0
    Safari: 13.1.2
  npmPackages:
    @redwoodjs/core: ^0.14.0 => 0.14.0

### PR DESCRIPTION
**Pull request by robobunny**
Fixes #907 

## My Solution

... is pretty straightforward.

1. use `fs.existsSync` to check for api/jest.config.js and web/jest.config.js
2. use axios to fetch the config files from the `/create-redwood-app` template repository
3. fs.writeFileSync to write them to the project api and/or web folders

- it works when either `api/jest.config.js` or `web/jest.config.js`  or both are missing

## Drawbacks

- it performs the check every time you run `yarn rw test`. Which isn't a huge deal considering the default behavior is to `--watch` so it should only be eating up a couple milliseconds at the beginning of a dev session, but if someone's running `yarn rw test` more frequently for some reason then it's going to add up maybe?
- it only checks that those files exist, it doesn't verify that they're right. Not sure how much difference that makes, to be honest.
- it's pretty ugly ... maybe there's a way to refactor or maybe it makes more sense to put those functions in a file in `/lib` and import them?

### CODE REVIEW

**Comment by robobunny** [comment]
whoops i think i made a mistake and some changes from an irrelevant commit (see PR #1373) are in there too... is that a problem?

**Comment by peterp** [comment]
@robobunny I think this is a great start, but I have a few concerns about it automatically downloading the configurations if they're missing. There may be a case where I don't want them to be around anymore, and then each time I delete them and run the command they're re-installed.

I'm wondering if this would work well as a setup command instead? `yarn rw setup redwood-jest`

**Comment by robobunny** [comment]
> There may be a case where I don't want them to be around anymore, and then each time I delete them and run the command they're re-installed.

Hmmm.... you may be right. But the command throws an error if they don't exist (according to #907), so I can't imagine wanting to run it without them. I haven't tried many edge cases.... maybe like if the user has a custom config that's named something else or saved somewhere else?

> I'm wondering if this would work well as a setup command instead? `yarn rw setup redwood-jest`

Seems logical. In that case, we could add error handling to `yarn rw test` if these files are missing that prompts the user to run `yarn rw setup redwood-jest` first.

What do you think @peterp?

**Comment by peterp** [comment]
@robobunny that's a great point, I hadn't realised that the command doesn't work if the config's are not included. I think it totally makes sense that the configs are then downloaded.

@thedavidprice Do you have any considerations?

**Comment by thedavidprice** [comment]
Hi Gents! Great to see this one in motion. Assuming we can (easily) add copy to the Jest error output in case that the configs don't exist, I'd recommend:
1. If the config(s) don't exist and Jest throws, add intelligent output copy
    - hey, yo! You're missing X config
    - you might need to add the config using the `yarn rw setup jest` (with link to relevant CLI doc)
2. add the Setup command for Jest config files

Thoughts/suggestions/disagreements?

**Comment by robobunny** [comment]
@thedavidprice That seems like a good solution and I assume it's as easy as adding a try/catch block to the yarn rw test command. I should have some time this weekend to take a closer look.

**Comment by robobunny** [comment]
So as I looked deeper into this I noticed a couple things: 

- The original issue (#907) was using RW version 0.15.0
- I tried deleting the jest.config.js files in a couple projects with newer versions of RW (0.19.0 and 0.20.0) and got an error, albeit a different one than the original issue (see attached).
- If I clone the /redwood repo as it currently stands (i.e. without this PR) and then `yarn rwt cpw` I get no error and Jest works fine, even without those config files. 

**Conclusion**: So I *think* issue #907 & therefore this PR is now moot.

I'm going to open a new PR with the proposed `yarn rw setup jest` command and the output message from `yarn rw test` just in case it's useful to someone.

The error output I'm getting with RW 0.20.0:

```
Error: Can't find a root directory while resolving a config file path.
Provided path to resolve: /home/william/Desktop/Robobunny/redwoodjs/example-todo/{,!(node_modules)/**/}jest.config.js
cwd: /home/william/Desktop/Robobunny/redwoodjs/example-todo
    at _default (/home/william/Desktop/Robobunny/redwoodjs/example-todo/node_modules/jest-config/build/resolveConfigPath.js:106:11)
    at readConfig (/home/william/Desktop/Robobunny/redwoodjs/example-todo/node_modules/jest-config/build/index.js:213:49)
    at /home/william/Desktop/Robobunny/redwoodjs/example-todo/node_modules/jest-config/build/index.js:446:18
    at Array.map (<anonymous>)
    at readConfigs (/home/william/Desktop/Robobunny/redwoodjs/example-todo/node_modules/jest-config/build/index.js:440:10)
    at async runCLI (/home/william/Desktop/Robobunny/redwoodjs/example-todo/node_modules/@jest/core/build/cli/index.js:230:59)
    at async Object.run (/home/william/Desktop/Robobunny/redwoodjs/example-todo/node_modules/jest-cli/build/cli/index.js:163:37)
```

**Comment by robobunny** [comment]
So I'm going to close this PR in favor of #1423

**Pull request closed without merging**
