### PR TITLE
WIP(router): Adds a router prompt component

### PR DESCRIPTION
**Pull request by xmaxcooking**
Hi! 

## Description 

This PR adds the missing feature to stop users from navigating. 
Currently it's only possible to prevent a page reload or a page close with [beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event).

## < RoutePrompt >

The new headless components can be used like this:

```ts
import {
  RoutePrompt,
  RoutePromptAbort,
  RoutePromptConfirm,
} from '@redwoodjs/router'

...

const PostForm = (props: PostFormProps) => {
  const form = useForm<FormPost>({
    defaultValues: {
      title: props.post?.title,
      body: props.post?.body,
      authorId: props.post?.authorId,
    },
  })
  
  const onSubmit = (data: FormPost) => {
    props.onSave(data, props?.post?.id)
  }

  return (
    <div className="rw-form-wrapper">
      <Form formMethods={form} onSubmit={onSubmit} error={props.error}>
        <RoutePrompt when={form.formState.isDirty}>
          Are you sure you want to leave?
          <RoutePromptConfirm>Confirm</RoutePromptConfirm>
          <RoutePromptAbort>Abort</RoutePromptAbort>
        </RoutePrompt>
        ....
      </Form>
    </div>
   )
```

## useNavigation()

So far navigation in redwood worked like:
```ts
import {
  navigate,
  back,
  routes,
} from '@redwoodjs/router'

...

return (
   <div>
     <button onClick={() => navigate(routes.posts()}>Go to posts</button>
     <button onClick={() => back(}>Go back</button>
   </div>
)

```

and now:
```ts
import {
  useNavigation,
  routes,
} from '@redwoodjs/router'

...

const { back, navigation } = useNavigation()

return (
   <div>
     <button onClick={() => navigate(routes.posts()}>Go to posts</button>
     <button onClick={() => back(}>Go back</button>
   </div>
)

```

Although these functions still work, they're now deprecated because they're bypassing the navigation context (blocking states)
These calls need to be refactored to the new hook useNavigation(). (unless you're using the redwood Link component, then it's already done)

## Notes

`useNavigation()` returns new functions to navigate and go back. The other functions returned by useNavigation don't have that much use, but can be used to create your own `<RouterPrompt>` components.

```
export interface NavigationContextInterface {
  blocked: boolean
  navigate: (to: string, options?: NavigateOptions) => void
  back: () => void
  block: (when: boolean) => void
  release: () => void
  confirm: () => void
  abort: () => void
}
```

## Todo's

- [x] Test edge cases with mixed deprecated navigate() and new navigate()
- [ ] navigation.test.tsx 
- [ ] Documentation for Components and hook
- [ ] Default Styling of components?

### CODE REVIEW

**Comment by xmaxcooking** [comment]
This is currently a draft .. because I will need some time to rework the deprecated navigate and back calls ..

and of course document this.

**Comment by xmaxcooking** [comment]
Marking this as `Ready for review` before I start to refactor and writing the docs. Thanks in advance!

**Comment by Tobbe** [comment]
@xmaxcooking Thanks for your PR! I know this is a feature that the community has requested. Could you please help me link in any forum posts, discord threads, issues etc you can find related to this?

Also some screenshots and/or videos of this feature working would be helpful 🙏 

To be completely honest with you, I'm not sure we have the bandwidth right now to do a proper review of this as a change this big (deprecating existing router functionality etc) would require the input from a lot of core team members. But if you could help with the things I asked for above that would make our job easier 🙂 

Thanks again for your PR. You're brave for taking on router modifications, this is a pretty complicated part of our code base! 😅

**Comment by xmaxcooking** [comment]
Hey @Tobbe 

I can try to make a video 😄 first time for everything.
As for the review.. well when I worked so deeply on the code base, I almost expected a rejection and therefore tested it a few
times to make sure it's at least not breaking. 

### Links
Discord:
- https://discord.com/channels/679514959968993311/1172256119813574807

Forum:
- https://community.redwoodjs.com/t/can-i-have-a-prompt-before-navigating-to-another-page/3652

**Comment by xmaxcooking** [comment]
Benching this for now. 

Tried to debug this today and absolutely nothing worked as it did when I marked this for review. 

I'm also having some weird issues with `yarn rwfw project:sync` and some changes aren't immediately applied in the test-project I built.

Very sorry about this. I do want/need this feature for redwood and will request a review as soon I'm confident again.

**Comment by Tobbe** [comment]
@xmaxcooking We did quickly discuss this in the team, and we do want a feature that lets you block routing. But we're not sure about the implementation yet.

Do you think you could take a look at [Remix's `useBlocker()`](https://remix.run/docs/en/main/hooks/use-blocker) and try to implement something more similar to that? And not adding new components to the router. Don't completely throw away what you have here, but rather try that as an alternative, so we can look at both versions and compare.

**Comment by xmaxcooking** [comment]
> We did quickly discuss this in the team, and we do want a feature that lets you block routing. But we're not sure about the implementation yet. 

Good to hear!

>Do you think you could take a look at [Remix's `useBlocker()`](https://remix.run/docs/en/main/hooks/use-blocker) and try to implement something more similar to that? 

>And not adding new components to the router. 

Sure! I can try to separate the blocker implementation into a separate hook like [useBlocker](https://reactrouter.com/en/main/hooks/use-blocker) and remove the components. 

Although that would still require a second hook similar to [useNavigate](https://reactrouter.com/en/main/hooks/use-navigate).

>Don't completely throw away what you have here, but rather try that as an alternative, so we can look at both versions and compare.

No problem, a second version sounds good.👍

**Comment by xmaxcooking** [comment]
Removed a previous fix that didn't work because the component never gets unmounted when using a bypass navigate.

Current version has two issues remaining:

- `back()` and manual browser back aren't blocked.
- RoutePrompt requires a form.reset to not block after a form.submit.

```ts
const onSubmit = (data: FormPost) => {
  props.onSave(data, props?.post?.id)
  form.reset(data)
}

....

return (
    <Form formMethods={form} onSubmit={onSubmit} error={props.error}>
      <RoutePrompt when={form.formState.isDirty}>
        Are you sure you want to leave?
        <RoutePromptAbort>Abort</RoutePromptAbort>
        <RoutePromptConfirm>Confirm</RoutePromptConfirm>
      </RoutePrompt>
      ...
    </Form>
)
```

I'm currently rethinking the approach to include `back()`.

**Comment by thedavidprice** [comment]
Closing this out. Work has moved to https://github.com/redwoodjs/redwood/pull/9843

**Pull request closed without merging**
