### PR TITLE
Added Decimal field type to Scaffold

### PR DESCRIPTION
**Pull request by BBurnworth**
Reference issue #4012 

Added Decimal field type to Scaffold by simply replicating the code for Float. Unsure if there is a more concise way of making this happen, such as a switch's fall-through.

It seems like [Tobbe's suggestion for NumberField](https://github.com/redwoodjs/redwood/issues/4012#issuecomment-1001748123) would possibly be more 'semantically' correct, and I tested a form input using `step='any'` and it does allows for decimal input with unlimited length. However, I was not sure how to add the `step='any'` property into the generator code, and I was also worried that I would be missing something deeper into the code so I went with this simple fix.

### CODE REVIEW

**Comment by dac09** [comment]
@dthyresson do you think you could take a look at this please? I think maybe we need one for BigInt as well I assume?

**Review by dthyresson — CHANGES_REQUESTED** [review]
Hi @BBurnworth many thanks for the PR.

I was wondering if there should be some tests for this and one could change:

```js
model Post {
  id       Int       @id @default(autoincrement())
  title    String
  slug     String    @unique
  author   String
  body     String
  image    String?
  isPinned Boolean   @default(false)
  readTime Int
  rating   Float?
  postedAt DateTime?
  metadata Json
  favorites Favorite[]
}
```

`readTime` from an Int to a Decimal -- or to just add another field that is a Decimal and update the tests and snapshots to confirm the form input rendering.

And @dac09 yes, while I did an 

```js
model Favorite {
  id      Int     @id @default(autoincrement())
  postId  Int
  post    Post    @relation(fields: [postId], references: [id])
  likes   BigInt
}
```

for BigInt, I neglected to add the input rendering, so I'll add an issue there.

But, I do think a test is needed before merging the Decimal input.

**Comment by dthyresson** [comment]
@BBurnworth Could you give me permission to push to this branch and I will add the tests, thanks!

**Comment by thedavidprice** [comment]
@BBurnworth per David T's request, here's how to give maintainers edit permission (which is easy to miss and hard to find):
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by BBurnworth** [comment]
@dthyresson @thedavidprice strange, i have had that setting checked since i made the PR... 

Also, David, I cannot make the meeting but if its recorded I can take a look.

image

**Comment by BBurnworth** [comment]
@dthyresson I invited you as a collaborator from the fork settings screen.

**Comment by dthyresson** [comment]
> @dthyresson I invited you as a collaborator from the fork settings screen.

Thanks!

**Review by dthyresson — APPROVED** [review]

**Comment by dthyresson** [comment]
I am having som push issues, so going to approve and add a separate PR for the tests

**Pull request merged**
