### PR TITLE
wip(auth): Get fresh token before making request

### PR DESCRIPTION
**Pull request by dac09**
Starts fix for #1576

- [x] Use fresh token for getCurrentUser
- [x] Use fresh token for other graphql requests
- [x] Add a way to watch for token changes from client
- [ ] Verify and test this

### CODE REVIEW

**Comment by peterp** [comment]
I'm a bit cautious of this approach, since it changes a bunch of assumptions and I'm not fully grokking the consequences of that.

Backing up a bit. I think the root cause for this problem is that we're not dynamically requesting the auth token on each request. 

This is solvable in Apollo by using an http auth-link (pseudo-code):

```js
import { AuthContext } from '@redwoodjs/auth'

const authLink = setContext((_, { headers }) => {
  // get the authentication token
  const { token } = AuthContext._currentValue

  // return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : "",
    }
  }
});
```

**Comment by viperfx** [comment]
My redwood app is still pre-production, but I face this almost on a daily basis during development. Token expires and all subsequent navigation inside redwood gives a 500 status from the API. (I am using Firebase as well).

Would the above suggestion with auth-link be implemented on global level in redwood or on an auth provider level?

**Comment by peterp** [comment]
@viperfx We'll solve this for everyone.

**Comment by dac09** [comment]
Closing this, new solution on the way.

**Pull request closed without merging**
