### PR TITLE
Bump latest Clerk version and fix broken import paths

### PR DESCRIPTION
**Pull request by SokratisVidros**
Fixes https://github.com/clerkinc/javascript/issues/444

### CODE REVIEW

**Comment by Tobbe** [comment]
Someone else created a very similar PR earlier https://github.com/redwoodjs/redwood/pull/6685 It touches the same file as this PR. Which one should we go with? 😅

**Comment by noire-munich** [comment]
Thanks you for taking the time to do this @SokratisVidros .

As @Tobbe points out, we have 2 PRs addressing the same issue but not in the same way and both would require changes to be mergeable. There might be something to discuss with @stephenhandley about the use of the instance paths, either way from our side we will take the first one which will implement the strongest proposition (ideally: not using instance path and having updated deps).

Also, @SokratisVidros if you have a strong opinion on the use of instance paths we need to hear about it :).

**Comment by SokratisVidros** [comment]
I am also posting this here: https://github.com/redwoodjs/redwood/pull/6685#issuecomment-1280380447

**Comment by NicholasDevStore** [comment]
When can this issue be solved?

**Comment by noire-munich** [comment]
> When can this issue be solved?

Pretty soon, probably by end of next week.

**Comment by jtoar** [comment]
@NicholasDevStore we just released this fix in https://github.com/redwoodjs/redwood/releases/tag/v3.3.2

**Pull request closed without merging**
