### PR TITLE
fix(telemetry): Safely lookup shell for windows

### PR DESCRIPTION
**Pull request by dac09**
Fixes the non-critical errors we're receiving from the CLI running on Windows. I'm not 100% certain if it always happens, because @cannikin had some code to detect the shell for windows, but on my Windows dev box, I never see the shell property.

Walkthrough: https://s.tape.sh/xGJk8Iu0

### CODE REVIEW

**Review by cannikin — APPROVED** [review]
Looks good to me! I double checked the database and `shell` can be null so we should be fine if it isn't sent up at all.

**Review by thedavidprice — CHANGES_REQUESTED** [review]
@dac09 I think this will still cause payload error for the case where windows doesn't provide `System.Shell`. Can you update starting L80:
```
  return {
    os: info.System.OS.split(' ')[0],
    osVersion: info.System.OS.split(' ')[1],
    shell: info.System.Shell.name,
```

to be
```
  return {
    os: info.System?.OS?.split(' ')[0],
    osVersion: info.System?.OS?.split(' ')[1],
    shell: info.System?.Shell?.name,
```

y/n/maybe?

**Review by thedavidprice — APPROVED** [review]

**Comment by thedavidprice** [comment]
Thanks @dac09! 

It's conceivable that `System` and/or `OS` might not exist, in which case sendTelemetry would throw. I've updated via separate commit. I'd rather err on the  side of having null values to process than now payload at all.

**Comment by dac09** [comment]
> Thanks @dac09! 
> 
> 
> 
> It's conceivable that `System` and/or `OS` might not exist, in which case sendTelemetry would throw. I've updated via separate commit. I'd rather err on the  side of having null values to process than now payload at all. 

Sure. I don't think system or OS are ever empty, but no harm in doing this. If only it was TypeScript....

**Pull request merged**
