### PR TITLE
Firebase auth options

### PR DESCRIPTION
**Pull request by ryanmdoyle**
This solves #2489, which is ultimately adding the capabilities of passing in the Google OAuth options for `setCustomParameters` and `addScope`.

****Currently, you can either call:****

- `logIn()`: which will default to use the Google provider
- `logIn('some_provider')`: Logs in using another firebase supported provider (Like facebook, github, etc)
- `login({email, password})`: logs user in using email/password

**The changes made will allow all the above, but casts the arguments into a single "options" object:**
```js
export type Options = {  
  providerId?: oAuthProvider  
  email?: string  
  password?: string  
  scopes?: string[] 
  customParameters?: CustomParameters}
}
```

This also allows someone to pass in an object for the Google provider method `setCustomParameters` or an array of requested scopes for the `addScope` method, which are applied if provided.

I also renamed some of the functions throughout for readability (such as changing `isPasswordCreds` to `hasPasswordCreds`)

### CODE REVIEW

**Comment by dac09** [comment]
Hey @ryanmdoyle thank you so much for this! We'll get around to this shortly, appreciate your help here and for being part of the community!

**Comment by thedavidprice** [comment]
Thank you @ryanmdoyle!

@dthyresson I've assigned this to you for review and direction. Are you available given this is not a next-release priority?

**Comment by thedavidprice** [comment]
@dthyresson could you help get this one going again when you have a chance?

**Comment by dthyresson** [comment]
Thanks @ryanmdoyle for this PR extended firebase auth to support other providers. So useful. And also many thanks for the docs.

This looks good to me and I'll approve. 

I'll add an issue in https://github.com/redwoodjs/playground-auth so and assign to you so we can update the Firebase examples there in our sandbox.

**Comment by thedavidprice** [comment]
We're having network time-outs on Windows CI runner. Will force merge now given other CI passing.

**Pull request merged**
