### PR TITLE
Set `cwd` to project's base path when running `yarn rw upgrade`

### PR DESCRIPTION
**Pull request by qooqu**
https://github.com/redwoodjs/redwood/issues/1659

used getPaths to get the base path, then added it to each execa with the cwd option

did some extremely rudimentary manual testing, so could definitely use some help on that front

### CODE REVIEW

**Comment by peterp** [comment]
Nice, thank you so much for this, and congrats on your first contribution to RedwoodJS!

**Review by peterp — APPROVED** [review]

**Comment by qooqu** [comment]
Thanks!

**Comment by qooqu** [comment]
ugh ... didn't mean for https://github.com/redwoodjs/redwood/pull/2081/commits/a9988978cdbb789e45c495db2fd6742b368d6795 to get in here. sorry

**Comment by thedavidprice** [comment]
Oh, nice! I'm attempting to get this into current release — retriggering Cypress now. (55min?? What in the world is wrong with our CI... 🤔 )

**Review by thedavidprice — APPROVED** [review]

**Comment by qooqu** [comment]
Nice!

**Pull request merged**
