### PR TITLE
Docs: Updated api-side-currentuser.md

### PR DESCRIPTION
**Pull request by OwenJRJones**
Changed '@requireAdmin' to '@requireAuth' as I believe this was a mistake, and also added a title/fixed some highlighting in the code containers related to adminPost services as it was missing/broken.

image

### CODE REVIEW

**Comment by Josh-Walker-GM** [comment]
Awesome! Would you be good to add titles to the other code blocks that are missing them?

**Comment by OwenJRJones** [comment]
> Awesome! Would you be good to add titles to the other code blocks that are missing them?

For sure, I should have done it initially but second guessed myself.

**Review by Josh-Walker-GM — APPROVED** [review]
Thanks!

**Comment by Josh-Walker-GM** [comment]
Thanks again for this first contribution! I hope you're enjoying redwood!

**Pull request merged**
