### PR TITLE
Run "yarn rw-gen" during create redwood app

### LINKED ISSUE #2754: New TS project can't find NotFoundPage
It seems like new (i.e. created from scratch) TypeScript Redwood Apps can't find the `NotFoundPage`. Steps to reproduce:
1. create a TS project: `yarn create redwood-app x-ts-route-error --ts`
2. go to `Routes.js`
3. observe:

image

### PR DESCRIPTION
**Pull request by jtoar**
TypeScript Redwood Apps (created with `yarn create redwood-app --ts`) can't find the `NotFoundPage` in the Routes.tsx file because the types haven't been generated yet (#2754). This PR fixes this by generating the types as a part of the install.

I think the types are supposed to help JS projects too, so I made it so that they're generated for JS projects as well on install.

### CODE REVIEW

**Comment by thedavidprice** [comment]
One area where our create-redwood-app.js script fails is that we assume `yarn install` is always run. But we provide an option for `--no-yarn-install`, which, if used alone, will cause the script to fail because it tries to convert to TS using `yarn rw ts-to-js`. (One simple way to improve this is to set the condition to only run ts-to-js command _if_  `--yarn-install=true`. I think a better solution would be to include the TS to JS transformation as a step in the installation script so that it could run whether or not yarn is installed.)

I'm curious if we'll have the same issue here where `--no-yarn-install` is passed but then the script fails because it can't generate the types... possibly?

**Comment by peterp** [comment]
Nice! Maybe we can add `skip` to the listr tasks if the install flag isn't present?

**Comment by jtoar** [comment]
@thedavidprice linking #1954 just cause you mentioned that there too, and it does indeed fail if yarn install isn't true which is definitely not ideal.

> I think a better solution would be to include the TS to JS transformation as a step in the installation script so that it could run whether or not yarn is installed

^ I'll see if I can include this here

**Comment by peterp** [comment]
@jtoar Could you try the ts-stuff in a different PR? I would like to get this one in alongside the eslint PR.

**Comment by jtoar** [comment]
@peterp Absolutely; I can go ahead and rebase this one it if it looks ready

**Comment by jtoar** [comment]
I included a check for `--yarn-install` just for now, so that it generates a TS project if `--yarn-install=false` (instead of failing). I did it via Listr's `enabled` property, but I could also do it via `skip` and provide a message:
```js
enabled: () => typescript === false,
skip: () => {
  if (yarnInstall === false) {
    return 'skipped; needs ts-to-js binary'
  }
},
```

**Review by peterp — APPROVED** [review]
Woot!

**Review by dac09 — APPROVED** [review]
LGTM too!

**Pull request merged**
