### PR TITLE
return for proper rendering

### PR DESCRIPTION
**Pull request by paybosllc**
works with return, don't know if adding <> </> would be better.

### CODE REVIEW

**Comment by Tobbe** [comment]
This is the same as https://github.com/redwoodjs/redwood/pull/6214 I closed that one, because the syntax is valid. But now I'm starting to doubt myself. Why do we get two PRs for the exact same thing so close to each other?  Is something confusing here that we need to change?

**Comment by paybosllc** [comment]
> This is the same as #6214 I closed that one, because the syntax is valid. But now I'm starting to doubt myself. Why do we get two PRs for the exact same thing so close to each other? Is something confusing here that we need to change?

I was working through your tutorial and I was getting a 'render error'. Adding the return to this component fixed the issue. I'm not an expert on react but I'm wondering if it has to do with scoping of the parent components.

**Comment by Tobbe** [comment]
Can you share a screenshot of the error in your editor please?

**Comment by paybosllc** [comment]
> Can you share a screenshot of the error in your editor please?
image

Just recreated this when clicking from the 'home page' to a specific article entry.

**Comment by Tobbe** [comment]
It's super weird, because the change you've suggested is a syntax error. It would have to be curly braces, not regular parentheses for the `return` to even be valid. Can you also share a screenshot of your editor with this code please?

**Comment by Tobbe** [comment]
Okay, yeah, I think I know what's going on.

You had this, right? 
image

And then you just removed all that inner code, leaving just `<Article ...`. Am I right? But you didn't see (because we didn't highlight) that `{` changed to `(` in this code snippet

image

**Comment by paybosllc** [comment]
> It's super weird, because the change you've suggested is a syntax error. It would have to be curly braces, not regular parentheses for the `return` to even be valid. Can you also share a screenshot of your editor with this code please?

Here's the code change I made to 'fix' the rendering issue.
image

**Comment by Tobbe** [comment]
To make this less confusing I think we should keep the curly braces from the first code block in the second as well. And add the `return` statement, because now it's needed.

**Comment by Tobbe** [comment]
> > It's super weird, because the change you've suggested is a syntax error. It would have to be curly braces, not regular parentheses for the `return` to even be valid. Can you also share a screenshot of your editor with this code please?
> 
> Here's the code change I made to 'fix' the rendering issue. image

Thank you! Just as I expected, you had the curly braces `{` still left in there from the first example. And then you do need a return statement. Had you changed to `(` as the second example shows it would have worked without the return statement like the example shows.

I can totally see how this is all super confusing. Sorry!

**Comment by paybosllc** [comment]
> Okay, yeah, I think I know what's going on.

 
> image

This is what was there following the tutorial.
https://redwoodjs.com/docs/tutorial/chapter2/routing-params
image

**Comment by Tobbe** [comment]
Exactly 🙂 

image

**Comment by paybosllc** [comment]
going to close and let the rw team address the docs.

**Comment by Tobbe** [comment]
I made a PR that changes to `{ return <Foo /> }`
https://github.com/redwoodjs/redwood/pull/6224

**Pull request closed without merging**
