### PR TITLE
GraphQLHookOptions - add refetchQueries type.

### PR DESCRIPTION
**Pull request by noire-munich**
As seen on the forums, `refetchQueries` is not typed yet,
https://community.redwoodjs.com/t/is-refetchqueries-deprecated/1791/9

PR for #1752

### CODE REVIEW

**Comment by Tobbe** [comment]
Thanks for getting started on this @noire-munich. Can you please clean up the lint warnings?

**Comment by noire-munich** [comment]
Done!
I'll write that one to a git hook...

**Comment by Tobbe** [comment]
> I'll write that one to a git hook...

Something I should have done myself a long time ago! 😁 

Now that I can read the code I had a second look, and I'm afraid this doesn't scale very well. Next time someone is going to want to use some other option for useQuery or useMutation. And what if they're using some other graphql client (i.e. not Apollo Client) that might not even have `refetchQueries` as an option at all?

I think we need to try to come up with a more generic solution. Probably something that uses actual generics. I've previously done some exploration around the whole gql client situation, and in doing so I've tried writing better types for everything. I don't have anything that's complete yet. But in one of my crazy experiments where I wrote my own gql client I did come up with something that's at least more flexible than what we have today with the types. Have a look here if you want https://github.com/redwoodjs/redwood/pull/1535/files#diff-dc5df66f19077795660133684ca45c60b2651b16962fc9cd3635f52bf03c661bR55

If it sounds like too much work, don't worry. I'll get around to fixing this myself eventually. Probably as soon as I run in to this problem myself in my own app. But if you do want to spend the time on it, that would be awesome! 🙂 No pressure either way.

**Comment by noire-munich** [comment]
> Now that I can read the code I had a second look, and I'm afraid this doesn't scale very well. Next time someone is going to want to use some other option for useQuery or useMutation. And what if they're using some other graphql client (i.e. not Apollo Client) that might not even have refetchQueries as an option at all?

Agreed! Which is why I proposed to make `refetchQueries` optional, if we're on an Apollo client it will make sense - or keeping it as the default RW graphql client.

This being said your solution is more elegant. I'm rather short on time lately, I can't block any PR related to this.
I had a look at your branch though, I'll definitely be looking forward to see your updates on it. I've seen a couple of @todos, do you have any checklist?

**Comment by Tobbe** [comment]
> I'm rather short on time lately, I can't block any PR related to this.

No worries, someone else will get to it eventually :)  That PR I linked was an experiment as part of this bigger idea: https://github.com/redwoodjs/redwood/issues/1602 Your imput on that one is appreciated, if you have anything to add :)

**Comment by thedavidprice** [comment]
@dac09 ok for this one in v0.25?

**Comment by Tobbe** [comment]
I'm marking this as draft until @noire-munich, I or someone else implements a more generic solution than what's currently in this PR (see my previous comments for details)

**Comment by dac09** [comment]
Looks clear to me. Shouldn't conflict with prerender

**Comment by noire-munich** [comment]
> No worries, someone else will get to it eventually +1 That PR I linked was an experiment as part of this bigger idea: #1602 Your imput on that one is appreciated, if you have anything to add slightly_smiling_face

that's great, thanks :).
I'll put #1602 on my study radar then

**Comment by jtoar** [comment]
@noire-munich super sorry we lost track of this one! @dac09 will https://github.com/redwoodjs/redwood/pull/2485 handle this?

**Comment by dac09** [comment]
Implemented in #2485 - thanks for this @noire-munich !

**Pull request closed without merging**
