### PR TITLE
Added Github Templates

### PR DESCRIPTION
**Pull request by Burnsy**
### Pull Request

I have created the GitHub templates for;
- pull request
- bug report
- feature request
- question 

I want these to help organize the conversations that are happening on the redwood. Also, it makes it easier to find what people need. Potentially also will help with automatic tagging based upon the template selected. 

### Package Modified
- [ ] api
- [ ] auth
- [ ] cli
- [ ] core
- [ ] create-redwood-app
- [ ] dev-server
- [ ] eslint-config
- [ ] eslint-plugin-redwood
- [ ] internal
- [ ] router
- [ ] testing
- [ ] web
- [x] other

### Versioning
- [ ] Patch: Bug Fix
- [x] Minor: New Feature
- [ ] Major: Breaking Change

### Fixed Issues
N/A

### Test instructions
N/A

### CODE REVIEW

**Comment by Burnsy** [comment]
Should Templates use Emojis or Not? Example emojis in titles and Labels.

**Comment by cannikin** [comment]
We were just talking about PR templates yesterday at Jamstack Conf! Were you in on that discussion? If not then this is *amazing* timing. :)

I'll defer to @thedavidprice on the emoji question, he's the emoji person among us! I'm still trying to figure out what a Tiktok is.

**Comment by thedavidprice** [comment]
ha! Oh, @cannikin I only use emojis now because you showed me the keyboard shortcut. Also, rockets 🚀

@Burnsy huge thanks for taking initiative on this. You've prompted the core team to further discussion, which is great. But last we talked, we identified the current challenge not being organization/structure of Issues and PRs themselves, but of higher levels things like size, priority, expectations, etc. 

That said, I'm putting this on the agenda for our next meeting. We'll loop back after that!

**Comment by Burnsy** [comment]
every repo needs 🚀, ✨ and 🎉! 

I am happy that it got it pushed into the light and I understand that, there might be certain ways that some issues or feedback may want to be taken such as on the forms. 

I think if the case is that we want questions to be answered on the form we should still have a question template and explain that they should be posted on the forms using the code snippet that does not show. (as seen in the bug template explaining the commands to use to get versions.

**Comment by thedavidprice** [comment]
@mojombo looping you in here per conversation. Some notes on my end regarding the high-level process aspects that could improve processes, which might be better as documentation Vs. templates. As I mentioned, I think process is what we can/should improve currently more than organization -- goal being continued momentum but aligned direction.

- **Mega PRs are getting hard to digest:** we've had some 1000+ line commits. We've had 1 line commits. In general, if it's "less than 50 lines", just go for it. If it's more than that, start with an Issue including a plan (and goal) for review allowing us to potentially break into chunks. 
- **PRs should include:** 1) tests (add new if missing) and 2) updated docs -- or create a new Issue (and link) for next steps to be done in this regard. We're having a hard time catching up on both tests and docs -- definitely swimming upstream.
- **Summary of merged PR:** it's becoming more challenging to keep up with incoming and, specifically, reconciling the diff between what was originally proposed and the eventual implementation. This is a great example of [a super helpful summary](https://github.com/redwoodjs/redwood/pull/632#issue-425561978) -- it reminds me of the Team App and having a feed that’s a digest of updates. I think it's going to be increasingly important to have something equivalent as a practice for PRs. 
    - next steps should be a part of the summary -- getting harder to connect the dots as well as track down a paper trail

**Comment by kimadeline** [comment]
Templates are a great way to provide structure and lower the "context rebuilding" burden on the maintainers, but I also feel that—at least for PR templates—they should give an overview of what's going on without drowning the reviewers under too much info. I also agree that some of the info (for example the prereqs questions) should live as contributing or troubleshooting guidelines, as I find them easier to reference and point people towards.

🧇 _emoji_ 🐳 _interlude_ 🩹
 
👉  I have a couple of questions of varying relevance:
- Issue templates: Do we want to move the environment section up? 
- PR templates: Should the `Fixed issues` section merge with the short description? 
- Should each PR reference at least one open issue? Do we need a core contributor to have taken a look at the issue before accepting PRs (for prioritization/visibility/triage purposes)?
- More visual summaries of what the PR does or what the issue looks like? Screenshots, videos, gifs (tooting my own 🎺  here? dunno what you're talking about), you name it!

At the end of the day, what do the maintainers want to know and how do they want this summary to look like?

🌾 _the_ 🗿 _end_ 🎠

**Comment by thedavidprice** [comment]
Another good reference template was suggested in "Creating initial issue templates suggestions" #761

I closed as a duplicate, but you can see the suggested outlines here:
https://github.com/redwoodjs/redwood/pull/761/files

**Comment by jeliasson** [comment]
Add some emojis to these templates and they will spark 🔥 

Good work!

> @cannikin
> [...] I'm still trying to figure out what a Tiktok is.

This cracked me up.

**Comment by Burnsy** [comment]
We could put a call together sometimes next week, to talk about how we want to format them and to get these templates merged 🚀 @cannikin @thedavidprice @mojombo

**Comment by peterp** [comment]
@Burnsy Super sorry about the lack of response here.

I would love to see a template for pull-requests that's more conversational and instructional for the contributor who is opening the pull-request, something along the lines of:

"Hey! We love and appreciate that you're opening a pull-request for RedwoodJS.

Your pull-request is reviewed by real humans with lives outside of open-source, we would love to give you constructive feedback about the code you're trying to commit to this project, so here are some guidelines to make that easier for the both of us:

1. Try to keep the amount of changes below a certain number of lines. Pull-requests with 100's of lines of changes are difficult to review and will likely not get merged. If you're finding that difficult split up your PR into smaller ones that can be reviewed individually.
2. If your pull-request has a related open issue then please link to it, if it doesn't then it might be a good idea to open one first (whoops) so that the RedwoodJS team can figure out if it's something that we think should be fixed, included, or changed in RedwoodJS at this time.
3. Include visual summaries of what the PR does? Screenshots, videos, gifs (tooting my own 🎺 here? dunno what you're talking about), you name it! (Thanks @kimadeline )
"

@Burnsy Let me know how you feel about the approach above?

I would suggest that we remove the issue templates for now.

/cc @thedavidprice @jtoar

**Comment by thedavidprice** [comment]
100% this is the approach to take. I know Tom has wanted to review this in the past so I also suggest we loop him in once we have things for review. Some thoughts/suggestions:
- Good work emphasizing the "we ❤️ contributors" theme. I think people are looking for 1) their efforts are welcome and _then_ 2) how to do it. This hits both.
- We have really good Contributing docs. Should add links
- Examples are more helpful than text. E.g. linking to one of Kim-Adelines PRs for summary example would be great

**Comment by peterp** [comment]
Hey there @Burnsy, I get the feeling that this isn't the right time for this PR. We don't get a lot of bad pull-requests, so I'm going to close this off for now.

**Comment by Burnsy** [comment]
I agree Peter ☺️ don't worry!

**Pull request closed without merging**
