### PR TITLE
[CI] Try tuning docker

### PR DESCRIPTION
**Pull request by jtoar**
See https://github.com/redwoodjs/redwood/pull/4082#issuecomment-1009259175

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
I'm curious if you saw good results with this -- I'm trying to debug a similar issue.

**Comment by thedavidprice** [comment]
@jonjohnsonjr Honestly, it's hard to say. Things have been improving over time but we keep having to throw 💩 at the wall and see what sticks — zero visibility into workflows (without terrible manual iteration process) is rough going.

We did end up with 
```
      - name: Tune linux network
        run: sudo ethtool -K eth0 tx off rx off
```

'cause why not. 🤷‍♂️

If you're experiencing pain, we're right there with you. God speed.

**Comment by jtoar** [comment]
@jonjohnsonjr basically what @thedavidprice said, but I will add that I think for us it had next-to-no effect and I planned on removing it.

**Comment by jtoar** [comment]
For completeness, what ended up solving the problem was increasing the timeout of a very specific step.

**Comment by thedavidprice** [comment]
@jtoar when/where did we notice resolution in the Windows yarn install timeouts — was that basically a Yarn 3 solution?

**Comment by jtoar** [comment]
@thedavidprice upgrading to yarn 3 fixed the install timeouts for us yeah.

**Pull request closed without merging**
