### PR TITLE
Add a CI workflow file to create-redwood-app template

### PR DESCRIPTION
**Pull request by jtoar**
Closes https://github.com/redwoodjs/redwood/issues/2559. Also see discussion in https://github.com/redwoodjs/redwood/pull/2615. We have an action over in https://github.com/redwoodjs/project-ci-action. Let's ship it with redwood apps.

### CODE REVIEW

**Comment by thedavidprice** [comment]
To Do:

- [ ] add README instructions to the workflow
- [ ] improve Action to use GitHub Postgres
- [ ] make a decision about linter default

**Comment by jtoar** [comment]
We're not going to include this in CRWA till the action reaches `v1`.

**Comment by thedavidprice** [comment]
> We're not going to include this in CRWA till the action reaches v1.

Ha! No way. I meant wait until we publish the 1.0.0 for the GH Action https://github.com/redwoodjs/project-ci-action

Sorry about the confusion! 😂

**Comment by jtoar** [comment]
@thedavidprice I may need some more clarification on this; I think we said the same thing? 😅

**Comment by jtoar** [comment]
This action is used in deploy target CI but would need more work before being included in CRWA. Closing for now since we're trying to clean up stale PRs. I'm updating deploy target CI now. I may be able to update the action at the same time. But till that happens, let's just make room for a new PR when it's more likely to be merged.

**Pull request closed without merging**
