### PR TITLE
Use actions/cache for Windows runner and E2E

### PR DESCRIPTION
**Pull request by thedavidprice**
- uses actions/cache for Windows. Tested here #2835  and is now invalidating correctly!
- ~~switch back to Ubuntu for E2E~~ Won't complete on Ubuntu; sticking with MacOS
    - cache is not hitting on MacOS; framework yarn install > 6 min
- uses actions/cache for E2E (note: installation occurs 2x; this only applies to the initial yarn install)
- lots of tweaks to E2E: simplify logger test, turn off recording

**Current Workarounds:**
- turned off Cypress video and recording
- Not running E2E Tutorial "Routing Params" and "Forms"
- Only running Storybook build step because others rely on Routing Params and Forms
- I'm using the new Cypress "start" config to run `yarn rw dev`: api and web logs now output with run — mixed about this
- Splitting into two Cypress runs with CLI in the second run (without the dev server running)

Future TO DO:
- We need to try switching to CircleCI for more horsepower. This is infuriating.
- Run Cypress tests in parallel, which might require restructuring tests and code mods. See @dac09 idea here https://github.com/redwoodjs/redwood/pull/2842/files

### CODE REVIEW

**Comment by thedavidprice** [comment]
Wowza, we can parallelize Cypress: https://andreybleme.com/2020-03-27/boost-your-cypress-tests/

However, two of our tests (Storybook and CLI) rely on the code mods from the first test, so they'll fail. But now I'm motivated...

**Comment by thedavidprice** [comment]
**Initial Run**
There will not be a cache. Expecting normally long runtimes
- Ubuntu lint/build/test: 5m
- Windows lint/build/test: 13m
- E2E: never stopped... network schmetwork

**Cached**
- Ubuntu lint/build/test: 4m
- Windows lint/build/test: 7m
- Completed e2e: 4m (Logger passed), 3m (Storybook failed), > 10m other two

**Comment by Tobbe** [comment]
I appreciate all the love you're giving the Windows issue David!

**Comment by thedavidprice** [comment]
@Tobbe you bet! It's Cypress that currently gets no love from me 😡

**Comment by thedavidprice** [comment]
Moved actionable items to #2845

**Comment by thedavidprice** [comment]
https://andreybleme.com/2020-03-27/boost-your-cypress-tests/

**Pull request closed without merging**
