### PR TITLE
Update baremetal.js

### PR DESCRIPTION
**Pull request by sglyon**
For some reason on my machine the git clone action was happening in the server's home directory and not in the config path. This fixed the issue for me.

### CODE REVIEW

**Comment by jtoar** [comment]
Tagging @cannikin—when you get a chance, thanks!

**Comment by cannikin** [comment]
Hmm, I deploy everything with baremetal and have never run into this issue...can you share your `deploy.toml`? What were the paths it was trying to deploy on? Did it try to deploy to `~` for you?

**Comment by sglyon** [comment]
Sure, here is deploy.toml

```
❯ cat deploy.toml
# This file contains config for a baremetal deployment
#
# SSH connection options include:
#
# * host - the remote server hostname/IP
# * port - defaults to 22
# * username - required, the user you're connecting as
# * password - only set if you're not using key-based authentication
# * privateKey - a Buffer containing the private key (use this _or_ 'privateKeyPath', not both)
# * privateKeyPath - local file path to a private key that will be sent with the connection request
# * passphrase - used if your private key has a passphrase
# * agentForward - set to `true` to forward the client machine's ssh credentials
#
# See https://redwoodjs.com/docs/deploy/baremetal for more info

[[production.servers]]
host = "app.jupyteach.com"
username = "sglyon"
port = 22042
agentForward = true
sides = ["api","web"]
packageManagerCommand = "/home/sglyon/.nvm/versions/node/v18.15.0/bin/yarn"
monitorCommand = "pm2"
path = "/home/sglyon/hosting/jupyteach-rw-deployed"
processNames = ["serve", "faktory"]
repo = "git@github.com:sglyon/jupyteach-rw.git"
branch = "main"
keepReleases = 5
```

**Comment by sglyon** [comment]
Sure, here is deploy.toml

```
❯ cat deploy.toml
# This file contains config for a baremetal deployment
#
# SSH connection options include:
#
# * host - the remote server hostname/IP
# * port - defaults to 22
# * username - required, the user you're connecting as
# * password - only set if you're not using key-based authentication
# * privateKey - a Buffer containing the private key (use this _or_ 'privateKeyPath', not both)
# * privateKeyPath - local file path to a private key that will be sent with the connection request
# * passphrase - used if your private key has a passphrase
# * agentForward - set to `true` to forward the client machine's ssh credentials
#
# See https://redwoodjs.com/docs/deploy/baremetal for more info

[[production.servers]]
host = "app.jupyteach.com"
username = "sglyon"
port = 22042
agentForward = true
sides = ["api","web"]
packageManagerCommand = "/home/sglyon/.nvm/versions/node/v18.15.0/bin/yarn"
monitorCommand = "pm2"
path = "/home/sglyon/hosting/jupyteach-rw-deployed"
processNames = ["serve", "faktory"]
repo = "git@github.com:sglyon/jupyteach-rw.git"
branch = "main"
keepReleases = 5
```

**Comment by sglyon** [comment]
Sure, here is deploy.toml

```
❯ cat deploy.toml
# This file contains config for a baremetal deployment
#
# SSH connection options include:
#
# * host - the remote server hostname/IP
# * port - defaults to 22
# * username - required, the user you're connecting as
# * password - only set if you're not using key-based authentication
# * privateKey - a Buffer containing the private key (use this _or_ 'privateKeyPath', not both)
# * privateKeyPath - local file path to a private key that will be sent with the connection request
# * passphrase - used if your private key has a passphrase
# * agentForward - set to `true` to forward the client machine's ssh credentials
#
# See https://redwoodjs.com/docs/deploy/baremetal for more info

[[production.servers]]
host = "app.jupyteach.com"
username = "sglyon"
port = 22042
agentForward = true
sides = ["api","web"]
packageManagerCommand = "/home/sglyon/.nvm/versions/node/v18.15.0/bin/yarn"
monitorCommand = "pm2"
path = "/home/sglyon/hosting/jupyteach-rw-deployed"
processNames = ["serve", "faktory"]
repo = "git@github.com:sglyon/jupyteach-rw.git"
branch = "main"
keepReleases = 5
```

**Comment by sglyon** [comment]
Sure, here is deploy.toml

```
❯ cat deploy.toml
# This file contains config for a baremetal deployment
#
# SSH connection options include:
#
# * host - the remote server hostname/IP
# * port - defaults to 22
# * username - required, the user you're connecting as
# * password - only set if you're not using key-based authentication
# * privateKey - a Buffer containing the private key (use this _or_ 'privateKeyPath', not both)
# * privateKeyPath - local file path to a private key that will be sent with the connection request
# * passphrase - used if your private key has a passphrase
# * agentForward - set to `true` to forward the client machine's ssh credentials
#
# See https://redwoodjs.com/docs/deploy/baremetal for more info

[[production.servers]]
host = "app.jupyteach.com"
username = "sglyon"
port = 22042
agentForward = true
sides = ["api","web"]
packageManagerCommand = "/home/sglyon/.nvm/versions/node/v18.15.0/bin/yarn"
monitorCommand = "pm2"
path = "/home/sglyon/hosting/jupyteach-rw-deployed"
processNames = ["serve", "faktory"]
repo = "git@github.com:sglyon/jupyteach-rw.git"
branch = "main"
keepReleases = 5
```

**Comment by cannikin** [comment]
Okay, back from vacation!

So your app is being deployed to `/home/sglyon` instead of `/home/sglyon/hosting/jupyteach-rw-deployed` as defined in the `deploy.toml` file? Maybe because you're using an absolute path to `yarn` instead of just plain `yarn`, which is what I've always done!

Do you have this actual code change in your copy of Redwood and everything deploys correctly with it?

**Comment by jtoar** [comment]
Hey @sglyon, gentle nudge: this one still relevant to you?

**Comment by jtoar** [comment]
Closing for now but happy to reopen if you're still interested

**Comment by sglyon** [comment]
Hey sorry for being MIA there -- I did have to make this change when deploying to bare metal. It didn't work before, but did work with this patch.

I ended up switching to fly for deployment so this is not currently relevant to me.

Thanks!

**Pull request closed without merging**
