### PR TITLE
[Tutorial] Chapter 2: Wrap rendered `<article>` in React fragments

### LINKED ISSUE #5008: [Tutorial w/TypeScript] Warning: 'ArticlesCell' return type 'Element[]' not a valid JSX element.
Working through the tutorial in TypeScript mode, VSCode complains about the `ArticlesCell` return type:

grafik

Interestingly, the warning doesn't appear while the `Success` function still returns the Articles wrapped in `<ul>`, it only starts appearing when we change them to render as individual `<article>`s as advised at the end of https://redwoodjs.com/docs/tutorial/chapter2/cells#our-first-cell

However, wrapping `<ArticlesCell />` in a fragment or a div in `Homepage.tsx` does not make the warning go away.

Compilation succeeds nevertheless so it's possible to continue the tutorial, but still it would be nice to know which type to annotate the cell with so this warning goes away.

Reporting this non-critical finding here [as advised](https://github.com/redwoodjs/redwood/issues/234#issuecomment-1086800949).

### PR DESCRIPTION
**Pull request by Philzen**
This avoids warning `'ArticlesCell' cannot be used as a JSX component.
Its return type 'Element[]' is not a valid JSX element.`.

Closes #5008

### CODE REVIEW

**Comment by cannikin** [comment]
Thanks! Are there any further instances of these same code snippets further on, or are these the only three?

**Comment by Philzen** [comment]
> Are there any further instances of these same code snippets further on, or are these the only three?

@cannikin at least as far as i could see – i searched through the tutorial until chapter 5 where the wrapper is different (and valid) already b/c of the tailwind redesign introduced during the "intermission" chapter.

**Comment by cannikin** [comment]
Great, thanks!

**Comment by cannikin** [comment]
Great, thanks!

**Pull request merged**
