### PR TITLE
Added styling import after running scaffold.

### PR DESCRIPTION
**Pull request by llmaboi**
No mention to including the styling was in the readme.  Don't know if it was because something was missed on generation of a "scaffold" or if it needs to manually happen.

### CODE REVIEW

**Comment by Tobbe** [comment]
@llmaboi This is really strange. I just created a new RW app and added a scaffold, and for me scaffold.css was automatically added to App.js

**Comment by llmaboi** [comment]
That is bizarre. I can try this again and will respond with an update.  I assumed that would be the behavior, which is why I mention that in the initial comment.

**Comment by llmaboi** [comment]
@Tobbe  Still no luck on my end. Maybe it is something to do with my environment? I'm using VSCode and nvm with yarn.
I don't normally use `yarn` but is it normal for it to open a ton of command prompts and take me away from my current terminal when running commands?

```bash
yarn rw g scaffold post
  √ Generating scaffold files...
    √ Successfully wrote file `./web\src\components\Post\EditPostCell\EditPostCell.tsx`
    √ Successfully wrote file `./web\src\components\Post\Post\Post.tsx`
    √ Successfully wrote file `./web\src\components\Post\PostCell\PostCell.tsx`
    √ Successfully wrote file `./web\src\components\Post\PostForm\PostForm.tsx`
    √ Successfully wrote file `./web\src\components\Post\Posts\Posts.tsx`
    √ Successfully wrote file `./web\src\components\Post\PostsCell\PostsCell.tsx`
    √ Successfully wrote file `./web\src\components\Post\NewPost\NewPost.tsx`
    √ Successfully wrote file `./api\src\graphql\posts.sdl.ts`
    √ Successfully wrote file `./api\src\services\posts\posts.ts`
    √ Successfully wrote file `./api\src\services\posts\posts.scenarios.ts`
  √ Generating scaffold files...
    √ Successfully wrote file `./web\src\components\Post\EditPostCell\EditPostCell.tsx`
    √ Successfully wrote file `./web\src\components\Post\Post\Post.tsx`
    √ Successfully wrote file `./web\src\components\Post\PostCell\PostCell.tsx`
    √ Successfully wrote file `./web\src\components\Post\PostForm\PostForm.tsx`
    √ Successfully wrote file `./web\src\components\Post\Posts\Posts.tsx`
    √ Successfully wrote file `./web\src\components\Post\PostsCell\PostsCell.tsx`
    √ Successfully wrote file `./web\src\components\Post\NewPost\NewPost.tsx`
    √ Successfully wrote file `./api\src\graphql\posts.sdl.ts`
    √ Successfully wrote file `./api\src\services\posts\posts.ts`
    √ Successfully wrote file `./api\src\services\posts\posts.scenarios.ts`
  √ Generating scaffold files...
    √ Successfully wrote file `./web\src\components\Post\EditPostCell\EditPostCell.tsx`
    √ Successfully wrote file `./web\src\components\Post\Post\Post.tsx`
    √ Successfully wrote file `./web\src\components\Post\PostCell\PostCell.tsx`
    √ Successfully wrote file `./web\src\components\Post\PostForm\PostForm.tsx`
    √ Successfully wrote file `./web\src\components\Post\Posts\Posts.tsx`
    √ Successfully wrote file `./web\src\components\Post\PostsCell\PostsCell.tsx`
    √ Successfully wrote file `./web\src\components\Post\NewPost\NewPost.tsx`
    √ Successfully wrote file `./api\src\graphql\posts.sdl.ts`
    √ Successfully wrote file `./api\src\services\posts\posts.ts`
    √ Successfully wrote file `./api\src\services\posts\posts.scenarios.ts`
    √ Successfully wrote file `./api\src\services\posts\posts.test.ts`
    √ Successfully wrote file `./web\src\scaffold.css`
    √ Successfully wrote file `./web\src\layouts\PostsLayout\PostsLayout.tsx`
    √ Successfully wrote file `./web\src\pages\Post\EditPostPage\EditPostPage.tsx`
    √ Successfully wrote file `./web\src\pages\Post\PostPage\PostPage.tsx`
    √ Successfully wrote file `./web\src\pages\Post\PostsPage\PostsPage.tsx`
    √ Successfully wrote file `./web\src\pages\Post\NewPostPage\NewPostPage.tsx`
  √ Adding layout import...
  √ Adding set import...
  √ Adding scaffold routes...
  √ Adding scaffold asset imports...
  √ Generating types ...
```
```tsx
/// web/src/App.tsx
import { FatalErrorBoundary, RedwoodProvider } from '@redwoodjs/web';
import { RedwoodApolloProvider } from '@redwoodjs/web/apollo';

import FatalErrorPage from 'src/pages/FatalErrorPage';
import Routes from 'src/Routes';

import './index.css';

const App = () => (
  <FatalErrorBoundary page={FatalErrorPage}>
    <RedwoodProvider titleTemplate="%PageTitle | %AppTitle">
      <RedwoodApolloProvider>
        <Routes />
      </RedwoodApolloProvider>
    </RedwoodProvider>
  </FatalErrorBoundary>
);

export default App;
```

**Comment by Tobbe** [comment]
@llmaboi I wonder if this is a Windows issue

What's the output of `yarn rw info` for you?

**Comment by llmaboi** [comment]
@Tobbe 
```bash
yarn rw info

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.0.0 - ~\AppData\Local\Temp\xfs-618ca917\node.CMD
    Yarn: 3.2.0 - ~\AppData\Local\Temp\xfs-618ca917\yarn.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.50)
  npmPackages:
    @redwoodjs/core: 1.1.0 => 1.1.0
```

**Comment by Tobbe** [comment]
@llmaboi Thanks for the info, and sorry this isn't working for you. I'll see if I can reproduce on a Windows computer later today

**Comment by llmaboi** [comment]
@Tobbe Not a problem, just wanted to make the maintainers aware of this issue.

**Comment by Tobbe** [comment]
Sorry it took a bit longer than I hoped, but I just now tried on a Windows computer as well

```
$ yarn rw info

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\Temp\xfs-61841d93\node.CMD
    Yarn: 3.2.0 - ~\AppData\Local\Temp\xfs-61841d93\yarn.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.50)
  npmPackages:
    @redwoodjs/core: 1.1.1 => 1.1.1
```

And it seems to work just fine for me.
    
image

I'm sorry, but I'm not really sure how to debug this any further without a way to reproduce the issue :(

**Pull request closed without merging**
