### PR TITLE
WIP: Create new @redwoodjs/realtime package for Subscriptions and Live Queries

### PR DESCRIPTION
**Pull request by dthyresson**
New package needed to resolve peer dependency issues when deploying graphql-server to Netlify and Vercel.

### CODE REVIEW

**Comment by jtoar** [comment]
@dthyresson I think I'm going to redo this one; I'm not sure which branch we started from, so hard to tell what I'm supposed to keep/discard from resolving merge conflicts

**Comment by dthyresson** [comment]
Ok sorry about that. I’ll take it back once the plug-in is in the package

**Comment by dthyresson** [comment]
Woah yeah from that file list it has way more changes than needed

**Comment by jtoar** [comment]
Closing in favor of https://github.com/redwoodjs/redwood/pull/8878.

**Pull request closed without merging**
