### PR TITLE
fix: Moves `fastify.addContentTypeParser(...)` above `configureFastify(...)`

### PR DESCRIPTION
**Pull request by CeleroChris**
Hi Redwood :wave:

My name is Chris and I'm a software engineer with Celero Commerce.  My team and I are working on an application that uses Redwood running on Azure.

Recently, we wanted more control over the Fastify instance that Redwood uses, but ran into issues when trying to add our `ContentTypeParser` for `multipart/form-data`.  

While Redwood allows for custom configuration of Fastify through `configureFastify` in `server.config.js`, the `ContentTypeParser` for `multipart/form-data` and `application/x-www-form-urlencoded` is added _after_ `configureFastify(...)` is called.

When I try to add our `ContentTypeParser` for `multipart/form-data`:
```js
// inside server.config.js
/** @type {import('@redwoodjs/api-server/dist/fastify').FastifySideConfigFn} */
const configureFastify = async (fastify, options) => {
  if (options.side === 'api') {
    fastify.log.info({ custom: { options } }, 'Configuring api side')
    
    fastify.removeContentTypeParser(['multipart/form-data'])
    
    fastify.addContentTypeParser(
      'multipart/form-data',
      (req, payload, done) => {
        payload.on('end', () => {
          done()
        })
      }
    )
  }
}
```

I encounter this error from Fastify:
```sh
FastifyError [Error]: Content type parser 'multipart/form-data' already present.
```

In this PR, I suggest moving `fastify.addContentTypeParser(...)` _above_ `configureFastify(...)`.  

With this change, we would have (nearly) complete access to Fastify which I believe was the goal when `configureFastify` was added back in July (https://github.com/redwoodjs/redwood/pull/5903).

When you have the opportunity, please give this a look over.  

Thank you for your time and thank you for Redwood!

### CODE REVIEW

**Review by jtoar — COMMENTED** [review]
Hey @CeleroChris, thanks for the contribution, and makes sense to me. @dthyresson you're more familiar with fastify than me—anything I might be missing?

**Comment by dthyresson** [comment]
Hi @CeleroChris thanks for the PR an appreciate the patience over the holidays for the slow response on my part.

Your change make sense, but I wonder if

https://www.fastify.io/docs/latest/Reference/ContentTypeParser/#hascontenttypeparser

a `hasContentTypeParser` check might be worth adding in `configureFastify` or not? To see if that content parser has been custom added or not?

Maybe it's best as you have done to always add it beforehand?

**Review by dthyresson — CHANGES_REQUESTED** [review]
Thoughts on adding 
[fastify.io/docs/latest/Reference/ContentTypeParser/#hascontenttypeparser](https://www.fastify.io/docs/latest/Reference/ContentTypeParser/#hascontenttypeparser)

a hasContentTypeParser check might be worth adding in configureFastify or not? To see if that content parser has been custom added or not?

**Comment by CeleroChris** [comment]
Hi @dthyresson

Thanks for getting back and I hope you all had a wonderful holiday!

I actually tried using `hasContentTypeParser()` in `configureFastify()`, but I kept running into a collision error.  

Fastify does not allow overlapping `ContentTypeParser`s and will throw an error if two `ContentTypeParser`s are defined for the same type (they will not clobber):

```sh
api | FastifyError [Error]: Content type parser 'multipart/form-data' already present.
api |     at ContentTypeParser.add (/Users/chrisdavis/dev/celero-northstar/core/node_modules/fastify/lib/contentTypeParser.js:51:11)
api |     at /Users/chrisdavis/dev/celero-northstar/core/node_modules/fastify/lib/contentTypeParser.js:327:60
api |     at Array.forEach (<anonymous>)
api |     at Object.addContentTypeParser (/Users/chrisdavis/dev/celero-northstar/core/node_modules/fastify/lib/contentTypeParser.js:327:17)
api |     at withFunctions (/Users/chrisdavis/dev/celero-northstar/core/node_modules/@redwoodjs/api-server/dist/plugins/withFunctions.js:34:11)
api |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
api |     at async apiServerHandler (/Users/chrisdavis/dev/celero-northstar/core/node_modules/@redwoodjs/api-server/dist/cliHandlers.js:82:13) {
api |   code: 'FST_ERR_CTP_ALREADY_PRESENT',
api |   statusCode: 500
api | }
```

As the code stands now, if I call `hasContentTypeParser('multipart/form-data')` in `configureFastify()`, the result will be `false` because lines 30-34 have not been called _yet_ in `withFunctions.js`:
https://github.com/redwoodjs/redwood/blob/99fce77e01198cddd1fcea83453f25562952e280/packages/api-server/src/plugins/withFunctions.ts#L30-L34

The following code will run successfully in `configureFastify()`:
```js
if (fastify.hasContentTypeParser('multipart/form-data') === false) {
  fastify.addContentTypeParser('multipart/form-data', ...)
}
```

But, I will encounter an error when lines 30-34 are eventually called.  

The `addContentTypeParser(...)` in `withFunctions.ts` is colliding with the `addContentTypeParser(...)` in `configureFastify()` (not the other way around).

It also means I cannot use `removeContentTypeParser(...)` or `removeAllContentTypeParsers()` in `configureFastify()` because the `ContentTypeParser` does not exist _yet_.

I hope this helps understand the change I'm requesting.

**Comment by dthyresson** [comment]
@CeleroChris Appreciate this detailed response and trust that you’ve given it lots of thoughtful consideration.

Approved and merging.

**Review by dthyresson — APPROVED** [review]
Approved

**Pull request merged**
