### PR TITLE
Fixes generating scenarios for relations where the field name is different than the relation name

### LINKED ISSUE #1649: Service / SDL generation is broken when using relations
I'm noticing when you have a relation column that has a different name then the Table it is referring to you get an error like this:
```
  ✖ Generating SDL files...
    → No schema definition found for `Author` in schema.prisma file
No schema definition found for `Author` in schema.prisma file
```

This happens when you for example have two tables, Post and User, and you name the user relation different on Post like this:

```
model Post {
  id       Int    @id @default(autoincrement())
  title    String
  author   User   @relation(fields: [authorId], references: [id])
  authorId Int
}

model User {
  id    Int    @id @default(autoincrement())
  posts Post[]
}
```

To make it easier to reproduce you can use this repo/branch: https://github.com/jvanbaarsen/rw-examples

It happens when you run: `yarn rw g sdl post`

### PR DESCRIPTION
**Pull request by cannikin**
Closes #1649

### CODE REVIEW

**Comment by cannikin** [comment]
@thedavidprice assuming the checks pass, this should be good!

@brentjanderson did you want to try this out? You can install this PR version of Redwood with `yarn rw upgrade --pr 1848:0.25.1-fbf4a83`

**Comment by brentjanderson** [comment]
Worked for me on that test repo. :shipit:

**Comment by thedavidprice** [comment]
🚀

**Comment by jvanbaarsen** [comment]
🎉 Thanks :)

**Pull request merged**
