### PR TITLE
Fixed input border issue 

### PR DESCRIPTION
**Pull request by SarveshLimaye**
#3579 

@cannikin I tried with different red color but it was not looking good, so I have added a soft red glow. Could you pls review my pr.

 
image

### CODE REVIEW

**Comment by SarveshLimaye** [comment]
@cannikin I am getting error after running command  yarn test -u

image

**Comment by cannikin** [comment]
Hmm, you’ve already run `yarn install` in there, correct?

**Comment by SarveshLimaye** [comment]
@cannikin Yes. Should I run yarn framework install

**Comment by cannikin** [comment]
Hmm, I didn’t think that was a command. I tried just opening the PR in Gitpod (fully self-contained VS Code instance in the browser, preloaded with Redwood) and the tests ran. You can the same thing, in the Checks section blow, click on “Details” next to the Gitpod row. Once that boots up you should be able to start a new terminal window, `cd redwood` and then `yarn test -u`. Let me know if that works!

**Comment by SarveshLimaye** [comment]
@cannikin it worked thanks a lot!

**Comment by cannikin** [comment]
Looks great! Thanks so much for this fix, it's the details like this that really give Redwood the polish that people love. We're looking forward to your next PR! 😀

**Pull request merged**
