### PR TITLE
Remove unused QUERY variable generated through scaffolding

### PR DESCRIPTION
**Pull request by leighhalliday**
After generating scaffolding I noticed that there is an unused variable `QUERY` in the `NewName.js` template. Was this on purpose?

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks for this @leighhalliday Looping in the MasterOfGenerators @cannikin ⚔️

**Comment by ajcwebdev** [comment]
Does this mean there's a [Redwood series in the works](https://www.youtube.com/channel/UCWPY8W-FAZ2HdDiJp2RC_sQ)? 🧐

**Comment by cannikin** [comment]
Whoops! I think we used to explicitly refetch or something in there, but we updated the default cache strategy and it's handled automatically now.

There may be a test or two that verifies the content of this generated file, which is probably why the test step is failing!

**Review by cannikin — APPROVED** [review]
Approved, assuming the tests get fixed!

**Comment by thedavidprice** [comment]
@leighhalliday do you need any help here with the failing tests?

**Comment by dac09** [comment]
Hey @leighhalliday just following up on this! Looks like only thing missing updating the tests. It's now much easier to update the tests for this, just update the snapshot :):

```
yarn test -u
```
Which should update the snapshot for you :)

**Comment by thedavidprice** [comment]
- updated from `main`
- updated test snapshots via `yarn test -u`

**Pull request merged**
