### PR TITLE
Add build:test-project to CI along with additional commands

### PR DESCRIPTION
**Pull request by thedavidprice**
The idea here is to round out my release QA process in CI:
- build and test the build:test-project with every PR
- use the build project to test CLI commands not yet included in CI

ToDo:
- [ ] Matrix run on Linux and Windows; Node.js v14 and v16
- [ ] include _all_ commands from E2E + QA commands
- [ ] Possibly use Playwright to manage yarn rw dev and yarn rw serve
- [ ] add necesary options to `yarn build:test-project`

### CODE REVIEW

**Comment by jtoar** [comment]
@thedavidprice If `yarn build:test-project` was failing for you, there's a fix for it in my PR here: https://github.com/redwoodjs/redwood/pull/3908/commits/d9a0c706e9ae5af2295ca9fcd21d7a983a0c8aa6

**Comment by dac09** [comment]
@thedavidprice once you do this, maybe we can simply the test project creation so that we just copy files across rather than use jscodeshift or run generate commands?

**Comment by thedavidprice** [comment]
@dac09 OH, this just gave me an idea... will work on it within this PR and show you that way.

🤞

**Comment by thedavidprice** [comment]
replaced by #4495

**Pull request closed without merging**
