### PR TITLE
Updates baremetal setup post-install doc link

### PR DESCRIPTION
**Pull request by cannikin**
The deploy docs are broken out into their own pages now, so I had to update this link!

### CODE REVIEW

**Review by thedavidprice — APPROVED** [review]

**Comment by thedavidprice** [comment]
Adding to the list for Patch release. Thanks!

**Comment by cannikin** [comment]
Were you able to test it? Did you count on deploy-target-ci or did you do it manually?

**Comment by thedavidprice** [comment]
This one's just the docs

**Comment by cannikin** [comment]
OH YEAH

**Comment by thedavidprice** [comment]
PR'S

EVERYWHERE

**Pull request merged**
