### PR TITLE
Fix - No delete command for directives

### PR DESCRIPTION
**Pull request by MJ1992**
@jtoar 
Fix for - "No delete command for directives"  #5191 

Added File  for destroy directive command- `yarn rw d  directive <name> <type>`
Added Test for destroy directive command

### CODE REVIEW

**Comment by jtoar** [comment]
@MJ1992 thanks for the quick turnaround! The implementation works as is, but there's one thing that we could improve on. It requires a user to specify the directive's `type`:

```
gitpod /workspace/rw-test-app $ yarn rw d directive uppercase
rw d directive <name> <type>

Destroy a Directive

Positionals:
  name  Name of the Directive                                [string] [required]
  type  Type of the Directive                                [string] [required]

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --cwd      Working directory to use (where `redwood.toml` is located.)

Not enough non-option arguments: got 1, need at least 2
```

But it doesn't seem like the directive's `type` is really necessary. Even if a user generates a `transformer` directive, passing `validator` also destroys it.

Also, for consistency, do you think we could copy the way the other destroy commands (like the [component destroy command](https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/destroy/component/component.js)) are written by using `createYargsForComponentDestroy`?

<blockquote>
<details>
<summary>
Spoiler: I didn't want to suggest something that wouldn't work, so I made sure it would first. So here's the implementation I'd like to see. Feel free to just copy paste this, or solve it first without looking for a challenge!
</summary>
<br />

```js
import { files as directiveFiles } from '../../generate/directive/directive'
import { createYargsForComponentDestroy } from '../helpers'

export const description = 'Destroy a directive'

export const { command, builder, handler, tasks } =
  createYargsForComponentDestroy({
    componentName: 'directive',
    // The value of `type` doesn't matter so we just pass it one of the valid types
    filesFn: (args) => directiveFiles({ ...args, type: 'validator' }),
  })
``` 
</details>
</blockquote>

**Comment by MJ1992** [comment]
@jtoar PR updated. 
I realised while implementing that `type` is not necessary  but didn't want to update the files fn or hard code.So I added custom function.
Thanks for the suggestion.

**Review by jtoar — APPROVED** [review]
> I realised while implementing that type is not necessary but didn't want to update the files fn or hard code.So I added custom function.

Ah totally understood. I think hardcoding's ok here since the type doesn't affect the filepath at all, but if it turns out it's not ok somehow later, it's on me! Thanks for contributing @MJ1992, this looks good to go 🚀

**Comment by thedavidprice** [comment]
@jtoar this one needs an update to the CLI Doc, correct?
https://redwoodjs.com/docs/cli-commands#destroy-alias-d

**Comment by jtoar** [comment]
Yes; totally forgot. @MJ1992 no pressure, but would you be updating the docs? Happy to do it if not!

**Comment by MJ1992** [comment]
@jtoar Done. PR #5236

**Pull request merged**
