### PR TITLE
Remove dev-server, and use api-server instead

### PR DESCRIPTION
**Pull request by dac09**
### What does it do?
- Removes dev-server package
- Uses api-server during dev, for both babel and esbuild builds
- Changes build and dev commands, so that babel and esbuild ways of building are "standardized"

- 🆕 hot reload mode for api server, which just reloads the "lambdas" when a change is detected, rather than restart the whole server. This is currently not being used in the dev server, unless you the env var `HOTRELOAD_API`

### CODE REVIEW

**Comment by dac09** [comment]
@peterp should we use this opportunity to rename `api-server` to something else?

I also wanted to change the names of the binaries `rw-api-esbuild` and `rw-api-babel` aren't the best are they - what do you think?

**Comment by dac09** [comment]
Thanks @peterp - all good. From observation, you're totally right that transpiling is the most expensive, but restarting the node process does cost approx 1000ms on my machine. Ideally we'd use incremental builds on babel, but looks like incremental builds are only supported in watch mode. https://github.com/babel/babel/pull/8877

I think its more important that the api-server behaves consistently between babel/esbuild builds, which is my primary goal in this PR - so I'll take out the hotreloading behaviour if its causing issues. It  seems to stall our cypress e2e tests (too many watchers?)

The other reason I need transpiling first, is because this is step 1 in supporting functions in folders with scenarios and tests.

**Comment by peterp** [comment]
Hmpf... It takes 10s to start the api-server? That doesn't seem right to me. I wish we had some measurements so we could be sure we're not making things worse.

**Comment by peterp** [comment]
fwiw I'm working on the pre-transpilation step for the web-side, and there are lots of interesting findings in this approach. I'm looking forward to share it soon :)

**Comment by peterp** [comment]
I've been thinking about this a bit. Here's an approach that I would like to recommend:

1. Make the api-server long running with pm2 or nodemon.
2. Create a "watcher" for the api files in `packages/internal/src/build/api.ts`
3. Transpile the files in `watcher` and use `kill-port` or some kind of PID file to restart the `api-server`
4. Make sure `api-server` deals with SIGTERM appropriately by closing the connections.

**Comment by peterp** [comment]
> I also wanted to change the names of the binaries rw-api-esbuild and rw-api-babel aren't the best are they - what do you think?

I just used that for testing - I think it's ok to delete those bins and just use them programmatically in the CLI

**Comment by dac09** [comment]
@peterp 

Finally got the tests to start passing! It turns out reloading the server can be a real pain, compared to the old "just wait for babel to finish its job" - the advantage there was that the server would just delay the request till babel recompiled in memory, in this case we have to introduce a wait (https://github.com/redwoodjs/redwood/pull/2887/files#diff-30fefa2f8c816ba77f01b70abcf03a2eb8d6eeac0427bf1d4e412b2e114c08a1R120). 

> I've been thinking about this a bit. Here's an approach that I would like to recommend:

I think our main problem is that babel doesn't really do incremental builds, see the new debounced rebuild and restart call (https://github.com/redwoodjs/redwood/pull/2887/files#diff-e94c312ef6626c18e8d25469d161aa147d02b4b537dea909b78c9fc6490432fdR119) - not sure if we can achieve the same with nodemon - that introduces a lot of unnecessary rebuilds, the debounce helps a bit. 

Last remaining issue - prerender is now failing, and I don't have a clue why. Notice I haven't touched anything in babel config or prerender. The error comes from our route loader plugin

```shell

var AboutPage = {
    ^

SyntaxError: Identifier 'AboutPage' has already been declared
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
```

Please help :)!!

**Comment by dac09** [comment]
I have a theory - because we're now using babel to do the build, it populated the babel cache and when it tries to prerender, it uses the cached version and tries to modify it.

**Comment by peterp** [comment]
@dac09 Can I commit to this branch?

**Comment by dac09** [comment]
Closing in favour of a shared branch

**Pull request closed without merging**
