### PR TITLE
remove deprecated ESBuild as a Web build option

### LINKED ISSUE #3506: ESBuild has been deprecated as a Web build option: needs to be removed from config and docs
When the API build was updated to be a two-step transpire, using ESBuild for the second step, the option to use `--esbuild` for Web was removed. If someone trying to add the option to build or dev, the commands will now fail.

TO DO:
- [ ] remove `--esbuild` option and related code related to redwood.toml (I believe it's completely removed from CLI)
- [ ] update CLI and redwood.toml docs to remove info about using --esbuild

### PR DESCRIPTION
**Pull request by 7shantanu7**
closes #3506 

@thedavidprice as you mentioned, I didn't touched ESBuild files for the API build process.

### CODE REVIEW

**Comment by Tobbe** [comment]
This looks great @7shantanu7! If you want you can get started on the doc updates needed as well. Let me know if you don't want to do the docs and I'll get someone else to take a look at that 🙂

**Comment by 7shantanu7** [comment]
@Tobbe I'll update the doc 👍

**Comment by thedavidprice** [comment]
Thank you @7shantanu7! Please do let me know if you create a PR to update the docs on https://github.com/redwoodjs/redwoodjs.com Otherwise it's on my list.

**Comment by 7shantanu7** [comment]
@thedavidprice redwoodjs/redwoodjs.com#827 👀

**Pull request merged**
