### PR TITLE
Router: <Route redirect="">

### PR DESCRIPTION
**Pull request by Tobbe**
Fix support for writing redirects straight in the router. The syntax is `<Route path="/old/path" redirect="/new/path" />`

The existing code caused warnings like these

```
    console.error
      Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
          in RouterImpl (created by LocationProvider)
          in LocationProvider (created by Context.Consumer)
          in Location (created by Router)
          in Router (created by TestRouter)
          in TestRouter

      33 |   componentDidMount() {
      34 |     this.HISTORY_LISTENER_ID = gHistory.listen(() => {
    > 35 |       this.setState(() => ({ context: this.getContext() }))
         |            ^
      36 |     })
      37 |   }
      38 |

      at printWarning (../../node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (../../node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnAboutRenderPhaseUpdatesInDEV (../../node_modules/react-dom/cjs/react-dom.development.js:23250:15)
      at scheduleUpdateOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:21165:3)
      at Object.enqueueSetState (../../node_modules/react-dom/cjs/react-dom.development.js:12639:5)
      at LocationProvider.setState (../../node_modules/react/cjs/react.development.js:471:16)
      at listener (src/location.tsx:35:12)
      at navigate (src/history.tsx:16:9)

    console.error
      Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
          in PageLoader (created by Loaders)
          in Loaders (created by RouterImpl)
          in RouterImpl (created by RouterImpl)

       95 |     this.clearLoadingTimeout()
       96 |
    >  97 |     this.setState({
          |          ^
       98 |       pageName: name,
       99 |       Page: module.default,
      100 |       slowModuleImport: false,

      at printWarning (../../node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (../../node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnAboutUpdateOnUnmountedFiberInDEV (../../node_modules/react-dom/cjs/react-dom.development.js:23161:5)
      at scheduleUpdateOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:21169:5)
      at Object.enqueueSetState (../../node_modules/react-dom/cjs/react-dom.development.js:12639:5)
      at PageLoader.setState (../../node_modules/react/cjs/react.development.js:471:16)
      at PageLoader.startPageLoadTransition (src/page-loader.tsx:97:10)
```

### CODE REVIEW

**Comment by Tobbe** [comment]
@cannikin As per your request 🙂

**Comment by cannikin** [comment]
😮 Thanks @Tobbe !!

**Comment by thedavidprice** [comment]
@dac09 thoughts on when to merge this one, v0.25 or v0.26?

@Tobbe are you waiting for a code review?

**Comment by dac09** [comment]
HODL please!

**Comment by Tobbe** [comment]
> @Tobbe are you waiting for a code review?

Yes

**Review by dac09 — APPROVED** [review]

**Pull request merged**
