### PR TITLE
Trying to fix some tests on Windows

### PR DESCRIPTION
**Pull request by Tobbe**

### CODE REVIEW

**Comment by thedavidprice** [comment]
@Tobbe This one's failing on ESlint, which blocked the Jest tests form running. Did you already run `yarn lint --fix` locally? Wondering if that's an additional issue with Windows. <sigh>

I thought I had a config on this runner to complete tests even if one failed. I'll try to add that now (can remove before/if this is added to master).

**Comment by Tobbe** [comment]
> This one's failing on ESlint

I noticed! Such an anticlimax! I was super curious to see how the actual test runs would fare 😆

**Comment by thedavidprice** [comment]
ubuntu! 🚀🎉
windows... well, those logs kinda blew up so I couldn't tell much 😬But you're seeing improvements locally?!?

**Comment by Tobbe** [comment]
Holly cow those failure logs are __brutal__! Almost crashed my browser trying to load up the raw logs 😛 

But one highlight I managed to find was this:

> 2020-06-04T21:48:16.3444076Z @redwoodjs/cli: [0m[7m[1m[32m PASS [39m[22m[27m[0m [2msrc/commands/generate/__tests__/[22m[1mhelpers.test.js[22m

That's one of the test files I've fixed

**Comment by thedavidprice** [comment]
ha! yeah, same issue -- I had to download to view. And even then they were incomplete.

**PASS** yesssssssssss

A win is a win is a win 🤣

**Comment by Tobbe** [comment]
Yeah, found another one

> 2020-06-04T21:48:22.8019257Z @redwoodjs/cli: [0m[7m[1m[32m PASS [39m[22m[27m[0m [2msrc/commands/generate/component/\_\_tests\_\_/[22m[1mcomponent.test.ts[22m

On a side note, I also found this line

> 2020-06-04T21:48:23.5419683Z @redwoodjs/cli: [0m[7m[1m[32m PASS [39m[22m[27m[0m [2mdist/commands/generate/component/\_\_tests\_\_/[22m[1mcomponent.test.ts[22m

Should it really be running tests inside the dist/ folder?

**Comment by Tobbe** [comment]
Anyway, looks like I'm on to something here 😀 I'll continue fixing tests locally, and pushing here. Hopefully, as more and more tests start passing, the logs will actually soon be readable 😉 

But that will have to be tomorrow (later today... 💤)

**Comment by thedavidprice** [comment]
> Should it really be running tests inside the dist/ folder?

Hmm, it should not. Curious where you're seeing that. 

Until tomorrow! Thanks again.

**Comment by Tobbe** [comment]
To get a baseline, I pulled this line from the logs from the latest run (that already had some fixed test cases)
```
2020-06-04T21:48:40.7302864Z @redwoodjs/cli: Tests:       237 failed, 147 passed, 384 total
```

**Comment by Tobbe** [comment]
After those five commits above, it now looks like this
```
2020-06-05T10:10:44.4878575Z @redwoodjs/cli: Tests:       172 failed, 212 passed, 384 total
```

**Comment by Tobbe** [comment]
🎉

**Comment by thedavidprice** [comment]
ezgif-3-bd5346cdbf10

**Comment by thedavidprice** [comment]
This is just amazing help, @Tobbe! Can't say thank you enough.

**Comment by Tobbe** [comment]
Anything else you want me to do before this can be merged?

**Comment by thedavidprice** [comment]
No, thank you! I should be able to get this merged today -- just wanted to look through again before I did.

**Comment by thedavidprice** [comment]
@Tobbe this is a heroic amount of tedious, repetitive work contributed. Just 🚀

I wanted to run something by you directly. Do you have a [Forum](https://community.redwoodjs.com) account so I can send you a DM? Or email if not -- mine is thedavid@thedavidprice.com if that works better.

**Pull request merged**
