### PR TITLE
set up yarn offline cache

### PR DESCRIPTION
**Pull request by thedavidprice**
_moved from_ https://github.com/redwoodjs/redwood/pull/2637

@peterp this could use discussion + plan between you, me, and @dac09 

What it does:
- Sets up Yarn offline cache; add dependency tgz files to repo in new directory

More information about Yarn's offline cache[ is here](https://classic.yarnpkg.com/blog/2016/11/24/offline-mirror/). This substantially increases the size of the repo and download time. However, it should substantially increase `yarn install` for both local development _and_ CI as well as provide offline support and better overall performance on slow networks. 

If it doesn't, we'll remove it.

TO DO:
-[ ] can we leverage this as a kind of cache mechanism in CI? (Especially for windows runners)

### CODE REVIEW

**Comment by peterp** [comment]
I think this PR has a bunch of benefits. My favorite is that it's pretty easy to see a dependency change when a file is added or removed, but I think overall we have way to many dependencies. I would love to figure out a strategy for reducing them.

I thought this PR would improve installation times, but that doesn't appear to be the case. Both with and without the cache it's roughly ~35 seconds on my local machine. Linking is the most expensive task here.

**Comment by peterp** [comment]
@thedavidprice @dac09 I think we should try this PR and see if it works for us. It's very easy to undo and is transparent to most contributors.

**Review by peterp — APPROVED** [review]

**Comment by thedavidprice** [comment]
Attempting use of --offline in CI here "try yarn --offline in GH workflows" #2686

**Comment by thedavidprice** [comment]
Oh my, this is super annoying — will happen anytime a dependency version is changed. The screenshot below is packages that changed with **one** upgraded dependency, obscuring the 4 files with code changes I want to review:
Screen Shot 2021-06-01 at 5 50 51 PM

**Pull request merged**
