### PR TITLE
Fix db/generate (nested command-dirs) help messages

### PR DESCRIPTION
**Pull request by jtoar**
Doing something like `yarn rw db seed --help` displays the help message for `yarn rw db` instead of `yarn rw db seed`:

<details><summary>Output for <code>yarn rw db help</code></summary>

```terminal
~/redwood-app$ yarn rw db --help
yarn run v1.22.4
$ /redwood-app/node_modules/.bin/rw db help
rw <command>

Commands:
  rw db down           Migrate your database down.
  rw db generate       Generate the Prisma client.
  rw db introspect     Introspect your database and generate the models in
                       api/prisma/schema.prisma (overwrites existing models).
  rw db save [name..]  Create a new migration.
  rw db seed           Seed your database with test data.
  rw db up             Generate the Prisma client and apply migrations.

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
Done in 0.88s.
```
</details>

<details><summary>Output for <code>yarn rw db seed --help</code></summary>

```terminal
~/redwood-app$ yarn rw db seed help
yarn run v1.22.4
$ /redwood-app/node_modules/.bin/rw db seed help
rw <command>

Commands:
  rw db down           Migrate your database down.
  rw db generate       Generate the Prisma client.
  rw db introspect     Introspect your database and generate the models in
                       api/prisma/schema.prisma (overwrites existing models).
  rw db save [name..]  Create a new migration.
  rw db seed           Seed your database with test data.
  rw db up             Generate the Prisma client and apply migrations.

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
Done in 0.90s.
```
</details>

This fix correctly "scopes" help output for db (and generate):

<details><summary>New output for <code>yarn rw db seed --help</code></summary>

```terminal
~/redwood-app$ yarn rw db seed --help
yarn run v1.22.4
$ /redwood-app/node_modules/.bin/rw db seed --help
rw db seed

Seed your database with test data.

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
Done in 0.89s.
```
</details>

**The fix**

The fix was simply removing `.args` from the builder of `db.js` and `generate.js`:

```diff
// db.js
- yargs.commandDir('./dbCommands').demandCommand().argv
+ yargs.commandDir('./dbCommands').demandCommand()
```

```diff
// generate.js
- yargs.commandDir('./generate', { recurse: true }).demandCommand().argv
+ yargs.commandDir('./generate', { recurse: true }).demandCommand()
```

### CODE REVIEW

**Comment by thedavidprice** [comment]
🤯

This might be my new favorite PR. All. Time. I'm so glad I complained about this while we were talking 😆

If you are able to take this one step further, _all_ the commands need to be constrained for errors using either [.strict()](https://yargs.js.org/docs/#api-strictenabledtrue) or [.strictCommands()](https://yargs.js.org/docs/#api-strictcommandsenabledtrue). 
 
You can see the history of Peter and I's attempts starting in [this comment](https://github.com/redwoodjs/redwood/pull/136#issuecomment-609384533) from PR #136 

I think ideally this should be used one time at the top-level builder, `src/index.js`, but we also experimented using it within `generator.js` (for example). Just make sure wherever it goes that it does not become _too_ restrictive and either throw false error on other commands or not all all options for all commands to be use.

No worries if you don't want to dig into this part. Just let me know and I'll pick up the work in #136

**Comment by jtoar** [comment]
Be careful what you complain about--I might just fix it. :sweat_smile: And I started looking at that after throwing this one up. I ran into the generate commands error you mentioned in that thread. Definitely down to dig in here.

**Comment by jtoar** [comment]
@thedavidprice A top-level (index.js) `strict()` seems to be working for generators since v0.7.0. When you have the chance, could you confirm that `yarn rw g` commands work with this PR on your machine too?

This still might not be ideal for `db` commands (they still work, but can take more varied options if I remember correctly?), but generators weren’t working at all on the previous release and seem to work now for some reason.

**Comment by thedavidprice** [comment]
Nice! I'll take this for a test drive today and loop back.

**Comment by thedavidprice** [comment]
K, super loving this.

Also, super rad unexpected behavior --> just yesterday I updated the `build.js` command to use a dynamic default for the build option array of Sides. I check for existing directories and then add them to the "option default" array:
```javascript
  app: {
    choices: ['api', 'web'],
    default: optionDefault(webExists, apiExists),
  },
```

When the Yargs --help is run, I totally expected it to output ` optionDefault(webExists, apiExists)` as a string or some nonsense. But it works!
```bash
$ yarn rw build --help
...
# in case of both directories existing
  --app                         [choices: "api", "web"] [default: ["web","api"]]

# in case where only web/ exists
  --app                               [choices: "api", "web"] [default: ["web"]]
```

I just 😍when the details JustWork™

**Comment by thedavidprice** [comment]
Closes #136 

This one is working 💯. Merging now.

**Pull request merged**
