### PR TITLE
Add generic typeless InputField component

### PR DESCRIPTION
**Pull request by gfpacheco**
Adds a new generic typeless `InputField` component as per discussed here: #578 

Not sure that's something you still want, and since English is not my native language I didn't even try to write any docs for it, sorry.

### CODE REVIEW

**Comment by cannikin** [comment]
This is great, thanks! I can add the docs for it.

What do you think about the loop that generates each of the other types now returning this instead of a raw HTML `<input>` the way it does now? Then there's only one instance of `<input>` anywhere and it's inside this component.

**Comment by gfpacheco** [comment]
That makes total sense! I don't know how I didn't see that earlier. I guess I still need to be more comfortable with the code, look around more and not be so scared of breaking things 😂

**Comment by cannikin** [comment]
haha We break things all the time, you get used to it! 😅

**Comment by cannikin** [comment]
I'll test this next week and merge, then add some docs!

**Comment by cannikin** [comment]
Took a while but it's done, thanks again!

**Pull request merged**
