### PR TITLE
Rename default datasource

### PR DESCRIPTION
**Pull request by jvanbaarsen**
When looking in the documentation for experimental features (For example
using DB native types) you need to add a previewFeatures flag to the
Generate block, and then in the docs they use `@db.*` everywhere.

So as an example if you'd want to use the Postgres native Date field you
get something like this:

`createdAt DateTime @default(now()) @db.Date`

Since we use `DS`as a default datasource it can trip users up a bit
since `@DS.Date` is not a valid Prisma line (Somehow they don't like the
uppercase datasource).

So if we would already rename it to `datasource db {}` we would make it
easier for users in the future.

As a sidenote, Prisma is using `datasource db {}` themselves in the docs as well.

### CODE REVIEW

**Comment by thedavidprice** [comment]
Ok, so this would be a non-breaking change we'd suggest people update via manual code mod. Also, we'd need to:
- [ ] update code mods used by e2e
- [ ] @cannikin conceptually can you think of any ways this might have downstream effects on generators? Assuming not. But might be worth updating fixtures for tests. 
- [ ] will need to update Tutorial(s) where code is displayed

@peterp anything else you can think of that we should consider along with this one? Such a small change. But, you know, Prisma always has me nervous.

@jvanbaarsen Based on feedback and recommendations regarding my questions above, I can help if/as needed. Would be great to get it all in with this PR.

**Comment by cannikin** [comment]
This is literally the first time I've ever noticed that the datasource gets a name `DS`. 😮 I'm pretty sure the generators don't do anything with that value, considering I've never noticed it before!

**Comment by jvanbaarsen** [comment]
@thedavidprice No problem I can pick up the first and latter todo. (I believe the second one has been answered now right?)

**Comment by peterp** [comment]
> @peterp anything else you can think of that we should consider along with this one? Such a small change. But, you know, Prisma always has me nervous.

Not that I can think of.

**Comment by thedavidprice** [comment]
Thanks so much, @jvanbaarsen I've updated the original tasks I outlined. Recognizing I'm being a bit particular about this one, we've had so many unexpected hiccups with Prisma along the way I've learned to be thorough.

I can take a stab at any of those three items as well — just don't want to lose track of them. Keep me posted as need.

**Comment by thedavidprice** [comment]
Update here: not getting this into the current release v0.28. But will pick up the effort for v0.29 starting next week.

**Comment by thedavidprice** [comment]
**Update**: Jeroen and I connected. He is going to be out of the loop for a while, so I am going to take lead on this PR for the final steps.

**Comment by thedavidprice** [comment]
- [x] update code mods, tests, and fixtures
- [x] rwjs.com udpates https://github.com/redwoodjs/redwoodjs.com/pull/699
- [x] learn.rwjs.com updates https://github.com/redwoodjs/learn.redwoodjs.com/pull/107

@dac09 I don't think this is a breaking change. Will update v0.33 notes for code mod update. TBD otherwise.

**Pull request merged**
