### PR TITLE
Add useLocation hook to Redwood Router

### PR DESCRIPTION
**Pull request by Terris**
This PR adds a useLocation hook to Redwood Router to expose location data. Useful for creating side effects on route change (e.g. fire off analytics data or dismiss a flash message).

### CODE REVIEW

**Comment by peterp** [comment]
This is really cool, thank you!

**Comment by jtoar** [comment]
@thedavidprice @peterp Just pinging this one&mdash;does it look ok to merge?

**Comment by thedavidprice** [comment]
Hi all, will this one require Doc updates?

**Comment by jtoar** [comment]
Most definitely!

**Pull request merged**
