### PR TITLE
Clarify wording and remove unused code

### PR DESCRIPTION
**Pull request by jessicard**
The contact form is referred to as "message" in other areas, so "comment" confused me.

This PR also removes the `UpdateContactInput` chunk in the code block, as the tutorial has us remove the field in the mutation and it confused me that the input was still there.

Is there a good code removal highlight to use here, or is removing it enough?

### CODE REVIEW

**Comment by callingmedic911** [comment]
@jessicard Thanks again for the PR! Keep 'em coming! :))

Just wanted to confirm:
> as the tutorial has us remove the field in the mutation and it confused me that the input was still there

You meant that since we are not using `updateContact` mututation, there's no point to maintain the `UpdateContactInput` type right?

**Comment by jessicard** [comment]
@callingmedic911 Yay! 😊

Yes that's right! I know it doesn't hurt to keep the `UpdateContactInput` type around, but it definitely confused me for a moment.

**Review by callingmedic911 — APPROVED** [review]

**Comment by callingmedic911** [comment]
@jessicard would you be interested to join RedwoodJS's Contributor's Meetup? Casual meetup, once a month. Here are more details: https://community.redwoodjs.com/t/contributors-meetups-a-next-step-for-redwoodjs-participation/2470

**Comment by jessicard** [comment]
@callingmedic911 Oh this looks amazing! I'd love to join, thank you for inviting me :)

**Comment by callingmedic911** [comment]
DMed you the link on Discord. Hope it's okay. :)

**Pull request merged**
