### PR TITLE
Updated Readme.md to add a quickstart in Github page

### LINKED ISSUE #1059: Add quickstart in Github's Readme.md to save time in starting a boilerplate.
I wanted to share one quick personal opinion on Readme of redwood.js. I love the documentation very well written. I do feel like the Github page should have a very quick install/setup steps. I had to go through tutorial to find that it was kinda not very efficient. 

From the docs ---> 
```
Installation & Starting Development
We'll use yarn (yarn is a requirement) to create the basic structure of our app:

yarn create redwood-app ./redwoodblog
Copy
You'll have a new directory redwoodblog containing several directories and files. Change to that directory and let's create the database, and then start the development server:

cd redwoodblog
yarn redwood dev
Copy
A browser should automatically open to http://localhost:8910 and you will see the Redwood welcome page:

To learn more visit:  https://redwoodjs.com/tutorial/installation-starting-development
```

I think we should add this in Readme.md of root Github and maybe add something like to see more information we add link to docs.

### PR DESCRIPTION
**Pull request by CR1AT0RS**
Updated Readme.md to add a quickstart in Github page. Closes #1059

### CODE REVIEW

**Comment by peterp** [comment]
Great addition! I'll look into why the tests are failing, should be entirely unrelated.

**Comment by thedavidprice** [comment]
@CR1AT0RS thank you for this!

@peterp @jtoar I recommend this content is moved to a new "Quick Start" page on the website that would be added as a doc to the Nav right below "Introduction". This is a good start for content, but I imagine we'll want to add a bit more, and I don't think the purpose of the README will be able to accommodate much more content. It already adds a different flow to the overall narrative (not bad as is, but not quite the same).

We could then use the same callout with **Tutorial:** at the top of the README to link to the Quick Start document page.

What do you think? I’ve created a new Issue for discussion here:

**Comment by CR1AT0RS** [comment]
@thedavidprice I think that's a good idea. Redwood has a different narrative in readme which is more focussed on architecture, why are we doing this and how is this different. I'd be very happy to contribute in every way possible. Thanks for adding this item in roadmap.

**Comment by thedavidprice** [comment]
@CR1AT0RS great! Would you like to take a stab at this Issue then? redwoodjs/redwoodjs.com#339

If so, please dive in. If you have any questions about the .com repo (how to add a doc, add new nav, etc.) just ask myself or @jtoar and we'd be happy to help. And don't feel like you have to add _more_ content other than the current Quick Star you have — it's great to get us going. Of course you're welcome to extend if you'd like, especially if there are other items you know would have been great for getting started as a new user. (Maybe like a "Commonly used commands and concepts" cheatsheet.)

**Pull request merged**
