### PR TITLE
Add tests for CLI generators

### PR DESCRIPTION
**Pull request by peterp**

### CODE REVIEW

**Comment by thedavidprice** [comment]
## Babel ignore `…test.js.snap` and `__snapshot__/`

@peterp I spend a good amount of time [jiggering](https://www.dictionary.com/browse/jiggering) our Babel ignore config — at this point all I know is that something is broken, but I have no idea _what_, specifically.

**Here is the build script:**
https://github.com/redwoodjs/redwood/blob/cc7b342f7a9023bdd9499d605fd0b5b540b9c150/packages/cli/package.json#L36

**And the associated configuration for ignored files, which I am attempting to update to include `**/__snapshots__` and files matching `…test.js.snap`:**
https://github.com/redwoodjs/redwood/blob/cc7b342f7a9023bdd9499d605fd0b5b540b9c150/babel.config.js#L89-L92

**Here are my results:**
- the current ignore patterns/settings are **NOT** working in full. The only pattern that is ignored is that for `…test.js` files. 
- I tried altering `/\.test\.(js|ts)/` to only specify `.ts` for testing, however, babel would **not** ignore `.ts` (I created a test test file). Additionally, babel is **not** currently ignoring the directories — if it were, the test file patterns wouldn’t be needed in the cli package. (I did try the directory matching for each individually, using different options, and couldn’t get them to work.)
- I tried adding `—ignore **/__tests__` to the script, which did **not** work
- I tried adding the `ignore: [..]` config to `cli/.babelrc.js`, which did *not* work 

My suspicion is that something is broken between using “ignore: []” within the config file and “--no-copy-ignored” within the script. However, this still doesn’t explain how the “ignore: []” **does** work for the `/\.test\.(js|ts)/` setting but for _nothing_ else. E.g. it does not ignore “..test.ts” file if I try only `/\.test\.ts/`

JS, am I right?!? ¯\_(ツ)_/¯

**Comment by thedavidprice** [comment]
My best diagnoses is that babel’s new `--no-copy-ignored` is busted — it only ignores `.js` files but doesn’t work with anything else in the config “ignore:” array. See this comment:
https://github.com/babel/babel/issues/6226#issuecomment-590393822

I submitted a new issue:
https://github.com/babel/babel/issues/11394

Now trying an alternate method — possibly a second script for cleanup of “dist/“ after building.

**Comment by thedavidprice** [comment]
@peterp I believe this is ready for you to review.

I’m using a workaround for the build, which includes a new build script setup and a cross-platform package, rimraf, to clean up the `__tests__` directories that shouldn’t ship in “dist/“.

NOTE: I tested the cli build locally on my Windows setup. The build script runs correctly with no errors. **However,** the rimraf command uses a glob and does not work as expected on Windows (the `__tests__` directories are not deleted). Since this will only affect Windows local build and dev, and is not an issue with “dist/“ but merely un-optimal for publishing, I suggest we proceed as is.

@cannikin might help to have your eyes on the build “dist/“ one more time before we merge.

**Comment by cannikin** [comment]
@thedavidprice `/dist` looking good!

@peterp I think this is ready if you want to review the **101 files that changed**. If that's too much let's get on a call and I can go through them.

I didn't go with snapshots, I ended up making a `/fixtures` directory inside each `__tests__`. Having that one giant snapshot that had to be updated seemed fragile to me: you could have made a change that broke multiple tests, you fix one test and then update—now all the snapshots are updated but you  never fixed the other tests. They're passing and you assume everything is good. WHOOPS. I saw a `fixtures` path in one of the other packages so it didn't feel too crazy. Now you can be fairly confident that if you update a fixture it will only affect the tests that directly reference it.

**Comment by cannikin** [comment]
Heads up, it might not affect anyone else but I'm going to branch off this branch and work on the new relationships stuff.

**Comment by peterp** [comment]
@cannikin cool, let's chat tomorrow

**Pull request merged**
