### PR TITLE
chore: fix dependency comments; remove `^` @redwoodjs/x

### LINKED ISSUE #2869: Lerna and NPM are re-ordering placeholder dependencies `x----x----x`
@peterp I didn't want this to get lost in the shuffle. Are you diagnosing further?

Original comment here:
https://github.com/redwoodjs/redwood/commit/3a94b3fa47856dda487dcb712b12d5d0a77a93af#r52420754

Packages:
- [core/package.json](https://github.com/redwoodjs/redwood/commit/3a94b3fa47856dda487dcb712b12d5d0a77a93af#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7) change reference
- [testing/package.json](https://github.com/redwoodjs/redwood/commit/3a94b3fa47856dda487dcb712b12d5d0a77a93af#diff-2e7c3ac725b3cfef5bf295ec1f18f1315889df2f73645a3cb08ddda5fa11a071) change reference

### PR DESCRIPTION
**Pull request by thedavidprice**
fixes #2869

@peterp I'm using a different comments package to resolve the dependency duplication issue.

Also, I've removed the `^` from @redwoodjs/ packages (again) and will watch during the next release cycle to see if I can resolve Lerna reverting.

### CODE REVIEW

**Comment by peterp** [comment]
lol, awesome, lgtm!

**Comment by thedavidprice** [comment]
Hmm, the npm changes in Testing package might disprove my theory. Regardless, I'll get this in and then watch during the next release cycle.

**Comment by thedavidprice** [comment]
local tests passed. merging...

**Comment by thedavidprice** [comment]
Gah, doesn't seem to be working now... 

```
error Couldn't find any versions for "c----x----1" that matches "^0 Types"
161
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
162
Error: Couldn't find any versions for "c----x----1" that matches "^0 Babel"
```

breaking CI

**Pull request merged**
