### PR TITLE
Don't try to start the api server unless RSC is enabled

### LINKED ISSUE #10274: Do not require `web` argument for `serve` command when serving RSC apps
### Summary

Right now `yarn rw serve` assumes there is both a web and api side and so `yarn rw serve` with no additional arguments will always start both servers. If you try to launch both but either the web or api side is missing, you'll get an error.

However, in RSC-land, there is only one server. I should be able to use `yarn rw serve` without the `web` argument as it's the only server that exists anyway.

### Detailed proposal

Update checks in `packages/cli/src/commands/serve.js` to *not* raise an error if an argument is left off when serving an RSC app.

### PR DESCRIPTION
**Pull request by cannikin**
Closes #10274

### CODE REVIEW

**Review by Josh-Walker-GM — APPROVED** [review]
Nice, yeah this is better/less friction when you have RSCs enabled.

**Comment by thedavidprice** [comment]
marking this as RSC milestone. It got pulled into `next` and was throwing errors. Let me know otherwise.

**Comment by cannikin** [comment]
Hmm, the RSC example photo app has no /api directory so depends on this change to start the `serve` process.  I forget how the next branch works, I though we just used that for docs?

**Comment by jtoar** [comment]
@cannikin the next branch is where all our stable releases are cut from 😂

**Pull request merged**
