### PR TITLE
Secure Services: skip beforeResolver export check for files in root of api/src/services

### LINKED ISSUE #2879: MissingBeforeResolver everywhere
So, I opted in secured services today, which felt easy to implement.
However, it appears I'd have to add the beforeResolver to any file in my api/src/services/**/* as per this which pops in my terminal:

```cli
api esbuild | MissingBeforeResolver: Must define a `beforeResolver()` in src/services/accountPaymentConfigurations/index/d
api esbuild |     at makeServices (/Workspace/Code/SportOffice/node_modules/@redwoodjs/api/dist/makeServices.js:32:13)
api esbuild |     at Object.<anonymous> (/Workspace/Code/SportOffice/api/dist/functions/graphql.js:3823:45)
api esbuild |     at Module._compile (internal/modules/cjs/loader.js:1185:30)
api esbuild |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
api esbuild |     at Module.load (internal/modules/cjs/loader.js:1034:32)
api esbuild |     at Function.Module._load (internal/modules/cjs/loader.js:917:16)
api esbuild |     at Module.require (internal/modules/cjs/loader.js:1074:19)
api esbuild |     at require (internal/modules/cjs/helpers.js:72:18)
api esbuild |     at setLambdaFunctions (/Workspace/Code/SportOffice/node_modules/@redwoodjs/api-server/dist/middleware/withFunctions.js:35:9)
api esbuild |     at withFunctions (/Workspace/Code/SportOffice/node_modules/@redwoodjs/api-server/dist/middleware/withFunctions.js:79:3)
```

And I do mean any file, even the `index.d.ts` files to declare my module's types.

Is this really the desired behaviour?

```
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.0.0 - /tmp/yarn--1624454722295-0.4335277431123732/node
    Yarn: 1.22.5 - /tmp/yarn--1624454722295-0.4335277431123732/yarn
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.1
  npmPackages:
    @redwoodjs/core: ^0.34.1 => 0.34.1 

Done in 11.04s.
```

### PR DESCRIPTION
**Pull request by cannikin**
If you have any JS or TS file in the root of `api/src/services` in your app, an error will be raised that the file doesn't export any `beforeResolver()`. The root of this directory will not contain services (they should all be in a subdirectory named the same as the service file, otherwise they can't be used as GraphQL resolvers anyway) so it's safe to ignore any files here in the root and not require they contain beforeResolver rules.

Closes #2879

### CODE REVIEW

**Comment by peterp** [comment]
@cannikin Does this just ignore an `index.{js,ts}` file in the `api/src/services` folder?

**Comment by cannikin** [comment]
> @cannikin Does this just ignore an `index.{js,ts}` file in the `api/src/services` folder?

It'll ignore anything in root yeah, but after more thought it should probably exclude anything that isn't the actual service file—a file with the same name as the directory its in. Those are the only things that will ever be used as Apollo providers, right? Anything else that lives in there would just be includes used by others, and shouldn't have to export a `beforeResolver()`.

**Comment by peterp** [comment]
Hmmm... So I have a weird mixtures of services, they're sometimes in folders, but sometimes not. As an examples:

```terminal
services/
  - invite.ts
  - currentUser/currentUser.ts
  - todo/todo.ts
  - tags.ts

**Comment by cannikin** [comment]
So `invite.ts` and `tags.ts` are used as resolvers?? How does that work? Remember that structure that comes in when `import *` looks like:

```javascript
{
  currentUser_currentUser: {
    // ...
  },
  todo_todo: {
    // ...
  }
}
```

Doesn't the mapping of SDL Query/Mutation resolvers to services depend on that naming, like `todo_todo`?

**Comment by peterp** [comment]
Aaaaah! We only look at the named exports, and each named export has to be unique. So the filenames don't actually matter! The named exports must match the query and mutation operations.

**Comment by peterp** [comment]
Just another point. The service's named exports must exist for the query/ mutation operations specified in the schema.

You can export a service that does not exist in a schema.

**Comment by cannikin** [comment]
HMMMMM Then is this fix actually possible? You could export anything from anywhere...

**Comment by cannikin** [comment]
> You can export a service that does not exist in a schema.

Yeahhhhhhhh hmmm.  Maybe `makeServices` needs to be WAY smarter and actually compare your SDL against your exports? Or maybe `beforeResolver` should be in a standalone file and apply to ALL services everywhere, instead of per-file like we're doing now?

**Comment by peterp** [comment]
I think it's nice that we have a before resolver for each file, since you can apply different logic to different things... 🤷 , but I haven't actually started using them in my own resolvers.

I think we should make `makeServices` way smarter. Would it work for you if we only got a list of _actual_ resolver functions and just ignored everything else?

**Review by peterp — COMMENTED** [review]
Note: I wanted to transfer my "comment" to a "Review Comment" and lost it.

I think the best approach may be to make `makeServices` smarter, and just parse the _actual_ resolvers?

I kinda like that we have a beforeResolver in each file.

**Comment by cannikin** [comment]
Closing in favor of a simpler solution that actually solves the original problem: ignoring `index.d.ts` files...

**Pull request closed without merging**
