### PR TITLE
Remove cleanup from some generator test templates

### PR DESCRIPTION
**Pull request by jtoar**
Removes cleanup from cell, component, layout, and page because it already runs automatically: https://testing-library.com/docs/react-testing-library/setup#skipping-auto-cleanup.

### CODE REVIEW

**Comment by cannikin** [comment]
image

You love to see it!

**Comment by cannikin** [comment]
Hmm, bunch of check failures. It looks like something is still expecting `cleanup` to be present...is that in the tests that are generated by the generator? Test inception!

**Comment by jtoar** [comment]
@cannikin Yep it was in the fixtures! Now that -17 is up to -51. :exploding_head:

**Comment by thedavidprice** [comment]
This looks great and thanks for getting to it before me @jtoar 

@RobertBroersma want to loop you in to confirm before we merge -- confirming this is what needed to be done?

**Comment by RobertBroersma** [comment]
That was fast! Looks good to me 👍

**Pull request merged**
