### PR TITLE
Ignore index.d.ts files when doing glob imports

### LINKED ISSUE #2879: MissingBeforeResolver everywhere
So, I opted in secured services today, which felt easy to implement.
However, it appears I'd have to add the beforeResolver to any file in my api/src/services/**/* as per this which pops in my terminal:

```cli
api esbuild | MissingBeforeResolver: Must define a `beforeResolver()` in src/services/accountPaymentConfigurations/index/d
api esbuild |     at makeServices (/Workspace/Code/SportOffice/node_modules/@redwoodjs/api/dist/makeServices.js:32:13)
api esbuild |     at Object.<anonymous> (/Workspace/Code/SportOffice/api/dist/functions/graphql.js:3823:45)
api esbuild |     at Module._compile (internal/modules/cjs/loader.js:1185:30)
api esbuild |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
api esbuild |     at Module.load (internal/modules/cjs/loader.js:1034:32)
api esbuild |     at Function.Module._load (internal/modules/cjs/loader.js:917:16)
api esbuild |     at Module.require (internal/modules/cjs/loader.js:1074:19)
api esbuild |     at require (internal/modules/cjs/helpers.js:72:18)
api esbuild |     at setLambdaFunctions (/Workspace/Code/SportOffice/node_modules/@redwoodjs/api-server/dist/middleware/withFunctions.js:35:9)
api esbuild |     at withFunctions (/Workspace/Code/SportOffice/node_modules/@redwoodjs/api-server/dist/middleware/withFunctions.js:79:3)
```

And I do mean any file, even the `index.d.ts` files to declare my module's types.

Is this really the desired behaviour?

```
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.0.0 - /tmp/yarn--1624454722295-0.4335277431123732/node
    Yarn: 1.22.5 - /tmp/yarn--1624454722295-0.4335277431123732/yarn
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.1
  npmPackages:
    @redwoodjs/core: ^0.34.1 => 0.34.1 

Done in 11.04s.
```

### PR DESCRIPTION
**Pull request by cannikin**
Closes #2879

### CODE REVIEW

**Comment by cannikin** [comment]
@peterp just double checking this is the only change that needs to be made?

**Comment by cannikin** [comment]
@peterp on second thought I just updated it to ignore ALL `*.d.ts` files... does that still work?

**Review by peterp — APPROVED** [review]

**Comment by peterp** [comment]
As @cannikin pointed out this needs to change a bit - we need to make the file that does the "glob" ignore the `.d.ts` files, the place to do that is over here:

https://github.com/redwoodjs/redwood/blob/dc4730b65818cb061042b29680e94b8ca2603706/packages/core/src/babelPlugins/babel-plugin-redwood-import-dir.ts#L49-L52

**Comment by peterp** [comment]
Fixed in #3188

**Pull request closed without merging**
