### PR TITLE
Update typescript lint rule for no-unused-vars

### LINKED ISSUE #1802: @typescript-eslint mismatch with eslint
I've noticed at least some rule for @typescript-eslint does not match the one with eslint:

[eslint-config/index.js](https://github.com/redwoodjs/redwood/blob/d25b1eca452c9725b36788e890140ce4396263e7/packages/eslint-config/index.js#L115-L117):
```javascript
  'no-unused-vars': [
    'error',
    { varsIgnorePattern: '^_', argsIgnorePattern: '^_' },
  ]
```

but no corresponding rule for typescript.

It's no big deal extending my `package.json` to handle this,
```json
...
  "eslintConfig": {
    "extends": "@redwoodjs/eslint-config",
    "rules": {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { "varsIgnorePattern": "^_", "argsIgnorePattern": "^_" },
      ]
    }
  }
...
```
I just thought it would make more sense if rw supports it out of the box.

I am not aware if any other typescript rules are mis-aligned as well or not.

### PR DESCRIPTION
**Pull request by jangxyz**
Fixes #1802

### CODE REVIEW

**Review by peterp — CHANGES_REQUESTED** [review]
Nice, could you check the prettier warnings here and fix em. :)

**Comment by peterp** [comment]
I think you can also run `yarn lint:fix`

**Comment by jangxyz** [comment]
Done :)

**Comment by peterp** [comment]
@jangxyz No worries, thanks for this!

**Review by peterp — APPROVED** [review]

**Pull request merged**
