### PR TITLE
Add flash message component

### PR DESCRIPTION
**Pull request by Terris**
This PR is a feature prototype - it adds a messaging component called "Flash".

[Usage Demo App](https://rw-flash-demo.netlify.app/users)

- It uses React context to provide/consume an array of message objects.
- It uses useReducer to provide performant actions like `addMessage`, `dismissMessage`, and `cycleMessage`
- Messages can be programmatically added, dismissed, cycled (mark viewed, then dismissed) and/or persisted to allow developer control over message lifecycles
- It adds a custom `useIntercom` hook to make the actions and message list readily available to any child of `<RedwoodProvider>`
- it adds a Flash component to web
- it includes the Flash component in scaffold templates
- It adds related tests

An example use for this feature could be to "flash" a message when a record is created, deleted or modified.

MERGE INSTRUCTIONS:

- after merge, [@redwoodjs/redwoodjs.com #187](https://github.com/redwoodjs/redwoodjs.com/pull/187) will need to be merged

### CODE REVIEW

**Comment by Terris** [comment]
> Holy cow that was quick! Is this ready for review? Any chance you could put together a little sample app that uses the functionality and put it on Netlify somewhere so we could play with it in action?

I'd be delighted. :)

**Comment by Terris** [comment]
@cannikin I've put together a little demo of the functionality for "intercom" by building a flash component in an example redwood app. You can see that [here](https://5ed999f3a05d70000750612a--redwood-shop.netlify.app/). And the code for it is [here](https://github.com/Terris/redwood-shop/pull/2).

When first visiting the site you should see a "persisted" message (top of page). This might be an example of a "We use cookies" message or the like—one that needs to be dismissed via user interaction. If you dismiss this message and want to see it again you'll need to delete the localStorage record I created to mock this behavior.

In the admin section (/user) you'll see typical flash messages after creating, updating and deleting user records. These follow a more typical scenario where a message has a lifecycle. It can be dismissed immediately by the user or (in this case) it is dismissed on a route change.

It was my intention when developing the Intercom functionality to let the developer make decisions about message lifecycle and UI on the redwood-app side. But we could certainly include a Flash component in the scaffold files to serve as an example, if you and the team decide you like this feature and want to merge it in.

Of course, I'm also happy to make any changes you see fit. Thanks for considering!

**Comment by cannikin** [comment]
Amazing! Thanks so much for the demo app, it makes it really clear how everything works.

I'd love get this added to the scaffold generator so you get messaging when creating/editing/deleting records.

Is there an easy to way to add a user-defined timeout that lets the message dismiss itself? So if you don't do anything, it'll just close itself after 5 seconds, for example? I always wished the Rails flash had that functionality!

One maybe bug we noticed—if you don't dismiss the homepage one and then go to the admin, then back home, it seems to dismiss itself. I found one where I didn't dismiss the homepage one, then created a user in the admin and it showed both messages (as expected). But I didn't dismiss either one, went back to the homepage, and now the original message was gone.

Thanks again, this is great!

**Comment by cannikin** [comment]
Ahhh just looked at the implementation and it looks like that's on purpose! It only shows the banner the first time you visit the site (really the CoreLayout) so any time you leave and come back to that layout it's going to not show the banner again (like when going between the admin and back to the homepage).

**Comment by Terris** [comment]
> I'd love get this added to the scaffold generator so you get messaging when creating/editing/deleting records.

Absolutely.

> Is there an easy to way to add a user-defined timeout that lets the message dismiss itself? So if you don't do anything, it'll just close itself after 5 seconds, for example? I always wished the Rails flash had that functionality!

Yep. I'll add that feature to the Flash component.

> Ahhh just looked at the implementation and it looks like that's on purpose! It only shows the banner the first time you visit the site (really the CoreLayout) so any time you leave and come back to that layout it's going to not show the banner again (like when going between the admin and back to the homepage).

Right. That's more or less a "bug" or quirk of my specific implementation in the demo. My thinking is that it's the developers responsibility to code up the rules for when and how a message is dismissed and, hopefully, I've provided enough tooling in the IntercomContext api to make that easy. I'm sure we'll soon find ways that it isn't :)

So, cool. Next step is to build a standardized Flash component for the scaffold generator. I'll get started.

**Comment by Terris** [comment]
@cannikin Wanted to know what you think—I'm not married to the "Intercom" domain. I was just thinking that it would be cool to name it something different than the rails-y canonical, "Flash", but... If you have an idea or just want to go with "Flash" as it's a recognizable feature name, that's totally fine with me.

**Comment by cannikin** [comment]
Hmm, my only hesitation with "intercom" is that I always associate that name with https://www.intercom.com/ but maybe that's just me.

I'm totally fine with just "Flash", that might even help some folks recognize what it is that know it from the Rails world!

**Comment by Terris** [comment]
@cannikin - I've got updated code and a new demo for the changes we discussed [here](https://rw-flash-demo.netlify.app/users). Code is [here](https://github.com/Terris/redwood-flash-demo).

- I renamed the component and context api to "Flash".
- I added a Flash display component to redwood/web
- I include this component in scaffold templates and add success messages for CRUD actions.
- The flash component can be given a timeout prop - it's messages are dismissed after the time has lapsed.
- I still need to update the related web/flash/readme file with related usage instructions

In the meantime are there any style changes you'd like to see? Do you think we should animate the message in/out in some way? Any further functionality suggestions?

Thanks!

**Comment by thedavidprice** [comment]
@Terris this is looking great! And I ❤️ seeing the doc already included. 

The "home" for this doc will be the redwoodjs.com repo in the docs/ directory:
https://github.com/redwoodjs/redwoodjs.com/tree/master/docs

I can move it after this is merged unless you beat me to it. Just didn't want you to think it disappeared.

**Comment by cannikin** [comment]
MERGEDDDD  Thanks so much for this @Terris!

**Comment by thedavidprice** [comment]
I'll take care of the doc merge as well -- aiming for v0.11.0 in the next 18 hours 😉

**Comment by thedavidprice** [comment]
@Terris one last question here. I'm getting the following ESLint warning. Does this look like something to address with a fix, or something we should have ESLint ignore?
```bash
/redwoodjs-redwood/packages/web/src/flash/Flash.js
  10:6  warning  React Hook useEffect has missing dependencies: 'cycleMessage' and 'message.id'. Either include them or remove the dependency array                react-hooks/exhaustive-deps
  18:6  warning  React Hook useEffect has missing dependencies: 'dismissMessage', 'message.id', and 'timeout'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

/redwoodjs-redwood/packages/web/src/flash/__tests__/flash.test.js
  23:8  warning  React Hook useEffect has a missing dependency: 'addMessage'. Either include it or remove the dependency array
```

**Pull request merged**
