### PR TITLE
Working towards mutation in cells

### PR DESCRIPTION
**Pull request by ajoslin103**
This is another attempt at adding mutation to the redwood cells

### CODE REVIEW

**Comment by ajoslin103** [comment]
currently waiting on this issue: https://github.com/redwoodjs/redwood/issues/4591

**Comment by ajoslin103** [comment]
continuing on the work of https://github.com/redwoodjs/redwood/pull/2870

**Comment by ajoslin103** [comment]
I'll need some typescript support on this work (https://github.com/redwoodjs/redwood/pull/4594/files#diff-a9f714237033f7ee5281fc355d15d5a5847aa7d957044b9ff19f051f8a5e6933R272) 

I want to support both QUERY and MUTATION in Cells 

Part of getting this to work I would like the Typescript to complain if there is both a QUERY and a MUTATION (There can be only One!)

**Comment by simoncrypta** [comment]
I would also link the interesting post on our forum about this for more context : 
https://community.redwoodjs.com/t/cells-with-mutation/2231/5

For the issue, I will dig it and come back to you soon. 

For the next step I will let @jtoar check if is a priority for V1 since he had the background from the last PR.

Thank you for keep up this PR ! :)

**Comment by ajoslin103** [comment]
some more nice logic: https://community.redwoodjs.com/t/rerun-cell-query/805/7?u=ajoslin103

**Comment by ajoslin103** [comment]
I have since changed my stance [mildly] on this -- I don't need mutation in a "cell" I just need it to be as easy as a cell.

I think most of the trouble I've had implementing mutation in a cell comes from some of the underlying differences in the way Apollo handles queries vs mutations -- I've not internalized the differences enough to know how to make it work well.

When I get stuck building something from the inside out - it helps me to switch perspectives: so, how would I want to use it?

usage patterns
  1. something akin to a cell that I can put on a page and it will write when rendered with given params [fire & forget]
  2. something with event-driven callbacks: onError; onSuccess, which I can call as a Function in response to user actions

**Pull request closed without merging**
