### PR TITLE
Generators

### LINKED ISSUE #29: Scaffold generator
#27

### PR DESCRIPTION
**Pull request by cannikin**
Closes #29 

* [x] CRUD for SDL generator
* [x] CRUD for service generator
* [x] Scaffold generator

### CODE REVIEW

**Comment by peterp** [comment]
It would nice to format the source of the templates via [prettier](https://prettier.io/docs/en/api.html#prettierformatsource--options) before they're written to the filesystem.

That way we can either ensure that our defaults are applied, or those of our users are applied if they have a custom prettier configuration.

**Comment by cannikin** [comment]
@peterp Added a TODO item for prettier!

**Comment by cannikin** [comment]
I think this is about as far as I can go until a couple of other things are in master (auto mapping of resolvers, automatically adding new SDL entries to `makeMergedSchema`).

Any objections to merging this into master? @peterp @mojombo

**Pull request merged**
