### PR TITLE
Used RHF get to retrieve errors

### PR DESCRIPTION
**Pull request by LBrian**
A simple fix for #2979 to retrieve form `errors` using lodash like `get` utility from RHF

### CODE REVIEW

**Comment by Tobbe** [comment]
Thank you Brian! Do you think it would also be possible to add a unit test for this?

**Review by peterp — APPROVED** [review]

**Comment by Tobbe** [comment]
Thanks for the test! I hope I get a chance to give this a spin tonight

**Comment by thedavidprice** [comment]
@Tobbe would you like me to hold merging until you review? Assuming that's the case. But if within the next hour I can get into v0.35 release.

**Review by thedavidprice — APPROVED** [review]
👍

**Comment by Tobbe** [comment]
Hey @LBrian I noticed that the `errorClassName` didn't work properly when I tested

image

The "First Name" input is named "firstName", and it gets the red border. The "Last Name" input is named "last.name", and it did not get the red border.

There was another place in the code where we also used `errors[props.name]`. So I took the liberty to fix that one as well for you. Hope you don't mind.

**Comment by thedavidprice** [comment]
Thanks for the help, everyone!

**Comment by LBrian** [comment]
> Hey @LBrian I noticed that the `errorClassName` didn't work properly when I tested
> 
> image
> 
> The "First Name" input is named "firstName", and it gets the red border. The "Last Name" input is named "last.name", and it did not get the red border.
> 
> There was another place in the code where we also used `errors[props.name]`. So I took the liberty to fix that one as well for you. Hope you don't mind.

Nice catch @Tobbe! My bad, thanks for that.

**Pull request merged**
