### PR TITLE
Add `PORT` environment variable override

### LINKED ISSUE #890: Add support for `yarn rw dev --port 8080`
In order for `vercel dev` to proxy to `rw`, it needs to pass a port.

Ideally this could be a `--port` flag or it could also use a `PORT` environment variable.

The flag would need to have precedence over the port defined in `redwood.toml`, otherwise it will never work since `create-redwood-app` generates a `redwood.toml`.

### PR DESCRIPTION
**Pull request by styfle**
Fixes #890

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks @styfle! I agree this is a simple way forward. Appreciate your diving in.

@peterp for context, this is the continuation of conversation in the Slack channel regarding Vercel support for `vercel dev`. Thoughts about this implementation? I can't think of another example we've handled like this. I like the simplicity, but I'm not sure where/how to document -- it's not CLI, or redwood.toml, or Env Var... ? Maybe for consistency it's worth a bit more time to add the Yargs option.

@jtoar thoughts about where/how to add this to the docs? Or any other reactions?

**Comment by jtoar** [comment]
@thedavidprice Maybe Builds? https://redwoodjs.com/docs/builds but it's looking like we should have a doc/cookbook just on deployments. We could pivot Builds to be that doc.

**Comment by peterp** [comment]
@thedavidprice You're right, since we're going to target multiple platforms the env var might be an unclear option to support in the future. The yargs argument would be more appropriate.

**Comment by thedavidprice** [comment]
Ok, I definitely don't want to hold up Vercel support. Let's review where we're at in the morning when we meet to discuss v0.15 release. We could ship this and follow up with the Yargs option. Or got with Yargs for v0.15 given time.

Either way, I'm #stoked about Vercel deploy! Thanks @styfle 🚀

**Comment by thedavidprice** [comment]
Update: I'm working on this now --> approach is a CLI option that's a string to be used for adding any set of Webpack DevServer config options appended to our `yarn rw dev` command.

**Comment by styfle** [comment]
Great, as long as it allows me to assign the port of the dev web server it should work!

**Comment by thedavidprice** [comment]
@styfle I'll have Peter take a look at the approach in #904 If this is approved, it will allow CLI option to pass a string of any/all Webpack DevServer config. E.g. in your case you'd use:
`yarn rw dev --wpc="--port 1234"`

The effectively results in `yarn webpack-dev-server --port 1234`

Thoughts?

**Comment by styfle** [comment]
@thedavidprice That sounds like it will work, thanks!

**Comment by styfle** [comment]
@thedavidprice I also noticed that there is a option for `browser.open = true` that is automatically enabled. Will your PR also disable that? Perhaps `yarn rw dev --wpc="--port 1234 --open false"`?

**Comment by thedavidprice** [comment]
@styfle yes, exactly! I'm making a couple of changes on the PR and will test then merge. Peter and I discussed, and we're going to close this one and not merge in favor of #904

**Pull request closed without merging**
