### PR TITLE
Coercion: loop over nested children

### LINKED ISSUE #825: CoercedValues function in web/form breaks forms that include any direct child node without props
https://github.com/redwoodjs/redwood/blob/96be36ab705ae5f7ec30262e2167e7bcb8ce4a87/packages/web/src/form/form.js#L190

This line is passing in direct children of `<Form />` to the coercedValues function. If any of these elements are not Inputs with name props, the form throws an error onSubmit.

To replicate, create a Redwood form that includes any direct children other than RW Inputs:

```js
<Form onSubmit={onSubmit}>
  <p>Some text</p>
  <div className="field">
    <TextField name="email" />
  </div>
</Form>
```
and submit =>

```bash
Uncaught (in promise) TypeError: Cannot read property 'props' of null
    at form.js:186
    at Array.forEach (<anonymous>)
    at coerceValues (form.js:183)
    at form.js:221
    at react-hook-form.es.js:1215
```
Screen Shot 2020-07-11 at 1 23 51 AM

### PR DESCRIPTION
**Pull request by Tobbe**
I'd prefer we go with #834 instead of this one

Fixes #825

### CODE REVIEW

**Comment by Terris** [comment]
Thanks @Tobbe 

I just have to be honest here, I can't really get behind this. Performing that level of recursion every time my form gets submitted just to potentially coerce a couple values feels like a hefty and unnecessary debt. If the developer could easily opt in or out then I'd say have at it, but as it is now, I have no choice but to perform this operation on forms that may not need and may be very deeply nested.

That's just my opinion and I don't mean to create friction—I just want to find the best solution for all of us. It may be a good time to bring in the big guns and see what @peterp thinks.

**Comment by thedavidprice** [comment]
Thank you both for prioritizing this!

Looping in @cannikin as well

**Comment by Tobbe** [comment]
@Terris Thanks for being honest. I respect your opinion, and I agree that recursively looping over the children isn't very pretty. That said, it's only ever going to be O(n), so I don't think performance is going to be an issue, if that's what you're worried about.

Adding a prop to `<Form>` to turn all of this off (or on) would be easy, but I don't think we should do that. IMHO that would only add even more complexity for our users. Even so, if this is something the rest of you would want, I'd be happy to implement it :) 

How about we merge this, to make sure we don't have a broken release? And then we can all think about how to better solve this problem going forward.

**Comment by Tobbe** [comment]
@Terris I have an alternative implementation in PR #834 Do you think that is a better solution?

**Comment by Terris** [comment]
> e an alternative implementation in PR #834 Do you think that is a better solution?

I think it's 100% better. I hope you like it better too. #834 Has my vote. Nice job @Tobbe

**Comment by thedavidprice** [comment]
Closing per conversation in #825

**Pull request closed without merging**
