### PR TITLE
Windows: Fix ESlint errors

### LINKED ISSUE #400: Windows Contributing: running `yarn lint` gives false error
There is a known ESLint issue for Windows system. See PR #395

If you are a Windows user and planning to contribute, _you could get stuck in a loop where the ESlint fixes you apply locally cause a CI error when you create a PR_. To avoid this for the near-term, **please follow these instructions:**
- re-clone your local redwoodjs/redwood repository in order to apply line ending settings from the `.gitattributes` file. This prevents a git line-ending change which occurs at the time a repo is cloned. 
> Note: this file was merged into ‘master’ on April 7. If you cloned locally _after_ this date, you will not need to re-clone.
- **DO NOT** run `yarn lint —fix`
- You _will_ need to fix lint errors you create. However, you should **ignore** any errors of the kind `There should be no empty line within import group import/order`. 
> Note: by “ignore” we mean simply ignore and do not fix… We prefer you not use a ESlint comment, although we may need to implement in the future). 

There are currently 12 instances of this false error — you can see an example in the [“Run ESlint” section of this CI run](https://github.com/redwoodjs/redwood/pull/395/checks?check_run_id=566887702).

### PR DESCRIPTION
**Pull request by thedavidprice**
Continues work from #363 specific to `yarn lint` issues and errors on Windows.

Closes #400

### CODE REVIEW

**Comment by thedavidprice** [comment]
@peterp @mohsen1 @weaversam8  

## Local Windows 
Here are the current issues on my local Windows machine:
**1.** 23 files are shown as modified immediately after `git clone ...` Appears to be line ending related.
**2.** 3,000+ CRLF line ending errors (even with `.gitattributes` set)
**3.** @peterp I'm confused about why I get the following error if I run `yarn lint` prior to running `yarn build`:
```
ESLint couldn't find the plugin "@redwoodjs/eslint-plugin-redwood".

(The package "@redwoodjs/eslint-plugin-redwood" was not found when loaded as a Node module from the directory "/Users/price/Repos/redwoodjs-redwood".)
```

## GH Actions Windows Runner
The CRLF errors have resolved, most likely due to the `.gitattributes` file.
  **4.** Now we are receiving an error about empty lines in import group
<details>
<summary>error details</summary>
```
Run yarn lint
2
  yarn lint
3
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
4
  env:
5
    CI: true
6
yarn run v1.22.4
7
$ yarn eslint packages
8
$ D:\a\redwood\redwood\node_modules\.bin\eslint packages
9

10
D:\a\redwood\redwood\packages\api\src\makeMergedSchema\rootSchema.js
11
##[error]  2:1  error  There should be no empty line within import group  import/order
12

13
D:\a\redwood\redwood\packages\cli\src\commands\build.js
14
##[error]  3:1  error  There should be no empty line within import group  import/order
15

16
D:\a\redwood\redwood\packages\cli\src\commands\dev.js
17
##[error]  3:1  error  There should be no empty line within import group  import/order
18

19
D:\a\redwood\redwood\packages\cli\src\commands\generate\commands\page.js
20
##[error]  4:1  error  There should be no empty line within import group  import/order
21

22
D:\a\redwood\redwood\packages\cli\src\commands\generate\commands\scaffold.js
23
##[error]  7:1  error  There should be no empty line within import group  import/order
24

25
D:\a\redwood\redwood\packages\cli\src\commands\generate\commands\sdl.js
26
##[error]  6:1  error  There should be no empty line within import group  import/order
27

28
D:\a\redwood\redwood\packages\cli\src\commands\generate\helpers.js

```
</details>

**Comment by thedavidprice** [comment]
@mohsen1 which error were you referring to? (from #363)
> I think the issue is within the order rule in eslint-plugin-import where assumption is made that end of line is "\n". Replacing that with require("os").EOL should fix it.
>
> Made a PR to get this fixed over there. It might take a while to get it fixed. Maybe disable the rule for now? You can make eslint config disable it based on the environment.

Also porting this comment from @peterp 
> It seems that Windows is not working well with:
https://github.com/tleunen/eslint-import-resolver-babel-module, we use this package to resolve our babel aliases, and to group our imports into logical sections.

**Comment by thedavidprice** [comment]
🤦‍♂ Ah, the reason the line ending error resolved on GH Action Windows runner is because _only_ the branch is checked out for testing. So the `.gitattributes` config is working! I’ve just now confirmed locally now that the file is in ‘master’. Also, the “changed files present immediately after cloning” has resolved as well. 🎉

There is one remaining error (with 12 instances) shown below. As of now I’m not sure where this is coming from unless it’s related to @mohsen1’s comment above re: `eslint-plugin-import`.

(fyi @cannikin) If Windows users are unaware of this issue, they’ll likely `lint —fix` locally, experience a lint error from our CI when they create a PR, and then be in a super confused loop. I’ll create a new issue to associate with this PR. In the meantime please and be on the lookout. 👀

See full error in the “Run ESlint” section of [this GH Action Run](https://github.com/redwoodjs/redwood/pull/395/checks?check_run_id=566887702).
```shell
Run yarn lint   
shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}’"
yarn run v1.22.4
$ yarn eslint packages
$ D:\a\redwood\redwood\node_modules\.bin\eslint packages

D:\a\redwood\redwood\packages\api\src\makeMergedSchema\rootSchema.js
##[error]  2:1  error  There should be no empty line within import group  import/order

D:\a\redwood\redwood\packages\cli\src\commands\build.js
##[error]  3:1  error  There should be no empty line within import group  import/orde

D:\a\redwood\redwood\packages\cli\src\commands\dev.js
##[error]  3:1  error  There should be no empty line within import group  import/order

...

```

**Comment by weaversam8** [comment]
@thedavidprice - AFAIK the error about `no empty line within import group` is the same error we were deailing with in https://github.com/redwoodjs/redwood/pull/363#issuecomment-609396134.

@mohsen1's comments about the source of this error might be helpful, but [he also closed his own PR](https://github.com/benmosher/eslint-plugin-import/pull/1720) on that project, so we might need an update from him about whether his remarks about the cause of the error are correct or not.

**Comment by thedavidprice** [comment]
There were initially two lint errors: one about CRLF (about 3k instances), and another about `no empty line…` (12 instances). The latter was buried in the former. It might be the case you tested locally after we added the ‘.gitattributes’ file, which is what resolved the CRLF error.

I can see the PR has been closed and read through the thread. I still don’t know which plugin is causing this error, but if we believe it’s due to ‘eslint-plugin-import’, the maintainer asked us to open a PR linking to the error. Could be a good next step regardless:
https://github.com/benmosher/eslint-plugin-import/pull/1720#issuecomment-609497430

**Comment by weaversam8** [comment]
I've found the text of the error [in the code of](https://github.com/benmosher/eslint-plugin-import/blob/5d00854f3c59a497f0a850c6ccab01a012d6b8db/src/rules/order.js#L472) `eslint-plugin-import`, so I'm pretty sure that's where it's coming from. You're probably write that our next steps is to add a failing test case as a PR to that repo.

**Comment by thedavidprice** [comment]
Our code passes lint on Mac/Ubuntu and looks like this:
```javascript
// web/src/RedwoodProvider.js

import PropTypes from 'prop-types'

import { GraphQLProvider as RealGraphQLProvider } from 'src/graphql'
```

Lint fails on Windows. It gives the error `There should be no empty line within import group  import/order` and wants the code to look like this:
```javascript
// web/src/RedwoodProvider.js

import PropTypes from 'prop-types'
import { GraphQLProvider as RealGraphQLProvider } from 'src/graphql'
```

The plugin responsible for the import/order setting is [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import). For docs see:
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

Our settings are here:
https://github.com/redwoodjs/redwood/blob/05bfc65a775190f9ba9238a06441741cd44574fb/packages/eslint-config/index.js#L96-L109

Lastly, we are also using eslint-import-resolver-babel-module to support our import/order settings:
https://github.com/redwoodjs/redwood/blob/05bfc65a775190f9ba9238a06441741cd44574fb/packages/eslint-config/index.js#L59-L61

**Comment by thedavidprice** [comment]
YES 🎉🎉🎉

Screen Shot 2020-04-11 at 11 01 46 AM

issue with eslint-plugin-import

Some cleanup and then ready to rock.

**Comment by thedavidprice** [comment]
## Error with Prettier v2.0.4
I ran into the “cannot find eslint-plugin” error when trying to upgrade to Prettier v2.0.4.

Leaving at v2.0.2 works just fine.

**Comment by thedavidprice** [comment]
@peterp @cannikin Some yay/boo here. 
- YAY: ESlint is now working on Windows 👍 
- BOO: The new CLI tests are not 👎 

It’s all path related, of course. 😢 E.g
```shell
@redwoodjs/cli:  FAIL  src/commands/generate/__tests__/helpers.test.js (7.672s)
@redwoodjs/cli:   ● templateForComponentFile creates a proper output path for files
@redwoodjs/cli:     expect(received).toEqual(expected) // deep equality
@redwoodjs/cli:     Expected: "/path/to/project/web/src/pages/FooBarPage/FooBarPage.js"
@redwoodjs/cli:     Received: "\\path\\to\\project\\web\\src\\pages\\FooBarPage\\FooBarPage.js"
```

See the current CI runner results here:
https://github.com/redwoodjs/redwood/pull/395/checks?check_run_id=579488271

Thoughts about next steps?

**Comment by peterp** [comment]
@thedavidprice Wooh! 

I tried to use `path.normalize`, to fix this, that mostly seemed to work, but there are other places where it's now broken, and I'm assuming it's also path related.

Tough to debug.

**Comment by thedavidprice** [comment]
@peterp I’m not sure what wasn’t working locally for you. But EVERYTHING is now passing for both Ubuntu and Windows runners 🎉

Merging this ‘cause it works. The only significant change will be adding Windows runner to the CI. Given our conversation about this yesterday, let’s see if this 1) works and 2) is sustainable. If not then revert to the path as discussed.

**Comment by thedavidprice** [comment]
last note about run times for CI:
- windows ~2m
- ubuntu ~2m

**Comment by theoradicella** [comment]
Hi there, when running `yarn rw lint` on a windows machine (it doesn't happen on my mac), some cmd's are opened and then I get the following warnings:
Capture
What's the exact fix for this? 
We realized this because our husky pre-commit hook, which was runing `yarn rw lint --fix` was entering a loop, only on windows machines.

**Comment by cannikin** [comment]
Hmm, I'm guessing the "CR" in there is a carriage return? Maybe Windows doesn't like our newline characters. We only use `\n` but used to be that Windows liked `\r\n`. That might be just an eslint setting we need to change? https://eslint.org/docs/rules/linebreak-style

**Comment by theoradicella** [comment]
I saw someone else had the same issue [here](https://github.com/redwoodjs/redwood/pull/363#issuecomment-609467882)
it's just I don't find the solution. Is there any?

**Comment by cannikin** [comment]
Preface: I'm not an eslint expert! But it seems like we should not consider that a problem if you're on Windows (not sure if eslint can detect what system you're on), as long as they really do get converted back to `\n` when you commit in git.

And then we could rely on our own CI systems to make sure that any `\r\n` didn't actually make it into `main` when it runs for each PR.

**Comment by theoradicella** [comment]
It doesn't bother me to see the es-lint warning, the problem is that my fellow developers with windows enter an inifinite loop when commiting due to husky running `yarn rw lint`. I'm trying to find a way so that the husky pre-commit hook can runs freely on any OS.

**Comment by theoradicella** [comment]
[UPDATE]: I bypassed this rule on the eslint config and on prettier, warnings don't show up anymore, but the main error we are facing is still not solved. When running `yarn rw lint` on windows, some system consoles are opened. And also our husky pre-commit enters a loop. Whereas this is not happening on mac OS. So it's not related to these warnings. Trying to figure out what's going on, why running `yarn rw lint` on windows opens some consoles? what's this command doing behind?

**Comment by theoradicella** [comment]
https://github.com/okonet/lint-staged/issues/1164

**Comment by jtoar** [comment]
@theoradicella the console-opening behavior you're seeing is probably the same as what's reported here: https://github.com/redwoodjs/redwood/issues/5728. See if adding `REDWOOD_DISABLE_TELEMETRY=1` to your project's `.env` file fixes it.

**Pull request merged**
