### PR TITLE
Removed development console.log lines

### PR DESCRIPTION
**Pull request by cjreimer**
This PR removes the development console.log lines I left in by accident in PR #2613.
Thanks to @callingmedic911 for catching!!

### CODE REVIEW

**Comment by callingmedic911** [comment]
Thanks @cjreimer! I noticed these as well, no impact on functionality but thought I should let you know:
- Should we also remove [these](https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/scaffold/scaffold.js#L77)? (From 77 to 80) Looks like same code around but commented.
- There are double slash in imports in scaffolds snap at a few places ([example](https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap#L4)), can you please check if this is intentional? 
- New TODOs at a few places, just wanted to double check if there's work due. Also let me know if I can help to resolve any. 🙂

**Review by dac09 — APPROVED** [review]

**Comment by dac09** [comment]
Looks good but worth addressing the comments above @cjreimer - thanks for this!

**Comment by cjreimer** [comment]
Just pushed changes to address the comments.  Thanks so much, @callingmedic911 for the QC!  Not that's it's a good excuse, but I was obviously a bit busy and rushed when I was trying to close out this PR.

**Comment by thedavidprice** [comment]
🚀 Thank you all! I'll take it from here and get this merged.

**Comment by callingmedic911** [comment]
> Just pushed changes to address the comments. Thanks so much, @callingmedic911 for the QC! Not that's it's a good excuse, but I was obviously a bit busy and rushed when I was trying to close out this PR.

@cjreimer No worries! Gentle reminder about the second point:
> There are double slash in imports in scaffolds snap at a few places (example), can you please check if this is intentional?

I haven't had the chance to look at the code but it could be due to some empty/null variable. For example `/path/${emptyVariable}/remainingPath`. Or am I missing something here? :)

**Comment by thedavidprice** [comment]
@callingmedic911 ah, very interesting. I wonder if it's from `const sP` or `const cPath` here in this code that was changed (starting around line 54):
https://github.com/redwoodjs/redwood/pull/2613/files?file-filters%5B%5D=.js&file-filters%5B%5D=.template&file-filters%5B%5D=.ts#diff-97bce3cf4db8026a128a3524084ef34dc51cef5d93130d4caa4c032991982c2c

**Review by thedavidprice — CHANGES_REQUESTED** [review]
@cjreimer Current changes are ok to go in as is, but if you are available it would be great to fix the `//` in this PR as well. 

Just let me know if you'd prefer to merge this as is and then open an Issue or PR for next steps. 

Thanks!

**Components with the import `//`**
I'm seeing this in the E2E project in the following places:
1. `web/src/components/Post/PostCell/PostCell.js`
```
import Post from 'src/components//Post/Post'
```

2. `web/src/components/Post/Posts/Posts.js`
```
import { QUERY } from 'src/components//Post/PostsCell'
```

3. `web/src/components/Post/PostsCell/PostsCell.js`
```
import Posts from 'src/components//Post/Posts'
```

4. For all pages, e.g. `web/src/pages/Post/EditPostPage/EditPostPage.js`
```
import EditPostCell from 'src/components//Post/EditPostCell'
```

others:
```
import NewPost from 'src/components//Post/NewPost'
...
import PostCell from 'src/components//Post/PostCell'
...
import PostsCell from 'src/components//Post/PostsCell'

```

**Comment by cjreimer** [comment]
Thanks for all the catches!  I'm sorry I missed these things!  I'll get on it now this evening!

**Comment by cjreimer** [comment]
OK, I addressed the `//` issue in the imports and added test coverage for this case as well.  We had test coverage of the imports in the case of scaffold paths, but not in the case of no scaffold path being passed in.

Thanks for the catches, and please let me know if there's anything else needed!

**Review by thedavidprice — APPROVED** [review]

**Comment by thedavidprice** [comment]
Looks great @cjreimer Merging now 🚀

**Pull request merged**
