### PR TITLE
Update comment-form.md

### PR DESCRIPTION
**Pull request by fakkio**
Fix a broken import in example code

### CODE REVIEW

**Comment by callingmedic911** [comment]
@fakkio Thanks for working on it. Changes look good but we want to avoid changing docs inside the `versioned_docs` directory. I think the path you want to modify is:
- docs/tutorial/chapter6/comment-form.md
- docs/tutorial/chapter7/rbac.md

After changing the docs you can visit the canary version, something like:
https://deploy-preview-5637--redwoodjs-docs.netlify.app/docs/canary/introduction

More details on contributing docs: https://github.com/redwoodjs/redwood/blob/main/docs/README.md

**Comment by fakkio** [comment]
@callingmedic911 I see, I just clicked on the button `Edit this page` in the documentation, maybe they should change that link?
Ok done, do i have to revert the other changes?

**Comment by callingmedic911** [comment]
> @callingmedic911 I see, I just clicked on the button `Edit this page` in the documentation, maybe they should change that link? 

That's a fair feedback, I'll this to team.

> Ok done, do i have to revert the other changes?

That's right, we just want to keep the canary one.

**Comment by Tobbe** [comment]
> @callingmedic911 I see, I just clicked on the button `Edit this page` in the documentation, maybe they should change that link?

@callingmedic911 and I have discussed this, and we agree. I created an issue for it https://github.com/redwoodjs/redwood/issues/5655

**Review by jtoar — APPROVED** [review]
Thanks @fakkio!

**Pull request merged**
