### PR TITLE
schemaPath must be the same as default toml

### PR DESCRIPTION
**Pull request by pdjota**
The default schemaPath must point to api db. This usually is not a problem because https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/redwood.toml#L13 sets the correct value when creating a new project. 

Closes https://github.com/redwoodjs/redwood/issues/2644
Related https://github.com/redwoodjs/redwoodjs.com/pull/703

### CODE REVIEW

**Comment by pdjota** [comment]
hey @thedavidprice , could you take a look at this?

**Comment by pdjota** [comment]
please also check https://github.com/redwoodjs/redwoodjs.com/pull/703

**Review by thedavidprice — CHANGES_REQUESTED** [review]
@peterp I want to confirm this default config udpate _before_ we merge this. I believe we left this as `prisma/` in order to have backward compatibility for projects that didn't update the directory name to `db/`, correct?

If that's the only reason it was left as is, I think it's time to update. If you agree, I'll make sure to highlight the change in the Breaking section of the Release Notes (with instructions for code mod).

**Comment by peterp** [comment]
@thedavidprice I think you're 100% correct. This should be the way forward :)

**Review by thedavidprice — APPROVED** [review]
🚀

**Comment by thedavidprice** [comment]
Ok, next step --> I'm going to _remove_ the config from the CRWA/template as it's now optional. Will communicate people have choices going forward, but the default has now changed.

**Comment by thedavidprice** [comment]
See remove CRWA/template/redwood.toml schemaPort #2702

**Pull request merged**
