### PR TITLE
fix cell generated test template

### PR DESCRIPTION
**Pull request by thedavidprice**
@peterp looping you in on this one. Dom and I are coordinating the generated tests that need to be fixed/completed. This seemed to do the trick for cells but would welcome your eyes/improvement.

### CODE REVIEW

**Comment by thedavidprice** [comment]
Looking further, I found this original Cell test template sketch:
https://github.com/redwoodjs/redwood/issues/629

Now looking into using the mock file to do something closer to ^^

**Comment by thedavidprice** [comment]
closes #629

**Comment by thedavidprice** [comment]
@peterp This one is ready for review -- any suggests about other/better ways to incorporate the existing mock file into the tests? Also, I took some notes from Robert for specific Jest queries used. Please confirm that's what you'd like to see in the template.

**Comment by RobertBroersma** [comment]
Hey @thedavidprice 

Rendering the individual parts of a cell is kind of testing implementation details. What I would love to see is something more like in #629, but with MSW instead of `MockedProvider`

Something like this:
```js
import { render, screen, graphql } from '@redwoodjs/testing'

import BlogPostCell from './BlogPostCell'

describe('BlogPostCell', () => {
  it('renders post succesfully', async () => {
    graphql.query('GetPost', (req, res, ctx) => {
      return res(
        ctx.data({
          post: {
            title: 'Post Title',
            id: 'id-123',
            body: 'Test',
            __typename: 'Post',
          },
        })
      )
    })

    render(<BlogPostCell id="id-123" />)

    expect(await screen.findByText(/Post Title/)).toBeInTheDocument()
  })

  it('handles errors', async () => {
    graphql.query('GetPost', (req, res, ctx) => {
      return res(
        ctx.errors([
          {
            message: 'Whoops!',
          },
        ])
      )
    })

    render(<BlogPostCell id={1} />)

    expect(await screen.findByText(/Whoops!/)).toBeInTheDocument()
  })
})
```

I'm not so familiar with the generator outputs, so I'm not sure if this is possible, but I think it is!

This way the test is closer to the real world use of `BlogPostCell`. The user will after all be using `<BlogPostCell />` and not the individual parts of the cell.

Does that make sense?

**Review by peterp — APPROVED** [review]
I think @RobertBroersma's suggestion make sense, but this pull-request may have been focusing on fixing the test templates. Maybe we should open another issue for improving them?

**Comment by RobertBroersma** [comment]
@peterp Oh my bad, I didn't realize it was broken! I think the new issue you're describing is #629 . I'll put my snippet there

**Review by RobertBroersma — APPROVED** [review]

**Pull request merged**
