### PR TITLE
Upgrade Yargs v17

### LINKED ISSUE #3621: upgrade Yargs from v16.2.0 to v17
cc @jtoar 

Releases:
- https://github.com/yargs/yargs/releases

Breaking changes:
- https://github.com/yargs/yargs/releases/tag/v17.0.0

I attempted a naive upgrade, which didn't work. Couldn't quickly diagnose the issue.

Ideally we'd include this in v1-rc

### PR DESCRIPTION
**Pull request by jtoar**
- closes #3621

### CODE REVIEW

**Comment by thedavidprice** [comment]
New constraint (you added) is making me so happy right now 😂

Screen Shot 2021-11-03 at 9 53 04 PM

**Comment by jtoar** [comment]
@thedavidprice I gave another go at trying to get the serve tests to parse correctly and I came up empty so I've removed them in this PR. They're good tests, but they don't test that things actually get served—just that if you call `yarn rw serve`, the `bothServerHandler` is called, etc. That we've set yargs up properly basically. We don't have that kind of coverage for the rest of the CLI and things still reliably work.

I'm happy to focus on adding back those kinds of tests during the v1 rc. I feel ok removing them now because testing the fact that `yarn rw serve` calls `bothServerHandler` is easy to QA manually. Also, we never make changes to the CLI directory structure, so I'm happy to QA it once as a part of this PR and feel good that it works. Let me know what you think!

**Comment by jtoar** [comment]
It's worth noting that the last change to this file was to fix something on Windows:
- https://github.com/redwoodjs/redwood/pull/2668

That makes me less certain that things will work. I can manually QA using my Windows machine to be sure.

**Comment by thedavidprice** [comment]
cc @dac09

**Comment by thedavidprice** [comment]
@jtoar I believe this one is prioritized correctly, but it's still bugging me that we haven't upgraded due to a test that 1) we're not sure even applies to our CLI and 2) begs the question as to whether or not we correctly understand Yargs parsing.

If needed, we can see if Ben Coe has some insite on why the test is failing for v17 but passing v16 — when you're ready, let's take that step.

**Comment by jtoar** [comment]
Finally managed it in https://github.com/redwoodjs/redwood/pull/5416.

**Pull request closed without merging**
