### PR TITLE
(feat): Add TS prompt to Create Redwood App

### PR DESCRIPTION
**Pull request by ehowey**
Addresses https://github.com/redwoodjs/redwood/issues/6275

Continued from https://github.com/redwoodjs/redwood/pull/6332 - I got lost in `git reset` hell and just started fresh!

Based on the conversation from the previous PR this PR is reduced in scope and achieves the following:

`yarn create redwood-app ~/tmp/rw-test388` -> Prompt for TS or JS
`yarn create redwood-app ~/tmp/rw-test388 --ts` -> No prompt. TS project
`yarn create redwood-app ~/tmp/rw-test388 --no-ts` -> No prompt. JS project (or --ts=false, which yargs also gives you for free)

A couple of notes:

- The default for `ts` in Yargs is set to null so that the user is prompted by default, default for the prompt is Y though.
- I added an error for when `--no-ts --no-yarn-install` are used together
- Please feel free to change/modify the welcome message. It is a simple placeholder.
- The `userArgs` object is a bit of a workaround, but the best way I could think of handling the prompt override based on user input to the command line. If typescript is null, then the `userArgs` ends up being an empty object, which means that the prompt will be shown to the user.
- Sorry it is such a messy diff, because of the async function for the prompt everything ends up with changes to spacing leading to a really hard to view file diff.

### CODE REVIEW

**Comment by Tobbe** [comment]
> * Sorry it is such a messy diff, because of the async function for the prompt everything ends up with changes to spacing leading to a really hard to view file diff.

image

"Hide whitespace" makes it super easy to read 🙂

**Comment by ehowey** [comment]
Good feedback - made the requested changes and have done a final test run.  From what I can tell it is all working as expected. Thanks for all of the support and guidance on this one Tobbe!  Really appreciated!

Conversation for another place/thread but I am also going to throw up another "experimental" PR with some of those other ideas we have chatted about just to continue spitballing ideas for improvements to the install experience.

**Comment by jtoar** [comment]
Excited for this! Now that it's merged I just tried to try it out via `yarn create redwood-app@canary test` and it failed with:

```
/private/var/folders/dt/yks4v5m53k114qxgz6jh4pgw0000gn/T/xfs-9f7c3693/dlx-8848/.pnp.cjs:19377
      Error.captureStackTrace(firstError);
            ^

Error: create-redwood-app tried to access prompts, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: prompts
Required by: create-redwood-app@npm:2.2.5-canary.313 (via /Users/dom/.yarn/berry/cache/create-redwood-app-npm-2.2.5-canary.313-d72727c361-8.zip/node_modules/create-redwood-app/dist/)

Require stack:
- /Users/dom/.yarn/berry/cache/create-redwood-app-npm-2.2.5-canary.313-d72727c361-8.zip/node_modules/create-redwood-app/dist/create-redwood-app.js
    at Function.require$$0.Module._resolveFilename (/private/var/folders/dt/yks4v5m53k114qxgz6jh4pgw0000gn/T/xfs-9f7c3693/dlx-8848/.pnp.cjs:19377:13)
    at Function.require$$0.Module._load (/private/var/folders/dt/yks4v5m53k114qxgz6jh4pgw0000gn/T/xfs-9f7c3693/dlx-8848/.pnp.cjs:19231:42)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/dom/.yarn/berry/cache/create-redwood-app-npm-2.2.5-canary.313-d72727c361-8.zip/node_modules/create-redwood-app/dist/create-redwood-app.js:41:39)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require$$0.Module._extensions..js (/private/var/folders/dt/yks4v5m53k114qxgz6jh4pgw0000gn/T/xfs-9f7c3693/dlx-8848/.pnp.cjs:19421:33)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.require$$0.Module._load (/private/var/folders/dt/yks4v5m53k114qxgz6jh4pgw0000gn/T/xfs-9f7c3693/dlx-8848/.pnp.cjs:19244:22)
```

Seems like a simple fix: just add prompts as a dependency to create-redwood-app since it imports prompts. Also my global version of yarn is 3.2.3. It may work on yarn 1 but I haven't confirmed.

**Comment by Tobbe** [comment]
Took like five tries to get the windows tests to pass

**Pull request merged**
