### PR TITLE
Prevent re-initialization of a Firebase app that is already initialized

### PR DESCRIPTION
**Pull request by cjreimer**
THIS PERHAPS SHOULD BE A RECOMMENDATION FOR ALL USERS IN THE RELEASE NOTES AS IT WILL NOT BE FIXED WITH A REDWOOD UPGRADE.  This pr only addresses the CLI firebase setup.

A firebase app will throw an error if you try to reinitialize it after it is already initialized.  Thus, an additional check if already initialized:

```
export const firebaseClient = ((config) => {
  if (!firebase.apps.length) {
    firebase.initializeApp(config)
  }
  return firebase
})(firebaseClientConfig)
```

is more resilient than the previous code.

```
export const firebaseClient = ((config) => {
  firebase.initializeApp(config)
  return firebase
})(firebaseClientConfig)
```

### CODE REVIEW

**Comment by peterp** [comment]
@cjreimer Oooh, where you in a situation with this code executed twice?

**Comment by cjreimer** [comment]
@peterp thanks for the review!  

I first saw the error in the playground-auth app.  It is generated when doing a hot reload during development changes.  The error is:
image
And the simple fix proposed addresses it.

I had not seen the error in my main app we're developing until now when testing.  The reason is that the initialization code in my app is in App.js, which we don't touch often.  If I edit App.js, the error appears in my app as well.

It appears the issue is with webpack Hot Module Replacement (HMR), which causes a reinitialization if the affected code is changed.  I have not seen the issue on a simple browser reload of the app.

This does appear to be a development time issue only at this point.  Would you prefer to save a line in the codebase for an infrequent error that should only be development-related?  We could move this to the docs only if someone wants to add it manually.

**Comment by peterp** [comment]
@cjreimer Ah, that's super valid. Let's get this merged. Could you fix the failing test?

**Comment by cjreimer** [comment]
Ahh ... fixed the snapshot.  The windows test is still failing.  I believe it's an issue with the windows test run.

Is there an easier way to get the test to retry other than to force a commit with a dummy change?

**Comment by Tobbe** [comment]
> Is there an easier way to get the test to retry other than to force a commit with a dummy change?

Not sure if it's a permission thing or not, but I can just click this (after clicking "Details" on the failing run)

image

**Comment by cjreimer** [comment]
Thanks @Tobbe.  I can't see it now after the tests are passed and I don't remember seeing that button before, but all look for it next time a test fails.

**Comment by Tobbe** [comment]
Click "Show all checks"
image

Click "Details"
image

Click re-run (upper right corner)
image

If you can't see it, it's probably a permission thing

**Comment by cjreimer** [comment]
Must be a permission thing.  This is what I see (at least on a completed successful run):

image

**Comment by Tobbe** [comment]
> Must be a permission thing.

Yeah, totally. Too bad though :(  Annoying having to push dummy commits to re-trigger the runs

**Review by dthyresson — COMMENTED** [review]
LGTM Thanks for this fix!

**Comment by cjreimer** [comment]
Glad to help!  I appreciate the core team keeping things moving!

**Comment by thedavidprice** [comment]
Merging now. Adding to checklist for v0.33 --> Code Mods recommended if using Firebase.

Merging related doc as well now as it is helpful instruction with/without this setup change.

🚀

**Pull request merged**
