### PR TITLE
Support table relationships in service generators

### LINKED ISSUE #316: Relation support
Hi, I just tried Redwood for a new personal project.

At first I thought this could be the one boilerplate to rule them all, lots of great stuff, very organized.
I went through the entire tutorial, it's great btw.

But the illusion ended when I tried to create my first relation.

I wrote my prisma schema like this:

```
model Teacher {
  id Int @id @default(autoincrement())
  name String
  courses Course[]
}

model Course {
  id Int @id @default(autoincrement())
  name String
  teacher Teacher
}
```

And after running `yarn rw db save` I saw that Prisma generates the db field without the `Id` suffix, but that's just Prisma's fault, I guess I can live with that.

Then I ran `yarn rw g scaffold` for both teacher and course models and realized the generated GraphQL schema was like this:

```
  type Teacher {
    id: Int!
    name: String!
    courses: Course
  }

  type Course {
    id: Int!
    name: String!
    teacher: Teacher
  }
```

Not only teacher's `courses` field wasn't an array, both teacher's `courses` and course's `teacher` fields didn't have `!` as expected since they didn't have `?` on Prisma schema. So I went and fixed them (together with their inputs).

Then I went to the GraphQL Playground and created a teacher, so far so good, until I tried to create a course and got a really weird error, very hard to read (because it was coming from prisma), but I managed to identify: the `createCourse` function created by the scaffold was like this:

```
export const createCourse = ({ input }) => {
  return db.course.create({
    data: input,
  })
}
```

But needed to be like this:

```
export const createCourse = ({ input: { teacher, ...input } }) => {
  return db.course.create({
    data: { ...input, teacher: { connect: { id: teacher } } },
  })
}
```

My next disappointment was with the course query, of course querying the teacher field from course wouldn't work since the resolver only gets the course from the database and there's no resolver for the `teacher` field (the same happens with the courses field on Teacher).

PS: I still don't know how to create a field resolver, but I'll ask somewhere else.

Not to mention the web part, where teacher queries all have the `courses` fields but without any subfields (the same for Course's `teacher` field) and the forms have a Int field for each relation field.

I'm sorry it might seem I'm just saying bad things about a open source project, I really appreciate your efforts, I'm gonna keep using Redwood and try helping as much as I can. I just hoped there was anything in the docs saying relations are a work in progress or something.

PS: I have a few years of Node and GraphQL experience (not so much with tooling though), would be happy to tell how I (as a developer) would expect things to work, and maybe help with the implementation.

### LINKED ISSUE #327: Scaffold generator ignores relations
This issue is for improving Redwood's relation support (see #316).

------------------------------------------------

## Summary

When running `yarn rw generate scaffold ModelName`, if a model include relations, the scaffolded pages will all (or almost all) be broken. This primarily comes from generating invalid GraphQL queries.

## Example

If we use the following example schema (`prisma.schema`)

```prisma
// datasource + generator statements omitted
// [...]

model IceCream {
  id       String @id @default(cuid())
  flavor   String
  toppings Topping[]
}

model Topping {
  id   String @id @default(cuid())
  name String
}
```

The [Cell](https://redwoodjs.com/tutorial/cells) to display a single `IceCream` (`web/src/components/IceCreamCell/IceCreamCell.js` will generate a GraphQL query like this:

```js
export const QUERY = gql`
  query FIND_POST_BY_ID($id: String!) {
    iceCream: iceCream(id: $id) {
      id
      flavor
      toppings
    }
  }
`
```

This is strictly not valid GraphQL. Since `toppings` is a relation, referencing the `Topping` model, the query would need to select some subfields. In the above example, modifying the query to the following would fix the problem.

```js
export const QUERY = gql`
  query FIND_POST_BY_ID($id: String!) {
    iceCream: iceCream(id: $id) {
      id
      flavor
      toppings {
        id
      }
    }
  }
`
```

Additionally, the `IceCream` component itself would need to be modified to reference the `iceCream.toppings.id` field instead of just `iceCream.toppings`.

## Solution

> Although scaffolds will probably never be built out to the point of adding forms for relationships, the SDL and service generators should be able to introspect and build them when possible. [[source]](https://github.com/redwoodjs/redwood/issues/316#issuecomment-602274285)

[It is an open question](https://github.com/redwoodjs/redwood/issues/316#issuecomment-602274285) exactly how much the scaffolding generator should assume, but I think we can agree that it shouldn't generate broken code when relations are involved. 

We don't know for sure what fields we should query for on an item that has a relation, but maybe for starters, we can assume an `id` field exists, query for that, and display a hyperlinked ID in the generated pages when displaying a relation. [(There's already evidence that we enforce an ID column to exist on all generated models.)](https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/generate/commands/sdl.js#L37-L43)

This is probably a big PR, but definitely necessary.

### PR DESCRIPTION
**Pull request by cannikin**
When generating an SDL, if any tables reference each other via prisma's `@relation` syntax, we will create the equivalent expected resolver syntax in the generated service.

### Example

The following GraphQL query is not currently supported out of the box with Redwood's implementation of SDL + services. For the given `schema.prisma`:

```
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id     Int     @id @default(autoincrement())
  title  String  @unique
  body   String
  user   User    @relation(fields: [userId], references: [id])
  userId Int
}
```

You should be able to write the following GraphQL query:

```gql
posts {
  id
  title
  body
  user {
    name
    email
  }
}
```

We will create the following additional functions in the `posts.js` service:

```js
export const Post = {
  user: (_obj, { root }) => db.post.findOne({ where: { id: root.id } }).user(),
}
```

And the following functions in the `users.js` service:

```js
export const User = {
  posts: (_obj, { root }) => db.user.findOne({ where: { id: root.id } }).posts(),
}
```

Apollo will automatically use these relationships to make the GraphQL query above work.

Closes #316 
Closes #327

### CODE REVIEW

**Comment by cannikin** [comment]
Hmm, I have a dilemma. While this does add relationships to the services, the scaffolds created when there's a relationship are busted. Two reasons:

1. The foreign key field like `userId` is a string, when the GraphQL expects an `Int` (related to #392)
2. Even if the ID is cast properly, Prisma blows up when trying to assign `userId` a value. It expects you to connect to an actual User record (?????)

So we could release this along with a note that scaffolds won't work with it yet. Instead of relationships being 100% broken, they're now only 50% broken. :)  Getting data OUT of a service works great, it's inserting that's killing us.

Or don't do anything until both problems above are fixed. That probably means more complaints about relationships not being supported in the meantime. :(

**Comment by gfpacheco** [comment]
I was working on this but I got stuck because [prisma's `getDMMF` doesn't give us the fields argument](https://github.com/prisma/prisma/discussions/2096).

They just told me that it now does, but it's still in the alpha branch, and I thought `Id$` wasn't a reliable way to do it, but I guess that's good enough, I'm glad someone with more time was able to finish it.

**Comment by weaversam8** [comment]
Great work getting this out the door @cannikin! 🎉 

Can't wait to try it out!

**Comment by weaversam8** [comment]
@cannikin - This closed #327, but I think this actually should have closed #324. #327 was the issue for the generated UI stuff not working, while #324 was the issue for services not properly resolving relation fields.

If that's the case, #324 should definitely be closed by this issue, but #327 should probably be reopened, unless this PR is bigger than I've noticed so far.

**Comment by cannikin** [comment]
#327 was was actually fixed a couple PRs ago. The generated query on the display pages excludes other objects now and only pulls scalar fields. So if you had a `Post` with a `userId` you would get that in your query, no `user`. You can add that yourself, of course, but the scaffolded pages will only include scalars for editing. https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/generate/scaffold/scaffold.js#L149

**Pull request merged**
