### PR TITLE
improve Upgrade command so `-t` accepts any string

### PR DESCRIPTION
**Pull request by thedavidprice**
Previously the `--tag` option only accepted `canary` or `rc`. This PR allows user to pass any string as a tag option, which means you can now specific versions e.g. `yarn rw upgrade -t 0.19.2-canary.37`

I've updated the option description to the following:
```bash
Upgrade all @redwoodjs packages via interactive CLI

Options:
  --help         Show help                                             [boolean]
  --version      Show version number                                   [boolean]
  --dry-run, -d  Check for outdated packages without upgrading         [boolean]
  --tag, -t      [choices: "canary", "rc", or specific-version] WARNING:
                 "canary" and "rc" tags are unstable releases!          [string]
```

### CODE REVIEW

**Comment by thedavidprice** [comment]
@jtoar I was hoping to find a way for yargs to suggest choices and also allow a string. No such luck. As you see here I'm now allowing user to pass any string. And I'm attempting to give good guidance via the description.

- Is this still clear?
- Any other Yargs ideas about how better to handle this?

**Comment by jtoar** [comment]
@thedavidprice I think it's clear; here's a few thoughts:

- In the description, provide an example of what a specific-version would look like, like the one you provided in your first comment: `0.19.2-canary.37`, just to give people an idea of what goes
- And/or link to where you can find specific-versions: https://www.npmjs.com/package/create-redwood-app (is that the right link?)
- I need to try this first, but the options object takes a coerce property we could probably use (src: https://yargs.js.org/docs/#api-reference-coercekey-fn). It  looks like we could check the specific-version against a regex and throw if it's incorrect. I'll try this locally to see if works. It'd be something like...

```diff
    .option('tag', {
      alias: 't',
      description:
        '[choices: "canary", "rc", or specific-version] WARNING: "canary" and "rc" tags are unstable releases!',
      type: 'string',
+     coerce('tag', (arg) => {
+       ...check to see if arg is a valid specific-version string
+     })
    })
```

**Comment by thedavidprice** [comment]
@jtoar Updated copy and added example. New output:
```bash
Upgrade all @redwoodjs packages via interactive CLI

Options:
  --help         Show help                                             [boolean]
  --version      Show version number                                   [boolean]
  --dry-run, -d  Check for outdated packages without upgrading         [boolean]
  --tag, -t      [choices: "canary", "rc", or specific-version (see example
                 below)] WARNING: "canary" and "rc" tags are unstable releases!
                                                                        [string]

Examples:
  rw upgrade -t 0.20.1-canary.5  Specify a version. URL for Version History:
                                 https://www.npmjs.com/package/@redwoodjs/core

```

Thoughts?

**Comment by Tobbe** [comment]
This is great! Was looking for something like this the other day when I wanted to upgrade an old RW project to a newer version, but not the latest. So hoping this means something like this would also work `yarn rw upgrade -t 0.18.0`

**Comment by thedavidprice** [comment]
@jtoar @dac09 
I'm merging this as is to get it in `main`. You both had some ideas about possible constraints, which could be helpful but likely aren't urgent. Anyway, please do a follow-up PR as needed.

**Comment by dac09** [comment]
@thedavidprice @jtoar added validation in #1304

**Pull request merged**
