### PR TITLE
Fix cell plugin not handling default and named export

### PR DESCRIPTION
**Pull request by gfpacheco**

### CODE REVIEW

**Comment by gfpacheco** [comment]
@peterp the CI is breaking because of my intentional "breaking" test. I guess I should just remove that, what do you think?

**Comment by peterp** [comment]
> I just wanted to make sure the plugin would still process it as a Cell if export const QUERY was there. But I'm not sure that's needed.

I think that's a good call, you could disable ESLint with a pragma mark for the specific file.
By adding: `/* eslint-disable */` to the top of the file.

I guess we could disable it for all fixtures, but then we would loose the ability to automatically format them. (Since we format via ESLint.)

**Comment by gfpacheco** [comment]
> I think that's a good call, you could disable ESLint with a pragma mark for the specific file.
> By adding: `/* eslint-disable */` to the top of the file.

That didn't work, I tried disabling the whole file and just one line, but eslint kept complaining about the double default export error.

**Comment by peterp** [comment]
Cool, cool, cool - Thanks for that. I'll see if I can figure that out later.

**Pull request merged**
