### PR TITLE
Add tailwind generator

### PR DESCRIPTION
**Pull request by jtoar**
This PR adds a generator that adds Tailwind to a Redwood app:

```
yarn rw g tailwind
```

rw-g-tailwind

We do already have the process documented in the doc on [Webpack Configuration](https://redwoodjs.com/docs/webpack-configuration#adding-tailwindcss). But I feel like adding Tailwind to a Redwood app happens often enough to warrant a generator for it. Let me know if you guys think it's extraneous though. And/or if it should be part of a larger "css" generator:

```
yarn rw g css tailwind
```

Right now, adding-directives-to-your-index.css bit is a note at the end, much like the way auth works:

```
const notes = [
  'Add the following directives to your ./web/src/index.css:',
  '',
  '@tailwind base;',
  '@tailwind components;',
  '@tailwind utilities;',
]
```

I thought this was better than just overwriting `index.css` but open to any suggestions there as well.

### To-dos:
- [x] Should this be part of a larger css generator? I.e. just one of many options accessed through `yarn rw g css`
- [x] Should this output a note about adding directives to `index.css` (current behavior), or just overwrite the file?
- [x] Add tests! (skipping for now @peterp )

### CODE REVIEW

**Comment by peterp** [comment]
This is awesome!

I would love to see more of these utility generators included by the community, so maybe we could give them a place to add them all? I like your suggestion of `css`, but that might be too focused.

What about something like `yarn rw g util`

**Comment by peterp** [comment]
It would be cool if we could also send them to the tailwind documentation.

**Comment by thedavidprice** [comment]
Hmm, I need to think about it further in order to give more specific reasons, but this case strikes me something that can be better handled as a package, e.g. `redwood-tailwindcss`. (Also, admittedly didn't dive into your code yet, Dom.)

Has anyone explored how/if something like this would work as a package?

**Comment by mojombo** [comment]
@thedavidprice Even if the only thing the generator did was add a package, it might still be worth it to have as a generator. The sense of ease you get from doing this is very powerful. Like, "I want to use TailwindCSS, I know what to do: use a generator to get it set up!". Some utility generators will do more, some will do less, but if you know to start with a generator, that can show people the "official" way to do things and remove any mental roadblocks to getting it done.

**Comment by jtoar** [comment]
@cannikin We have the postcss-loader ready to go by default: https://github.com/redwoodjs/redwood/blob/1e3cfcbf67b6cdca2e0dfbba000bcb67a7204f50/packages/core/config/webpack.common.js#L61-L74

In a new project, I can just add a `postcss.config.js` (the same one as the template) and not even a `webpack.config.js` and tailwind works (provided you install the packages and add the directives to `index.css`). But I'm still not too fluent in Webpack Configese, so there's a good chance I don't know what's going on! Especially with the
```
config.optimization = {
  minimize: false,
}
```
part. @peterp Could you weigh in here?

> Also did we mention in another issue/PR somewhere that tailwind.config.js really needs to go in the root of the whole project if we want the VS Code extension to pick up and add hints and autocomplete?

Yes! On slack. We also threw around the idea of opening a PR but I don't think we did yet. Should we leave it in the root dir for now and attach a note at the end of the generator: "Ordinarily, we'd put this in web/config, but since the vscode extension..."

**Comment by jtoar** [comment]
@thedavidprice Per generator vs package, my thought process was exactly as @mojombo said. I didn't know how to make a package, and I knew the auth generator already did a bunch of fancy things, like installing stuff and outputting notes, so I just pretty much just used it as my guide while making this one.

**Comment by cannikin** [comment]
> In a new project, I can just add a postcss.config.js (the same one as the template) and not even a webpack.config.js and tailwind works

Whatttt is this as of 0.13? I gotta upgrade!

> We also threw around the idea of opening a PR but I don't think we did yet.

Ahhh so is the path hardcoded in Redwood internals somewhere and we can't just change the path in `postcss.config.js`?

```
module.exports = {
  plugins: [
    require('tailwindcss')(path.resolve(__dirname, '..', 'tailwind.config.js')),
    require('autoprefixer')
  ],
}
```

**Comment by jtoar** [comment]
It looks like it was in v0.11.0 judging by the [milestones](https://github.com/redwoodjs/redwood/milestone/7?closed=1) (and here's the PR: https://github.com/redwoodjs/redwood/pull/696).

As per the path, you mean the `tailwind.config.js` path right? I think we can move it, I got that `postcss.config.js` (and all the instructions for setting up tailwind in general) from [mdv.io](https://mdv.io/). 

I should probably change the syntax in the `postcss.config.js` (we hardly use `require` anywhere else). I got stuck in the "Make it work" phase&mdash;time to make it right?

**Comment by jtoar** [comment]
@cannikin This works, so we can leave the `tailwind.config.js` in the base dir this way:

```js
const path = require('path')

const { getBaseDir } = require('@redwoodjs/internal')

module.exports = {
  plugins: [
    require('tailwindcss')(path.resolve(getBaseDir(), 'tailwind.config.js')),
    require('autoprefixer'),
  ],
}
```

**Comment by cannikin** [comment]
> This works, so we can leave the tailwind.config.js in the base dir this way:

Awesome! Have you tried the VS Code plugin, are hints and stuff working??

**Comment by jtoar** [comment]
Will check that now! Just to be super clear: the desired behavior is leave the `tailwind.config.js` in the root dir (until we can configure the extension to look elsewhere)?

**Comment by cannikin** [comment]
> the desired behavior is leave the tailwind.config.js in the root dir

Correct! I think we want people's VS Code plugins without any messing around.

**Comment by peterp** [comment]
Just a heads up that the vscode extension works if it's in `<baseDir>/web`, but not if it's in `<baseDir>/web/config`

**Comment by cannikin** [comment]
> Just a heads up that the vscode extension works if it's in `<baseDir>/web`, but not if it's in `<baseDir>/web/config`

Verified!

**Comment by jtoar** [comment]
Quick update: running into a problem with `util` being a subcommand of `generate` which is already recursively looking through all the directories in `./generate` for commands. Might be an easy fix&mdash;just need to spend more time on it, hopefully later today.

**Comment by jtoar** [comment]
@cannikin Took some time to circle back, but this one's done! I've tested it thoroughly locally, but haven't added any bona fide tests as I wasn't sure exactly how to test it (unlike the other generators, there's no parameters involved in the command). Let me know if anything else looks like it needs changes.

Summary
- adds a new entry-point generator command: `util` (as in `yarn rw g util`)
- adds `tailwind` as the first util command: `yarn rw g util tailwind`
- the tailwind command configures tailwindcss by:
  - installing modules
  - making `web/config/postcss.config.js`
  - initializing a `tailwind.config.js` and putting it  in `web/` so it works with intellisense
  - outputting a note about adding tailwind directives to `index.css`

**Comment by cannikin** [comment]
Looks good to me! I'd just want to get @mojombo's feelings about that `util` namespace...

**Comment by jtoar** [comment]
@peterp Is it ok to import from `@redwoodjs/internal`like I'm doing in the `postcss.config.js` template?

https://github.com/redwoodjs/redwood/pull/828/files#diff-e8715eadab66dd143fd6bbbae1bed8d1R3

**Comment by nadnoslen** [comment]
Hey @jtoar, thanks for putting this together.  I needed to add tailwindcss to my redwood `0.15.3` app this morning so decided to follow your `tailwind.js` command script in this PR ... rather than follow a blog post from the internets:

1. ✅  Installed the dev dependencies to the web workspace
1. ✅  Copied over your `postcss.config.js` contents into `web/config/postcss.config.js`
1. ✅  Generated the `tailwind.config.js` and moved it to the `web` directory
1. ✅  Added the `@tailwind` directives to my `web/src/index.css`

Even with the `tailwind.config.js` living in the `web` directory, I can get VS Code to autocomplete my styles in my jsx `className` attributes & the `@apply` in my css files.  

My app has instantly applied the tailwindcss reset and is gleefully accepting the utility classes as expected.

I'm not seeing any conflicts with my scaffolded pages.

🥇 🎉  This util is looking great and I can't wait until others can benefit from it via the command line.  Thanks gang!!

**Review by peterp — APPROVED** [review]

**Comment by peterp** [comment]
@jtoar Using getPaths like that is fine. Sorry, I didn't know this was up for review because it had an unchecked "add tests" step.

**Comment by peterp** [comment]
@jtoar Actually on second thought I'm going to move the `getPaths` functionality. Could you use a relative path here instead? These files are next to one another right?

**Comment by jtoar** [comment]
@peterp No worries--I was trying to think of how to test this and just haven't come up with any good ideas yet. The files are just copied over, so it doesn't make sense to test that their content is the same. Testing that the vscode extension works would be best :sweat_smile:

Should I make something similar to the `./tasks/test-tutorial`?

**Comment by peterp** [comment]
@jtoar That would be tough - I think it's OK to not have tests for this right now. Our generators need a bit of an overhaul so that the modifications can be exposed via JSON output instead of directly writing to files, but that's a future concern. This is good to merge!

**Comment by peterp** [comment]
@jtoar :shipit:

**Comment by thedavidprice** [comment]
@jtoar Do you know if this generator has been added to the docs yet (or is in process)? Happy to help if not.

**Comment by jtoar** [comment]
@thedavidprice Hasn't been added yet--I can add it momentarily. I'll 1) add it to the cli commands doc and 2) link to it from the webpack config "adding tailwind" section.

**Pull request merged**
