### PR TITLE
feat(testing/api): Configure jest to ignore ".scenarios.[jt]s$" files

### PR DESCRIPTION
**Pull request by V1shvesh**
Solves for #10870

### Description:
`./api` directory structure:
image
`./web` directory structure:
image

Before: 

`yarn rw test api`:
image

`yarn rw test web`:
image

After:
`yarn rw test api`:
image

`yarn rw test web`:
image

### CODE REVIEW

**Comment by Tobbe** [comment]
Thanks for your PR @V1shvesh 
I'd like @cannikin to take a look at this, but he's on vacation right now. I'll ask him to take a look when he's back at work again 🙂

**Comment by V1shvesh** [comment]
Thank you for guiding me on the next steps, @Tobbe! I was a bit unsure how to proceed here.

**Comment by dthyresson** [comment]
@cannikin could you review ? Thanks!

**Comment by cannikin** [comment]
Thanks so much @V1shvesh this is great!

Do you think we should do the same thing for `*.stories.js` and `*.mock.js` files on the web side? I haven't tried it, but I assume if you put them in a `/__tests__` dir then this same behavior will occur!

**Comment by cannikin** [comment]
Also, could you add a changeset for this PR? Just run `yarn changesets` in the root of the repo and it'll generate the file and pre-fill it with the PR description above.

**Comment by V1shvesh** [comment]
> Thanks so much @V1shvesh this is great!
> 
> Do you think we should do the same thing for `*.stories.js` and `*.mock.js` files on the web side? I haven't tried it, but I assume if you put them in a `/__tests__` dir then this same behavior will occur!

image

@cannikin confirmed the issue, I can update the PR to include the fix for `web/**/__tests__/` files as well.

**Comment by V1shvesh** [comment]
@cannikin creating a new PR with updated branch name + title to capture the updated scope: #11108.
Closing this PR.

**Pull request closed without merging**
