### PR TITLE
Add a workflow file to create-redwood-app

### LINKED ISSUE #2559: GH Action CI
It would be amazing to have a RedwoodJS CI Action and publish it to GH Marketplace. The GH Action would:

- [x] diagnostic check
- [x] lint
- [x] build
- [x] test

### PR DESCRIPTION
**Pull request by jtoar**
Closes #2559; but the purpose of this PR is more to just get the conversation started. I pretty much just copied the "Lint, build and run tests" workflow in our repo (located here https://github.com/redwoodjs/redwood/blob/main/.github/workflows/build-eslint-jest.yaml). Those three things seem like table stakes.

@thedavidprice you had mentioned publishing a Redwood action. This PR adds a workflow instead. Even if we do publish an action, it'll have to be used in a workflow, so it makes sense to add `.github/workflows/ci.yml` or `main.yml`, etc. to create-redwood-app at some point. But would the action just encapsulate all these jobs/steps? Would it take inputs? What did you imagine it being?

Other considerations:
- Should we have one file with many jobs with many steps, or many files with few jobs and few steps?
- I think we need to add more comments. Way more comments. Workflows and actions have their own learning curve
- Is ubuntu-latest enough as far as runners go?

### CODE REVIEW

**Comment by peterp** [comment]
Awesome idea! Thanks for getting the conversation started!

I like the visibility of providing the different steps: "lint, build, and test." But there is a bit of a risk that if we want to change those commands that we need to ask the user to update their GitHub action. I think we can solve this in two ways:

1. Add a `rw ci` command that performs these tests.
2. Create our own custom GitHub action.

**Comment by thedavidprice** [comment]
Nice! I've been sitting on this for waaayyy too long. Thanks for moving it forward. Here's what I had imagined:
1. add a workflow file to the CRWA template
2. the workflow file would run an Action, something like `actions/redwoodjs-ci`, which we would publish and maintain
3. The published action would run:
    - build
    - lint
    - `yarn rw check` diagnostics
    - tests

Some options for discussion:
- Workflow config to turn things on/off (probably not necessary... or maybe for the future)
- Projects have storybook files —> I've wondered if we could do something with those for project CI as well? Maybe that's a separate E2E Action that could be added. Theoretically, we would know which components have stories and could check if they're rendered without error (or even for mock data). I'm just not sure how useful of a default experience that would be. And I'm not sold using Cypress for Storybook CI is the way to go either. 

Quick research results about using Storybook for CI:
- Cypress + Storybook (what we do in Framework CI): https://spin.atomicobject.com/2020/07/06/test-storybook-cypress/
- Storyshots Jest Snapshots (new to me): https://jongleberry.com/ci-workshop/03-storybook.html

**Comment by jtoar** [comment]
Here's an example repo of what the action might look like: https://github.com/jtoar/redwoodjs-ci/blob/main/action.yml. It's a [composite action](https://docs.github.com/en/actions/creating-actions/about-actions#composite-run-steps-actions), which just means that it runs a whole bunch of steps. We should publish the action under this repo, so it would be used in the workflow file like `uses: redwoodjs/redwoodjs-ci@v1`.

You can see an example run of that action here: https://github.com/jtoar/redwoodjs-ci-test/runs/2662511039?check_suite_focus=true. It seems like the `--no-watch` flag on `yarn rw test` might actually be unnecessary?

**Comment by thedavidprice** [comment]
> It seems like the --no-watch flag on yarn rw test might actually be unnecessary

^^ Interesting. Can you confirm Jest defaults to no-watch in the CI context? (Fwiw, I still think our default should be --no-watch... 😉) I suggest leaving it in if there's any chance we're unclear about behavior.

- Repo: Let me know when/if you're ready for us to create a repo for the action. I just need the name!
- Reminder from our discussion to add `yarn rw check` to Action.

**Comment by jtoar** [comment]
@thedavidprice I'm ready for a repo, not sure what it should be named though. The way the action will be used, it'll always be prefixed with `redwoodjs` since that's the name of the organization. So should it just be named ci?

```
- uses: redwoodjs/ci@v1
```

**Comment by jtoar** [comment]
Sorry didn't mean to close this off!

**Comment by pi0neerpat** [comment]
One thing missing here is injecting the DATABASE_URL

**Comment by jtoar** [comment]
Closing in favor of https://github.com/redwoodjs/redwood/pull/5188.

**Pull request closed without merging**
