### PR TITLE
Abstract away NODE_OPTIONS exp. await flag for console

### PR DESCRIPTION
**Pull request by jtoar**
The console command requires the `NODE_OPTIONS` env var to be set to `--experimental-repl-await`. This PR makes it so that the console command spawns an execa child process to configure it automatically so that users don't have to.

This solution's based on the comment here: https://github.com/nodejs/node/issues/13209#issuecomment-560161777.

### CODE REVIEW

**Comment by thedavidprice** [comment]
Current Issues:
- in case of no existing Prisma Client, rw console will throw
- seems to auto-execute the repl every time CLI commands are run

Most likely need to resolve post the release of v0.22. Hold off on promotion and including in Tutorial 2 until fixed and in a release.

**Comment by thedavidprice** [comment]
@peterp This is a weird one all around. Could you take a look and see if you have some ideas for how to better approach in general?

**Comment by peterp** [comment]
@jtoar I think we can close this now?

**Comment by peterp** [comment]
Closing this because we merged something else in #1619

**Pull request closed without merging**
