### PR TITLE
fix: running tests with mysql datasource

### PR DESCRIPTION
**Pull request by vitaliimelnychuk**
I have been using Redwoodjs for a few days and really like the experience of the framework.

I am trying to use Redwoodjs with Mysql as datasource but having problems with tests execution:

I am running `yarn rw test api` and have this error in response:

```
Raw query failed. Code: `1064`. Message: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"User"' at line 1`
```
the error came from `api/src/directives/skipAuth/skipAuth.test.js` that was generated by default. 

Looks the problem was with quotes configuration that I was able to fix simple by adding `async/await` since  getSchemaConfig is asynchronous.

### CODE REVIEW

**Comment by vitaliimelnychuk** [comment]
@cannikin @jtoar Can you take a look and start the CI?

**Comment by thedavidprice** [comment]
@vitaliimelnychuk Thank you for opening this PR! Code looks good. Before merging, I just want to confirm you've functionally tested on your project and are confirming this fix works for you, correct?

**Comment by vitaliimelnychuk** [comment]
Hey @thedavidprice! Yes, I just added those few lines and everything working fine for me.

**Comment by dac09** [comment]
Thank you for your contribution @vitaliimelnychuk - nice catch!

**Pull request merged**
