### PR TITLE
Remove an empty line!

### PR DESCRIPTION
**Pull request by guledali**

### CODE REVIEW

**Comment by guledali** [comment]
@peterp how make the CI pass?

**Comment by thedavidprice** [comment]
Hi @guledali! Thanks for this. Is the reason for making this change because the generated file is throwing an ESLint error right away?

For reference, here's the CI test error:
```bash
@redwoodjs/cli:     -
@redwoodjs/cli:       import Posts from 'src/components/Posts'
@redwoodjs/cli:       export const QUERY = gql`
@redwoodjs/cli:         query POSTS {
@redwoodjs/cli:           posts {
@redwoodjs/cli: 
@redwoodjs/cli:       109 |   expect(
@redwoodjs/cli:       110 |     files['/path/to/project/web/src/components/PostsCell/PostsCell.js']
@redwoodjs/cli:     > 111 |   ).toEqual(
@redwoodjs/cli:           |     ^
@redwoodjs/cli:       112 |     loadGeneratorFixture('scaffold', path.join('components', 'indexCell.js'))
@redwoodjs/cli:       113 |   )
@redwoodjs/cli:       114 | })
@redwoodjs/cli: 
@redwoodjs/cli:       at Object.<anonymous> (src/commands/generate/scaffold/__tests__/scaffold.test.js:111:5)
```

@cannikin looks like we might  need your help here -- I've no idea why removing the empty line would break a path in the test?

**Comment by cannikin** [comment]
> I've no idea why removing the empty line would break a path in the test?

That's looking at the content of the file that's generated and comparing it against the fixture file. So if the generated file now has one less line break it won't match the fixture.

We used to have an eslint rule that put empty lines between imports from packages and imports from other paths in the app itself...did those rules get changed? I had that empty line in there so there wouldn't be any changes between what came out of the generator and what the linter would fix if you went into the file and saved it yourself...

**Comment by guledali** [comment]
> We used to have an eslint rule that put empty lines between imports from packages and imports from other paths in the app itself...did those rules get changed? 

I think so
Screenshot 2020-06-01 at 19 05 25

**Comment by cannikin** [comment]
Ahh interesting. Is this the only generated file that has that empty line?

**Comment by guledali** [comment]
@cannikin Just checked that's the only file

**Comment by cannikin** [comment]
Awesome! You'll just have to update the text fixture for that file and remove the newline from that as well. Locally you can `cd` into the `cli` package and `yarn test` to check that it's working.

**Comment by guledali** [comment]
@jtoar, I'm closing this one, not much of change anyway and + new templates are coming soon https://github.com/redwoodjs/redwood/issues/686#issuecomment-643344906

**Pull request closed without merging**
