### PR TITLE
Update E2E Tutorial test: add Toast and <Set /> per Tutorial

### PR DESCRIPTION
**Pull request by thedavidprice**
The Tutorials now use the new Toast messaging and Router Sets. Using the code from the Tutorial, this PR adds Toast and Sets to the Cypress Tutorial test. (Note: this is definitely something to implement _before_ releasing next time... 🤦‍♂️)

To Dos:
- [x] passing checks as-is with new code for Toast and Sets
- [x] Add UI check to confirm Toast message appears and is closed after clicking
- [x] Add UI check to confirm CSS is applied to scaffolded CRUD
- [x] Resolve Server Response 400 that happens after a successful test run (see screenshot below)

### CODE REVIEW

**Comment by peterp** [comment]
Hmmm... This might be a "flakey test," is it something that's constantly reproducible?

**Comment by peterp** [comment]
If it is constantly reproducible, maybe turn of fast refresh in redwood.toml and try again.

**Comment by peterp** [comment]
@thedavidprice Just for my own sake was it the react fast refresh? I think we're writing too many files too quickly and the reloading mechanisma gets confused.

**Review by peterp — APPROVED** [review]
Looks good to me, thanks David 🙇‍♂️

**Comment by thedavidprice** [comment]
@peterp I tried it with the fast refresh off, which didn't resolve the final 400 error. However, I resolved it by simply adding a final `cy.visit('http://localhost:8910/')`. And now it's a clean run.

Also added two scaffold CSS checks and three Toast messaging checks.

Screen Shot 2021-04-06 at 12 21 19 AM

**Pull request merged**
