### PR TITLE
Stop initializing Loaders during render to fix remounting

### LINKED ISSUE #267: Are layouts re-rendered on each navigation
If two routes share the same layout does that layout re-render, unmount and remount. What's the cost associated with that?

Based off of this tweet:
https://mobile.twitter.com/sebastienlorber/status/1238889193461383169

### PR DESCRIPTION
**Pull request by jtoar**
While digging into #267, I noticed that `Loaders` is remounting all the time too.

Here's a gif of the react dev tools profiler on a vanilla Redwood app. Notice that every time I navigate to a new page, `Loaders` says it's "rendered for the first time":

loader-rerendering

I'm pretty sure that `Loaders` shouldn't be remounting on every page navigation. The props do change, and that should cause a rerender, but for `Loaders` to be ripping itself out of the DOM seems a little excessive. 

I think the reason for this is `Loaders` is initialized _during_ `RouterImpl`'s rendering:

https://github.com/redwoodjs/redwood/blob/ff1f7b6040093855fd98a20cb3c478c2bab97d00/packages/router/src/router.js#L148-L158

This means `Loaders` is always made to order when `RouterImpl` renders, and since React compares **by reference** to decide if something (and its whole subtree!) should render and commit, `Loaders` always does.

> NOTE: I'm still learning the nuances of React so I might be wrong about the exact details of that above part.

### The fix

A quick fix is just to repeat code. That's what I did so far in this PR, and you can already see the difference in the profiler (just the fact that you can see the different timestamps for `Loader` means its working):

loader-rerendering-fixed

I think one added bonus is that the flash between page navigations is gone too? I don't see it anymore with this fix in the Redwood app I'm using to test this out locally.

But to close it out, I'm thinking about a better solution for this problem, but just wanted to make sure I got the issue right first before making major changes. Am I on the right track here?

### CODE REVIEW

**Comment by jtoar** [comment]
Diagnosing that failing test now.

**Comment by peterp** [comment]
@jtoar this is amazing, thank you for this <3

**Comment by peterp** [comment]
I guess we need to figure out why the test is failing?

**Comment by peterp** [comment]
@jtoar Please let me know if you need some help figuring out why that test is failing.

**Comment by peterp** [comment]
The problem here is that different "params" to the same page are not causing a re-render.

**Comment by mojombo** [comment]
This is great stuff! Closing in favor of the fixed version at #1284.

**Pull request closed without merging**
