### PR TITLE
Feat: add RW logo (create redwood app welcome msg)

### PR DESCRIPTION
**Pull request by spanarin**

### CODE REVIEW

**Comment by jtoar** [comment]
Thanks @spanarin, this is looking great! Context for others: @spanarin asked me how to contribute to Redwood. I mentioned that some of the core team wanted CRWA to include a logo. Here's a screen recording:

https://github.com/redwoodjs/redwood/assets/32992335/00f4d4bc-33bd-4613-a7df-1deee5140177

**Comment by Tobbe** [comment]
From Dom's video:
image

Are the tops of the 'd's not aligned with the rest of the letter on purpose?

**Comment by spanarin** [comment]
> From Dom's video: image
> 
> Are the tops of the 'd's not aligned with the rest of the letter on purpose?

It's not a feature, it's a bug :) I'll fix that

**Comment by jtoar** [comment]
Hey @spanarin thanks for taking a stab at this! I think I told you that I showed this to the team. Going to close this out for now given their feedback, but it was a lot of fun to review.

**Pull request closed without merging**
