### PR TITLE
yarn rwt link now copies files over, slightly different to copy:watch

### LINKED ISSUE #1931: [Contribution flow only] Linking causes prerender to fail
### What?
When running `yarn rw build web` on a project 
- that has been linked with `yarn rwt link`, 
or 
- is run in the e2e (which essentially is the same as rwt link

 prerendering always fails with the following message (if a hook is used in the app)

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

This is because `react` and `react-dom` versions don't resolve to the same instance (even if the version is the same), as described in (3) of the error.

### LINKED ISSUE #2078: rwt link error: "https://registry.yarnpkg.com/@redwoodjs%2f.DS_Store: Not found".
When running through the contributor documentation I ran into an issue when trying to run rwt link on my newly created redwood-app

image

I ran `yarn install`: it worked 
I ran `yarn rwt link` it fails
I ran `yarn install` again and it continuously fails

`yarn-error.log` information
```
Arguments: 
  /usr/local/Cellar/node/15.2.1/bin/node /usr/local/Cellar/yarn/1.22.10/libexec/bin/yarn.js install

PATH: 
  /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Yarn version: 
  1.22.10

Node version: 
  15.2.1

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@redwoodjs%2f.DS_Store: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:66988:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:140749:22)
      at Request.emit (node:events:329:20)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141721:10)
      at Request.emit (node:events:329:20)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141643:12)
      at Object.onceWrapper (node:events:435:28)
      at IncomingMessage.emit (node:events:341:22)
      at endReadableNT (node:internal/streams/readable:1294:12)
      at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

Additionally, I did downgrade node to 14.16.0 just to check if the node version was to high and had a similar issue

### PR DESCRIPTION
**Pull request by dac09**
### What?
- Removes auto-unlink because its buggy, just has a message instead
- Doesn't use symlinks, but instead of copied the packages over from PATH_TO_RW/packages to Project_Dir/redwood
This is to prevent the duplicate react issue where `FRAMEWORK_PATH/node_modules/react` and `PROJECT_PATH/node_modules/react` are both used during prerender
- Automatically adds the redwood folder to gitignore
- Improves logic for adding resolutions by ignoring hidden directories
- tries to make unlink a little more consistent by deleting `node_modules/@redwoodjs` before yarn installing again

Fixes #1931
Fixes #2078

### CODE REVIEW

**Comment by peterp** [comment]
Oh man, this is interesting... 

I don't know if I understand this issue 100% correctly.

Doesn't copying the `./packages` from the framework to the `redwood-project/packages` folder, instead of using symlinks, solve this issue?

The e2e tests copy the packages, and only 1 version of React is installed and referenced, and pre-render is working correctly as far as I can tell.

We could modify the workflow for `copy:watch` so that copies to the `<project>/packages` instead of `node_modules`, and if we wanted to be fancy we could use `npm publish --dry-run --json` to determine exactly which files to copy.

**Comment by dac09** [comment]
> Doesn't copying the `./packages` from the framework to the `<project>/packages` folder, instead of using symlinks, solve this issue?

It doesn't sadly! As far as yarn/workspaces is concerned soft links and copying are identical.

> The e2e tests copy the packages, and only 1 version of React is installed and referenced, and pre-render is working correctly as far as I can tell.

yeah the problems only rears it's head when you use hooks. Our e2e tests don't have useAuth for example. The problem is when two instances of react exist. One in FRAMEWORK_REPO/node_modules and one in PROJECT/node_modules

> We could modify the workflow for copy:watch so that copies to the <project>/packages instead of node_modules, and if we wanted to be fancy we could use npm publish --dry-run --json to determine exactly which files to copy.

Hmm, sure I like this, but I think we should do it to selectively `ln -s` maybe. What I'm not a fan of in copying, is that it needs another watcher to sync changes.

**Comment by dac09** [comment]
FYI, the reason its not a problem when you build web is because of this line here:https://github.com/redwoodjs/redwood/blob/8beda5bf24cff078160840347de7e78f7a042ec6/packages/core/config/webpack.common.js#L191

I tried doing the same thing in babel-preset with babel-plugin-module-resolver, but that doesn't seem to work. This might be the most elegant solution, if you wanted to try @peterp

**Comment by peterp** [comment]
> It doesn't sadly! As far as yarn/workspaces is concerned soft links and copying are identical.

🤔 Is the problem that we have `./node_modules/react` and another react somewhere else? Where is the other react installed?

**Comment by dac09** [comment]
Sorry I'm not doing a great job explaining the problem!

To be specific (~/Code/redwood is framework path)
- runPrerender.tsx is using its own react from ~/Code/redwood/node_modules/react
- the page/component is use its react from ~/Code/my-sample-project/node_modules/react

**Comment by peterp** [comment]
Ah ok, I think this is where we are getting confused. This is how node resolves packages:

> [Loading from node_modules folders](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)
If the module identifier passed to require() is not a core module, and does not begin with '/', '../', or './', then Node.js starts at the parent directory of the current module, and adds /node_modules, and attempts to load the module from that location. Node.js will not append node_modules to a path already ending in node_modules.

> If it is not found there, then it moves to the parent directory, and so on, until the root of the file system is reached.

So when you're using symlinks it's going to reach the node_modules in the framework.

Node added a flag to [preserve the symlinks](https://nodejs.org/api/cli.html#cli_preserve_symlinks), but I don't think anyone uses it.

> By default, when Node.js loads a module from a path that is symbolically linked to a different on-disk location, Node.js will dereference the link and use the actual on-disk "real path" of the module as both an identifier and as a root path to locate other dependency modules. In most cases, this default behavior is acceptable. 
```

{appDir}
 ├── app
 │   ├── index.js
 │   └── node_modules
 │       ├── moduleA -> {appDir}/moduleA
 │       └── moduleB
 │           ├── index.js
 │           └── package.json
 └── moduleA
     ├── index.js
     └── package.json
```

So with copying it would actually resolve to the project's react, instead of the framework's react. (Since yarn would symlink to the same folder as the project, not the framework.)

The same is true of Webpack: https://webpack.js.org/configuration/resolve/#resolvesymlinks

**Comment by dac09** [comment]
Ah this is a very good point. I'm not sure why I was getting the same errors on a copy. Will investigate tomorrow

**Comment by peterp** [comment]
> I'm not sure why I was getting the same errors on a copy.

Maybe we fixed that issue with resolutions! I think we're fighting a many headed hydra.

**Comment by dac09** [comment]
@peterp I've updated this PR to _copy_ instead of using symlinks. Now also modifies the gitignore folder, to prevent spamming the user's repo with all the redwood files. Let me know what you think :)

**Comment by dac09** [comment]
Just realised that copying files, instead of linking brings back the old issue of having to install new dependencies included in redwood. :/ 

We should discuss how to continue with this:

**Option 1:** Use copy, and accept limitations that we will manually have to install new modules included in any of the redwood packages

**Option 2:** Use previous version, where react in the framework was symlinked to react in the project. This does introduce additional complexity

**Comment by peterp** [comment]
> Just realised that copying files, instead of linking brings back the old issue of having to install new dependencies included in redwood. :/

As far as I know it does not bring back the old issue, if the copied files are part of the workspace, yarn should install the contents of the package.json files when you run `yarn install`

**Comment by dac09** [comment]
> As far as I know it does not bring back the old issue, if the copied files are part of the workspace, yarn should install the contents of the package.json files when you run `yarn install`

Hmm, man you're right, this stuff is so confusing. What happens is if you're running link, and _then_ install a new module, it won't pick it up. You have to stop the watcher and run `yarn rwt link` again. I suppose thats alright?

**Comment by KrisCoulson** [comment]
Just wanted to circle back I pulled this branch locally and ran `rwt link` and it does fix https://github.com/redwoodjs/redwood/issues/2078

**Comment by dac09** [comment]
Closing in favour of https://github.com/redwoodjs/redwood/pull/2122

**Pull request closed without merging**
