### PR TITLE
Stringify function body prevents Netlify 502 error

### PR DESCRIPTION
**Pull request by dthyresson**
# Addresses Issue

Resolves https://github.com/redwoodjs/redwood/issues/864

When deploying to Netlify, having the body not JSON.stringify-ed can result in 502 Bad Gateway errors due to a "Netlify encoding hiccup".

Perhaps it is best to wrap it in a stringify -- at least to call out/alert the developer that practice.

The lack of JSON.stringify has been noted several times on Netlify community as well:

https://community.netlify.com/t/debugging-a-function-returns-502/429/5

# Proposed Solution

Change the function template:

```js
export const handler = async (event, context) => {
  return {
    statusCode: 200,
    body: JSON.stringify({
      data: `${name} function`,
    })
  }
}
```

Note: also added the `data` instead of simply returning a string, since this is a common return payload.

# Considerations

* most of my functions to a try and catch and in the catch return either a `401` unauthorized or `400` bad request ... or even `500` internal server error.
* may want to add this to template to encourage proper status handling?

### CODE REVIEW

**Comment by dthyresson** [comment]
Looks like the failing test wasn't the template test (as I had checked that) but instead

```
@redwoodjs/router:     console.error
@redwoodjs/router:       Warning: An update to LocationProvider inside a test was not wrapped in act(...).
```
Perhaps b/c my "branch is out-of-date with the base branch"?

**Comment by peterp** [comment]
Those looks like warnings that are annoyingly wrapped in console.error, but they don't make the tests fail.

You're failure is over here:
image

**Comment by dthyresson** [comment]
> failure is over here

Thanks, I was not running my test locally correctly; now I understand how to do that.

**Comment by dthyresson** [comment]
I was looking at a [jamstackfns](https://jamstackfns.com/f/spotify) function and it just dawned on me that Vercel and Netlify have slightly different function implementations. Should RW support a flag to generate a Netlify or Vercel flavor-based template?

**Comment by peterp** [comment]
@dthyresson Nope, Vercel takes care of that on their end.

We will "settle" on a function signature at some point (most likely just the most standard) and we'll transpile at build time to the deploy target.

**Comment by dthyresson** [comment]
> we'll transpile at build time to the deploy target.

Makes sense. I have to keep reminding myself that RW aims to be both platform-agnostic while improving the dev experience ... and transpiling gives you that flexibility and dev peace of mind that "it'll take care of it for me".

**Pull request merged**
