### PR TITLE
Simplify log message format for web in api-server

### PR DESCRIPTION
**Pull request by dthyresson**
See: https://github.com/redwoodjs/redwood/issues/3784

This PR changes the message format of the api-server to more closely mimic the old Express server and Morgan logging where there was no metadata for the request and response and that info was contained in a single line statement.

However, since Fastify has a log statement per request and response, not all info is available and the pino pretty formatting can only have a single output format for all statements:

```bash
api | INFO [2021-12-08 18:10:41.466 +0000]: e12ecbf0-8176acb1-5f2c579d incoming request  POST 
api | DEBUG [2021-12-08 18:10:41.467 +0000] (graphql-server): GraphQL execution started: PollCurrentVersionQuery
api | DEBUG [2021-12-08 18:10:41.467 +0000] (graphql-server): GraphQL execution completed: PollCurrentVersionQuery
api | INFO [2021-12-08 18:10:41.468 +0000]: e12ecbf0-8176acb1-5f2c579d request completed 200  1.2969579696655273
api | INFO [2021-12-08 18:11:01.492 +0000]: e464718d-696a34c6-c34d0ea8 incoming request  POST 
api | DEBUG [2021-12-08 18:11:01.498 +0000] (graphql-server): GraphQL execution started: PollCurrentVersionQuery
api | DEBUG [2021-12-08 18:11:01.499 +0000] (graphql-server): GraphQL execution completed: PollCurrentVersionQuery
api | INFO [2021-12-08 18:11:01.500 +0000]: e464718d-696a34c6-c34d0ea8 request completed 200  6.534749984741211
api | INFO [2021-12-08 18:11:21.515 +0000]: b42957f7-8f6727a3-e9d6df30 incoming request  POST 
api | DEBUG [2021-12-08 18:11:21.516 +0000] (graphql-server): GraphQL execution started: PollCurrentVersionQuery
api | DEBUG [2021-12-08 18:11:21.516 +0000] (graphql-server): GraphQL execution completed: PollCurrentVersionQuery
api | INFO [2021-12-08 18:11:21.517 +0000]: b42957f7-8f6727a3-e9d6df30 request completed 200  0.9761669635772705
```

Info's a web side Fastify request and responses.

Debugs are graphql-server api-side logging.

The format is:

`'{reqId} {msg} {res.statusCode} {req.method} {responseTime}'`

* Where `reqId` isa uniquely generated id.
* Either status (request only) or method is shows (response only)
* Duration *(response only)
* 
`api | INFO [2021-12-08 18:11:21.517 +0000]: b42957f7-8f6727a3-e9d6df30 request completed 200  0.9761669635772705`

The issue was initially noted by @orta and asking to get his input to see if this is a better format.

### CODE REVIEW

**Comment by orta** [comment]
👍🏻 this is better!

**Comment by dac09** [comment]
Do you think we need req Id for dev?

**Comment by dthyresson** [comment]
> Do you think we need req Id for dev?

Perhaps not but I though it might be helpful to have an id that can connect a request statement with its corresponding response.

But it dev, maybe not so important.

In production since the req and res are still included in output (not prettified), if there is a requestId in the headers then that gets set.

**Comment by simoncrypta** [comment]
> Then there is no need for Pino Pretty and that dependency is removed completely.

Okay this is amazing, that also mean we could wait next major release to introduce the `pino.transport` 😁

**Comment by dthyresson** [comment]
Just going to simply the log output for the moment. In a subsequent issue, we want remove `prettyPrint` and the dev dependencies and want to look at custom parsing of the NDJSON output similar to https://github.com/lrlna/pino-colada just in dev.

**Review by dac09 — APPROVED** [review]

**Pull request merged**
