### PR TITLE
Checks for the existence of a route in Routes.js

### LINKED ISSUE #171: Check for existence of routes before creating them again
If you run a generator twice with `--force` it will append its routes again, even if those exact same routes already exist.

### PR DESCRIPTION
**Pull request by sharcastic**
Fixes #171

### CODE REVIEW

**Comment by sharcastic** [comment]
Closes #171

**Comment by sharcastic** [comment]
@cannikin Can you review this? I can't seem to add reviewers to this PR. All the options on the right tab (reviewers, assignees, etc) are completely disabled for me. 

Thanks.

**Comment by cannikin** [comment]
@peterp This looks good to me, am I missing anything?

**Comment by peterp** [comment]
Looks good to me too. Let's merge it and then I can write a test for it.

**Pull request merged**
