### PR TITLE
AuthProvider: return `signup()` output from auth client

### PR DESCRIPTION
**Pull request by jvanbaarsen**
When you signup via Supabase you get all the meta data back in the
return of the `signup` call. We now eat all that output instead of
giving it back to the user.

I noticed that we already do something similar to Sign In, so I
basically took that concept and applied that for signUp as well.

@dthyresson Do you think we break people's app by not returning `reauthenticate()`?

### CODE REVIEW

**Review by dthyresson — COMMENTED** [review]
@jvanbaarsen I think this is fine. @Tobbe what do you think?

The [playground auth](https://github.com/redwoodjs/playground-auth) should be updated with this PR to test too.

In fact there are a few Supabase updates that need to be done to get up to current including redirectTo and oauth scope support.

**Comment by Tobbe** [comment]
I think this is the correct behavior. 

But, this is where semver is difficult. Is this a breaking change or not? Theoretically it is, `signUp` still returns a promise, But previously it would always resolve to `undefined`, now it'll resolve to something else. How likely is it that someone has code that depends on the promise resoling to `undefined`? Like 0.0001% risk...

**Comment by jvanbaarsen** [comment]
@Tobbe My feel is that this is not really a "breaking" change. We can mention it in the release notes so the 0.00001% of people run into this are aware of the problem.

**Comment by jvanbaarsen** [comment]
In the auth example I'm wondering how https://github.com/redwoodjs/playground-auth/blob/main/web/src/components/Supabase/Supabase.js#L81 could have worked. Since Supabase eats up the error that they throw and add it to the return object, so an error is never thrown. Or was that the old integration they used?

**Comment by Tobbe** [comment]
@jvanbaarsen Yeah, you might be right. They changed that back in Oct of last year. https://supabase.io/blog/2020/10/30/improved-dx

**Comment by thedavidprice** [comment]
@Tobbe @jvanbaarsen @dthyresson 
- is this one ready for final review (or ready to merge?) Seems like there are a couple potential next steps required.
- could I get a one-sentence description of the behavior change associate with this PR --> agreed this is not "breaking", but I would like to highlight the change with a separate bullet point

Thanks again!

**Comment by Tobbe** [comment]
image

I did that with the intent to merge as soon as all checks had completed, but then I had to go pick up the kids. I'll try again.

**Comment by Tobbe** [comment]
> could I get a one-sentence description of the behavior change associate with this PR
RW's `signUp` from `useAuth` returns a promise that will now resolve with the return value of the underlying auth client's sign up method. Previously that promise always resolved with `undefined`

Sorry. That's two sentences.

**Comment by jvanbaarsen** [comment]
@Tobbe Thanks for taking this across the line!

**Pull request merged**
