### PR TITLE
Fix double dots in static/media

### PR DESCRIPTION
**Pull request by pavelloz**
Fixes https://github.com/redwoodjs/redwood/issues/5476

### CODE REVIEW

**Review by jtoar — APPROVED** [review]
Thanks @pavelloz! I had to go through the webpack docs just to remind myself exactly what this changed. It is indeed, just a dot. 😆

webpack-ext-docs

(source: https://webpack.js.org/configuration/output/#template-strings)

I know you removed the dot for the png rule, but why don't we just add back that change while we're at? I already confirmed it's adding an extra dot locally.

**Comment by pavelloz** [comment]
> I know you removed the dot for the png rule, but why don't we just add back that change while we're at? I already confirmed it's adding an extra dot locally.

I just didnt want to do something i cannot test and could cause unexpected regression where we dont look at.  
But since you know where it affects things, I will just add it back and have it fixed as well :)

**Comment by pavelloz** [comment]
Did i just found flaky test? :P

**Comment by jtoar** [comment]
@pavelloz Not that was fixed over here https://github.com/redwoodjs/redwood/pull/5561. So now that we've got checks going again let's get this merged.

**Review by jtoar — APPROVED** [review]

**Pull request merged**
