### PR TITLE
fix(deps) resolve yarn warnings regarding unmet peer dependencies for Redwood projects

### PR DESCRIPTION
**Pull request by thedavidprice**
Running `yarn install` in a Redwood project results in a wall of information, most of which are warnings about peer dependencies and unmet dependency version requirements. We (framework authors) put up with it but that's not the case for developers — best case they find the output warnings annoying (and hopefully don't miss important errors); worst case it turns people away from using Redwood.

Some, but not all, warnings are from Redwood packages. Many are upstream.  At this time, there is no known negative impact from these dependency warnings — i.e. ideally they would all be resolved, but doing so has diminishing returns and is an ongoing maintenance consideration. This PR silences warnings that are considered acceptable and resolves those that are not. (Note: contributions are welcome for anyone who'd like to completely resolve these warnings!)

Lastly, warnings != errors. This PR does not touch errors (if/when applicable).

### Resulting Output
Here's what `yarn install` will look like with changes from this PR

yarn-install

Nice, right?!? 🤯

## Handling existing peer dep warnings
There are two cases of warnings handled by this PR.

Case 1) [YN0002 - MISSING_PEER_DEPENDENCY](https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency)
This PR silences these warnings using yarnrc `logFilters`.

Important: devs can still inspect these warnings via `yarn explain peer-requirements` or by managing their projects' `logFilters` config.

Case 2) [YN0060 - INCOMPATIBLE_PEER_DEPENDENCY](https://yarnpkg.com/advanced/error-codes#yn0060---incompatible_peer_dependency)
Because this can only be resolved via the parent package, this PR moves the necessary package code into the respective Redwood Package, thus properly fixing the incompatibility. 

## Breaking
This PR breaks a CSS import in the a11y Template `layout.tsx.a11yTemplate`, which is used when anyone generates a layout component with the `--skipLink` command option: `yarn redwood generate layout <name> --skipLink`

```diff
// web/src/layouts/MyLayout/MyLayout.{jsx|tsx}

import { SkipNavLink, SkipNavContent } from '@redwoodjs/router'
-import '@reach/skip-nav/styles.css'
+import '@redwoodjs/router/skip-nav.css'
```

## ToDo

- [x] Update redwoodjs/docs/a11y
- [ ] Codemode for layout component import change (might not be necessary as find+replace would work just fine)

### CODE REVIEW

**Comment by thedavidprice** [comment]
@Tobbe can we target this one for v7? It's a nice DX + quality of life change. Already documented for Upgrade Guide. 

Happy to handle conflicts. Just let me know.

**Comment by Tobbe** [comment]
@thedavidprice I agree. Looks like a really nice DX improvement. Dom had some reservations about exactly how it was implemented. He'll review and get back to us with comments.

**Comment by jtoar** [comment]
I'd like to try to fix the peer dependencies instead of silencing them. I understand that some of them aren't our packages and will have to be fixed upstream, in which case silencing may be the answer. But most of them are ours. Here's the errors we get (on CRWA install):

```
➤ YN0002: │ @graphql-tools/graphql-tag-pluck@npm:7.5.2 [c7cbc] doesn't provide @babel/core (p1e703), requested by @babel/plugin-syntax-import-assertions
➤ YN0002: │ @redwoodjs/babel-config@npm:6.5.1 doesn't provide graphql-tag (pf22c7), requested by babel-plugin-graphql-tag
➤ YN0002: │ @redwoodjs/cli@npm:6.5.1 doesn't provide react (pe6864), requested by @redwoodjs/prerender
➤ YN0002: │ @redwoodjs/cli@npm:6.5.1 doesn't provide react-dom (pa48b5), requested by @redwoodjs/prerender
➤ YN0002: │ @redwoodjs/core@npm:6.5.1 doesn't provide @babel/core (pe4eb4), requested by @babel/cli
➤ YN0002: │ @redwoodjs/core@npm:6.5.1 doesn't provide @babel/core (p46f04), requested by babel-loader
➤ YN0002: │ @redwoodjs/core@npm:6.5.1 doesn't provide graphql (pe91e0), requested by graphql-tag
➤ YN0002: │ @redwoodjs/eslint-config@npm:6.5.1 doesn't provide babel-plugin-module-resolver (p80f0a), requested by eslint-import-resolver-babel-module
➤ YN0002: │ @redwoodjs/internal@npm:6.5.1 doesn't provide @babel/core (pf8803), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @redwoodjs/internal@npm:6.5.1 doesn't provide @babel/core (p0e01e), requested by @babel/plugin-transform-typescript
➤ YN0002: │ @redwoodjs/internal@npm:6.5.1 doesn't provide @types/node (pa9a45), requested by ts-node
➤ YN0002: │ @redwoodjs/internal@npm:6.5.1 doesn't provide graphql-tag (p760e6), requested by @graphql-codegen/typescript-react-apollo
➤ YN0002: │ @redwoodjs/prerender@npm:6.5.1 [6c4a1] doesn't provide prop-types (p735c2), requested by @redwoodjs/web
➤ YN0002: │ @redwoodjs/testing@npm:6.5.1 doesn't provide @babel/core (pf0dd0), requested by babel-jest
➤ YN0002: │ @redwoodjs/testing@npm:6.5.1 doesn't provide @testing-library/dom (p2a890), requested by @testing-library/user-event
➤ YN0002: │ @redwoodjs/testing@npm:6.5.1 doesn't provide prop-types (p36610), requested by @redwoodjs/web
➤ YN0002: │ @redwoodjs/testing@npm:6.5.1 doesn't provide react (p51fa6), requested by @redwoodjs/router
➤ YN0002: │ @redwoodjs/testing@npm:6.5.1 doesn't provide react (pc9a52), requested by @redwoodjs/web
➤ YN0002: │ @redwoodjs/testing@npm:6.5.1 doesn't provide react (p82884), requested by @testing-library/react
➤ YN0002: │ @redwoodjs/testing@npm:6.5.1 doesn't provide react-dom (p99887), requested by @redwoodjs/router
➤ YN0002: │ @redwoodjs/testing@npm:6.5.1 doesn't provide react-dom (pafa91), requested by @redwoodjs/web
➤ YN0002: │ @redwoodjs/testing@npm:6.5.1 doesn't provide react-dom (pec9a5), requested by @testing-library/react
➤ YN0002: │ react-hot-toast@npm:2.4.1 [7fc6b] doesn't provide csstype (pfadc9), requested by goober
➤ YN0002: │ react-hot-toast@npm:2.4.1 [83bf0] doesn't provide csstype (pe3290), requested by goober
➤ YN0002: │ react-hot-toast@npm:2.4.1 [ca55a] doesn't provide csstype (pd2f5d), requested by goober
➤ YN0002: │ web@workspace:web doesn't provide graphql (paad35), requested by @redwoodjs/forms
➤ YN0060: │ web@workspace:web provides react (p993b3) with version 18.2.0, which doesn't satisfy what @redwoodjs/router and some of its descendants request
➤ YN0060: │ web@workspace:web provides react-dom (p76ae6) with version 18.2.0, which doesn't satisfy what @redwoodjs/router and some of its descendants request
```

Here's a more workable list...

- [ ] [BLOCKED] @graphql-tools/graphql-tag-pluck

  ```
  ➤ YN0002: │ @graphql-tools/graphql-tag-pluck@npm:7.5.2 [c7cbc] doesn't provide @babel/core (p1e703), requested by @babel/plugin-syntax-import-assertions
  ```

  Depends on the `@graphql-codegen` major upgrade, the status of which is unknown.
 
- [ ] @redwoodjs/babel-config

  ```
  ➤ YN0002: │ @redwoodjs/babel-config@npm:6.5.1 doesn't provide graphql-tag (pf22c7), requested by babel-plugin-graphql-tag
  ```

  This one should be as easy as adding `graphql-tag`

**Comment by Tobbe** [comment]
Here's an instance of where those warnings tripped up one of our users: https://github.com/redwoodjs/redwood/issues/9760

**Review by jtoar — APPROVED** [review]
Merging this one. I scaled back my changes after yarn 4. Yarn 4 drastically reduces the number of peer dependency warnings it console out of the box. From the [blog post](https://yarnpkg.com/blog/release/4.0#improved-user-interface):

> You will also notice it doesn't print as much warnings around peer dependencies, as we now try to only print warnings for actionable situations.

Here's the dependency warnings yarn v4 prints:

```
$ yarn
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ react is listed by your project with version 18.2.0, which doesn't satisfy what @redwoodjs/router (p1eae0) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react-dom is listed by your project with version 18.2.0, which doesn't satisfy what @redwoodjs/router (p62015) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0002: │ web@workspace:web doesn't provide graphql (p0b33c), requested by @redwoodjs/forms.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 397ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 348ms
➤ YN0000: · Done with warnings in 0s 948ms
```

There's only three now. David's original changes address the react ones, and the change I made to forms gets rid of the third.

Just so that I don't get misinterpreted, this doesn't mean that everything is fixed. (Things weren't necessarily broken either, Yarn was just doing it's job.) I just want this PR to get merged because what it has is already a big win, and I've let the scope creep too much before when I tried doing too much.

**Pull request merged**
