### PR TITLE
Support UUIDs for dbAuth in graphiql setup

### PR DESCRIPTION
**Pull request by mdkess**
Fixes https://github.com/redwoodjs/redwood/issues/7966

I couldn't figure out how to fix dependencies for the unit tests, but happy to add a unit test for this as well. Tested locally though.

### CODE REVIEW

**Comment by thedavidprice** [comment]
Nice! I'm looping in @dthyresson to get this across the finish line. 

And welcome to the Redwood PRs @mdkess It's great to see what I hope is the first of many PRs to come (no pressure 😉)

**Comment by aUsABuisnessman** [comment]
> Fixes https://github.com/redwoodjs/redwood/issues/7966
> 
> I couldn't figure out how to fix dependencies for the unit tests, but happy to add a unit test for this as well. Tested locally though. 
Quote> could be in dependencie hell through Syntax. Anyway i also test on locally on Edge - Dev version.
I 7966

**Comment by aUsABuisnessman** [comment]
> > Fixes https://github.com/redwoodjs/redwood/issues/7966
> > 
> > I couldn't figure out how to fix dependencies for the unit tests, but happy to add a unit test for this as well. Tested locally though. 
> Quote> could be in dependency hell w/Syntax. Anyway i also test on locally on Edge - Dev version.
> ink
> 
> 

is this bug CTF i am registered on HTB, if so that would pan out AWESOME 4 me.

**Comment by dthyresson** [comment]
Sorry @mdkess I read this thread wrong early in the morning and didn't see that you were to original author. Apologies.

**Pull request closed without merging**
