### PR TITLE
Wait until auth is resolved before querying in a cell

### LINKED ISSUE #3402: Cell queries are called twice when the route is unprotected and secured mode is off
// TODO: Provide reproducible repo

To reproduce:
1. Bootstrap a new redwood app
2. Add dbAuth
3. Scaffold login/signup pages
4. Create a cell that queries some data
5. Use that cell in a route/page that is not private
6. Login to the app
7. Visit the route

Expected:
Data hits the loading state, then shows the data when it succeeds

Actual:
Cell hits the loading state, then success state, then loading state again, then success state again.

### PR DESCRIPTION
**Pull request by deibeljc**
Fixes #3402 and possibly #3706.

The issue was that the auth provider and the cell would fire off at the same time and then when the auth query was resolved, it updated the context state which causes the app to update and re-query. I believe that because the auth call is so fast (at least on local) it would queue up the cell queries so cache couldn't be used in the cell and it forces a hard refresh of the component.

The fix I put in is to wait for the auth provider to resolve, if it is defined, before rendering the cell query.

### CODE REVIEW

**Comment by thedavidprice** [comment]
Woah, thank you for this @deibeljc 🚀

There's been a lot of internal discussion about how to handle this with some current work in progress. Looping in @jtoar who's the lead on the project and can sync your work here with this initiatives.

**Comment by jtoar** [comment]
@deibeljc great work to not only find out the cause but also suggest a one line fix! This what I came up with too. We're still weighing our options for this one though because we don't want to stop all Cells from rendering, even those that don't require auth. Let me explain why all Cells don't have to wait by responding to what you said here: 

> I believe that because the auth call is so fast (at least on local) it would queue up the cell queries so cache couldn't be used in the cell and it forces a hard refresh of the component.

This is almost correct, but it's not actually that auth is so fast that cache can't be used. It's that when the `AuthProvider`'s state changes, the cache gets completely thrown out. I just fixed this in https://github.com/redwoodjs/redwood/pull/3746. It doesn't stop Cells from rendering twice but does restore the expected behavior of going from Loading -> Success (because data hasn't changed) and not Loading -> Success -> Loading -> Success.

So that 'problems solved. But your PR also solves the double rendering (and committing) of authenticated Cells, which go from Loading -> Failure -> Loading -> Success. We still want to fix that, but not at the expense of stopping all Cells from rendering till auth's resolved. 

So why not just expose another config option for Cells, like

```js
export const waitForAuth = true
```

The answer is that we hate having one more thing to configure and we think we can do better by automatically checking your GraphQL SDL for `requireAuth` or `skipAuth` and then telling the Cell to wait for auth or not. This brings us into babel territory and I just haven't had time to go there yet.

Sorry for the long winded explanation but I hope that got the idea across. I'll leave this open for a bit / so we can have more of a back and forth if you want. And I can also leave this open as one solution to the problem in case the auto babel stuff doesn't end up working out.

**Comment by deibeljc** [comment]
Yeah that makes total sense @jtoar! I like the idea of the auto-transform from babel, although a user could rename requireAuth or skipAuth to something else which would sadly break that. I'll look into the avenue that uses the GQL SDL to solve this. Since you are already generating types for queries on cells, maybe there is some way to hook into that to add auth metadata on the type that can be used under the hood.

**Comment by jtoar** [comment]
Resolved by https://github.com/redwoodjs/redwood/pull/4320.

**Pull request closed without merging**
