### PR TITLE
TS: Fix missing properties in CellFailureProps type

### PR DESCRIPTION
**Pull request by callingmedic911**
**Problem:** 
Currently `CellFailureProps` allows usage of `error` field only, even though other nice fields from `QueryResult` are available like `refetch` function.

Screenshot 2021-08-20 at 12 26 56 PM

Expected behavior is to allow access of such other properties (without breaking test and stories).

@dac09 @thedavidprice

### CODE REVIEW

**Comment by callingmedic911** [comment]
While I was checking this, I see `CellLoadingProps` doesn't have `Partial` and it makes sense since `Loading` doesn't have any argument to use by default (when freshly generated). But it would make test cases a bit tricky to use if I use any of the `QueryResult` argument and I use `CellLoadingProps` as type.

Cell.tsx
Screenshot 2021-08-20 at 2 07 35 PM

Cell.test.tsx
Screenshot 2021-08-20 at 2 10 53 PM

What do you think? Should we also add `Partial` in`CellLoadingProps`?

**Comment by dac09** [comment]
Could we verify something with this change Aditya please - if you generate a component, could you please check the test/story files for TS errors?

> What do you think? Should we also add Partial inCellLoadingProps?
If no errors above, yeah makes total sense to add this.

**Comment by callingmedic911** [comment]
Here's how it's looking with changes for both `CellFailureProps` and `CellLoadingProps`: https://s.tape.sh/4p58O8GY

**Review by dac09 — APPROVED** [review]

**Comment by dac09** [comment]
Tested on gitpod, looking good! :)

**Pull request merged**
