### PR TITLE
Add a link in the header to the AI Sidekick

### PR DESCRIPTION
**Pull request by keithtelliott**
This PR adds a link to the AI Sidekick in the navigation header of the docs pages.

It is a simple approach.  But, it may be a reasonable way to add the Fixie AI chatbot quickly.  

Associated with this is a [PR](https://github.com/redwoodjs/redwoodjs.com/pull/130) on the web site repo, add a new page for the Sidekick.

### CODE REVIEW

**Comment by dthyresson** [comment]
@keithtelliott I adde the labels so that the deploy preview can complete. See: https://deploy-preview-9282--redwoodjs-docs.netlify.app/docs/canary/introduction

I did try the link but got an error:

image

Because the other PR is in preview and the link urls don't match:

https://deploy-preview-130--redwoodjs-com.netlify.app/sidekick


Question: why would the Sidekick be on the marketing site and not docs?

**Comment by keithtelliott** [comment]
Hi @dthyresson - thanks for digging-in and checking out this PR.  

Your question... 
> Question: why would the Sidekick be on the marketing site and not docs?

No particular reason.  I just took a path of least resistance and added a page via a familiar method on the main site.  The sidekick could live at docs/sidekick instead (or both).  The tasks:  !) add the fixie package to the Docusaurus site; 2) create a sidekick page on the docusaurus site add populate it with code sorta like what's shown below, 3) Update the Docusaurus config to put links in the left nav as we desire.  

I'm out of time for now, so I'll just pause and ask...  what do you think?

```js
// Will need to change this to a Docusaurus style page (the following is a RedwoodJS page)

import { ControlledFloatingFixieEmbed } from 'fixie/web'

const SidekickPage = () => {
  const style = {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 1000,
    width: '60%',
    height: '80%',
    overflow: 'auto',
    backgroundColor: 'rgba(0,0,0,0.4)',
  } as const

  return (
    <>
      <ControlledFloatingFixieEmbed
        visible={true}
        debug={false}
        // Eventually replace the following agentId with a more official RedwoodJS version
        agentId="keithtelliott/fixie-sidekick-template"
        agentSendsGreeting={true}
        chatTitle="Your RedwoodJS AI Sidekick, powered by Fixie.ai"
        style={style}
      />
    </>
  )
}

export default SidekickPage
```

**Comment by adriatic** [comment]
I have yet to try running Keith's code - I only read @dthyresson's comments so far. So, I will try to run this project and give my feedback to all that care (writing here may be not what you expect - is there a discussion on this in the discourse (not discord)?

**Comment by keithtelliott** [comment]
Thanks for jumping in @adriatic!  

These associated [PR](https://github.com/redwoodjs/redwoodjs.com/pull/130) may be a better place to start - it simply creates a page on the main redwoodjs.com site that includes the client side of the Fixie sidekick.  

And yes, I think this is a good place to communicate (I'll need to remember to check my GitHub alerts, so I reply promptly).

**Comment by adriatic** [comment]
@keithtelliott I would be interested in a discussion thread in https://community.redwoodjs.com/ - assuming that there are other folks interested in generative AI in the context of Redwood. I happen to believe that accessing Fixie from Redwood via [www.redwoodjs.com/docs/sidekick](http://www.redwoodjs.com/docs/sidekick) is suboptimal because you **switch** the context **from** the place where you want Fixie's help **to** a new context that Fixie provides.

In the case where the developer reads the online docs, consider this UI:

image

However, interacting with Fixie would be most natural when using VSCode - as the Fixie's response would be immediately available to a copy/paste action. Discussing this option would be best in the context of https://community.redwoodjs.com/, I think. 
I also plan to invite @zachkoch to this discussion (if you agree)

**Comment by Tobbe** [comment]
Thanks for getting the ball rolling on this @keithtelliott! 

I tried the chatbot at https://deploy-preview-130--redwoodjs-com.netlify.app/sidekick. Is that the best way to get a feel for how well the sidekick can answer questions?

I asked about adding custom form validators, and the answer wasn't good enough for me to feel comfortable including this on our docs side just yet. But maybe some more fine-tuning can get it there 🙂 It suggested using `npm` to install `yup` to accomplish the task. I would expect it to suggest `yarn add` instead, as we only talk about yarn in our docs. It also used generic html elements instead of the Redwood-specific `<Form>`, `<TextField>` etc components.

Next steps: 
1. Improve the AI sidekick to provide answers that are more relevant to a Redwood project.
2. Demo at a core-team meeting
3. Address feedback from meeting
4. Merge PR

**Comment by keithtelliott** [comment]
Sounds good Tobbe.  I appreciate you defining the next steps - reasonable
and clear.

**Comment by adriatic** [comment]
Since I am copied to this thread (courtesy of Github), let me make a few comments.

- Redwood apps seem to heavy to use in the context of AI as there is. lot of code that would not be used ever. 
- If someone believes that adding a sidekick to the RW app in development would help the developer (something I agree with) - this task will be a lot easier to achieve by creating a netxjs based mini-app (see [this document](https://tailwindcss.com/docs/guides/nextjs) and use this tool to get answers from the sidekick).
- Such approach may "offend" some hard core "redwoodians" - so my own approach on Redwood-AI context is the creation of a "miniscule" Redwood app (created by following Redwood tutorial up to (and not including [A Second Page and a Link](https://redwoodjs.com/docs/tutorial/chapter1/second-page)), and add properly modified the information on [Get started with Tailwind CSS](https://tailwindcss.com/docs/installation). 
- RW supports the Tailwindcss for some time, so the term "properly modified" refers to the detailed description of the side-effects of running `yarn rw setup ui tailwind` - command that adds Tailwindcss to a Redwood app:

```
    yarn rw setup ui tailwind
    ✔ Installing project-wide packages...
      ✔ Install prettier-plugin-tailwindcss@0.4.1
    ✔ Installing web side packages...
     ✔ Install postcss, postcss-loader, tailwindcss, autoprefixer
    ✔ Configuring PostCSS...
    ✔ Initializing Tailwind CSS...
    ✔ Adding directives to index.css...
     ↓ Updating tailwind 'scaffold.css'...
    ✔ Adding recommended VS Code extensions to project settings...
    ✔ Adding tailwind config entry in prettier...
    ✔ Adding tailwind prettier plugin...
```
If anyone believes that a more detailed description of constructing the "miniscule" Redwood app, might be of interest to a wider readership, let me know and I will post such article on [RedwoodJS Community](https://community.redwoodjs.com/).

**Comment by thedavidprice** [comment]
@keithtelliott is this something you'd like to keep working on? Should we close it out? Thoughts otherwise?

**Comment by keithtelliott** [comment]
@thedavidprice I recommend that we close this out, and NOT incorporate it.  Fixie AI is shutting down the service we were going to use, and early testing did not build confidence.  

We should add an AI chat support feature eventually, but that can be a new PR…

Note, we should also close the following PR, which is related:  https://github.com/redwoodjs/redwoodjs.com/pull/130

**Comment by keithtelliott** [comment]
Closing because this AI chat feature did not work out (see comments above).

**Pull request closed without merging**
