### PR TITLE
Adjust the production usage warning

### PR DESCRIPTION
**Pull request by amorriscode**
[Prisma 2.0 was released on June 9th](https://www.prisma.io/blog/announcing-prisma-2-n0v98rzc8br1) so I don't think there is a need for this messaging anymore.

### CODE REVIEW

**Comment by thedavidprice** [comment]
Hi @amorriscode! Thanks for opening your first Redwood PR 🎉

We completely agree this language needs to be updated. And we took the first stab but got lost in a list about figuring out all the things _not_ production-ready, which led to working on a v1.0 Roadmap doc... we got lost in the weeds. So we'd ❤️ your help with this. 

**Here's the text I suggest we use:**
> WARNING: RedwoodJS software has not reached a stable version 1.0 and should not be considered suitable for production use. In the "make it work; make it right; make it fast" paradigm, Redwood is in the later stages of the "make it work" phase.

Next up, a warning of this type occurs in several places. However, the code you edited currently in this PR is _not_ for the application itself — it's a copy of the create-redwood-app (CRWA) repo, which is used here for testing purposes. So you can revert and ignore anything in __fixtures__.

But these areas across a couple repos need the current copy replaced with my suggested copy above:
- The README: https://github.com/redwoodjs/redwood/blob/main/README.md
- Router doc: https://github.com/redwoodjs/redwood/blob/main/packages/router/README.md
- Form doc: https://github.com/redwoodjs/redwoodjs.com/blob/main/docs/form.md
- CRWA README: https://github.com/redwoodjs/create-redwood-app/blob/master/README_APP.md

So what do you think, would you be able to update this PR with these changes as well as create a PR in the CRWA repo?

**Comment by amorriscode** [comment]
Thanks for helping with the messaging @thedavidprice! I'll work on opening PRs for all those areas!

**Comment by amorriscode** [comment]
Updated this PR and created the following PRs: [#289 on redwoodjs.com](https://github.com/redwoodjs/redwoodjs.com/pull/289), [#92 on create-redwood-app](https://github.com/redwoodjs/create-redwood-app/pull/92).

**Comment by thedavidprice** [comment]
Great work! All three PRs are now merged.

**Pull request merged**
