### PR TITLE
Update VS Code private icon logic

### PR DESCRIPTION
**Pull request by M0nica**
- This PR is related to: https://github.com/redwoodjs/redwood/issues/917
- I wasn't sure how to test this locally...I have a test app running to watch changes in my local instance of `redwood` however I did not see any changes to the VSCode outline when I made these changes. I've installed https://marketplace.visualstudio.com/items?itemName=decoupled.studio but I am not seeing the gist icon _or_ the private-gist icon for page files 🤔 

This branch was branched off of: https://github.com/redwoodjs/redwood/pull/1325 

This is what I see in VSCode for my test app ([example-todo](https://github.com/redwoodjs/example-todo)) with a private route when running my redwood changes locally:
Screen Shot 2020-10-12 at 2 28 24 PM

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks @M0nica! Labeled and looped in Aldo via Assignment. 

> I wasn't sure how to test this locally...

^^ Ah, great question. @aldonline I'm curious as well if it's even possible to locally test things VS Code Extension specific... recommendations for workarounds until the codebase is open? (Which, to be clear, is _not_ a subtle nudge to hurry up or reprioritize 😆)

**Comment by aldonline** [comment]
Hi @M0nica, 

1. Please uninstall Decoupled Studio and install the [Redwood IDE](https://marketplace.visualstudio.com/items?itemName=decoupled.redwoodjs-ide). This is the official extension moving forward. We will eventually make it completely opensource and move it into the redwoodjs/redwood monorepo
2. When the extension is activated, it will look for `node_modules/@redwoodjs/structure/dist/language_server/start.js` and use it to start a language server process in the background. This means that most of the features that you see in VSCode will come from code that is installed alongside the Redwood framework (in the structure package, which is what you're editing right now). In other words, you should be able to use the same workflow described in [CONTRIBUTING.md](https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md) ex: (`yarn rwt copy:watch`). Just make sure to restart VSCode whenever you make a change so the extension starts a language server with the updated code.

Notes to self:
* Remove all Redwood functionality from Decoupled Studio. Show a warning and a link to the Redwood IDE
* Add a CONTRIBUTING.md file to the structure package

**Comment by thedavidprice** [comment]
@aldonline Ah, super helpful instructions. And, yes, please do add Contributing info to the package Readme. And/or let me know how I can help.

This one looks ready for review. Let me know when it's ready and I’ll get it merged.

Thanks, all!

**Review by aldonline — APPROVED** [review]

**Comment by thedavidprice** [comment]
Thanks, all 🚀

**Pull request merged**
