### PR TITLE
Handle path for generators

### PR DESCRIPTION
**Pull request by fveauvy**
This pull request aims to handle path argument for layout, component, page and cell generators. It's a work in progress.

This PR is related to issues #2232, #1597 and to this [Discourse thread](https://community.redwoodjs.com/t/addition-to-the-cell-generator/2008).

## What changed ?

- extract the `splitPathAndModel` function and moved it to `generate/helpers.js`. Scaffold's generator and destroyer are using it to decompose the command argument `<path/model>`. 
- rename it to `splitPathAndName` because it wouldn't only be used to destructurate a model (but also a component/layout/cell name).
- include the path provided by the command argument to the `componentOutputPath` from `templateForComponentFile`.

Adding a path to the argument of a cell generator command isn't breaking anymore (see the screenshot below).

output of cell generation

And find the generated cell below :

```js
export const QUERY = gql`
  query AdminTestQuery {
    test {
      id
    }
  }
`

export const Loading = () => <div>Loading...</div>

export const Empty = () => <div>Empty</div>

export const Failure = ({ error }) => <div>Error: {error.message}</div>

export const Success = ({ test }) => {
  return JSON.stringify(test)
}
```

I tested every destroy commands and they seem to work as intended in the case of a `<path/name>` argument pattern.

However, the destroy command isn't deleting the empty folder generated from the path argument.

 - If I first run `yarn rw g component ui/button`, here's the output :
```sh
  ✔ Generating component files...
    ✔ Successfully wrote file `./web/src/components/Ui/Button/Button.test.js`
    ✔ Successfully wrote file `./web/src/components/Ui/Button/Button.stories.js`
    ✔ Successfully wrote file `./web/src/components/Ui/Button/Button.js`
```

 - Then I run `yarn rw d component ui/button` :
```sh
  ✔ Destroying component files...
    ✔ Destroying `./web/src/components/Ui/Button/Button.test`...
    ✔ Destroying `./web/src/components/Ui/Button/Button.stories`...
    ✔ Destroying `./web/src/components/Ui/Button/Button`...
    ✔ Cleaning up empty directories...
      ✔ Removing empty `./web/src/components/Ui/Button`...
✨  Done in 2.98s.
```

The empty folder `Ui` will remain. 

## Questions

I have a couple of questions before I proceed further. 

@Tobbe @cannikin : I took the liberty of tagging you two for your input since we discussed the matter on Discourse.

1. What should I do about the remaining/empty folder when we use the destroy command (see the `ui/button` case above) ?
2. Should I use camelCase instead of PascalCase for the path folder ? I don't mind either way.
   - `component/ui/Button/Button.js`
   - `component/Ui/Button/Button.js`

## What's left to do ?

- [x] Fix scaffold destroyer
- [x] Fix page generator command when using <path/name> argument (it's not working for now)
- [x] Path folders should use camelCase instead of PascalCase for components, layouts and cells generators
- [x] Path folders shoud use camelCase instead of PascalCase for components, cells and layout generated after a scaffold
- [x] Adapt scaffold test suite to camelCase 
- [x] Destroy page should delete story and test files aswell as the page itself
- [x] Write tests with path and nested path patterns for layout generator
- [x] Write tests with path and nested path patterns for component generator
- [x] Delete empty folder remaining after destroying a <path/name> component
- [x] Write tests with path and nested path patterns for cell generator
- [ ] Write tests with path and nested path patterns for sdl generator
- [ ] Write tests with path and nested path patterns for page generator- 
- [ ] Fix unavailable page when using nested path for page and scaffold generators (from eslint rule @redwoodjs/redwood/no-unavailable-pages)
- [ ] Change the CLI doc accordingly

### CODE REVIEW

**Comment by Tobbe** [comment]
I'm no authority here, but I can never resist an opportunity to voice my opinions 😉 

> * What should I do about the remaining/empty folder when we use the destroy command (see the `ui/button` case above) ?

If it's empty I'd say delete it. Like if you generate a bunch of stuff into an admin/ folder, then delete it all again, the last thing to be deleted should delete the folder too


> * Should I use camelCase instead of PascalCase for the path folder ? I don't mind either way.
>   
>   * `component/ui/Button/Button.js`
>   * `component/Ui/Button/Button.js`

I prefer `ui` in this case, but also no strong opinion. 

But again, please wait for Rob's input.

**Comment by cannikin** [comment]
I agree with @Tobbe on both counts: delete empty directories, and camelCase!

**Comment by thedavidprice** [comment]
Will this also close https://github.com/redwoodjs/redwood/issues/1597?

Thanks for getting this going @fveauvy 🚀

**Comment by fveauvy** [comment]
> Will this also close #1597?
> 
> Thanks for getting this going @fveauvy 🚀

Yes, absolutely ! I forgot to add this issue. I'll edit the PR comment.

**Comment by Tobbe** [comment]
@fveauvy Wow, lots of changes going in here. Thanks for all the work you're putting in to this. But it looks like you have some other changes too, that don't really have anything with this PR to do. Could it be a merge or rebase that went wrong? If you could take a look at that, this will be much easier to review once it's done. Thanks!

**Comment by fveauvy** [comment]
Hello @Tobbe,

These commits were added when I run `git pull upstream main` after the new release of redwood on my local project.

I followed these guidelines to setup my contribution flow : https://www.dataschool.io/how-to-contribute-on-github/

I don't know what I did wrong there :(

**Comment by Tobbe** [comment]
> These commits were added when I ran `git pull upstream main`

I always do `git pull --rebase upstream main`. That way I always only have my own changes on top of the remote's code.

Easiest for you right now is probably to squash all your commits, so you only have one commit to worry about, and then rebase that single commit on upstream's main. Then force push it to your branch.

**Pull request closed without merging**
